### ISSUE TITLE
ae2 stuff encoder not working fully

### ISSUE THREAD

**Issue by Pa4ok** [GTNewHorizons/GT-New-Horizons-Modpack#10261]
### Your GTNH Discord Username

Pa4ok#2731

### Your Pack Version

2.1.2.3

### Your Server

private

### Type of Server

dedicated

### Your Expectation

ae2 stuff encoder should lay out craft on nei ? button
![image](https://user-images.githubusercontent.com/40999563/166474156-560fa6b4-d522-4cf0-bffe-9774906a45e7.png)

### The Reality

nei are closing, and there is no craft in encoder

error in console
java.io.StreamCorruptedException: invalid type code: 1F
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1700) ~[?:1.8.0_332]
        at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2094) ~[?:1.8.0_332]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1657) ~[?:1.8.0_332]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_332]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_332]
        at net.bdew.lib.network.NBTTagCompoundSerialize.readObject(NBTTagCompoundSerialize.scala:23) ~[NBTTagCompoundSerialize.class:?]
        at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184) ~[?:1.8.0_332]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2322) ~[?:1.8.0_332]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213) ~[?:1.8.0_332]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669) ~[?:1.8.0_332]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431) ~[?:1.8.0_332]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355) ~[?:1.8.0_332]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213) ~[?:1.8.0_332]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669) ~[?:1.8.0_332]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_332]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_332]
        at net.bdew.lib.network.SerializedMessageCodec.decode(SerializedMessageCodec.scala:55) [SerializedMessageCodec.class:?]
        at net.bdew.lib.network.SerializedMessageCodec.decode(SerializedMessageCodec.scala:29) [SerializedMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) [MessageToMessageCodec$2.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) [MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.1.6]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:243) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:178) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:863) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:349) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:703) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:589) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332] 

### Your Proposal

I think it's the consequences of your last bdlib update with fixing packet deserialization

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
```
cfg messageWhitelist {
    exact = =[
        "[B"
    ]
}
```
Put this in `config/bdlib/net-filter.cfg` for now.

**Comment by boubou19** [comment]
Btw the encoder is now deprecated as you can directly encode stuff with ghost items thanks to not enough energistics

**Comment by Pa4ok** [comment]
another class to permit

> `net.bdew.lib.network.InvalidClassException: scala.collection.immutable.List$SerializationProxy
> 	at net.bdew.lib.network.SerializedMessageCodec$$anon$1.resolveClass(SerializedMessageCodec.scala:49) ~[SerializedMessageCodec$$anon$1.class:?]
> 	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1988) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1852) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2186) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_332]
> 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_332]
> 	at net.bdew.lib.network.SerializedMessageCodec.decode(SerializedMessageCodec.scala:55) ~[SerializedMessageCodec.class:?]
> 	at net.bdew.lib.network.SerializedMessageCodec.decode(SerializedMessageCodec.scala:29) ~[SerializedMessageCodec.class:?]
> 	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
> 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
> 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
> 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
> 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
> 	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) ~[FMLProxyPacket.class:1.1.6]
> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:243) ~[ej.class:?]
> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:178) ~[nc.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:863) ~[MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:349) ~[lt.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:703) ~[MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:589) ~[MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]`
