### ISSUE TITLE
Cannot open power station GUI

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/GT-New-Horizons-Modpack#10323]
### Your GTNH Discord Username

Gates_ice#4537

### Your Pack Version

2.1.2.3qf

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

N/a

### The Reality

While right clicking on the controller block, no GUI is opened. Machine is formed and functioning.

In GregTech.log, I can see the following:

```
Encountered Exception while rightclicking TileEntity, the Game should've crashed now, but I prevented that. Please report immediately to GregTech Intergalactical!!!
java.lang.NullPointerException
	at gtPlusPlus.xmod.gregtech.api.gui.CONTAINER_PowerSubStation.func_75142_b(CONTAINER_PowerSubStation.java:49)
	at gregtech.api.gui.GT_ContainerMetaTile_Machine.<init>(GT_ContainerMetaTile_Machine.java:52)
	at gregtech.api.gui.GT_Container_MultiMachine.<init>(GT_Container_MultiMachine.java:14)
	at gtPlusPlus.xmod.gregtech.api.gui.CONTAINER_PowerSubStation.<init>(CONTAINER_PowerSubStation.java:21)
	at gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.storage.GregtechMetaTileEntity_PowerSubStationController.getServerGUI(GregtechMetaTileEntity_PowerSubStationController.java:142)
	at gregtech.common.GT_Proxy.getServerGuiElement(GT_Proxy.java:1733)
	at cpw.mods.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:243)
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:75)
	at net.minecraft.entity.player.EntityPlayer.openGui(Unknown Source)
	at gregtech.api.metatileentity.BaseTileEntity.openGUI(BaseTileEntity.java:116)
	at gregtech.api.metatileentity.BaseTileEntity.openGUI(BaseTileEntity.java:110)
	at gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.storage.GregtechMetaTileEntity_PowerSubStationController.onRightclick(GregtechMetaTileEntity_PowerSubStationController.java:130)
	at gregtech.api.metatileentity.MetaTileEntity.onRightclick(MetaTileEntity.java:255)
	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.onRightclick(GregtechMeta_MultiBlockBase.java:2491)
	at gregtech.api.metatileentity.BaseMetaTileEntity.onRightclick(BaseMetaTileEntity.java:1463)
	at gregtech.common.blocks.GT_Block_Machines.func_149727_a(GT_Block_Machines.java:365)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Your Proposal

N/a

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/157
