### ISSUE TITLE
Crash preventing me to join the server

### ISSUE THREAD

**Issue by ESCHUFLI** [GTNewHorizons/GT-New-Horizons-Modpack#10465]
### Your GTNH Discord Username

ESCHUFLI#3565

### Your Pack Version

2.1.2.3

### Your Server

My own dedicated server, installed from GTNH Server Packs

### Your Actions

Everytime I load up Minecraft and try to join my server, my game crashes. This didn't happen 6 hours ago and I didn't do any NBT-heavy actions before my last disconnection (which was without any errors). Once I try joining the game, I can't get past the joining screen without crashing. I tried uninstalling Optifine, FTB Utils and FTB Lib but it was still crashing. I even tried installing a fresh build...

### Crash Report

**CLIENT LOG**
[crash-2022-06-10_09.18.32-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8876662/crash-2022-06-10_09.18.32-client.txt)

**SERVER LOG**
[09:18:30] [User Authenticator #1/INFO]: UUID of player ESCHUFLI is [REDACTED]
[09:18:30] [Netty IO #4/INFO] [FML]: Client protocol version 2
[09:18:30] [Netty IO #4/INFO] [FML]: Client attempting to join with 274 mods : BuildCraft|Silicon@7.1.27,AromaBackup@0.1.0.0,ProjRed|Expansion@4.7.5,ExtraBees@2.0.34,HardcoreEnderExpansion@1.9.2-GTNH,blocklimiter@0.55,MouseTweaks@2.4.4,Botany@2.0.34,dreamcraft@1.9.22-pre,endercore@0.2.6,BWCore@0.0.1,BuildCraft|Robotics@7.1.27,irontank@1.2.6,forgelin@1.9.2-GTNH-1.7.10-Edition,galacticgreg@1.0.7,Ic2Nei@1.2.1,openglasses@1.2.3-GTNH,GalaxySpace@1.1.16-GTNH,betterbuilderswands@1.7.10-0.9.1-GTNH,BiomesOPlenty@2.1.3-GTNH,LunatriusCore@1.1.6-GTNH,openmodularturrets@2.2.11-247,gtnhtcwands@1.2.6,ForgeMultipart@1.2.7,hodgepodge@1.7.1,lootgames@2.0.5,malisisdoors@1.7.10-1.13.2,berriespp@1.3.5.9,BrandonsCore@1.0.0.12,CoFHCore@1.7.10R3.1.4,malisiscore@1.7.10-0.14.3,ResourceLoader@1.3,catwalks@2.0.4,ExtraTrees@2.0.34,StorageDrawers@1.11.13-GTNH,gendustry@1.6.5.3-GTNH,TGregworks@GTNH-1.0.22,enhancedlootbags@1.0.5,BuildCraft|Energy@7.1.27,modtweaker2@0.9.8,IC2@2.2.828-experimental,WitcheryExtras_ASM@0.1-Beta,IguanaTweaksTConstruct@1.7.10-2.2.2,FML@7.10.99.99,Natura@2.5.0,defaultserverlist@1.0,NEIAddons|Forestry@1.12.19,ThE-core@1.0.0.1,BiblioWoodsNatura@1.5,<CoFH ASM>@000,NettyPatch@0.3.1,Automagy@0.28.2,hydroenergy@1.0.10,ProjRed|Illumination@4.7.5,TMechworks@0.2.16.3,LogisticsPipes@0.9.4.5.4,Australia@1.7.30-pre,NotEnoughItems@2.2.9-GTNH-pre,Thaumcraft@4.2.3.5,opensecurity@1.0.117,Waila@1.5.20,eternalsingularity@1.7.10-.1.0.4b,PlayerAPI@1.4,appliedenergistics2-core@rv3-beta-80-GTNH-pre,NEIAddons@1.12.19,StorageDrawersForestry@1.11.11-GTNH,BiblioCraft@1.11.7,WarpTheory@1.2.6-GTNH,BuildCraft|Core@7.1.27,OpenModsCore@0.10.6,betterloadingscreen@1.3.32-GTNH,bdlib@1.9.6,NEIAddons|Developer@1.12.19,tcinventoryscan@1.0.11,ProjRed|Transmission@4.7.5,naturescompass@1.3.1,WR-CBE|Logic@1.4.5,DummyCore@1.13,WitcheryExtras@1.1.5,RWG@Alpha 1.3.2,BetterAchievements@0.1.0,inventorytweaks@1.7.10,defaultworldgenerator@0.1-b13,InGameInfoXML@2.8.3.91,EMT@1.2.8.7,findit@1.0.5,GT++_Preloader@0.5-Beta,OpenBlocks@1.6.8-GTNH,harvestthenether@1.7.10,GoodGenerator@0.4.1,EnderStorage@1.4.11,ForbiddenMagic@0.6.2-GTNH,gregtech@MC1710,CropLoadCoreASM@0.0.2,CarpentersBlocks@3.3.8.2,EnderIO@2.3.1.31,Translocator@1.1.2.19,InfernalMobs@1.7.5-GTNH,CustomMainMenu@1.9.2,neiintegration@1.1.3,miscutils@1.7.30-pre,MrTJPCoreMod@1.1.0.33,Roguelike@1.5.2-GTNH,SpecialMobs@3.3.9,NEIAddons|Botany@1.12.19,sleepingbag@1.7.10-0.1.2,gtnhlanth@0.8.6,thaumicenergistics@1.3.16-GTNH,Aroma1997Core@1.0.2.16,CodeChickenCore@1.1.5,YAMCore@0.5.82,MineTweaker3@3.1.0,openprinter@0.1.0.132,GTTweaker@1.0,ThaumicTinkerer-preloader@0.1,oauth@1.06.1-GTNH,structurelib@1.0.16,bartworks@0.5.40-pre,NodalMechanics@1.1.-6-GTNH,TravellersGear@1.16.8-GTNH,adventurebackpack@1.0.4-GTNH,gtneioreplugin@1.0.10,gadomancy@1.0.8.4,betterp2p@1.0.6,Baubles@1.0.1.14,ProjRed|Core@4.7.5,FloodLights@1.2.8-137,TML@4.1.0-GTNH,ArchitectureCraft@1.7.6,ProjRed|Exploration@4.7.5,utilityworlds@1.0.9d,holoinventory@1.7.10-2.1.7-GTNH,Forestry@4.4.6,ae2wct@1.8.8.4-pre,Schematica@1.8.5-GTNH,OpenMods@0.10.6,ifu@1.9.2,RIO@2.4.5,tcneiadditions@1.1.0.6,GalacticraftCore@3.0.40-GTNH,BiblioWoodsBoP@1.9,torohealthmod@1.0.1,tc4tweak@1.4.16,p455w0rdslib@1.0.4,tcnodetracker@1.1.5,netherportalfix@1.0,questbook@2.1.3-GTNH,battlegear2@1.7.10-1.1.1.8,ForgeMicroblock@1.2.7,botanichorizons@1.0.5-GTNH,Ztones@1.7.10,ThaumicExploration@GRADLETOKEN_VERSION,EnderZoo@1.0.23,MagicBees@2.5.8-GTNH,ProjRed|Integration@4.7.5,betterquesting@3.0.355-GTNH,controlling@1.0.0,cookingforblockheads@1.2.8-GTNH,compactkineticgenerators@1.7.10-1.0,ModMixins@0.0.1,ae2stuff@0.5.1.15-GTNH,OpenComputers@1.7.5.24-GTNH,kekztech@0.6.3,McMultipart@1.2.7,ProjRed|Fabrication@4.7.5,SuperTic@1.2.2,ExtraUtilities@1.2.12,Railcraft@9.13.7-pre.dirty,detravscannermod@1.6.6,bq_standard@3.0.190-GTNH,WR-CBE|Addons@1.4.5,IC2NuclearControl@2.4.8,StevesCarts@2.0.1,MCFrames@1.0,ThaumicHorizons@1.2.1.2,BiblioWoodsForestry@1.7,ironchestminecarts@1.0.8,FastCraft@1.25,Forge@10.13.4.1614,avaritiaddons@1.5.3-GTNH,croploadcore@0.1.10,HardcoreDarkness@1.7,tinkersdefense@1.2,OpenComputers|Core@1.7.5.24-GTNH,ThaumicTinkerer@2.6.4,ThaumcraftResearchTweaks@1.0.3,OilTweak@1.0.3,AdvancedSolarPanel@1.7.10-3.5.1,AFSU@1.2.6-GTNH,JABBA@1.2.14,angermod@0.6.3,ProjRed|Transportation@4.7.5,AppleCore@3.1.9,cb4bq@1,bartworkscrossmod@0.5.40-pre,TiCTooltips@1.2.9,universalsingularities@8.6.5,supersolarpanel@1.7.10-1.1.1-GT-NH-Mod,HungerOverhaul@1.7.10-1.0.2.DEV.80bb6db,visualprospecting@1.0.28,ThaumicMachina@0.2.1,NEIAddons|CraftingTables@1.12.19,NEIAddons|ExNihilo@1.12.19,WailaHarvestability@1.1.10-GTNH,Botania@1.9.3-GTNH-pre,bartworkscrossmodtgregworkscontainer@0.5.40-pre,beebetteratbees@0.2,Avaritia@1.25,craftpresence@1.8.2,ProjRed|Compatibility@4.7.5,ForgeRelocation@0.0.1.4,TConstruct@1.7.10-1.9.0.14-GTNH,extracells@2.5.10,asielib@0.5.3,StevesFactoryManager@1.1.0-GTNH,BinnieCore@2.0.34,inpure|core@1.7.10R1.0.0B9,wawla@1.1.3-GTNH,RelocationFMP@0.0.1.2,Genetics@2.0.34,mcp@9.05,Mantle@0.3.4,journeymap@5.1.4p2,appliedenergistics2@rv3-beta-80-GTNH-pre,SGCraft@1.3.12-GTNH,thaumcraftneiplugin@@VERSION@,AromaBackupRecovery@1.0,DraconicEvolution@1.1.1,WR-CBE|Core@1.4.5,StorageDrawersMisc@1.11.11-GTNH,harvestcraft@1.0.12-GTNH,TaintedMagic@r7.6,TwilightForest@2.3.8.14,BuildCraft|Factory@7.1.27,ProjectBlue@1.1.7-GTNH,computronics@1.6.11-GTNH,GraviSuite@2.0.68u,NEIAddons|AppEng@1.12.19,neicustomdiagram@1.4.4.4,NettyPatch_ASM@0.3.1,GalacticraftMars@3.0.40-GTNH,BuildCraft|Compat@7.1.11,wailaplugins@0.2.5,HelpFixer@1.0.7,itlt@1.0.3,neenergistics@1.3.11,AWWayofTime@1.3.8,IronChest@6.0.70,creativecore@1.3.25-GTNH,RandomThings@2.2.4,bugtorch@1.1.2-GTNH,thaumicbases@1.4.29,SpiceOfLife@v.2.0.0-carrot-beta10,WitchingGadgetsCore@1.2.18-GTNH,StorageDrawersNatura@1.11.11-GTNH,spongemixins@1.5.0,BuildCraft|Transport@7.1.27,StorageDrawersBop@1.11.11-GTNH,wanionlib@1.8.2,Aroma1997CoreHelper@1.0.2.16,chisel@2.10.9-GTNH,StevesAddons@0.10.23,Backpack@2.2.5-GTNH,ToxicEverglades@1.7.30-pre,ThaumcraftMobAspects@1.0.0-GTNH,witchery@0.24.1,enhancedportals@3.0.12,overloadedarmorbar@1.0.1,WitchingGadgets@1.2.18-GTNH,BuildCraft|Builders@7.1.27,chiseltones@@VERSION@,littletiles@1.2.1-GTNH,tectech@5.0.6,BloodArsenal@1.7.10-1.2.5
[09:18:30] [Netty IO #4/INFO] [FML]: Attempting connection with missing mods [MobiusCore, admintools, FTBL, FTBU, JourneyMapServer, Morpheus, Opis] at CLIENT
[09:18:31] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[09:18:31] [Server thread/INFO]: ESCHUFLI[/127.0.0.1:50898] logged in with entity id 683 at (-1016.7814777554328, 60.0, 581.7584095405701)
[09:18:31] [Server thread/INFO]: ESCHUFLI joined the game
[09:18:31] [Server thread/INFO] [Adventure Backpack]: Joined EntityPlayer of name: ESCHUFLI
[09:18:31] [Server thread/INFO] [EnderCore]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[09:18:31] [Thread-16/INFO] [betterquesting]: Start force party quest sync
[09:18:31] [Server thread/INFO] [EnderCore]: Sending server configs to client for tterrag.wailaplugins.config.WPConfigHandler
[09:18:31] [Netty IO #4/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.EncoderException: java.io.IOException: String too big (was 155516 bytes encoded, max 32767)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:129) ~[MessageToByteEncoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:440) ~[NetworkDispatcher.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at net.minecraft.network.NetworkManager$1.run(NetworkManager.java:174) [ek.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [SingleThreadEventExecutor.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Caused by: java.io.IOException: String too big (was 155516 bytes encoded, max 32767)
	at net.minecraft.network.PacketBuffer.func_150785_a(SourceFile:143) ~[et.class:?]
	at net.minecraft.network.play.server.S02PacketChat.func_148840_b(SourceFile:33) ~[gj.class:?]
	at net.minecraft.util.MessageSerializer.encode(SourceFile:38) ~[fa.class:?]
	at net.minecraft.util.MessageSerializer.encode(SourceFile:14) ~[fa.class:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:111) ~[MessageToByteEncoder.class:?]
	... 15 more
[09:18:31] [Server thread/INFO] [Waila]: Player EntityPlayerMP['ESCHUFLI'/683, l='enh_s', x=-1016.78, y=60.00, z=581.76] connected. Sending ping
[09:18:32] [Server thread/INFO]: ESCHUFLI lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: String too big (was 155516 bytes encoded, max 32767)], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[09:18:32] [Server thread/INFO]: ESCHUFLI left the game

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by ESCHUFLI** [comment]
Using a backup on the server does NOT solve the issue.

**Comment by chochem** [comment]
closed in favor of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11937
