### ISSUE TITLE
gregtech.log spam

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10556]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.4-dev-pre14

### Your Server

Zeta

### Your Expectation

.

### The Reality

gregtech.log spammed with thousands of these lines:
```
In rewriteAsslineRecipes Pt. 2!
In rewriteAsslineRecipes!
```
 it also spams a lot of out of bounds errors in DT structure check
```
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at gregtech.common.tileentities.machines.multi.GT_MetaTileEntity_DistillationTower.checkMachine(GT_MetaTileEntity_DistillationTower.java:265)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.checkStructure(GT_MetaTileEntity_MultiBlockBase.java:281)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:296)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:451)
	at net.minecraft.world.World.func_72939_s(World.java:2583)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1542)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)
```

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNHAfx237v7** [comment]
See also https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10459
