### ISSUE TITLE
Holoinventory rendering issue

### ISSUE THREAD

**Issue by GTNHAfx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#10773]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.4 dev 18

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Sometimes when opening a block gui (say input hatch) and using tab to exit the gui, the NEI display left and right of the player inventory is not visible. Also the player inventory is shown as empty.

Don't have a screenshot right now, will attach next time it happens.

### The Reality

Not sure if related?

Following error is spammed in fml-client-latest.log

```
[14:13:13] [Client thread/WARN] [holoinventory/]: Some error while rendering the hologram :(
[14:13:13] [Client thread/WARN] [holoinventory/]: Please make an issue on github if this happens.
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.ArithmeticException: / by zero
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.dries007.holoInventory.client.Renderer.doRenderHologram(Renderer.java:331)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.dries007.holoInventory.client.Renderer.renderHologram(Renderer.java:298)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.dries007.holoInventory.client.Renderer.doEvent(Renderer.java:139)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.dries007.holoInventory.client.Renderer.renderEvent(Renderer.java:103)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1603_Renderer_renderEvent_RenderWorldLastEvent.invoke(.dynamic)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:261)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1354)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[14:13:13] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

### Your Proposal

see where arithmetic exception comes from

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/HoloInventory/pull/25
