### ISSUE TITLE
EnderO is incompatible with waila

### ISSUE THREAD

**Issue by OMGICE** [GTNewHorizons/GT-New-Horizons-Modpack#10822]
### Your Pack Version

2.3.1.39

### Your Server

Single Player

### Your Actions

Place Redstone Conduit on the ground.

### Crash Report
<details>

  <summary>crash log</summary>

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2022-07-25 15:04:14 CST
Description: Unexpected error

java.lang.NoSuchMethodError: crazypants.util.IFacade.getFacade(Lnet/minecraft/world/IBlockAccess;IIII)Lnet/minecraft/block/Block;
    at crazypants.enderio.waila.WailaCompat.getWailaStack(WailaCompat.java:143)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:156)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:97)
    at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:66)
    at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:78)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_588_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
    at net.minecraft.client.Minecraft.func_71407_l(MinecraftMixin.java:2064)
    at net.minecraft.client.Minecraft.func_71411_J(MinecraftMixin.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(MinecraftMixin.java:3603)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['OICEMAP'/881, l='MpServer', x=171.13, y=73.62, z=237.56]]
    Chunk stats: MultiplayerChunkCache: 483, 492
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (168,64,256), Chunk: (at 8,4,0 in 10,16; contains blocks 160,0,256 to 175,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 1032 game time, 1032 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 116 total; [EntityMinecartChest['entity.MinecartChest.name'/99, l='MpServer', x=97.50, y=19.50, z=204.50], EntityChicken['鸡'/100, l='MpServer', x=93.50, y=104.00, z=222.50], EntityChicken['鸡'/101, l='MpServer', x=92.50, y=104.00, z=224.50], EntityChicken['鸡'/102, l='MpServer', x=92.50, y=104.00, z=224.50], EntityPig['猪'/104, l='MpServer', x=103.50, y=113.00, z=236.50], EntityPig['猪'/105, l='MpServer', x=101.22, y=114.00, z=240.50], EntityPig['猪'/106, l='MpServer', x=103.78, y=114.00, z=241.78], EntityPig['猪'/107, l='MpServer', x=102.50, y=114.00, z=240.19], EntityMinecartChest['entity.MinecartChest.name'/116, l='MpServer', x=104.50, y=23.34, z=207.50], EntityItem['item.tile.rail'/123, l='MpServer', x=111.78, y=24.13, z=204.72], EntityItem['item.tile.rail'/124, l='MpServer', x=112.78, y=24.13, z=199.81], EntityItem['item.tile.rail'/125, l='MpServer', x=113.16, y=24.13, z=198.81], EntitySheep['羊'/126, l='MpServer', x=114.50, y=73.00, z=203.78], EntitySheep['羊'/127, l='MpServer', x=114.50, y=73.00, z=202.19], EntitySheep['羊'/128, l='MpServer', x=118.50, y=72.00, z=200.50], EntitySheep['羊'/129, l='MpServer', x=112.50, y=74.00, z=204.50], EntityMinecartChest['entity.MinecartChest.name'/130, l='MpServer', x=104.50, y=28.50, z=231.50], EntityChicken['鸡'/131, l='MpServer', x=105.50, y=114.00, z=240.50], EntityChicken['鸡'/132, l='MpServer', x=106.50, y=114.00, z=239.50], EntityChicken['鸡'/133, l='MpServer', x=106.50, y=114.00, z=242.50], EntityChicken['鸡'/134, l='MpServer', x=106.50, y=114.00, z=245.50], EntityMinecartChest['entity.MinecartChest.name'/135, l='MpServer', x=119.50, y=26.50, z=255.50], EntityMinecartChest['entity.MinecartChest.name'/136, l='MpServer', x=104.50, y=29.50, z=256.50], EntityItem['item.tile.torch'/137, l='MpServer', x=117.16, y=26.13, z=270.88], EntityMinecartChest['entity.MinecartChest.name'/142, l='MpServer', x=128.50, y=26.50, z=257.50], EntityChicken['鸡'/143, l='MpServer', x=132.47, y=111.00, z=256.59], EntityChicken['鸡'/144, l='MpServer', x=131.16, y=108.00, z=260.16], EntityChicken['鸡'/145, l='MpServer', x=129.50, y=109.00, z=263.50], EntityChicken['鸡'/146, l='MpServer', x=132.75, y=102.00, z=269.22], EntityItem['item.item.string'/167, l='MpServer', x=137.81, y=28.13, z=199.56], EntityChicken['鸡'/168, l='MpServer', x=137.50, y=94.00, z=275.50], EntityChicken['鸡'/169, l='MpServer', x=136.50, y=93.00, z=277.50], EntityChicken['鸡'/170, l='MpServer', x=137.50, y=93.00, z=279.50], EntityChicken['鸡'/171, l='MpServer', x=138.50, y=93.00, z=279.50], EntityItem['item.tile.mushroom15'/176, l='MpServer', x=160.88, y=23.13, z=279.88], EntityChicken['鸡'/181, l='MpServer', x=174.47, y=74.00, z=201.41], EntityChicken['鸡'/182, l='MpServer', x=183.50, y=70.00, z=198.50], EntityChicken['鸡'/183, l='MpServer', x=178.78, y=72.00, z=198.94], EntityChicken['鸡'/184, l='MpServer', x=176.50, y=69.00, z=197.50], EntityCow['牛'/185, l='MpServer', x=168.22, y=67.00, z=186.50], EntityCow['牛'/186, l='MpServer', x=169.81, y=67.00, z=186.50], EntityCow['牛'/187, l='MpServer', x=172.22, y=67.00, z=188.78], EntityCow['牛'/188, l='MpServer', x=173.81, y=67.00, z=187.19], EntityItem['item.tile.torch'/189, l='MpServer', x=171.97, y=22.13, z=233.59], EntityPig['猪'/198, l='MpServer', x=230.78, y=64.00, z=209.50], EntityPig['猪'/199, l='MpServer', x=231.50, y=63.00, z=210.50], EntityPig['猪'/200, l='MpServer', x=231.50, y=63.00, z=210.50], EntityPig['猪'/201, l='MpServer', x=229.47, y=64.00, z=209.50], EntityPig['猪'/202, l='MpServer', x=218.50, y=69.00, z=225.50], EntityPig['猪'/203, l='MpServer', x=216.50, y=69.00, z=227.50], EntityPig['猪'/204, l='MpServer', x=216.50, y=69.00, z=230.50], EntityPig['猪'/205, l='MpServer', x=210.16, y=69.00, z=234.28], EntityChicken['鸡'/207, l='MpServer', x=236.50, y=69.00, z=178.50], EntityChicken['鸡'/208, l='MpServer', x=237.50, y=70.00, z=179.50], EntityChicken['鸡'/209, l='MpServer', x=237.50, y=64.00, z=182.50], EntityChicken['鸡'/210, l='MpServer', x=237.50, y=63.00, z=181.50], EntityPig['猪'/211, l='MpServer', x=232.22, y=64.00, z=169.59], EntityPig['猪'/212, l='MpServer', x=232.50, y=64.00, z=172.50], EntityPig['猪'/213, l='MpServer', x=232.50, y=64.00, z=168.03], EntityPig['猪'/214, l='MpServer', x=233.81, y=64.00, z=170.81], Entity_SpecialCreeper['爬行者'/22746, l='MpServer', x=100.50, y=19.00, z=170.50], EntityFireSkeleton['火焰骷髅弓箭手'/22747, l='MpServer', x=217.28, y=11.00, z=253.28], Entity_SpecialZombie['僵尸'/22749, l='MpServer', x=182.31, y=30.00, z=317.63], EntityItemFrame['物品展示框'/230, l='MpServer', x=270.50, y=67.50, z=122.06], EntityItemFrame['物品展示框'/231, l='MpServer', x=271.50, y=67.50, z=122.06], EntityItemFrame['物品展示框'/232, l='MpServer', x=272.50, y=67.50, z=122.06], EntityItemFrame['物品展示框'/233, l='MpServer', x=270.50, y=66.50, z=122.06], EntityItemFrame['物品展示框'/234, l='MpServer', x=271.50, y=66.50, z=122.06], EntityItemFrame['物品展示框'/235, l='MpServer', x=272.50, y=66.50, z=122.06], EntitySplittingCreeper['高速爬行者'/22924, l='MpServer', x=114.50, y=19.00, z=246.50], Entity_SpecialZombie['僵尸'/22925, l='MpServer', x=144.50, y=19.00, z=252.50], EntityFishingZombie['钓鱼僵尸'/22926, l='MpServer', x=150.50, y=19.00, z=249.50], Entity_SpecialZombie['僵尸'/22927, l='MpServer', x=250.50, y=33.00, z=274.50], Entity_SpecialSkeleton['骷髅弓箭手'/22928, l='MpServer', x=118.50, y=17.00, z=190.50], EntityHusk['尸壳'/23003, l='MpServer', x=240.50, y=33.00, z=316.50], EntityClientPlayerMP['OICEMAP'/881, l='MpServer', x=171.13, y=73.62, z=237.56], Entity_SpecialZombie['僵尸'/13360, l='MpServer', x=102.50, y=27.00, z=202.50], EntityNinjaSkeleton['忍者骷髅弓箭手'/21606, l='MpServer', x=155.50, y=27.00, z=173.50], EntityBat['蝙蝠'/1310, l='MpServer', x=247.91, y=13.00, z=206.13], EntityCaveSpider['洞穴蜘蛛'/3369, l='MpServer', x=-36.50, y=-48.62, z=-20.50], Entity_SpecialZombie['冷酷无情的 僵尸'/1327, l='MpServer', x=227.50, y=17.00, z=251.50], EntityItem['item.item.seedrice'/21819, l='MpServer', x=178.25, y=67.13, z=266.78], EntityBat['蝙蝠'/1386, l='MpServer', x=157.88, y=18.00, z=166.44], EntityFireCreeper['火焰爬行者'/1405, l='MpServer', x=101.50, y=27.00, z=162.50], Entity_SpecialSkeleton['骷髅弓箭手'/1407, l='MpServer', x=103.03, y=27.00, z=163.38], Entity_SpecialZombie['僵尸'/1420, l='MpServer', x=245.50, y=18.00, z=228.50], EntityItem['item.item.feather'/21906, l='MpServer', x=178.16, y=72.13, z=199.63], EntityItem['item.tile.flower2.poppy'/21913, l='MpServer', x=148.59, y=22.13, z=175.91], EntityBat['蝙蝠'/1437, l='MpServer', x=105.50, y=29.01, z=193.75], EntityBlitz['狂风人'/1470, l='MpServer', x=217.50, y=12.00, z=260.50], EntityBat['蝙蝠'/1472, l='MpServer', x=169.56, y=37.42, z=269.94], EntityBat['蝙蝠'/1473, l='MpServer', x=169.22, y=37.20, z=272.66], Entity_SpecialCreeper['爬行者'/1480, l='MpServer', x=135.97, y=21.00, z=258.41], EntityJumpingCreeper['跳跃爬行者'/1559, l='MpServer', x=111.50, y=27.00, z=194.50], Entity_SpecialZombie['僵尸'/1560, l='MpServer', x=107.50, y=27.00, z=193.50], Entity_SpecialSkeleton['骷髅弓箭手'/22050, l='MpServer', x=110.50, y=34.00, z=196.50], Entity_SpecialZombie['僵尸'/1610, l='MpServer', x=180.63, y=24.00, z=282.72], EntityBat['蝙蝠'/1611, l='MpServer', x=186.31, y=23.00, z=298.16], EntityBat['蝙蝠'/1613, l='MpServer', x=244.25, y=17.00, z=221.53], EntityBat['蝙蝠'/22093, l='MpServer', x=185.59, y=26.00, z=309.41], EntityBat['蝙蝠'/22094, l='MpServer', x=187.75, y=25.00, z=304.13], EntityBat['蝙蝠'/1614, l='MpServer', x=247.69, y=17.00, z=222.66], EntityBat['蝙蝠'/1615, l='MpServer', x=245.72, y=17.00, z=224.38], EntityBat['蝙蝠'/22095, l='MpServer', x=245.47, y=28.16, z=270.06], Entity_SpecialSpider['蜘蛛'/22108, l='MpServer', x=176.50, y=24.00, z=274.50], Entity_SpecialSpider['蜘蛛'/22109, l='MpServer', x=129.19, y=14.00, z=191.28], Entity_SpecialSkeleton['骷髅弓箭手'/22111, l='MpServer', x=118.91, y=14.00, z=190.59], Entity_SpecialSkeleton['骷髅弓箭手'/22112, l='MpServer', x=122.13, y=14.00, z=192.72], Entity_SpecialSkeleton['骷髅弓箭手'/22115, l='MpServer', x=123.50, y=14.00, z=193.50], Entity_SpecialCreeper['爬行者'/1654, l='MpServer', x=107.50, y=40.00, z=195.50], EntityPoisonSpider['剧毒蜘蛛'/1689, l='MpServer', x=217.09, y=27.00, z=313.09], Entity_SpecialSpider['蜘蛛'/1690, l='MpServer', x=221.03, y=27.00, z=314.41], EntityDarkCreeper['黑暗爬行者'/1764, l='MpServer', x=236.50, y=40.00, z=251.50], Entity_SpecialSkeleton['骷髅弓箭手'/1840, l='MpServer', x=110.50, y=28.00, z=258.50], Entity_SpecialZombie['僵尸'/1868, l='MpServer', x=106.50, y=40.00, z=194.50], Entity_SpecialCreeper['爬行者'/1947, l='MpServer', x=90.50, y=24.00, z=186.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.Minecraft.func_71396_d(MinecraftMixin.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(MinecraftMixin.java:3614)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 11 (amd64) version 10.0
    Java Version: 1.8.0_333, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1115963904 bytes (1064 MB) / 2669674496 bytes (2546 MB) up to 14602469376 bytes (13926 MB)
    JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx13926m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 12, tcache: 94, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 94 mods loaded, 94 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA    FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA    Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA    CodeChickenCore{1.1.5} [CodeChicken Core] (minecraft.jar) 
    UCHIJAAAA    InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
    UCHIJAAAA    NotEnoughItems{2.2.19-GTNH} [NotEnoughItems] (NotEnoughItems-1.7.10-2.2.19-GTNH.jar) 
    UCHIJAAAA    se{0.4.1} [Super Enchants] (minecraft.jar) 
    UCHIJAAAA    <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    UCHIJAAAA    FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
    UCHIJAAAA    WorldEngine{1.1710.0} [WorldEngine] (1.7.10-ASJCore-1.2.0.0.jar) 
    UCHIJAAAA    asjpatcher{1.0} [asjpatcher] (1.7.10-ASJCore-1.2.0.0.jar) 
    UCHIJAAAA    hearts{1.0} [Hearts] ([1.7.10][1.7.2]+Heart+Crystal+1.0.jar) 
    UCHIJAAAA    flammpfeil.slashblade{mc1.7.10-r88} [SlashBlade] (SlashBlade-mc1.7.10-r88.jar) 
    UCHIJAAAA    flammpfeil.nihil{mc1.7.x-r8} [Nihil] ([1.7.X]-拔刀剑附属似蛭-Nihil-r8.jar) 
    UCHIJAAAA    levels{r3.0.1} [Levels] ([Secretmine.net]-《1.7.10》等级系统MOD.jar) 
    UCHIJAAAA    Yamazakura{1.0.0} [Yamazakura] ([山樱]SlashBlade-Yamazakura-mc1.7-r4.jar) 
    UCHIJAAAA    KeepingInventory{1.6} [Keeping Inventory] ([死亡不掉落MOD]KeepingInventory[1.7.10].jar) 
    UCHIJAAAA    Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA    Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJAAAA    harvestcraft{1.7.10j} [Pam's HarvestCraft] ([潘马斯丰收工艺]Pam's+HarvestCraft+1.7.10Lb.jar) 
    UCHIJAAAA    InfernalMobs{1.6.6} [Infernal Mobs] ([精英怪]InfernalMobs-1.7.10.jar) 
    UCHIJAAAA    falsepatternlib{0.9.4} [FalsePatternLib] (falsepatternlib-mc1.7.10-0.9.4.jar) 
    UCHIJAAAA    animfix{2.0.0-hotfix1} [AnimFix] (animfix-mc1.7.10-2.0.0-hotfix1.jar) 
    UCHIJAAAA    AppleCore{3.1.1} [AppleCore] (AppleCore-1.7.10-3.1.1.jar) 
    UCHIJAAAA    BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] (Bamboo-2.6.8.5.jar) 
    UCHIJAAAA    bamboolightplus{1.0.0} [BambooLight Plus] (bamboolight plus 1.0.0 MC1.7.10.jar) 
    UCHIJAAAA    BetterAchievements{0.1.0} [Better Achievements] (BetterAchievements-1.7.10-0.1.0.jar) 
    UCHIJAAAA    bettercrashes{@VERSION@} [BetterCrashes] (bettercrashes-1.7.10-1.1.3-GTNH.jar) 
    UCHIJAAAA    flammpfeil.slashblade.blademaster{mc1.7.2-r1} [BladeMaster] (BladeMaster-mc1.7.2-r1.2.jar) 
    UCHIJAAAA    bloodblade{1.0.0} [bloodblade] (BloodBlade1.3.9Final.jar) 
    UCHIJAAAA    Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
    UCHIJAAAA    campfirebackport{1.7.10-1.9.2} [Campfire Backport] (campfirebackport-1.7.10-1.9.2.jar) 
    UCHIJAAAA    ChestTransporter{2.0.6} [Chest Transporter] (ChestTransporter-1.7.10-2.0.6.jar) 
    UCHIJAAAA    CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
    UCHIJAAAA    cookingbook{1.0.140} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.140.jar) 
    UCHIJAAAA    cmm{1.0 by Dot_Silver} [Craftable Music Discs Mod - MCV 1.7.10] (Craftable Music Discs Mod 1.7.10.jar) 
    UCHIJAAAA    flammpfeil.darkraven{mc1.7.2-r2} [DarkRaven] (DarkRaven-mc1.7.2-r2.jar) 
    UCHIJAAAA    eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJAAAA    eide{1.0a} [Enchantment ID Extender] (EnchantmentIDExtender-1.0a.jar) 
    UCHIJAAAA    endercore{0.2.9} [EnderCore] (endercore-1.7.10-0.2.9.jar) 
    UCHIJAAAA    Waila{1.5.21} [Waila] (Waila-1.7.10-1.5.21.jar) 
    UCHIJAAAA    EnderIO{2.3.1.39} [Ender IO] (EnderIO-1.7.10-2.3.1.39.jar) 
    UCHIJAAAA    endlessids{1.3.0} [EndlessIDs] (endlessids-mc1.7.10-1.3.0.jar) 
    UCHIJAAAA    HardcoreEnderExpansion{1.9.3-GTNH} [Hardcore Ender Expansion] (HardcoreEnderExpansion-1.7.10-1.9.3-GTNH.jar) 
    UCHIJAAAA    TwilightForest{2.3.8.15} [The Twilight Forest] (TwilightForest-1.7.10-2.3.8.15.jar) 
    UCHIJAAAA    etfuturum{2.4.0} [§5§oEt Futurum Requiem] (Et_Futurum_Requiem-2.4.0.jar) 
    UCHIJAAAA    fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
    UCHIJAAAA    flammpfeil.fluorescentbar{mc1.7.2-r3} [fluorescentbar] (FluorescentBar-mc1.7.2-r3.jar) 
    UCHIJAAAA    foxex{1.1.2} [FoxBlade Extra] (FoxExtra狐月刀改 v1.1.2(MC1710).jar) 
    UCHIJAAAA    ganysend{1.11.3} [Gany's End] (Ganys+End-1.11.3.jar) 
    UCHIJAAAA    ganysnether{1.8.3} [Gany's Nether] (Ganys+Nether-1.8.3.jar) 
    UCHIJAAAA    GodFox{1.0.0} [GodFox] (GodFox1.1.5Final.jar) 
    UCHIJAAAA    immersivesnow{1.0b} [Immersive Snow] (immersive-snow-1.7.10-1.0b.jar) 
    UCHIJAAAA    IC2{2.2.828-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.828-experimental.jar) 
    UCHIJAAAA    inventorytweaks{1.5.15} [Inventory Tweaks] (inventorytweaks-1.7.10-1.5.15.jar) 
    UCHIJAAAA    ironbackpacks{1.7.10-1.2.20} [Iron Backpacks] (IronBackpacks-1.7.10-1.2.20.jar) 
    UCHIJAAAA    IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJAAAA    flammpfeil.slashblade.kirisaya{r1} [SlashBlade-Kirisaya] (Kirisaya-r1.jar) 
    UCHIJAAAA    MaterialsPlus{1.0.0} [MaterialsPlus] (MaterialsPlus+1.0+(1.7.10).jar) 
    UCHIJAAAA    Wa{1.7.10.16} [Wa] (mcmap.cc-[和风MOD][1.7.10].jar) 
    UCHIJAAAA    AencEx{0.0.1} [AencEx] (mcmap.cc-[更多的附魔MOD][1.7.10].jar) 
    UCHIJAAAA    me{1.3.2.1} [More Enchantments] (mcmap.cc-[更多的附魔MOD][1.7.10].jar) 
    UCHIJAAAA    mixingasm{0.2.1} [Mixingasm] (mixingasm-1.7.10-0.2.1.jar) 
    UCHIJAAAA    modernsplash{@VERSION@} [ModernSplash] (modernsplash-1.7.10-2c17c9a.jar) 
    UCHIJAAAA    flammpfeil.slashblade.murasamablade{mc1.7.2-r3.2} [murasamablade] (MurasamaBlade-mc1.7.2-r3.2.jar) 
    UCHIJAAAA    MysteriumLib{1.0} [§5Mysterium§aLib ] (MysteriumLib-1.0.jar) 
    UCHIJAAAA    neodymium{0.1.5} [Neodymium] (neodymium-1.7.10-0.1.5.jar) 
    UCHIJAAAA    netherlicious{3.2.3} [§6Netherlicious] (netherlicious-3.2.3.jar) 
    UCHIJAAAA    netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.7.10-1.1.1.jar) 
    UCHIJAAAA    recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-1.7.10-0.3.2.jar) 
    UCHIJAAAA    nechar{1.4.6} [Not Enough Characters] (NotEnoughCharacters-1.7.10-1.4.7.jar) 
    UCHIJAAAA    notenoughpets{2.3.3} [§eNot Enough Pets] (NotEnoughPets-1.7.10-2.3.3.jar) 
    UCHIJAAAA    skinport{1.7.10-v10d} [SkinPort] (SkinPort-1.7.10-v10d.jar) 
    UCHIJAAAA    flammpfeil.slashblade.anvilenchant{mc1.7.10-r1} [Slashblade-AnvilEnchant] (Slashblade-AnvilEnchant-mc1.7.10-r1.jar) 
    UCHIJAAAA    flammpfeil.slashblade.kamuy{mc1.7.10-r6} [Kamuy] (SlashBlade-Kamuy-mc1.7.10-r6.jar) 
    UCHIJAAAA    flammpfeil.slashblade.laemmle{mc1.7.10-r1} [Slashblade-Laemmle] (Slashblade-Laemmle-mc1.7.10-r1.jar) 
    UCHIJAAAA    flammpfeil.slashblade.zephyr{1.7.2 r1.2} [SlashBladeZephyr] (SlashBlade_Zephyr-mc1.7.2-r1.2.2.jar) 
    UCHIJAAAA    flammpfeil.slashbladewa{mc1.7.2-r1} [SlashBladeWa] (SlashBladeWa-mc1.7.2-r1.jar) 
    UCHIJAAAA    soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
    UCHIJAAAA    SpecialMobs{3.3.11} [Special Mobs] (SpecialMobs-1.7.10-3.3.11.jar) 
    UCHIJAAAA    spongemixins{1.5.0} [SpongeMixins Loader] (SpongeMixins-1.5.0.jar) 
    UCHIJAAAA    ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
    UCHIJAAAA    TofuCraft{2.1.6-MC1.7.10} [豆腐Craft (TofuCraft)] (TofuCraft-2.1.6-MC1.7.10.jar) 
    UCHIJAAAA    mrblade{2.12} [Technology Revolution Blade Extra] (TRblade技术革新 v2.1.2[MC1.7.10].jar) 
    UCHIJAAAA    VeinMiner{0.36.0_1.7.10-28a7f13} [Vein Miner] (VeinMiner-1.7.10-0.36.0.496+28a7f13.jar) 
    UCHIJAAAA    VeinMinerModSupport{0.36.0_1.7.10-28a7f13} [Mod Support] (VeinMiner-1.7.10-0.36.0.496+28a7f13.jar) 
    UCHIJAAAA    VillageNames{4.3.12} [§6Village Names] (VillageNames-1.7.10-4.3.12.jar) 
    UCHIJAAAA    WailaHarvestability{1.1.10-GTNH} [Waila Harvestability] (WailaHarvestability-1.7.10-1.1.10-GTNH.jar) 
    UCHIJAAAA    flammpfeil.slashblade.wanderer{mc1.7.2-r1} [SlashBladeWanderer] (Wanderer-mc1.7.2-r1.jar) 
    UCHIJAAAA    wawla{1.1.3-GTNH} [What Are We Looking At] (Wawla-1.7.10-1.1.3-GTNH.jar) 
    UCHIJAAAA    waystones{1.0.0} [Waystones] (Waystones_Jawsawn_Fork-mc1.7.10-1.0.0.jar) 
    UCHIJAAAA    weaponmod{v1.17.0} [Balkon's WeaponMod] (weaponmod-v1.17.0.jar) 
    UCHIJAAAA    flammpfeil.frostwolf{mc1.7.2-r1} [FrostWolf] (冰狼之刃-FrostWolf-mc1.7.2-r1.1.jar) 
    UCHIJAAAA    ironfurnaces{1.2} [Iron Furnaces] (更多熔炉.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.72' Renderer: 'NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2'
    CoFHCore: -[1.7.10]3.1.4-329
    ThermalFoundation: -[1.7.10]1.2.6-118
    EnderIO: Found the following problem(s) with your installation:
                  * Optifine is installed. This is NOT supported.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
    Suspected Mods: Ender IO (EnderIO), Waila (Waila)
    Launched Version: 1.7.10
    LWJGL: 2.9.1
    OpenGL: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.72, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: [Modernity-format1-v3.7.0.zip]
    Current Language: 简体中文 (中国)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
    Client Crashes Since Restart: 1
    Integrated Server Crashes Since Restart: 0
```

</details>
### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
can you double check the modpack version? 2.3.1.39 doesn't exist

**Comment by OMGICE** [comment]
> 你能仔细检查modpack版本吗？2.3.1.39 不存在

Yes, 1.7.10

**Comment by miozune** [comment]
It's NOT GTNH modpack but our EIO and Waila repo don't have issue form so you're posting here right?

**Comment by OMGICE** [comment]
> 它不是GTNH modpack，但是我们的EIO和Waila存储库没有问题表单，所以你在这里发帖对吗？

Yes, you're right :D
