### ISSUE TITLE
AE2 crash with level emitter

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#11210]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

appliedenergistics2-1.7.10-rv3-beta-103-GTNH-1-ga40ee74

### Your Server

priv srv

### Your Actions

I downloaded the latest (103) AE2 build and opened an inventory which contains an ME Level Emitter.
When using version 101, it works fine.

### Crash Report

[crash-2022-09-03_22.03.56-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9483328/crash-2022-09-03_22.03.56-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
hmm. This crash sounds concerning with regards to stable, but I am completely unable to reproduce it.

**Comment by chochem** [comment]
just to be sure I took that jenkins version. but no problems on my end.

**Comment by Szajkop** [comment]
Now I could not repliacte it either. I tried it again with a fresh install from GTNewHorizonsClient-1.7.10-2.1.2.4-29-pre with the v103 AE2 and its working fine. Maybe something else fucked with my main client, coz i needed to update many other mods from jenkins.

other note: before the crash happened there was en error thrown in the chat that some rendering had stackoverflow exception. After, when i opened my backpack all the items after the level emitter was invisible. When i tried to grab the level emitters it crashed.

**Comment by chochem** [comment]
do you have that overflow error in some log file?

**Comment by Szajkop** [comment]
[logs.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9484389/logs.zip)

**Comment by eigenraven** [comment]
Relevant stacktrace:
```
[11:30:19] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
	at xyz.kubasz.personalspace.world.PersonalWorldProvider.getSaveFolder(PersonalWorldProvider.java:127) ~[PersonalWorldProvider.class:?]
	at net.minecraft.world.chunk.storage.AnvilSaveHandler.func_75763_a(AnvilSaveHandler.java:26) ~[aym.class:?]
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:653) ~[mt.class:?]
	at net.minecraft.world.World.<init>(World.java:245) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) ~[mt.class:?]
	at WorldServerOF.<init>(WorldServerOF.java:69) ~[WorldServerOF.class:?]
	at WorldServerMultiOF.<init>(WorldServerMultiOF.java:23) ~[WorldServerMultiOF.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:72) ~[bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[11:30:19] [Server thread/ERROR]: This crash report has been saved to: C:\Users\SSD500\Desktop\gt\.\crash-reports\crash-2022-09-04_11.30.19-server.txt
[11:30:41] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
	at xyz.kubasz.personalspace.world.PersonalWorldProvider.getSaveFolder(PersonalWorldProvider.java:127) ~[PersonalWorldProvider.class:?]
	at net.minecraft.world.chunk.storage.AnvilSaveHandler.func_75763_a(AnvilSaveHandler.java:26) ~[aym.class:?]
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:653) ~[mt.class:?]
	at net.minecraft.world.World.<init>(World.java:245) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) ~[mt.class:?]
	at WorldServerOF.<init>(WorldServerOF.java:69) ~[WorldServerOF.class:?]
	at WorldServerMultiOF.<init>(WorldServerMultiOF.java:23) ~[WorldServerMultiOF.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:72) ~[bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[11:30:41] [Server thread/ERROR]: This crash report has been saved to: C:\Users\SSD500\Desktop\gt\.\crash-reports\crash-2022-09-04_11.30.41-server.txt
```

Looks like an interaction between optifine and personalspace, probably OF constructing dimension providers in an incompatible way. I'll have a look what it actually does to try to work around it.

**Comment by eigenraven** [comment]
The rendering errors are also real, but because it's a generic GL error captured at the end of the frame I don't think we can easily figure out what causes it, unless you manage to capture a trace with <https://apitrace.github.io/> while the rendering error happens.

**Comment by kuba6000** [comment]
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/compare/rv3-beta-101-GTNH...rv3-beta-103-GTNH#diff-0bec268c8094a70a5cfa23156678cc1f1683d26df2a9223a8def26d42b1e5041R111-R113
This code cant run client sided

**Comment by eigenraven** [comment]
Ticking TEs only happens on the server-side, and MinecraftServer.getServer() works both for dedicated servers and integrated singleplayer server.

**Comment by kuba6000** [comment]
> Ticking TEs only happens on the server-side, and MinecraftServer.getServer() works both for dedicated servers and integrated singleplayer server.

Yes, but it doesn't work on client that is connecting to a dedicated server

**Comment by Szajkop** [comment]
It seems like my message disappeared when i posted the zip file. For some context of the log: When i did the testing i joined my server and there i took the screenshots and experienced the rendering error. After that i tried to make a new single player world to test it again. While creating the world it crashed with the personaldim exception. (This is a new one and i think its not related to the ae2 error what u can see in the original crash report)

**Comment by Szajkop** [comment]
I tested the appliedenergistics2-1.7.10-rv3-beta-103-GTNH-2-ge669596.jar and both issues are gone. I could load into the SP world and place level emitters on the server. Thanks
