### ISSUE TITLE
Crash when use wireless me terminal to search recipe from NEI

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#11260]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.2.0.0 RC1

### Your Server

SP

### Type of Server

Single Player

### Your Actions

I just log in the game and want to craft a new defult quest update block
After left click on that item in NEI 
Crashed

### Crash Report

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2022-09-10 00:13:46 CEST
Description: Rendering screen

java.lang.NoClassDefFoundError: net/p455w0rd/wirelesscraftingterminal/client/me/ItemRepo
    at com.github.vfyjxf.nee.utils.IngredientTracker.getCraftableStacks(IngredientTracker.java:94)
    at com.github.vfyjxf.nee.utils.IngredientTracker.<init>(IngredientTracker.java:46)
    at com.github.vfyjxf.nee.client.NEEContainerDrawHandler.initIngredientTracker(NEEContainerDrawHandler.java:208)
    at com.github.vfyjxf.nee.client.NEEContainerDrawHandler.onDrawScreen(NEEContainerDrawHandler.java:91)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1775_NEEContainerDrawHandler_onDrawScreen_Post.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1062)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3104)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: net.p455w0rd.wirelesscraftingterminal.client.me.ItemRepo
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 25 more
Caused by: java.lang.NullPointerException

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by KamenriderZO** [comment]
![image](https://user-images.githubusercontent.com/77818313/189457172-54fb6535-a3fb-4358-9982-497d8b365183.png)

**Comment by Alexdoru** [comment]
update this mod to fix the crash https://github.com/GTNewHorizons/NotEnoughEnergistics/releases/download/1.3.17/NotEnoughEnergistics-1.7.10-1.3.17.jar
