### ISSUE TITLE
Crash when request a recipe of small osmium gear

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#11278]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.2.0.0 RC 1

### Your Server

SP

### Your Actions

Request a Craft to make small osmium gear through Wireless Universal Terminal
then Crash

### Crash Report

![image](https://user-images.githubusercontent.com/77818313/189505759-b76f4c3f-73e7-4bd1-9693-be08fab74ff0.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by KamenriderZO** [comment]
Report :
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2022-09-11 01:58:22 CEST
Description: Updating screen events

cpw.mods.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: cancel
    at cpw.mods.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:121)
    at cpw.mods.fml.common.ObfuscationReflectionHelper.getPrivateValue(ObfuscationReflectionHelper.java:60)
    at com.github.vfyjxf.nee.client.GuiEventHandler.getCancelButton(GuiEventHandler.java:96)
    at com.github.vfyjxf.nee.client.GuiEventHandler.onCraftConfirmActionPerformed(GuiEventHandler.java:82)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1768_GuiEventHandler_onCraftConfirmActionPerformed_Post.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:227)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:326)
    at appeng.client.gui.AEBaseGui.func_73864_a(AEBaseGui.java:305)
    at appeng.client.gui.implementations.GuiCraftConfirm.func_73864_a(GuiCraftConfirm.java:537)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at appeng.client.gui.AEBaseGui.func_146274_d(AEBaseGui.java:641)
    at appeng.client.gui.implementations.GuiCraftConfirm.func_146274_d(GuiCraftConfirm.java:552)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3104)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: cancel
    at cpw.mods.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:94)
    at cpw.mods.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:117)
    ... 33 more
Caused by: java.lang.NoSuchFieldException: cancel
    at java.lang.Class.getDeclaredField(Unknown Source)
    at cpw.mods.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:85)
    ... 34 more


A detailed walkthrough of the error, its code path and all known details is as follows:
------------------

**Comment by Alexdoru** [comment]
should be fixed https://github.com/GTNewHorizons/NotEnoughEnergistics/releases/download/1.3.18/NotEnoughEnergistics-1.7.10-1.3.18.jar
