### ISSUE TITLE
Attempting to place items in 2x2 player crafting grid causes crash to main menu on MP

### ISSUE THREAD

**Issue by Hachuurui** [GTNewHorizons/GT-New-Horizons-Modpack#11350]
### Your GTNH Discord Username

Hachuurui

### Your Pack Version

2.2.0.0 -RC3

### Your Server

gtnh.twpi.pw

### Type of Server

Thermos

### Your Expectation

Being able to craft in 2x2 crafting grid. In this case, I was attempting to make the Multiblock Hologram thingy from TecTec to see multiblocks. 

### The Reality

The moment you place any item in the 2x2 grid, you're kicked to the main menu and disconnected from the server. 

In this case, I placed a piece of paper. The item vanishes each time as well. Tested it also with a piece of lapis dust. 

### Your Proposal

No clue here XD I guess see if we can find why it happens? Nothing appears in the server log. Going to see if I can get a client log. Will also record it happening for you.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hachuurui** [comment]
Error caught:

java.lang.ClassCastException: bq_standard.handlers.PlayerContainerListener cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:105) ~[aap.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(InventoryCrafting.java:153) ~[aae.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77) ~[aay.class:?]
	at net.minecraft.inventory.Container.func_75144_a(Container.java:418) ~[zs.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2075) ~[nh.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Comment by Hachuurui** [comment]
Seems related to thermos
https://github.com/Funwayguy/BetterQuesting/issues/605

**Comment by mitchej123** [comment]
There is a mod on GitHub to fix this.  Please search next time. https://github.com/GTNewHorizons/BQ3-Thermos-patch
