### ISSUE TITLE
enderstroage crash

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#11431]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

RC3

### Your Server

priv srv

### Your Actions

this crash happened randomly while i was on the server. The log generated on the server console and the client got disconnected.

### Crash Report

`[16:01:05] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel ES
java.lang.NullPointerException
        at codechicken.enderstorage.storage.liquid.TankSynchroniser.handleVisiblityPacket(TankSynchroniser.java:269) ~[TankSynchroniser.class:?]
        at codechicken.enderstorage.internal.EnderStorageSPH.handlePacket(EnderStorageSPH.java:18) ~[EnderStorageSPH.class:?]
        at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:117) ~[PacketCustom$ServerInboundHandler.class:?]
        at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:78) ~[PacketCustom$CustomInboundHandler.class:?]
        at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:64) ~[PacketCustom$CustomInboundHandler.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
`

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
