### ISSUE TITLE
Breaking a vanilla sign disconnects the player from the server

### ISSUE THREAD

**Issue by christianvdstap** [GTNewHorizons/GT-New-Horizons-Modpack#11451]
### Your GTNH Discord Username

Lalaru

### Your Pack Version

2.2.0.0

### Your Server

Eta

### Your Expectation

Not being disconnected when breaking a sign

### The Reality

See title

### Your Proposal

Don't get disconnected when breaking a sign

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment]
Please include any relevant logs from the disconnect

**Comment by christianvdstap** [comment]
Nothing much to see in the log:
[16:05:39] [Client thread/INFO]: [CHAT] HonyMel_salmon joined the game.
[16:05:50] [Client thread/INFO]: [CHAT] [DSC] boubou_19: @Lalaru can you break a sign?
[16:05:58] [Client thread/INFO]: [CHAT] [Broadcast]: You can now automate your anchors with pipes.
[16:06:07] [Netty Client IO #13/INFO]: Restoring client configs.
[16:06:07] [Netty Client IO #13/INFO]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[16:06:07] [Netty Client IO #13/INFO]: Reset configs to client values for tterrag.wailaplugins.config.WPConfigHandler
[16:06:07] [Netty Client IO #13/INFO]: Unregistered Dimension: 30
... some more Unregistered Dimension ...
[16:06:07] [Netty Client IO #13/INFO]: Unregistered Dimension: 48
[16:06:07] [Netty Client IO #13/INFO]: Deregistering PersonalSpace dimension 196
... some more Deregistering PersonalSpace dimension ...
[16:06:07] [Netty Client IO #13/INFO]: Deregistering PersonalSpace dimension 197
[16:06:07] [Netty Client IO #13/INFO]: Scheduling client settings reset.
[16:06:07] [Client thread/INFO]: Mapping halted in /home/christian/games/technic/modpacks/mcnewhorizons/journeymap/data/mp/Official~GTNH~Server~3~EU_7dc26850~7fc1~4bb2~a5f5~b85d97c93a81/DIM0
[16:06:07] [Client thread/INFO]: Applying holder lookups
[16:06:07] [Client thread/INFO]: Holder lookups applied
[16:07:01] [Client thread/INFO]: World ID has been reset.
[16:07:01] [Client thread/INFO]: World UID is set to: null
[16:07:04] [Client thread/INFO]: Connecting to playeta.gtnewhorizons.com., 25565
[16:07:05] [Netty Client IO #14/INFO]: Server protocol version 2
[16:07:05] [Netty Client IO #14/INFO]: Attempting connection with missing mods [Aroma1997Core, NettyPatch_ASM, FastCraft, Aroma1997CoreHelper, AromaBackup, AromaBackupRecovery, beebetteratbees, BetterAchievements, bettercrashes, betterloadingscreen, controlling, craftpresence, CustomMainMenu, defaultserverlist, defaultworldgenerator, Ic2Nei, InGameInfoXML, inventorytweaks, itlt, journeymap, MouseTweaks, NettyPatch, oauth, overloadedarmorbar, ResourceLoader, Schematica, tcnodetracker, TiCTooltips, torohealthmod] at SERVER
[16:07:05] [Netty Client IO #14/INFO]: Injecting existing block and item data into this client instance

**Comment by mitchej123** [comment]
Anything in any of the other logs? latest.log? fml-latest-client.log?  @boubou19 Anything server side around this time?

**Comment by boubou19** [comment]
it's myessentials that is missbehaving: 
```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchFieldException: myEssentials
	at myessentials.classtransformers.SignClassTransformer.getMyEssentialsDataValue(SignClassTransformer.java:81) ~[SignClassTransformer.class:?]
	at myessentials.entities.api.sign.SignManager.loadSign(SignManager.java:29) ~[SignManager.class:?]
	at myessentials.entities.api.sign.SignManager.onPlayerBreaksBlock(SignManager.java:59) ~[SignManager.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_649_SignManager_onPlayerBreaksBlock_BreakEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.58]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.58]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:482) ~[ForgeHooks.class:1.7.10-1614.58]
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(Unknown Source) ~[mx.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(Unknown Source) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:761) ~[nh.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) ~[ji.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) ~[ji.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: myEssentials
	at myessentials.classtransformers.SignClassTransformer.getMyEssentialsDataField(SignClassTransformer.java:65) ~[SignClassTransformer.class:?]
	at myessentials.classtransformers.SignClassTransformer.getMyEssentialsDataValue(SignClassTransformer.java:79) ~[SignClassTransformer.class:?]
	... 18 more
Caused by: java.lang.NoSuchFieldException: myEssentials
	at java.lang.Class.getField(Class.java:1703) ~[?:1.8.0_292]
	at myessentials.classtransformers.SignClassTransformer.getMyEssentialsDataField(SignClassTransformer.java:62) ~[SignClassTransformer.class:?]
	at myessentials.classtransformers.SignClassTransformer.getMyEssentialsDataValue(SignClassTransformer.java:79) ~[SignClassTransformer.class:?]
	... 18 more
[16:06:11] [Server thread/INFO]: alphaest lost connection: Internal server error
```

**Comment by Glordir** [comment]
Right-clicking a sign (an already placed down one) also causes a disconnect.
I assume it has the same cause as breaking one.

**Comment by christianvdstap** [comment]
> Right-clicking a sign (an already placed down one) also causes a disconnect. I assume it has the same cause as breaking one.

Yes, same thing happens then
