### ISSUE TITLE
Server Hang on witch something

### ISSUE THREAD

**Issue by Glease** [GTNewHorizons/GT-New-Horizons-Modpack#11520]
### Your GTNH Discord Username

glee8e

### Your Pack Version

2.2.0.0-RC3

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Actions

Idling

### Crash Report

Thread dump
```
"Server thread" - Thread t@60
   java.lang.Thread.State: RUNNABLE
        at net.minecraft.world.World.func_94576_a(World.java:3199)
        at net.minecraft.world.World.func_72839_b(World.java:3186)
        at net.minecraft.entity.EntityLivingBase.func_85033_bc(EntityLivingBase.java:1830)
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1820)
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
        at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
        at net.minecraft.entity.monster.EntityWitch.func_70636_d(SourceFile:140)
        at toast.specialMobs.entity.witch.Entity_SpecialWitch.func_70636_d(Entity_SpecialWitch.java:200)
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
        at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
        at net.minecraft.world.World.func_72866_a(World.java:2070)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
        at net.minecraft.world.World.func_72870_g(World.java:2034)
        at net.minecraft.world.World.func_72939_s(World.java:1887)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1145)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at fastcraft.u.a(F:289)
        at fastcraft.H.aq(F:36)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

CPU sampling confirms this is taking up 100% cpu cycles, so it's safe to say something seriously wrong is happening.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
My guess would be this witch somehow getting a (-infinity,infinity) bounding box (or nan, or something similar) and caused it to work in awkward ways...

**Comment by Glease** [comment]
For some reason this witch has its bounding box's Z be around -3E13, where it should be 64-79 as it's in (-21. 4) chunk
![img](https://user-images.githubusercontent.com/4586901/193468607-5e6bc0d1-32d4-475d-bc89-a9e88ddaf879.png)

By brute force trying I'm 99.999% sure this is not the result of a bit flip. However, I'm unable to identify the actual source of this -3E13.

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
