### ISSUE TITLE
NEI Bookmark Drag & Drop constantly crashes when using items for patterns

### ISSUE THREAD

**Issue by S4mpsa** [GTNewHorizons/GT-New-Horizons-Modpack#11531]
### Your GTNH Discord Username

Sampsa#2464

### Your Pack Version

2.2.0.0

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Actions

Move bookmarked items into a pattern terminal. This also reorders the bookmarks tab, which is likely related and very annoying behavior.

### Crash Report

`java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:424)
    at java.util.ArrayList.remove(ArrayList.java:501)
    at codechicken.nei.BookmarkPanel$BookmarkGrid.removeItem(BookmarkPanel.java:269)
    at codechicken.nei.BookmarkPanel.handleDraggedClick(BookmarkPanel.java:1108)
    at codechicken.nei.PanelWidget.handleClickExt(PanelWidget.java:244)
    at codechicken.nei.LayoutManager.mouseClicked(LayoutManager.java:188)
    at codechicken.nei.guihook.GuiContainerManager.mouseClicked(GuiContainerManager.java:409)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java)
    at appeng.client.gui.AEBaseGui.func_73864_a(AEBaseGui.java:305)
    at com.glodblock.github.client.gui.GuiFCBaseMonitor.func_73864_a(GuiFCBaseMonitor.java:360)
    at com.glodblock.github.client.gui.GuiBaseFluidPatternTerminalEx.func_73864_a(GuiBaseFluidPatternTerminalEx.java:242)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at appeng.client.gui.AEBaseGui.func_146274_d(AEBaseGui.java:641)
    at com.glodblock.github.client.gui.GuiBaseFluidPatternTerminalEx.func_146274_d(GuiBaseFluidPatternTerminalEx.java:264)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3104)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by S4mpsa** [comment]
The crash doesn't happen every time, but consistently enough that adding multiple ghost items reliably crashes.

**Comment by Godelboard** [comment]
Not sure if this was same issue but it's probably related since it's the same reproduction steps:

In 2.1.2.3qf, I was able to drag and drop items from bookmarks or NEI directly logistics pipes interfaces (item filters, fluid filters, request table). In 2.2.0.0 now it's no longer working. However it does not cause a crash.

Just wanted to add that here since not sure it warranted its own ticket.
