### ISSUE TITLE
Server client kick on inventory crafting event

### ISSUE THREAD

**Issue by X-Niter** [GTNewHorizons/GT-New-Horizons-Modpack#11610]
### Your GTNH Discord Username

X_Niter#2563

### Your Pack Version

2.2.0.0

### Your Server

Private/Whitelisted server on Devious community (I am the owner)

### Type of Server

Thermos

### Your Expectation

Player capability to craft within their 2x2 inventory slots without crash/kick/session interruptions.

Currently on 2.2.0.0 Client and 2.2.0.0 Server that was recently upgraded/updated, trying to put anything inside the 2x2 crafting slots results in a server kick with `Internal Server Error`, logs showing a BQ class casting exception for

```
bq_standard.handlers.PlayerContainerListener cannot be cast to net.minecraft.entity.player.EntityPlayerMP
```

This cast exception reports players' container/inventory crafting packets leading me to believe it may be in fact revolving around the Better Questing mod trying to listen to the player's inventory crafting.

### The Reality

Currently on 2.2.0.0 Client and 2.2.0.0 Server that was recently upgraded/updated, trying to put anything inside the 2x2 crafting slots results in a server kick with `Internal Server Error.`

The full cast exception stack trace is embeded inside of `Server 2.2.0.0 Latest.log` close to the bottom of the log.
I have however provided the stack trace here for clearer visibility.

```
[20:33:25] [User Authenticator #10/INFO]: UUID of player X_Niter is f7460b48-310a-428b-ba49-b9b618efd24d
[20:33:25] [Netty IO #1/INFO]: Client protocol version 2
[20:33:25] [Netty IO #1/INFO]: Client attempting to join with 283 mods : BuildCraft|Silicon@7.1.27,AromaBackup@0.1.0.0,ProjRed|Expansion@4.7.7-GTNH,ExtraBees@2.0.43,HardcoreEnderExpansion@1.9.3-GTNH,blocklimiter@0.55,MouseTweaks@2.4.5-GTNH,Botany@2.0.43,dreamcraft@1.9.80,endercore@0.2.10,BWCore@0.0.1,BuildCraft|Robotics@7.1.27,kubatech@0.5.10,irontank@1.2.6,forgelin@1.9.6-GTNH,galacticgreg@1.0.8,Ic2Nei@1.2.1,openglasses@1.2.5-GTNH,GalaxySpace@1.1.16p-GTNH,betterbuilderswands@0.9.3-GTNH,BiomesOPlenty@2.1.0,LunatriusCore@1.1.7-GTNH,bettercrashes@1.1.6-GTNH,openmodularturrets@2.2.11-247,gtnhtcwands@1.2.6,ForgeMultipart@1.3.0,hodgepodge@1.7.35,lootgames@2.0.6,malisisdoors@1.13.5-GTNH,berriespp@1.3.6.3,BrandonsCore@1.0.0.13-GTNH,CoFHCore@1.7.10R3.1.4,malisiscore@0.14.5-GTNH,ResourceLoader@1.3,catwalks@2.0.4,ExtraTrees@2.0.43,ae2fc@1.0.18-gtnh,StorageDrawers@1.11.17-GTNH,gendustry@1.6.5.4-GTNH,TGregworks@GTNH-1.0.23,enhancedlootbags@1.0.5,BuildCraft|Energy@7.1.27,modtweaker2@0.9.9,IC2@2.2.828-experimental,WitcheryExtras_ASM@0.1-Beta,IguanaTweaksTConstruct@1.7.10-2.2.3,FML@7.10.99.99,Natura@2.5.3,defaultserverlist@1.1.1-GTNH,NEIAddons|Forestry@1.12.19,ThE-core@1.0.0.1,BiblioWoodsNatura@1.5,<CoFH ASM>@000,NettyPatch@0.3.1,Automagy@0.28.2,ProjRed|Illumination@4.7.7-GTNH,hydroenergy@1.0.12,TMechworks@0.2.16.4,LogisticsPipes@0.9.4.5.7-GTNH,thaumicinsurgence@0.0.6,Australia@1.7.110,NotEnoughItems@2.3.7-GTNH,Thaumcraft@4.2.3.5,opensecurity@1.0.119-GTNH,Waila@1.5.22,eternalsingularity@1.7.10-.1.0.4b,PlayerAPI@1.4,appliedenergistics2-core@rv3-beta-107-GTNH,NEIAddons@1.12.19,StorageDrawersForestry@1.11.17-GTNH,BiblioCraft@1.11.7,WarpTheory@1.2.6-GTNH,BuildCraft|Core@7.1.27,OpenModsCore@0.10.6,betterloadingscreen@1.3.36-GTNH,bdlib@1.9.8-GTNH,NEIAddons|Developer@1.12.19,tcinventoryscan@1.0.12-GTNH,ProjRed|Transmission@4.7.7-GTNH,naturescompass@1.3.6-GTNH,WR-CBE|Logic@1.4.8,DummyCore@1.13,WitcheryExtras@1.1.12,RWG@Alpha 1.3.2,BetterAchievements@0.1.0,MobiusCore@@MOD_VERSION@,inventorytweaks@1.5.15,defaultworldgenerator@0.2,InGameInfoXML@2.8.3.93,EMT@1.2.8.21,findit@1.0.11,GT++_Preloader@0.5-Beta,OpenBlocks@1.6.9-GTNH,harvestthenether@1.7.10,GoodGenerator@0.4.31,EnderStorage@1.4.12,ForbiddenMagic@0.6.4-GTNH,gregtech@MC1710,CropLoadCoreASM@0.0.2,CarpentersBlocks@3.3.8.2-GTNH,EnderIO@2.3.1.46,Translocator@1.1.2.20,InfernalMobs@1.7.5-GTNH,CustomMainMenu@1.9.2,neiintegration@1.2.3,miscutils@1.7.110,MrTJPCoreMod@1.1.0.33,Roguelike@1.5.3-GTNH,SpecialMobs@3.3.13,NEIAddons|Botany@1.12.19,Opis@1.3.6-mapless,sleepingbag@1.7.10-0.1.3,gtnhlanth@0.9.18,thaumicenergistics@1.3.19-GTNH,Aroma1997Core@1.0.2.16,CodeChickenCore@1.1.6,YAMCore@0.5.84,MineTweaker3@3.1.0,openprinter@0.1.0.132,GTTweaker@1.0,ThaumicTinkerer-preloader@0.1,oauth@1.06.1-GTNH,structurelib@1.2.0-beta.2,bartworks@0.5.86,NodalMechanics@1.1.-6-GTNH,TravellersGear@1.16.8-GTNH,adventurebackpack@1.0.5-GTNH,gtneioreplugin@1.0.17,gadomancy@1.0.8.5,betterp2p@1.0.12,Baubles@1.0.1.14,ProjRed|Core@4.7.7-GTNH,mxrandom@0.1.4,FloodLights@1.2.8-137,TML@4.1.0-GTNH,ArchitectureCraft@1.7.6,ProjRed|Exploration@4.7.7-GTNH,holoinventory@2.1.17-GTNH,Forestry@4.4.15,ae2wct@1.8.9.2,Schematica@1.9.1-GTNH,OpenMods@0.10.6,ifu@1.9.4,RIO@2.4.7,tcneiadditions@1.1.1.5.dirty,GalacticraftCore@3.0.44-GTNH,BiblioWoodsBoP@1.9,torohealthmod@1.0.1,tc4tweak@1.4.16,p455w0rdslib@1.0.4,tcnodetracker@1.1.6,netherportalfix@1.0,questbook@2.1.3-GTNH,battlegear2@1.1.2.1,ForgeMicroblock@1.3.0,botanichorizons@1.0.11-GTNH,Ztones@1.7.10,ThaumicExploration@1.1.92-GTNH,EnderZoo@1.0.23,MagicBees@2.5.12-GTNH,ProjRed|Integration@4.7.7-GTNH,betterquesting@3.0.367-GTNH,controlling@7.0.0,cookingforblockheads@1.2.12-GTNH,compactkineticgenerators@1.0.1,ModMixins@0.0.1,ae2stuff@0.5.1.15-GTNH,OpenComputers@1.7.7.2-GTNH,McMultipart@1.3.0,kekztech@0.6.15,ProjRed|Fabrication@4.7.7-GTNH,SuperTic@1.2.5,ExtraUtilities@1.2.12,Railcraft@9.13.12,detravscannermod@1.6.9,bq_standard@3.0.197-GTNH,WR-CBE|Addons@1.4.8,IC2NuclearControl@2.4.16,StevesCarts@2.0.2,MCFrames@1.0,ThaumicHorizons@1.2.1.6,BiblioWoodsForestry@1.7,ironchestminecarts@1.0.8,structurecompat@0.2.0,FastCraft@1.25,Forge@10.13.4.1614,avaritiaddons@1.5.4-GTNH,croploadcore@0.1.10,HardcoreDarkness@1.7,tinkersdefense@1.2,OpenComputers|Core@1.7.7.2-GTNH,ThaumicTinkerer@2.6.5,ThaumcraftResearchTweaks@1.0.3,OilTweak@1.0.3,AdvancedSolarPanel@1.7.10-3.5.1,AFSU@1.2.6-GTNH,JABBA@1.2.21,angermod@0.6.3,ProjRed|Transportation@4.7.7-GTNH,AppleCore@3.2.2,cb4bq@1,bartworkscrossmod@0.5.86,TiCTooltips@1.2.10,universalsingularities@8.6.5,supersolarpanel@1.7.10-1.1.1-GT-NH-Mod,HungerOverhaul@1.0.4-GTNH,gtnhlib@0.0.5,visualprospecting@1.0.33,ThaumicMachina@0.2.1,NEIAddons|ExNihilo@1.12.19,NEIAddons|CraftingTables@1.12.19,WailaHarvestability@1.1.10-GTNH,Botania@1.9.10-GTNH,bartworkscrossmodtgregworkscontainer@0.5.86,personalspace@1.0.19,beebetteratbees@0.2,Avaritia@1.30,craftpresence@v1.8.3-GTNH,ForgeRelocation@0.0.1.4,ProjRed|Compatibility@4.7.7-GTNH,TConstruct@1.9.4-GTNH,extracells@2.5.24,asielib@0.5.3,StevesFactoryManager@1.1.1-GTNH,BinnieCore@2.0.43,inpure|core@1.1.2-GTNH,sharewhereiam@0.2.0,RelocationFMP@0.0.1.2,wawla@1.1.3-GTNH,Genetics@2.0.43,mcp@9.05,Mantle@0.3.5,journeymap@5.1.4p2,appliedenergistics2@rv3-beta-107-GTNH,SGCraft@1.3.13-GTNH,thaumcraftneiplugin@@VERSION@,AromaBackupRecovery@1.0,DraconicEvolution@1.1.7-GTNH,WR-CBE|Core@1.4.8,StorageDrawersMisc@1.11.17-GTNH,harvestcraft@1.0.15-GTNH,TaintedMagic@r7.6,TwilightForest@2.3.8.16,BuildCraft|Factory@7.1.27,ProjectBlue@1.1.8-GTNH,computronics@1.6.16-GTNH,GraviSuite@2.0.68u,NEIAddons|AppEng@1.12.19,neicustomdiagram@1.4.4.6,NettyPatch_ASM@0.3.1,GalacticraftMars@3.0.44-GTNH,BuildCraft|Compat@7.1.12,wailaplugins@0.2.5,HelpFixer@1.0.7,itlt@1.0.3,neenergistics@1.3.21,AWWayofTime@1.3.14,IronChest@6.0.71,RandomThings@2.2.4,creativecore@1.3.27-GTNH,bugtorch@1.1.6.4-GTNH,thaumicbases@1.4.31,SpiceOfLife@2.0.5-carrot,WitchingGadgetsCore@1.2.21-GTNH,StorageDrawersNatura@1.11.17-GTNH,spongemixins@1.5.0,BuildCraft|Transport@7.1.27,StorageDrawersBop@1.11.17-GTNH,wanionlib@1.8.3,Aroma1997CoreHelper@1.0.2.16,chisel@2.10.16-GTNH,StevesAddons@0.10.24,Backpack@2.2.6-GTNH,ToxicEverglades@1.7.110,ThaumcraftMobAspects@1.0.0-GTNH,witchery@0.24.1,overloadedarmorbar@1.0.1,WitchingGadgets@1.2.21-GTNH,BuildCraft|Builders@7.1.27,chiseltones@1.0.4-GTNH,littletiles@1.2.7-GTNH,tectech@5.0.39,BloodArsenal@1.2.6
[20:33:25] [Netty IO #1/INFO]: Attempting connection with missing mods [kimagine, FTBL, FTBU, JourneyMapServer, Morpheus] at CLIENT
[20:33:26] [Server thread/INFO]: [Server thread] Server side modded connection established
[20:33:26] [Server thread/INFO]: X_Niter[/IP] logged in with entity id 3872 at ([world] 267.13833148796294, 74.0, -1152.773868002021)
[20:33:26] [Server thread/INFO]: Joined EntityPlayer of name: X_Niter
[20:33:26] [Server thread/INFO]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[20:33:26] [Server thread/INFO]: class java.lang.Integer
[20:33:26] [Server thread/INFO]: Sending config to X_Niter
[20:33:26] [Server thread/INFO]: Sending server configs to client for tterrag.wailaplugins.config.WPConfigHandler
[20:33:26] [Server thread/INFO]: Player EntityPlayerMP['X_Niter'/3872, l='world', x=267.14, y=74.00, z=-1152.77](X_Niter at 267.13833148796294,74.0,-1152.773868002021) connected. Sending ping
[20:33:26] [Thread-105/INFO]: Start force party quest sync
[20:33:27] [Server thread/INFO]: On Request: Sending WorldID packet to: X_Niter
[20:33:27] [Server thread/INFO]: X_Niter is an EntityPlayerMP attempting to send the worldId packet
[20:33:43] [Server thread/WARN]: Failed to handle packet for IP
java.lang.ClassCastException: bq_standard.handlers.PlayerContainerListener cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:105) ~[aap.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(InventoryCrafting.java:153) ~[aae.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77) ~[aay.class:?]
	at net.minecraft.inventory.Container.func_75144_a(Container.java:418) ~[zs.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2075) ~[nh.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_341]
[20:33:43] [Server thread/INFO]: X_Niter lost connection: Internal server error
[20:33:43] [Server thread/INFO]: X_Niter left the game.
[20:34:00] [Server thread/INFO]: Dim 86 : Mean tick time: 0.067 ms. Mean TPS: 20.000
```

[Server 2.2.0.0 Latest.log](https://gist.github.com/X-Niter/61484a85850de7a8814923583e2645a0)

### Your Proposal

I've asked around on Discord and was told to go ahead and make a report; I also did a Discord message history search to find one player mentioning this but it was not given any acknowledgment.

I looked around inside of the GitHub issues and didn't quite find anything like this specifically, if it does already exist, it may have been named or tagged in a unique manner and 600 issues is a lot to surf through.

Regarding the reproduction of the issue, I have had every player come into the server and test it, to which every single person had the issue. We all installed a fresh new 2.2.0.0 client and that did not do anything.

We thought on the idea of server wipe but we are all only on steam/lv stage which already took us quite a while to even get to.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
@eigenraven might be a good idea to add this mod inside BQ3, given we merged all the bq mods together.
