### ISSUE TITLE
Client crash when cancelling craft simulation plan from arcane crafting terminal

### ISSUE THREAD

**Issue by greesyB** [GTNewHorizons/GT-New-Horizons-Modpack#11628]
### Your GTNH Discord Username

Greesy#2016

### Your Pack Version

2.2.0.0-RC-2

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Actions

Simulate a craft from arcane crafting terminal, then cancel the craft before starting it.

### Crash Report

[crash-2022-10-12_17.14.15-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9769051/crash-2022-10-12_17.14.15-client.txt)

Relevant portion:
```
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at appeng.core.sync.packets.PacketSwitchGuis.<init>(PacketSwitchGuis.java:54)
	at appeng.client.gui.implementations.GuiCraftConfirm.switchToOriginalGUI(GuiCraftConfirm.java:528)
	at appeng.client.gui.implementations.GuiCraftConfirm.actionPerformed(GuiCraftConfirm.java:515)
	at thaumicenergistics.client.gui.GuiCraftConfirmBridge.actionPerformed(GuiCraftConfirmBridge.java:59)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:225)
	at net.minecraft.client.gui.inventory.GuiContainer.mouseClicked(GuiContainer.java:326)
	at appeng.client.gui.AEBaseGui.mouseClicked(AEBaseGui.java:305)
	at appeng.client.gui.implementations.GuiCraftConfirm.mouseClicked(GuiCraftConfirm.java:537)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.handleMouseInput(GuiContainer.java)
	at appeng.client.gui.AEBaseGui.handleMouseInput(AEBaseGui.java:641)
	at appeng.client.gui.implementations.GuiCraftConfirm.handleMouseInput(GuiCraftConfirm.java:552)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:268)
```

It seems base AE needs an `OriginalGui` case in `GuiCraftConfirm` for the arcane crafting terminal. I am no good at cross-mod dependencies yet, but can look into it more when I have time if no one else does.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by greesyB** [comment]
Somewhat related as it also involves compat with arcane crafting terminal in base AE according to Repo https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9667

**Comment by cwessel188** [comment]
PR opened for AE2: https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/194
