### ISSUE TITLE
Thaumcraft totem generation causes crash

### ISSUE THREAD

**Issue by GodlyIdea** [GTNewHorizons/GT-New-Horizons-Modpack#11833]
### Your Pack Version

2.2.3

### Your Server

Private server

### Your Actions

Was exploring the world and server crashed with message "Internal server error".
After server restart and logging in the crash occured right away.

By the crash log new chunk was generated and something in Thaumcraft totem generation logic is broken.

### Crash Report

Full:
[crash-2022-11-14_23.21.22-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10012062/crash-2022-11-14_23.21.22-server.txt)

Short:
`
Description: Exception in server tick loop

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generateTotem(ThaumcraftWorldGenerator.java:123)
	at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generateSurface(ThaumcraftWorldGenerator.java:431)
	at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.worldGeneration(ThaumcraftWorldGenerator.java:109)
	at thaumcraft.common.lib.world.ThaumcraftWorldGenerator.generate(ThaumcraftWorldGenerator.java:95)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at net.minecraft.world.gen.ChunkProviderServer.redirect$onRegistry$zzk000(ChunkProviderServer.java:527)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:596)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
`

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
It's an unsupported configuration to run with zero or negative node rarity in thaumcraft config.

**Comment by GodlyIdea** [comment]
Thanks for quick replay.
The config value was set to 2147483648 which seemed to overflow to negative side.
Max value seems to be 214748364 as code multiplys it by 10.
