### ISSUE TITLE
prevent netty from kicking you from the server

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#11937]
### Your GTNH Discord Username

boubou_19

### Your Pack Version

all

### Your Proposal

validate data before sending it throught Netty, as well as possibly indicating what block gets affected by it, for easy fix (like a line of log containing the coordinates of the TE being printed each time bad packets are formed)

<details>
  <summary>An example of the issue from Eta</summary>
  
```
[08/12/2022 19:37:00 PM]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:263)
[08/12/2022 19:37:00 PM]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131)
[08/12/2022 19:37:00 PM]     at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[08/12/2022 19:37:00 PM]     at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[08/12/2022 19:37:00 PM]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173)
[08/12/2022 19:37:00 PM]     at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[08/12/2022 19:37:00 PM]     at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[08/12/2022 19:37:00 PM]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[08/12/2022 19:37:00 PM]     at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[08/12/2022 19:37:00 PM]     at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[08/12/2022 19:37:00 PM]     at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149)
[08/12/2022 19:37:00 PM]     at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[08/12/2022 19:37:00 PM]     at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[08/12/2022 19:37:00 PM]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[08/12/2022 19:37:00 PM]     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100)
[08/12/2022 19:37:00 PM]     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480)
[08/12/2022 19:37:00 PM]     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447)
[08/12/2022 19:37:00 PM]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341)
[08/12/2022 19:37:00 PM]     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
[08/12/2022 19:37:00 PM]     at java.lang.Thread.run(Thread.java:748)
[08/12/2022 19:37:00 PM] Caused by: java.io.IOException: The received encoded string buffer length is longer than maximum allowed (34422052 > 131068)
[08/12/2022 19:37:00 PM]     at net.minecraft.network.PacketBuffer.func_150789_c(SourceFile:125)
[08/12/2022 19:37:00 PM]     at net.minecraft.entity.DataWatcher.func_151508_b(SourceFile:275)
[08/12/2022 19:37:00 PM]     at net.minecraft.network.play.server.S1CPacketEntityMetadata.func_148837_a(SourceFile:30)
[08/12/2022 19:37:00 PM]     at net.minecraft.util.MessageDeserializer.decode(SourceFile:40)
[08/12/2022 19:37:00 PM]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232)
[08/12/2022 19:37:00 PM]     ... 19 more
[08/12/2022 19:37:00 PM] [Netty Client IO #5/ERROR] NetworkDispatcher exception
```
 
</details>

<details>
  <summary>An example of the issue from Zeta</summary>
  
```
[08/12/2022 21:24:16 PM] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:263)
[08/12/2022 21:24:16 PM] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131)
[08/12/2022 21:24:16 PM] 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[08/12/2022 21:24:16 PM] 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[08/12/2022 21:24:16 PM] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173)
[08/12/2022 21:24:16 PM] 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[08/12/2022 21:24:16 PM] 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[08/12/2022 21:24:16 PM] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[08/12/2022 21:24:16 PM] 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[08/12/2022 21:24:16 PM] 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[08/12/2022 21:24:16 PM] 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149)
[08/12/2022 21:24:16 PM] 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[08/12/2022 21:24:16 PM] 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[08/12/2022 21:24:16 PM] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[08/12/2022 21:24:16 PM] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100)
[08/12/2022 21:24:16 PM] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480)
[08/12/2022 21:24:16 PM] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447)
[08/12/2022 21:24:16 PM] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341)
[08/12/2022 21:24:16 PM] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
[08/12/2022 21:24:16 PM] 	at java.lang.Thread.run(Thread.java:748)
[08/12/2022 21:24:16 PM] Caused by: net.minecraft.util.ReportedException: Loading NBT data
[08/12/2022 21:24:16 PM] 	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:407)
[08/12/2022 21:24:16 PM] 	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
[08/12/2022 21:24:16 PM] 	at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:54)
[08/12/2022 21:24:16 PM] 	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
[08/12/2022 21:24:16 PM] 	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
[08/12/2022 21:24:16 PM] 	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170)
[08/12/2022 21:24:16 PM] 	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125)
[08/12/2022 21:24:16 PM] 	at net.minecraft.nbt.CompressedStreamTools.func_152457_a(CompressedStreamTools.java:65)
[08/12/2022 21:24:16 PM] 	at net.minecraft.network.PacketBuffer.func_150793_b(SourceFile:89)
[08/12/2022 21:24:16 PM] 	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148837_a(SourceFile:41)
[08/12/2022 21:24:16 PM] 	at net.minecraft.util.MessageDeserializer.decode(SourceFile:40)
[08/12/2022 21:24:16 PM] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232)
[08/12/2022 21:24:16 PM] 	... 19 more
[08/12/2022 21:24:16 PM] Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
[08/12/2022 21:24:16 PM] 	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
[08/12/2022 21:24:16 PM] 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[08/12/2022 21:24:16 PM] 	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
[08/12/2022 21:24:16 PM] 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
[08/12/2022 21:24:16 PM] 	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
[08/12/2022 21:24:16 PM] 	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
[08/12/2022 21:24:16 PM] 	at java.io.DataInputStream.readFully(DataInputStream.java:195)
[08/12/2022 21:24:16 PM] 	at java.io.DataInputStream.readUTF(DataInputStream.java:609)
[08/12/2022 21:24:16 PM] 	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
[08/12/2022 21:24:16 PM] 	at net.minecraft.nbt.NBTTagCompound.func_152448_b(NBTTagCompound.java:388)
[08/12/2022 21:24:16 PM] 	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:50)
[08/12/2022 21:24:16 PM] 	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
[08/12/2022 21:24:16 PM] 	... 30 more
[08/12/2022 21:24:16 PM] [Netty Client IO #11/ERROR] NetworkDispatcher exception
```
 
</details>

possibly related issue: #10465

### Your Goal

The goal is to avoid chunkbans, which is already a vanilla issue.

### Your Vision

This will reduce all the time spent by server admins to spot the specific block causing the chunkban. Especially when the chunkban is so ancient that backups are all affected.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
wasent this solved with netty patcher long time agao ?

**Comment by Ethryan** [comment]
I didn’t see any linked code changes so I thought this was still waiting for a fix.
