### ISSUE TITLE
NEI fails to load use recipes

### ISSUE THREAD

**Issue by rjm0999** [GTNewHorizons/GT-New-Horizons-Modpack#11979]
### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I wanted to look at uses (press u or right click) for an item, NEI failed to load the recipes.

### The Reality

Chat shows the following message
"There was an error during loading recipe. Please check log for details."

	... 3 more

### Your Proposal

NEI loads uses for items

Log output

[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.util.concurrent.ExecutionException: java.lang.ClassCastException
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinTask.get(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.RecipeHandlerQuery.getHandlersWithRecipes(RecipeHandlerQuery.java:63)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.RecipeHandlerQuery.getRecipeHandlersParallel(RecipeHandlerQuery.java:45)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.RecipeHandlerQuery.runWithProfiling(RecipeHandlerQuery.java:32)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:15)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.api.ShortcutInputHandler.handleKeyEvent(ShortcutInputHandler.java:43)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:14)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:390)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:560)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:547)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3104)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassCastException
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 33 more
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassCastException
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.ReferencePipeline.collect(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.RecipeHandlerQuery.lambda$getHandlersWithRecipes$2(RecipeHandlerQuery.java:62)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassCastException: null not an ItemStack, ItemStack[] or List<ItemStack?
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.NEIServerUtils.extractRecipeItems(NEIServerUtils.java:375)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.PositionedStack.<init>(PositionedStack.java:24)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.PositionedStack.<init>(PositionedStack.java:33)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.<init>(ShapedRecipeHandler.java:30)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.<init>(ShapedRecipeHandler.java:36)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.ShapedRecipeHandler.loadUsageRecipes(ShapedRecipeHandler.java:118)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:423)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:550)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageAndCatalystHandler(TemplateRecipeHandler.java:575)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.GuiUsageRecipe.getUsageOrCatalystHandler(GuiUsageRecipe.java:48)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.GuiUsageRecipe.lambda$openRecipeGui$0(GuiUsageRecipe.java:14)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.AbstractTask.compute(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.CountedCompleter.exec(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source)
[15:22:37] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kInikel** [comment]
I have also the problem, but only when I want to search the recipe of an Ore.
So when I press "r" over an ore to see where it generates, the game tells me that it was unable to find the recipe.
Game notfication: "There was an error during loading recipe. Please check log for details."

**Comment by kInikel** [comment]
Ok, it seems like reinstalling wont fix it. 
But if you delete all files, restart the pc and than install the pack again the bug is gone.
Soooo, rjm0999 maybe this will help you too.

**Comment by chochem** [comment]
at least one such bug was fixed and it hasnt happened in any more recent version
