### ISSUE TITLE
NPE In GoodGenerator Precise Assembler texture lookup

### ISSUE THREAD

**Issue by PhoenixtheII** [GTNewHorizons/GT-New-Horizons-Modpack#12077]
### Your GTNH Discord Username

Phoenix the II

### Your Pack Version

2.2.8

### Your Server

My own

### Type of Server

None

### Your Actions

Build incomplete precise assembler. 

Wait/Walk further away from the assembler. 
Maybe it has something to do with backup generation too. Since that was running just before the clients crashed.

Client Crash!
Kill client through taskman, because it's literally spitting this stacktrace as fast it can.
Start client.
Join Server
Crash Loop.

This was happening on 2.2.7 too.

### Crash Report

[19:41:18] [Client thread/ERROR]: Failed to reset state after a crash
java.lang.IllegalStateException: Already tesselating!
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:219) ~[bmh.class:?]
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:212) ~[bmh.class:?]
	at net.minecraft.client.LoadingScreenRenderer.func_73718_a(LoadingScreenRenderer.java:147) ~[bbo.class:?]
	at net.minecraft.client.LoadingScreenRenderer.func_73719_c(LoadingScreenRenderer.java:94) ~[bbo.class:?]
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2193) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146) ~[bao.class:?]
	at net.minecraft.client.Minecraft.resetGameState(Minecraft.java:5200) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5117) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[19:41:18] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at gregtech.api.enums.Textures$BlockIcons.getCasingTextureForId(Textures.java:2082) ~[Textures$BlockIcons.class:?]
	at goodgenerator.blocks.tileEntity.PreciseAssembler.getTexture(PreciseAssembler.java:468) ~[PreciseAssembler.class:?]
	at gregtech.api.metatileentity.BaseMetaTileEntity.getTexture(BaseMetaTileEntity.java:1229) ~[BaseMetaTileEntity.class:?]
	at gregtech.common.render.GT_Renderer_Block.renderStandardBlock(GT_Renderer_Block.java:81) ~[GT_Renderer_Block.class:?]
	at gregtech.common.render.GT_Renderer_Block.renderWorldBlock(GT_Renderer_Block.java:1057) ~[GT_Renderer_Block.class:?]
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118) ~[RenderingRegistry.class:?]
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53) ~[FMLRenderAccessLibrary.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296) ~[blm.class:?]
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181) ~[blo.class:?]
	at fastcraft.ah.a(F:139) ~[fastcraft-1.25.jar:?]
	at fastcraft.ag.a(F:90) ~[fastcraft-1.25.jar:?]
	at fastcraft.HC.t(F:22) ~[fastcraft-1.25.jar:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187) ~[blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5104) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by kvieta** [comment]
Reproduced on 2.2.7
