### ISSUE TITLE
Transvector Interface and brains in a jar; 2 great tools that go HORRABLE together

### ISSUE THREAD

**Issue by Shibva** [GTNewHorizons/GT-New-Horizons-Modpack#12197]
### Your GTNH Discord Username

Shibva#3140

### Your Pack Version

2.2.2.0

### Your Server

nA

### Type of Server

Single Player

### Your Actions

PERSONAL NOTE: this issue was discovered while using GTNH mods outside of the pack; HOWEVER IS reproducable and SHOULD be present in-pack; all mods with this crash that caused this interaction are GTNH versiosns to clarify

so I was trying to steamline the experience gathering with a Brain in a Jar wtih a Soul Stone experence storage setup (Automagy)
and the Soul Sieve (thaumic Horizons) utilizing the handiness of the Transvenctor Interface (Thaumic Tinkerer; source of issue)

using what I know I hooked the 2 setups (interface in place of the BiaJ in the experience condensing setup) and expected the process to be automated efficently. The result was a crash once I binded the transvector interface to the Jar

To Reproduce:

1. place a sieve wtih a Brain Jar on top of it
2. buld the minimal setup to use the soul stone properly 
3. place the trasvector Interface where the Brain Jar would go in the soul stone XP storage setup
4. bind the interface with the brain jar
5. screen goes clear with nothing but background skybox? and game crashes from StackOverflow

6. Rejoin the world and crash again and again until the interface is removed

### Crash Report

this is a sliver of the report dumed down to the nessicary parts, the first part was cut but is the same line spammed repetivly

Time: 1/4/23 7:04 AM
Description: Unexpected error

java.lang.StackOverflowError: Unexpected error
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147438_o(World.java:2536)
	at thaumic.tinkerer.common.block.tile.transvector.TileTransvector.getTile(TileTransvector.java:61)
	at thaumic.tinkerer.common.block.tile.transvector.TileTransvectorInterface.getAspects(TileTransvectorInterface.java:302)
	at thaumic.tinkerer.common.block.tile.transvector.TileTransvectorInterface.getAspects(TileTransvectorInterface.java:303)
	at thaumic.tinkerer.common.block.tile.transvector.TileTransvectorInterface.getAspects(TileTransvectorInterface.java:303)
	at thaumic.tinkerer.common.block.tile.transvector.TileTransvectorInterface.getAspects(TileTransvectorInterface.java:303)
	at thaumic.tinkerer.common.block.tile.transvector.TileTransvectorInterface.getAspects(TileTransvectorInterface.java:303)
	at thaumic.tinkerer.common.block.tile.transvector.TileTransvectorInterface.getAspects(TileTransvectorInterface.java:303)
	at thaumic.tinkerer.common.block.tile.transvector.TileTransvectorInterface.getAspects(TileTransvectorInterface.java:303)
	at thaumic.tinkerer.common.block.tile.transvector.TileTransvectorInterface.getAspects(TileTransvectorInterface.java:303)
        ... repeated 
        
        -- Head --
Stacktrace:
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147438_o(World.java:2536)
	at thaumic.tinkerer.common.block.tile.transvector.TileTransvector.getTile(TileTransvector.java:61)
	at thaumic.tinkerer.common.block.tile.transvector.TileTransvectorInterface.getAspects(TileTransvectorInterface.java:302)
	at thaumic.tinkerer.common.block.tile.transvector.TileTransvectorInterface.getAspects(TileTransvectorInterface.java:303)
	at thaumic.tinkerer.common.block.tile.transvector.TileTransvectorInterface.getAspects(TileTransvectorInterface.java:303)
        ... (more repetivie)
        
        

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Shibva** [comment]
Visual Refrence:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/38770780/210559180-8bf99a14-9ab1-4fa1-8b3b-da915c228b5b.png">

**Comment by Shibva** [comment]
for the record: I added that bit in the title for the reason that I can soft-lock your save; not arguing with the name change, just a extra detail to highlight the severity of the bug

**Comment by Shibva** [comment]
*Typo: ..that IT can... (damnit autocorrect)

**Comment by Alastors** [comment]
This is a known bug with it and the tile entities in general
