### ISSUE TITLE
Crash on Callisto: Already tesselating! 

### ISSUE THREAD

**Issue by dvdmandt** [GTNewHorizons/GT-New-Horizons-Modpack#12318]
### Your GTNH Discord Username

DvDmanDT#3943

### Your Pack Version

2.2.3

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Actions

Just jumping around on Callisto, which we just reached. We were in the process of prospecting for ores when my friend crashed, and when I moved around a bit in the same area I also got the same crash.

Neither of us have OptiFine installed.

### Crash Report

One crash generated two crash reports for me:

[crash-2023-01-19_03.26.03-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10456866/crash-2023-01-19_03.26.03-client.txt)
[crash-2023-01-19_03.26.04-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10456867/crash-2023-01-19_03.26.04-client.txt)

Upon some log examination, I found an additional call stack, making a total of three different ones:
```[03:26:03] [Client thread/FATAL]: Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: 2
	at galaxyspace.SolarSystem.moons.callisto.block.CallistoBlocks.func_149691_a(CallistoBlocks.java:70) ~[CallistoBlocks.class:?]
	at net.minecraft.block.Block.func_149673_e(Block.java:556) ~[aji.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227) ~[blm.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4934) ~[blm.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247) ~[blm.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255) ~[blm.class:?]
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181) ~[blo.class:?]
	at fastcraft.ah.a(F:139) ~[fastcraft-1.25.jar:?]
	at fastcraft.ag.a(F:90) ~[fastcraft-1.25.jar:?]
	at fastcraft.HC.t(F:22) ~[fastcraft-1.25.jar:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187) ~[blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3104) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_345]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_345]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_345]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_345]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[03:26:03] [Client thread/ERROR]: Failed to reset state after a crash
java.lang.IllegalStateException: Already tesselating!
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:219) ~[bmh.class:?]
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:212) ~[bmh.class:?]
	at net.minecraft.client.LoadingScreenRenderer.func_73718_a(LoadingScreenRenderer.java:147) ~[bbo.class:?]
	at net.minecraft.client.LoadingScreenRenderer.func_73719_c(LoadingScreenRenderer.java:94) ~[bbo.class:?]
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2193) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146) ~[bao.class:?]
	at net.minecraft.client.Minecraft.resetGameState(Minecraft.java:3200) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3117) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_345]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_345]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_345]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_345]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[03:26:03] [Client thread/FATAL]: Unreported exception thrown!
java.lang.IllegalStateException: Already tesselating!
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:219) ~[bmh.class:?]
	at galaxyspace.core.render.sky.SkyProviderBase.renderSun(SkyProviderBase.java:274) ~[SkyProviderBase.class:?]
	at galaxyspace.core.render.sky.SkyProviderBase.renderDefault(SkyProviderBase.java:148) ~[SkyProviderBase.class:?]
	at galaxyspace.core.render.sky.SkyProviderBase.render(SkyProviderBase.java:135) ~[SkyProviderBase.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_72714_a(RenderGlobal.java:964) ~[bma.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1167) ~[blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3104) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_345]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_345]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_345]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_345]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

The first one references this code which looks wrong to me:
```
   @Override
    @SideOnly(Side.CLIENT)
    public IIcon getIcon(final int side, final int meta) {
        if (meta < 0 || meta > this.textures.length) {
            return this.textures[0];
        }
        return this.textures[meta];
    }
```
If `meta == this.textures.length` then `return this.textures[meta];` becomes out of bounds, which I assume throws an exception that bypasses ending an existing tesselation thing somewhere.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by dvdmandt** [comment]
This PR just adds an enchantment that gives an arbitrary armor item full hazmat protection. This PR does not contain any way apart from cheating to actually get the enchantment, the idea is to add a TC infusion enchantment recipe to NewHorizonsCoreMod.
