### ISSUE TITLE
Extreme heat exchanger critical error spam

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12345]
### Your Pack Version

2.2.3

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

The following error is constantly being spammed within our server logs:
`
[23:47:36] [Server thread/ERROR] [GregTech GTNH]: Encountered CRITICAL ERROR while saving MetaTileEntity.
[23:47:36] [Server thread/ERROR] [GregTech GTNH]: java.lang.IllegalArgumentException: Empty string not allowed
at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:23)
at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:105)
at goodgenerator.blocks.tileEntity.ExtremeHeatExchanger.saveNBTData(ExtremeHeatExchanger.java:155)
at gregtech.api.metatileentity.CommonMetaTileEntity.saveMetaTileNBT(CommonMetaTileEntity.java:49)
at gregtech.api.metatileentity.BaseMetaTileEntity.func_145841_b(BaseMetaTileEntity.java:169)
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370)
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197)
at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256)
at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302)
at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809)
at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569)
at fastcraft.u.a(F:289)
at fastcraft.H.aq(F:36)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
It is not being followed up by the following potentially related error:
`[23:52:10] [Server thread/ERROR] [StructureLib]: #########################################
[23:52:10] [Server thread/ERROR] [StructureLib]: #########################################
[23:52:10] [Server thread/ERROR] [StructureLib]: #########################################
[23:52:10] [Server thread/ERROR] [StructureLib]: #########################################
[23:52:10] [Server thread/ERROR] [StructureLib]: tierExtractor should never return notSet: -1
java.lang.Throwable
at com.gtnewhorizon.structurelib.structure.StructureUtility.lambda$ofBlocksTiered$0(StructureUtility.java:588) ~[StructureUtility.class:?]
at com.gtnewhorizon.structurelib.structure.StructureUtility$7.check(StructureUtility.java:684) ~[StructureUtility$7.class:?]
at com.gtnewhorizon.structurelib.structure.LazyStructureElement.check(LazyStructureElement.java:29) ~[LazyStructureElement.class:?]
at com.gtnewhorizon.structurelib.structure.StructureUtility$34.check(StructureUtility.java:2634) ~[StructureUtility$34.class:?]
at com.gtnewhorizon.structurelib.structure.IStructureDefinition.lambda$iterate$0(IStructureDefinition.java:419) ~[IStructureDefinition.class:?]
at com.gtnewhorizon.structurelib.structure.StructureUtility.iterateV2(StructureUtility.java:3045) [StructureUtility.class:?]
at com.gtnewhorizon.structurelib.structure.IStructureDefinition.iterate(IStructureDefinition.java:409) [IStructureDefinition.class:?]
at com.gtnewhorizon.structurelib.structure.IStructureDefinition.check(IStructureDefinition.java:89) [IStructureDefinition.class:?]
at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_EnhancedMultiBlockBase.checkPiece(GT_MetaTileEntity_EnhancedMultiBlockBase.java:161) [GT_MetaTileEntity_EnhancedMultiBlockBase.class:?]
at common.tileentities.GTMTE_LapotronicSuperCapacitor.checkMachine(GTMTE_LapotronicSuperCapacitor.java:411) [GTMTE_LapotronicSuperCapacitor.class:?]
at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.checkStructure(GT_MetaTileEntity_MultiBlockBase.java:301) [GT_MetaTileEntity_MultiBlockBase.class:?]
at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:317) [GT_MetaTileEntity_MultiBlockBase.class:?]
at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:536) [BaseMetaTileEntity.class:?]
at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1145) [mt.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]`

**Comment by Glease** [comment]
Line number do not match any version of GG source code on git. Please use a supported version of GG.

**Comment by Glease** [comment]
While the line number indeed does not match, I figured out how this err nontheless.

**Comment by Tommeh1** [comment]
> Line number do not match any version of GG source code on git. Please use a supported version of GG.

I'm using the version included with version 2.2.3 of the pack.
