### ISSUE TITLE
SimpleWrapperHandler exception

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12358]
### Your Pack Version

2.2.8

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

May be related to: #12357
The following error is being spammed after updating from 2.2.3 to 2.2.8:
`[20:37:05] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.RuntimeException: Missing
at cpw.mods.fml.server.FMLServerHandler.getClientToServerNetworkManager(FMLServerHandler.java:238) ~[FMLServerHandler.class:?]
at cpw.mods.fml.common.FMLCommonHandler.getClientToServerNetworkManager(FMLCommonHandler.java:530) ~[FMLCommonHandler.class:?]
at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$8.selectNetworks(FMLOutboundHandler.java:225) ~[FMLOutboundHandler$OutboundTarget$8.class:?]
at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:?]
at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:236) ~[SimpleNetworkWrapper.class:?]
at eu.usrv.yamcore.network.PacketDispatcher.sendToServer(PacketDispatcher.java:117) ~[PacketDispatcher.class:?]
at com.github.technus.tectech.thing.cover.GT_Cover_TM_EnderFluidLink$EnderFluidLinkUIFactory.addUIWidgets(GT_Cover_TM_EnderFluidLink.java:163) ~[GT_Cover_TM_EnderFluidLink$EnderFluidLinkUIFactory.class:?]
at gregtech.api.util.GT_CoverBehaviorBase$UIFactory.createWindow(GT_CoverBehaviorBase.java:462) ~[GT_CoverBehaviorBase$UIFactory.class:?]
at com.github.technus.tectech.thing.cover.GT_Cover_TM_EnderFluidLink.createWindow(GT_Cover_TM_EnderFluidLink.java:138) ~[GT_Cover_TM_EnderFluidLink.class:?]
at gregtech.api.gui.modularui.GT_UIInfos.createCoverContainer(GT_UIInfos.java:179) ~[GT_UIInfos.class:?]
at gregtech.api.gui.modularui.GT_UIInfos.lambda$static$3(GT_UIInfos.java:77) ~[GT_UIInfos.class:?]
at com.gtnewhorizons.modularui.common.internal.InternalUIMapper.getServerGuiElement(InternalUIMapper.java:50) [InternalUIMapper.class:?]
at cpw.mods.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:243) [NetworkRegistry.class:?]
at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:75) [FMLNetworkHandler.class:?]
at com.gtnewhorizons.modularui.common.builder.UIInfo.open(UIInfo.java:43) [UIInfo.class:?]
at gregtech.api.gui.modularui.GT_UIInfos.openCoverUI(GT_UIInfos.java:130) [GT_UIInfos.class:?]
at gregtech.api.util.GT_CoverBehavior.onCoverShiftRightclick(GT_CoverBehavior.java:324) [GT_CoverBehavior.class:?]
at gregtech.api.util.GT_CoverBehavior.onCoverShiftRightClickImpl(GT_CoverBehavior.java:107) [GT_CoverBehavior.class:?]
at gregtech.api.util.GT_CoverBehavior.onCoverShiftRightClickImpl(GT_CoverBehavior.java:19) [GT_CoverBehavior.class:?]
at gregtech.api.util.GT_CoverBehaviorBase.onCoverShiftRightClick(GT_CoverBehaviorBase.java:232) [GT_CoverBehaviorBase.class:?]
at gregtech.api.metatileentity.BaseMetaTileEntity.onRightclick(BaseMetaTileEntity.java:1620) [BaseMetaTileEntity.class:?]
at gregtech.common.blocks.GT_Block_Machines.func_149727_a(GT_Block_Machines.java:373) [GT_Block_Machines.class:?]
at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source) [mx.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) [nh.class:?]
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]`

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
Fixed in 2.3.0
