### ISSUE TITLE
Thaumcraft recipes doesn't show up in NEI even if the research is unlocked

### ISSUE THREAD

**Issue by 704009905** [GTNewHorizons/GT-New-Horizons-Modpack#12427]
### Your GTNH Discord Username

Hexadecimal#1191

### Your Pack Version

2.2.8

### Your Server

Self-hosted private server

### Type of Server

Vanilla Forge

### Your Expectation

NEI shows thaumcraft recipes after you unlock its research, or when "Show locked recipes" config in Thaumcraft NEI Additions mod is set to true.

### The Reality

Thaumcraft recipes don't show up even if the research is unlocked and Thaumcraft NEI Additions mod's config is set to always show the recipe regardless of research. It used to work for me in 2.2.0.0.
![image](https://user-images.githubusercontent.com/11241929/215325720-f14836fd-7604-45e8-b1fc-c556fd4e91d9.png)

Left or right click, R or U all doesn't work with thaumcraft research locked recipes, but other thaumcraft item which doesn't require research is normal.
This happens in my private 2.2.8 server for everyone and [Kayky#2822 mentioned it too](https://discord.com/channels/181078474394566657/234936569360809996/1067391231207932004) in discord. But it's so big a problem so I doubt this happens to everyone, or someone will have noticed it earlier. Restarting and reloading the recipe doesn't change anything.

### Your Proposal

Investigate if the problem is due to GTNH and solve it if possible

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
works just fine for me 
![image](https://user-images.githubusercontent.com/40274384/215326588-18657b55-3a43-45cd-8caf-a4e932833fa7.png)

**Comment by 704009905** [comment]
I did more tests with clean 2.2.0.0 and 2.2.8 multimc import. 2.2.0 works fine but 2.2.8 only worked once within many restarts.
I do find some information in [the log](https://gist.github.com/704009905/b4fb10c4544bed0c95809b6ada9bfc98).

```
[22:45:13] [NEI Plugin Loader/ERROR] [NotEnoughItems]: Failed to Load ru.timeconqueror.tcneiadditions.nei.NEIConfig
java.lang.NullPointerException
  at com.djgiannuzz.thaumcraftneiplugin.nei.recipehandler.ArcaneShapedRecipeHandler.<init>(ArcaneShapedRecipeHandler.java:43) ~[ArcaneShapedRecipeHandler.class:?]
  at ru.timeconqueror.tcneiadditions.nei.arcaneworkbench.ArcaneCraftingShapedHandler.<init>(ArcaneCraftingShapedHandler.java:38) ~[ArcaneCraftingShapedHandler.class:?]
  at ru.timeconqueror.tcneiadditions.nei.NEIConfig.loadConfig(NEIConfig.java:33) ~[NEIConfig.class:?]
  at codechicken.nei.NEIClientConfig$8.run(NEIClientConfig.java:458) [NEIClientConfig$8.class:?]
```
and
```
[22:45:14] [NEI Plugin Loader/ERROR] [NotEnoughItems]: Failed to Load com.djgiannuzz.thaumcraftneiplugin.nei.NEIConfig
java.lang.NullPointerException
  at com.djgiannuzz.thaumcraftneiplugin.nei.recipehandler.ArcaneShapedRecipeHandler.<init>(ArcaneShapedRecipeHandler.java:43) ~[ArcaneShapedRecipeHandler.class:?]
  at com.djgiannuzz.thaumcraftneiplugin.nei.NEIConfig.loadConfig(NEIConfig.java:27) ~[NEIConfig.class:?]
  at codechicken.nei.NEIClientConfig$8.run(NEIClientConfig.java:458) [NEIClientConfig$8.class:?]
[22:45:14] [NEI Plugin Loader/INFO] [Thaumcraft NEI Additions]: Initiated handler removing...
```
happens when world loading is finishing for the first time in this launch.

`[22:46:32] [Client thread/INFO] [NotEnoughItems]: FindFuels took 189.3 ms`
shows up when I check any thaumcraft recipes(press R) for the first time in this launch, which lags a bit. After that pressing R doesn't give any responses.

Resetting the config didn't work, and somehow 2.2.8 successfully showed thaumcraft NEI once for me. So maybe it is a random null pointer exception I guess?
