### ISSUE TITLE
TileEntitySpaceElevatorCable has throw an exception trying to write state

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12443]
### Your Pack Version

2.2.8

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

The following error is thrown in the server console everytime the server tries to save the world:
`[17:12:02] [Server thread/ERROR] [FML]: A TileEntity type galaxyspace.core.tile.machine.multi.TileEntitySpaceElevatorCable has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class galaxyspace.core.tile.machine.multi.TileEntitySpaceElevatorCable is missing a mapping! This is a bug!
at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]`

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Fixed by https://github.com/GTNewHorizons/Galaxy-Space-GTNH/pull/67

**Comment by Tommeh1** [comment]
> Fixed by https://github.com/GTNewHorizons/Galaxy-Space-GTNH/pull/67

That link leads to a 404 for me

**Comment by minecraft7771** [comment]
The repo is private due to the original authors wishes.
