### ISSUE TITLE
Thaumometer scanning Strontium Nugget crashes the game

### ISSUE THREAD

**Issue by D-Cysteine** [GTNewHorizons/GT-New-Horizons-Modpack#12462]
### Your GTNH Discord Username

D-Cysteine

### Your Pack Version

2.2.9-8 (pre)

### Your Server

SP

### Type of Server

None

### Your Actions

Scanning a Strontium Nugget (from GT++) with the Thaumometer crashes the game with a StackOverflowError. Note that GT++ adds two strontium nuggets; this is specifically the one named "Strontium Nugget", which has a Thaumcraft crucible duplication recipe, and not "Strontium-90 Nugget".

It looks like the cause of this crash is a recursion loop in Thaumcraft's code that attempts to get the aspects for the nugget, which in turn is due to some sort of interaction with the Thaumcraft crucible recipe for the Strontium Nugget. A few more notes to help debug:
 * It looks like the Strontium Nugget is the only GT++ nugget that has a Thaumcraft crucible recipe
 * The crucible duplication recipe is supposedly added by the "Metallurgic Perfection: Transmutation" research (under Witching Gadgets), but I didn't see the recipe listed in the Thaumonomicon entry for that research. Though I might have just missed it
 * No other item in the NEI item list crashes like this when retrieving aspects

### Crash Report

```
java.lang.StackOverflowError
    at java.util.AbstractCollection.toArray(Unknown Source)
    at thaumcraft.api.aspects.AspectList.getAspects(AspectList.java:65)
    at thaumcraft.api.aspects.AspectList.copy(AspectList.java:35)
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:567)
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891)
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551)
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525)
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:576)
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891)
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551)
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525)
(repeat forever)
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
is this a gt++ item ?

**Comment by D-Cysteine** [comment]
> is this a gt++ item ?

Yes

**Comment by Dream-Master** [comment]
maybe some magic gt++ asm stuff. Not sure how or if alk register the aspects on materials and item/blocks

**Comment by D-Cysteine** [comment]
Something about the crucible recipe seems to be causing a recursion loop, so the recipe might be broken somehow. It's just this one item that has this problem, as far as I can tell.

I think the aspect registration might be mostly automatic (based on recipes and stuff) and done in Thaumcraft code, so the issue might not be in GT++. The recursion loop seems to be entirely within Thaumcraft code.

Also would be good to get confirmation that other people have this problem too, otherwise it might just be my configs somehow. Though this should be a clean modpack install so not sure.

**Comment by D-Cysteine** [comment]
Hmm, I just tried on 2.2.8 and got the same crash.

Does the Strontium Nugget that worked have a Thaumcraft crucible recipe? And just to double-check, it was "Strontium Nugget" and not "Strontium-90 Nugget"?

**Comment by BritishCynic** [comment]
I didn't see a different one, but now that I can, yes, the "Strontium-90" one doesn't crash, but the "Strontium" one _does_.

**Comment by Glease** [comment]
probably need to debug what recipes are involved. IIRC TC has built in guards against recursive recipes so not sure why this specific item blows up.
