### ISSUE TITLE
Crash on launch after dying in Nether

### ISSUE THREAD

**Issue by iHonor** [GTNewHorizons/GT-New-Horizons-Modpack#12496]
### Your GTNH Discord Username

Kevin#1872

### Your Pack Version

2.2.8

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Actions

Went into the Nether and died to a Plague Zombie Pigman
Everytime I attempt to launch the server, it now fails to start (**Exception in server tick loop**).

### Crash Report

Troubleshooted for quite some time, but not sure what's causing this. The world seemed to be corrupted.
- Played with config\forge.cfg options 'removeErroringEntities' and 'removeErroringTileEntities'
- Same issue appears when loading world in SP
- Removed files ops.json, usercache.json, whitelist.json (Found article online)
- Removed folder world\playerdata
 
```
[11:55:08] [Server thread/INFO]: KevinHonor was slain by Plague Zombie Pigman
[11:55:10] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ArrayIndexOutOfBoundsException: 8389867
	at net.minecraft.world.chunk.NibbleArray.func_76582_a(SourceFile:28) ~[apv.class:?]
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76665_b(SourceFile:75) ~[apz.class:?]
	at net.minecraft.world.chunk.Chunk.func_76628_c(Chunk.java:548) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:878) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:862) ~[apx.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:500) ~[aqk.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) ~[AsynchronousExecutor$Task.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) ~[ChunkIOExecutor.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:596) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

[crash-2023-02-05_11.55.10-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10611140/crash-2023-02-05_11.55.10-server.txt)
[2023-02-05-2.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10611143/2023-02-05-2.log)
[fml-server-2.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10611148/fml-server-2.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
you have a corrupt chunk, load a backup.

Also add it to the pile lol, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11640
