### ISSUE TITLE
Server crash on 2.2.9 version (old Java)

### ISSUE THREAD

**Issue by relaksoid** [GTNewHorizons/GT-New-Horizons-Modpack#12569]
### Your GTNH Discord Username

Богдалик#2964

### Your Pack Version

2.2.9

### Your Server

private server

### Type of Server

Ultramine

### Your Actions

Replaced old files by new one from downloaded archive. 
Server start and got a crash.

### Crash Report

[crash-2023-02-12_23.03.40-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10717444/crash-2023-02-12_23.03.40-server.txt)
[full_log.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10717445/full_log.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
probably related to https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/240 as that function is modified there. @asdflj any idea?

**Comment by Eraldoe** [comment]
I am seeing a similar crash on 2.2.9 that seems to be related to dual interfaces instead.

[crash-2023-02-12_23.22.10-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10717676/crash-2023-02-12_23.22.10-server.txt)


```
java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
	at appeng.helpers.DualityInterface.pushItemsOut(DualityInterface.java:522)
	at appeng.helpers.DualityInterface.tickingRequest(DualityInterface.java:491)
	at appeng.tile.misc.TileInterface.tickingRequest(TileInterface.java:189)
	at com.glodblock.github.common.tile.TileFluidInterface.tickingRequest(TileFluidInterface.java:110)
	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:77)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:30)
	at appeng.me.Grid.update(Grid.java:248)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:189)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_767_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityClientPlayerMP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at appeng.helpers.DualityInterface.pushItemsOut(DualityInterface.java:522)
	at appeng.helpers.DualityInterface.tickingRequest(DualityInterface.java:491)
	at appeng.tile.misc.TileInterface.tickingRequest(TileInterface.java:189)
	at com.glodblock.github.common.tile.TileFluidInterface.tickingRequest(TileFluidInterface.java:110)

-- TileFluidInterface being ticked. --
Details:
	CurrentTickRate: 62
	MinTickRate: 5
	MaxTickRate: 120
	MachineType: com.glodblock.github.common.tile.TileFluidInterface
	GridBlockType: appeng.me.helpers.AENetworkProxy
	ConnectedSides: [WEST]
	Location: dimension=0, x=163, y=73, z=107
Stacktrace:
	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:77)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:30)
	at appeng.me.Grid.update(Grid.java:248)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:189)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_767_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by hucking** [comment]
not sure if this is related or not but when opening interface terminal and when requesting fluid crafting we had server crashes, adding crash reports here:
this was the first one when opening interface terminal:
```
java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
	at appeng.container.implementations.ContainerInterfaceTerminal.func_75142_b(ContainerInterfaceTerminal.java:95)
	at net.minecraft.inventory.Container.func_75132_a(SourceFile:54)
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88)
	at net.minecraft.entity.player.EntityPlayer.openGui(Unknown Source)
	at appeng.util.Platform.openGUI(Platform.java:320)
	at appeng.parts.reporting.PartInterfaceTerminal.onPartActivate(PartInterfaceTerminal.java:39)
	at appeng.parts.AEBasePart.onActivate(AEBasePart.java:430)
	at appeng.parts.CableBusContainer.activate(CableBusContainer.java:641)
	at appeng.block.networking.BlockCableBus.onActivated(BlockCableBus.java:397)
	at appeng.block.AEBaseTileBlock.func_149727_a(AEBaseTileBlock.java:288)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityClientPlayerMP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:114)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 21 more

```
and this was second after requesting fluid crafting (which also caused crash on startup because it kept trying to craft the fluid): 
```
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
	at appeng.helpers.DualityInterface.isBusy(DualityInterface.java:867)
	at appeng.me.cluster.implementations.CraftingCPUCluster.executeCrafting(CraftingCPUCluster.java:561)
	at appeng.me.cluster.implementations.CraftingCPUCluster.updateCraftingLogic(CraftingCPUCluster.java:528)
	at appeng.me.cache.CraftingGridCache.onUpdateTick(CraftingGridCache.java:128)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:30)
	at appeng.me.Grid.update(Grid.java:248)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:189)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_773_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityClientPlayerMP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:114)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 14 more

```

**Comment by GlodBlock** [comment]
fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commit/9f538845720747b9a4ac2cd1af7b2269511040fb
