### ISSUE TITLE
Jetpack related hotkeys seem to kick you from the server

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#12573]
### Your GTNH Discord Username

Hucking#0193

### Your Pack Version

2.2.9

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Actions

when pressing any jetpack hotkey (toggling the jetpack itself or toggling hover mode for example) it kicks the player from the server. Didn't test in SP but this is probably easily reproducible.

### Crash Report

```
[22:51:35] [Server thread/ERROR]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ServerCustomPacketEvent@3d755cca:
java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.util.EnumChatFormatting.func_110646_a(java.lang.String)'
	at gravisuite.Helpers.formatMessage(Helpers.java:520) ~[Helpers.class:?]
	at gravisuite.ItemAdvancedJetPack.switchWorkMode(ItemAdvancedJetPack.java:76) ~[ItemAdvancedJetPack.class:?]
	at gravisuite.keyboard.Keyboard.processKeyPressed(Keyboard.java:118) ~[Keyboard.class:?]
	at gravisuite.network.PacketKeyPress.execute(PacketKeyPress.java:74) ~[PacketKeyPress.class:?]
	at gravisuite.network.PacketHandler.onPacketData(PacketHandler.java:58) ~[PacketHandler.class:?]
	at gravisuite.network.PacketHandler.onPacket(PacketHandler.java:32) ~[PacketHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_650_PacketHandler_onPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) [FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) [NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) [NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[22:51:35] [Server thread/ERROR]: Index: 1 Listeners:
[22:51:35] [Server thread/ERROR]: 0: NORMAL
[22:51:35] [Server thread/ERROR]: 1: ASM: gravisuite.network.PacketHandler@28393712 onPacket(Lcpw/mods/fml/common/network/FMLNetworkEvent$ServerCustomPacketEvent;)V
[22:51:35] [Server thread/ERROR]: NetworkEventFiringHandler exception
java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.util.EnumChatFormatting.func_110646_a(java.lang.String)'
	at gravisuite.Helpers.formatMessage(Helpers.java:520) ~[Helpers.class:?]
	at gravisuite.ItemAdvancedJetPack.switchWorkMode(ItemAdvancedJetPack.java:76) ~[ItemAdvancedJetPack.class:?]
	at gravisuite.keyboard.Keyboard.processKeyPressed(Keyboard.java:118) ~[Keyboard.class:?]
	at gravisuite.network.PacketKeyPress.execute(PacketKeyPress.java:74) ~[PacketKeyPress.class:?]
	at gravisuite.network.PacketHandler.onPacketData(PacketHandler.java:58) ~[PacketHandler.class:?]
	at gravisuite.network.PacketHandler.onPacket(PacketHandler.java:32) ~[PacketHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_650_PacketHandler_onPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[22:51:35] [Server thread/ERROR]: There was a critical exception handling a packet on channel GraviSuite
java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.util.EnumChatFormatting.func_110646_a(java.lang.String)'
	at gravisuite.Helpers.formatMessage(Helpers.java:520) ~[Helpers.class:?]
	at gravisuite.ItemAdvancedJetPack.switchWorkMode(ItemAdvancedJetPack.java:76) ~[ItemAdvancedJetPack.class:?]
	at gravisuite.keyboard.Keyboard.processKeyPressed(Keyboard.java:118) ~[Keyboard.class:?]
	at gravisuite.network.PacketKeyPress.execute(PacketKeyPress.java:74) ~[PacketKeyPress.class:?]
	at gravisuite.network.PacketHandler.onPacketData(PacketHandler.java:58) ~[PacketHandler.class:?]
	at gravisuite.network.PacketHandler.onPacket(PacketHandler.java:32) ~[PacketHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_650_PacketHandler_onPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
 
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
I can toggle my gravipack flight mode just fine. Can you be more specific? based on the log I guess this is AdvancedJetPack?

**Comment by hucking** [comment]
yeah it was advanced nanochestplate. both when turning it on and off it would kick us from the server and also would show up an error when we login. the logs were purged for some reason, I can try to get another 2.2.9 instance going if you cannot reproduce. Were you testing on a server or in SP tho?

**Comment by chochem** [comment]
I am in SP. but graviplate, not nano

**Comment by paulzzh** [comment]
can confirm with quantum armor
<details>
[16:23:20] [Server thread/ERROR]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ServerCustomPacketEvent@16063ee8:
java.lang.NoSuchMethodError: net.minecraft.util.EnumChatFormatting.func_110646_a(Ljava/lang/String;)Ljava/lang/String;
        at gravisuite.Helpers.formatMessage(Helpers.java:520) ~[Helpers.class:?]
        at gravisuite.ItemGraviChestPlate.switchFlyState(ItemGraviChestPlate.java:82) ~[ItemGraviChestPlate.class:?]
        at gravisuite.keyboard.Keyboard.processKeyPressed(Keyboard.java:98) ~[Keyboard.class:?]
        at gravisuite.network.PacketKeyPress.execute(PacketKeyPress.java:74) ~[PacketKeyPress.class:?]
        at gravisuite.network.PacketHandler.onPacketData(PacketHandler.java:58) ~[PacketHandler.class:?]
        at gravisuite.network.PacketHandler.onPacket(PacketHandler.java:32) ~[PacketHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_664_PacketHandler_onPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-5.4]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:1.7.10-5.4]
        at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) [FMLEventChannel.class:1.7.10-5.4]
        at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) [NetworkEventFiringHandler.class:1.7.10-5.4]
        at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) [NetworkEventFiringHandler.class:1.7.10-5.4]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-5.4]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
[16:23:20] [Server thread/ERROR]: Index: 1 Listeners:
[16:23:20] [Server thread/ERROR]: 0: NORMAL
[16:23:20] [Server thread/ERROR]: 1: ASM: gravisuite.network.PacketHandler@6371a35b onPacket(Lcpw/mods/fml/common/network/FMLNetworkEvent$ServerCustomPacketEvent;)V
[16:23:20] [Server thread/ERROR]: NetworkEventFiringHandler exception
java.lang.NoSuchMethodError: net.minecraft.util.EnumChatFormatting.func_110646_a(Ljava/lang/String;)Ljava/lang/String;
        at gravisuite.Helpers.formatMessage(Helpers.java:520) ~[Helpers.class:?]
        at gravisuite.ItemGraviChestPlate.switchFlyState(ItemGraviChestPlate.java:82) ~[ItemGraviChestPlate.class:?]
        at gravisuite.keyboard.Keyboard.processKeyPressed(Keyboard.java:98) ~[Keyboard.class:?]
        at gravisuite.network.PacketKeyPress.execute(PacketKeyPress.java:74) ~[PacketKeyPress.class:?]
        at gravisuite.network.PacketHandler.onPacketData(PacketHandler.java:58) ~[PacketHandler.class:?]
        at gravisuite.network.PacketHandler.onPacket(PacketHandler.java:32) ~[PacketHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_664_PacketHandler_onPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-5.4]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:168) ~[EventBus.class:1.7.10-5.4]
        at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:1.7.10-5.4]
        at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:1.7.10-5.4]
        at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:1.7.10-5.4]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-5.4]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
[16:23:20] [Server thread/ERROR]: There was a critical exception handling a packet on channel GraviSuite
java.lang.NoSuchMethodError: net.minecraft.util.EnumChatFormatting.func_110646_a(Ljava/lang/String;)Ljava/lang/String;
        at gravisuite.Helpers.formatMessage(Helpers.java:520) ~[Helpers.class:?]
        at gravisuite.ItemGraviChestPlate.switchFlyState(ItemGraviChestPlate.java:82) ~[ItemGraviChestPlate.class:?]
        at gravisuite.keyboard.Keyboard.processKeyPressed(Keyboard.java:98) ~[Keyboard.class:?]
        at gravisuite.network.PacketKeyPress.execute(PacketKeyPress.java:74) ~[PacketKeyPress.class:?]
        at gravisuite.network.PacketHandler.onPacketData(PacketHandler.java:58) ~[PacketHandler.class:?]
        at gravisuite.network.PacketHandler.onPacket(PacketHandler.java:32) ~[PacketHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_664_PacketHandler_onPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-5.4]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:168) ~[EventBus.class:1.7.10-5.4]
        at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:1.7.10-5.4]
        at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:1.7.10-5.4]
        at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:1.7.10-5.4]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-5.4]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
[16:23:20] [Server thread/INFO]: Paulzzh lost connection: A fatal error has occured, this connection is terminated
</details>

**Comment by Metallikus** [comment]
Confirm.
Removing the **mods/gravisuiteneo-1.7.10-1.0.3.jar** solves this problem.

**Comment by boubou19** [comment]
> Confirm. Removing the **mods/gravisuiteneo-1.7.10-1.0.3.jar** solves this problem.

Ok but the mod is meant to stay as it is a total rework of all the questionably legal editions of gravisuite. 

@glowredman any idea?

**Comment by glowredman** [comment]
`EnumChatFormatting#getTextWithoutFormattingCodes` is a client-only method. I overlooked this when creating the `Helpers` mixin, should be an easy fix.
