### ISSUE TITLE
Server console error flood

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12654]
### Your Pack Version

2.2.10

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

When opening a cover, ever since 2.2.8 the following error used to be reported in the console, however, as of 2.2.10 it now never stops registering this error, even when the cover is no longer being accessed by a player:
```
Feb 19, 2023 10:08:59 PM io.netty.channel.embedded.EmbeddedChannel recordException
WARNING: More than one exception was raised. Will report only the first one and log others.
java.lang.RuntimeException: Missing
at cpw.mods.fml.server.FMLServerHandler.getClientToServerNetworkManager(FMLServerHandler.java:238)
at cpw.mods.fml.common.FMLCommonHandler.getClientToServerNetworkManager(FMLCommonHandler.java:530)
at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$8.selectNetworks(FMLOutboundHandler.java:225)
at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273)
at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115)
at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688)
at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717)
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893)
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239)
at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:236)
at eu.usrv.yamcore.network.PacketDispatcher.sendToServer(PacketDispatcher.java:117)
at com.github.technus.tectech.thing.cover.GT_Cover_TM_EnderFluidLink$EnderFluidLinkUIFactory.addUIWidgets(GT_Cover_TM_EnderFluidLink.java:160)
at gregtech.api.util.GT_CoverBehaviorBase$UIFactory.createWindow(GT_CoverBehaviorBase.java:450)
at com.github.technus.tectech.thing.cover.GT_Cover_TM_EnderFluidLink.createWindow(GT_Cover_TM_EnderFluidLink.java:135)
at gregtech.api.gui.modularui.GT_UIInfos.createCoverContainer(GT_UIInfos.java:166)
at gregtech.api.gui.modularui.GT_UIInfos.lambda$static$3(GT_UIInfos.java:74)
at com.gtnewhorizons.modularui.common.internal.InternalUIMapper.getServerGuiElement(InternalUIMapper.java:54)
at cpw.mods.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:243)
at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:75)
at com.gtnewhorizons.modularui.common.builder.UIInfo.open(UIInfo.java:44)
at gregtech.api.gui.modularui.GT_UIInfos.openCoverUI(GT_UIInfos.java:124)
at gregtech.api.util.GT_CoverBehavior.onCoverShiftRightclick(GT_CoverBehavior.java:257)
at gregtech.api.util.GT_CoverBehavior.onCoverShiftRightClickImpl(GT_CoverBehavior.java:83)
at gregtech.api.util.GT_CoverBehavior.onCoverShiftRightClickImpl(GT_CoverBehavior.java:20)
at gregtech.api.util.GT_CoverBehaviorBase.onCoverShiftRightClick(GT_CoverBehaviorBase.java:223)
at gregtech.api.metatileentity.BaseMetaTileEntity.onRightclick(BaseMetaTileEntity.java:1640)
at gregtech.common.blocks.GT_Block_Machines.func_149727_a(GT_Block_Machines.java:369)
at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at fastcraft.u.a(F:289)
at fastcraft.H.aq(F:36)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[22:09:01] [Server thread/ERROR]: FMLIndexedMessageCodec exception caught
java.lang.RuntimeException: Missing
at cpw.mods.fml.server.FMLServerHandler.getClientToServerNetworkManager(FMLServerHandler.java:238) ~[FMLServerHandler.class:?]
at cpw.mods.fml.common.FMLCommonHandler.getClientToServerNetworkManager(FMLCommonHandler.java:530) ~[FMLCommonHandler.class:?]
at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$8.selectNetworks(FMLOutboundHandler.java:225) ~[FMLOutboundHandler$OutboundTarget$8.class:?]
at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:?]
at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:236) ~[SimpleNetworkWrapper.class:?]
at eu.usrv.yamcore.network.PacketDispatcher.sendToServer(PacketDispatcher.java:117) ~[PacketDispatcher.class:?]
at com.github.technus.tectech.thing.cover.GT_Cover_TM_EnderFluidLink$EnderFluidLinkUIFactory.addUIWidgets(GT_Cover_TM_EnderFluidLink.java:160) ~[GT_Cover_TM_EnderFluidLink$EnderFluidLinkUIFactory.class:?]
at gregtech.api.util.GT_CoverBehaviorBase$UIFactory.createWindow(GT_CoverBehaviorBase.java:450) ~[GT_CoverBehaviorBase$UIFactory.class:?]
at com.github.technus.tectech.thing.cover.GT_Cover_TM_EnderFluidLink.createWindow(GT_Cover_TM_EnderFluidLink.java:135) ~[GT_Cover_TM_EnderFluidLink.class:?]
at gregtech.api.gui.modularui.GT_UIInfos.createCoverContainer(GT_UIInfos.java:166) ~[GT_UIInfos.class:?]
at gregtech.api.gui.modularui.GT_UIInfos.lambda$static$3(GT_UIInfos.java:74) ~[GT_UIInfos.class:?]
at com.gtnewhorizons.modularui.common.internal.InternalUIMapper.getServerGuiElement(InternalUIMapper.java:54) [InternalUIMapper.class:?]
at cpw.mods.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:243) [NetworkRegistry.class:?]
at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:75) [FMLNetworkHandler.class:?]
at com.gtnewhorizons.modularui.common.builder.UIInfo.open(UIInfo.java:44) [UIInfo.class:?]
at gregtech.api.gui.modularui.GT_UIInfos.openCoverUI(GT_UIInfos.java:124) [GT_UIInfos.class:?]
at gregtech.api.util.GT_CoverBehavior.onCoverShiftRightclick(GT_CoverBehavior.java:257) [GT_CoverBehavior.class:?]
at gregtech.api.util.GT_CoverBehavior.onCoverShiftRightClickImpl(GT_CoverBehavior.java:83) [GT_CoverBehavior.class:?]
at gregtech.api.util.GT_CoverBehavior.onCoverShiftRightClickImpl(GT_CoverBehavior.java:20) [GT_CoverBehavior.class:?]
at gregtech.api.util.GT_CoverBehaviorBase.onCoverShiftRightClick(GT_CoverBehaviorBase.java:223) [GT_CoverBehaviorBase.class:?]
at gregtech.api.metatileentity.BaseMetaTileEntity.onRightclick(BaseMetaTileEntity.java:1640) [BaseMetaTileEntity.class:?]
at gregtech.common.blocks.GT_Block_Machines.func_149727_a(GT_Block_Machines.java:369) [GT_Block_Machines.class:?]
at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source) [mx.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) [nh.class:?]
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
Additionally accessing a machine controller cover will throw the following error:
`[22:32:44] [Server thread/WARN]: Texture Getter of CycleButtonWidget was not set!`
In some cases closes the GUI of this cover will also result in a fatal error terminating the connection without further details as to why being logged

**Comment by miozune** [comment]
Please provide full fml log

**Comment by Tommeh1** [comment]
This fixes the largest issue, but not everything in my comment after it.

**Comment by Tommeh1** [comment]
> Please provide full fml log

As for these logs, they're no longer being generated since 2.2.10
