### ISSUE TITLE
Flawed cubic zirconia recipe is completely bugged in volcanus

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#12702]
### Your GTNH Discord Username

Keyla#3300

### Your Pack Version

2.2.10

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

Tried making flawed cubic zirconia in ebf (10 zirconium dust+20k Oxygen with yttrium oxide as a catalyst)

### The Reality

Oxygen and 10 zirconium dust disappear, one phantom zirconium dust item remains in the input bus. Volcanuses dont even start doing a recipe.
I dont have circuit#1 and zirconium ingots definitely dont smelt, its not a circuit conflict. Volcanuses keep being enabled, so its not energy issue.
https://imgur.com/PNOfNN9
This recipe works in EBF for me

### Your Proposal

fix the bug or tell me what im doing wrong if it is not a bug

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LewisSaber** [comment]
Can confirm

**Comment by LewisSaber** [comment]
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NullPointerException
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gregtech.api.util.GT_ParallelHelper.determineParallel(GT_ParallelHelper.java:316)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gregtech.api.util.GT_ParallelHelper.build(GT_ParallelHelper.java:179)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.processing.advanced.GregtechMetaTileEntity_Adv_EBF.checkRecipeGeneric(GregtechMetaTileEntity_Adv_EBF.java:287)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.processing.advanced.GregtechMetaTileEntity_Adv_EBF.checkRecipe(GregtechMetaTileEntity_Adv_EBF.java:220)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.checkRecipe(GT_MetaTileEntity_MultiBlockBase.java:372)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.runMachine(GT_MetaTileEntity_MultiBlockBase.java:429)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:315)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.onPostTick(GregtechMeta_MultiBlockBase.java:854)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.processing.advanced.GregtechMetaTileEntity_Adv_EBF.onPostTick(GregtechMetaTileEntity_Adv_EBF.java:318)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:522)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at fastcraft.u.a(F:289)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at fastcraft.H.aq(F:36)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[17:08:15] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

From fml-client-latest

**Comment by LewisSaber** [comment]
@BlueWeabo

**Comment by BlueWeabo** [comment]
Fucken NPEs. why do recipes have null item outputs

**Comment by BlueWeabo** [comment]
> > Fucken NPEs. why do recipes have null item outputs
> 
> Who add it? Alk or someone else ?

Most likely Alk, but I don't want to go through the code to search for it right now. Seems painful. much easier to add a null check

**Comment by chochem** [comment]
the other is bartworks, so not alk ;)

**Comment by BlueWeabo** [comment]
lovely

**Comment by BlueWeabo** [comment]
two code bases i don't want to look into. gt5u is enough
