### ISSUE TITLE
Crash StackOverflowError

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#12718]
### Your GTNH Discord Username

DreamMasterXXL#3371

### Your Pack Version

2.2.12-3

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Actions

Just look around and got this crash

### Crash Report

[crash-2023-02-26_23.13.33-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10834874/crash-2023-02-26_23.13.33-client.txt)
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10834876/fml-client-latest.log)
[PlayerActivity.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10834877/PlayerActivity.log)
[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10834878/GregTech.log)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10834879/latest.log)

### Final Checklist

- [ ] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
```
java.lang.StackOverflowError
    at java.lang.String.indexOf(String.java:2430)
    at java.lang.String.indexOf(String.java:2386)
    at net.minecraft.client.gui.FontRenderer.getCharWidthFloat(FontRenderer.java:759)
    at net.minecraft.client.gui.FontRenderer.func_78259_e(FontRenderer.java:1019)
    at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:956)
    at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:968)
    at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:968)
    at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:968)
    at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:968)
    at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:968)
    at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:968)
    at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:968)
    ```

**Comment by eigenraven** [comment]
This is the vanilla `String wrapFormattedStringToWidth(String str, int wrapWidth)` function, it recursively calls itself for every line it splits. Sadly the stacktrace is partially lost, so we can't tell what tried to wrap an enormous string to a fixed width, but most likely it was some gui code. Either the string was very long, or wrapWidth was very small, or both.

**Comment by Fiyorin** [comment]
doesn't seem to be fully fixed yet in hodgepodge-2.0.38 (rc2):

`java.lang.StackOverflowError
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:229)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:582)
    at java.lang.StringBuilder.append(StringBuilder.java:179)
    at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:967)
    at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:968)
    at net.minecraft.client.gui.FontRenderer.func_78280_d(FontRenderer.java:968)`

[crash-2023-03-04_11.53.29-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10888130/crash-2023-03-04_11.53.29-client.txt)

**Comment by eigenraven** [comment]
It looks like the mixin didn't apply, can you post the full log?

**Comment by Fiyorin** [comment]
pretty sure the UI of a forming press was open when it happened and there's this 
![image](https://user-images.githubusercontent.com/61357/222897302-df123a50-87e8-47e5-a789-3cfa04a78508.png)

**Comment by Fiyorin** [comment]
> It looks like the mixin didn't apply, can you post the full log?

[fml-client-latest.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10888173/fml-client-latest.zip)

**Comment by eigenraven** [comment]
oh huh I somehow completely missed that
```
[10:10:02] [main/ERROR] [mixin/]: mixins.hodgepodge.early.json:minecraft.MixinFontRenderer: Super class 'net.minecraft.client.gui.FontRenderer' of minecraft.MixinFontRenderer was not found in the hierarchy of target class 'net/minecraft/client/gui/FontRenderer'
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Super class 'net.minecraft.client.gui.FontRenderer' of minecraft.MixinFontRenderer was not found in the hierarchy of target class 'net/minecraft/client/gui/FontRenderer'
```

**Comment by Alexdoru** [comment]
https://github.com/GTNewHorizons/Hodgepodge/pull/191#pullrequestreview-1325009566
