### ISSUE TITLE
Using NEI to disable day/night cycle in a personal dimension crashes the game. (RC2)

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#12791]
### Your GTNH Discord Username

Abdiel Kavash#2431

### Your Pack Version

2.3.0-RC-2_(MMC)

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Create a new personal dimension (I used default settings, preset 3).

Enter said dimension.

Right-click one of the time of day icons in the top left of NEI to disable that part of the cycle.

Game crashes ("A fatal exception has occurred"), and brings me to the multiplayer server selection screen (even though this was a singleplayer world and I never touched MP on this install.)

The buttons work fine in the overworld, haven't tried in other dimensions.

### Crash Report

https://mclo.gs/HqbK5Jb

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
A crash is bad obviously. but not sure what you were trying to do. there is no day-night cycle there

**Comment by Connor-Colenso** [comment]
![image](https://user-images.githubusercontent.com/52056774/222939526-f97247b4-efa0-4baf-941b-ea27faabf684.png)

Anyway, does this brick the save? Can you log back into the world?

**Comment by AbdielKavash** [comment]
I can log back in just fine, it does not seem to have any negative effect other than the immediate crash.

The buttons worked correctly at least in 2.2.0.0 (as in, didn't crash -- as you say, there is no day cycle to be turned off).

**Comment by eigenraven** [comment]
```
	java.lang.RuntimeException: java.io.FileNotFoundException: C:\Games\PrismLauncher\instances\GT_New_Horizons_2.3.0-RC-2_(MMC)\.minecraft\saves\New World 2\PERSONAL_DIM_180\NEI\world.dat (The system cannot find the path specified)
	at codechicken.nei.NEIServerConfig.saveWorld(NEIServerConfig.java:114) ~[NEIServerConfig.class:?]
	at codechicken.nei.NEIServerConfig.disableAction(NEIServerConfig.java:143) ~[NEIServerConfig.class:?]
	at codechicken.nei.NEISPH.handlePropertyChange(NEISPH.java:116) ~[NEISPH.class:?]
	at codechicken.nei.NEISPH.handlePacket(NEISPH.java:59) ~[NEISPH.class:?]
	at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:116) ~[PacketCustom$ServerInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:78) ~[PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:65) ~[PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
	at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.io.FileNotFoundException: C:\Games\PrismLauncher\instances\GT_New_Horizons_2.3.0-RC-2_(MMC)\.minecraft\saves\New World 2\PERSONAL_DIM_180\NEI\world.dat (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_351]
	at java.io.FileOutputStream.open(Unknown Source) ~[?:1.8.0_351]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_351]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_351]
	at codechicken.nei.NEIServerUtils.writeNBT(NEIServerUtils.java:473) ~[NEIServerUtils.class:?]
	at codechicken.nei.NEIServerConfig.saveWorld(NEIServerConfig.java:112) ~[NEIServerConfig.class:?]
	... 21 more
```
