### ISSUE TITLE
Indefinite Freeze when opening Compressed Chest on specific GUI size and window size

### ISSUE THREAD

**Issue by kstvr32** [GTNewHorizons/GT-New-Horizons-Modpack#12800]
### Your GTNH Discord Username

neoprop#4986

### Your Pack Version

2.3.0-RC-2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Steps to reproduce:
- Start new world 
- Set GUI size to "Large"
- Resize window to 1720x1070 (or there about)
- Place compressed chest
- Right click compressed chest

It seems this bug only causes problems when the compressed chest GUI is small enough for NEI to render but large enough to overlap with it.

### Crash Report

[New Paste 1.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10892480/New.Paste.1.txt)

Freeze happened when I opened the compressed chest at 12:32:45

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by kstvr32** [comment]
Updating to RC3 fixed this issue.

**Comment by riking** [comment]
Here's a stack trace taken during the infinite hang. It's inside the BookmarkPanel.

```
"Client thread" #1 prio=5 os_prio=0 tid=0x00007f5c60012000 nid=0x1b0dad runnable [0x00007f5c6568f000]
   java.lang.Thread.State: RUNNABLE
	at java.util.HashMap.getNode(HashMap.java:573)
	at java.util.HashMap$EntrySet.contains(HashMap.java:1022)
	at java.util.AbstractCollection.containsAll(AbstractCollection.java:318)
	at java.util.AbstractSet.equals(AbstractSet.java:95)
	at net.minecraft.nbt.NBTTagCompound.equals(NBTTagCompound.java:356)
	at codechicken.nei.recipe.BookmarkRecipeId.equals(BookmarkRecipeId.java:141)
	at codechicken.nei.BookmarkPanel$BookmarkGrid.generateToDoSpaces(BookmarkPanel.java:182)
	at codechicken.nei.BookmarkPanel$BookmarkGrid.onGridChanged(BookmarkPanel.java:203)
	at codechicken.nei.ItemsGrid.updateGuiOverlapSlots(ItemsGrid.java:174)
	at codechicken.nei.ItemsGrid.refresh(ItemsGrid.java:154)
	at codechicken.nei.PanelWidget.resize(PanelWidget.java:121)
	at codechicken.nei.BookmarkPanel.resize(BookmarkPanel.java:792)
	at codechicken.nei.LayoutStyleMinecraft.layout(LayoutStyleMinecraft.java:107)
	at codechicken.nei.LayoutManager.layout(LayoutManager.java:337)
	at codechicken.nei.LayoutManager.load(LayoutManager.java:609)
	at codechicken.nei.guihook.GuiContainerManager.load(GuiContainerManager.java:381)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146280_a(GuiContainer.java)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
	at cpw.mods.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:472)
	at cpw.mods.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:303)
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:94)
	at net.minecraft.entity.player.EntityPlayer.openGui(Unknown Source)
	at cpw.mods.fml.common.network.internal.OpenGuiHandler.channelRead0(OpenGuiHandler.java:16)
	at cpw.mods.fml.common.network.internal.OpenGuiHandler.channelRead0(OpenGuiHandler.java:11)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(Unknown Source)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5107)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
