### ISSUE TITLE
ConcurrentModificationException saving world

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12802]
### Your Pack Version

2.2.10

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

Although we can't figure out what may be having problems saving and no further details are logged i'm making this issue either way in case someone with the same error can get a hold of more details:
`[04:46:14] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save World
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.util.ConcurrentModificationException
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:29)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:32)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:149)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:139)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75821_a(AnvilChunkLoader.java:265)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:251)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:30)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:23)
[04:46:15] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Thread.run(Thread.java:748)`
It does not occur every single time, only once every hour or 2

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
We will need more info to resolve this. I'll code a small opt-in debug feature in hodgepodge for this.

**Comment by Glease** [comment]
It's probably one of the net.minecraftforge.event.world.ChunkDataEvent.Save subscribers.

**Comment by Glease** [comment]
It's probably TecTech's event handler.. Should have made a copy.

**Comment by Glease** [comment]
I have walked through all registered ChunkDataEvent.Save and the only offender is TecTech one. The linked PR should be an exhaustive fix for this issue.
