### ISSUE TITLE
Unable to launch server

### ISSUE THREAD

**Issue by Jord38** [GTNewHorizons/GT-New-Horizons-Modpack#12844]
### Your GTNH Discord Username

Jord#9200

### Your Pack Version

2.3.0-RC-3

### Your Server

Private

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

Trying to start the server using the provided startserver-java9.bat but the server won't start.

### Crash Report

[17:08:07] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[17:08:07] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[17:08:07] [main/INFO]: Loading tweak class name xt
[17:08:07] [main/ERROR]: Unable to launch

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Jord38** [comment]
I have tried different java versions but none of them seem to work so far.
When running the startup script in console it seems to output a bit more information which might be useful.
`java -Xms6G -Xmx6G -Dfml.readTimeout=180 @java9args.txt -txt nogui
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0
[17:34:49] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by cpw.mods.fml.common.launcher.FMLTweaker (file:/C:/MC%20Servers/GTNH/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar)
WARNING: Please consider reporting this to the maintainers of cpw.mods.fml.common.launcher.FMLTweaker
WARNING: System::setSecurityManager will be removed in a future release
[17:34:49] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[17:34:49] [main/INFO]: Loading tweak class name xt
Range [0, -1) out of bounds for length 2
java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 2
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
        at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4602)
        at java.base/java.lang.String.substring(String.java:2715)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:122)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:37)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:11)
[17:34:49] [main/ERROR]: Unable to launch
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:37)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:11)
Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
        at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:77)
        at java.base/java.lang.SecurityManager.checkExit(SecurityManager.java:624)
        at java.base/java.lang.Runtime.exit(Runtime.java:113)
        at java.base/java.lang.System.exit(System.java:1908)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:170)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 3 more`

**Comment by Jord38** [comment]
I downloaded the Java 8 server pack and JRE and that seems to work fine. So not sure why it doesn't work with the 9+ server pack,

**Comment by Fiyorin** [comment]
how did "-txt" end up in the arguments, i'd take it out
```
java -Xms6G -Xmx6G -Dfml.readTimeout=180 @java9args.txt -txt nogui 
```

is this a fresh install or did you upgrade? just to make sure: you downloaded the java9 version of the pack right (GT_New_Horizons_2.3.0-RC-3_SERVER_JAVA9.zip)?

**Comment by Srdra2k3** [comment]
Have you changed your PATH to your java 9+ install location?

**Comment by Jord38** [comment]
> how did "-txt" end up in the arguments, i'd take it out
> 
> ```
> java -Xms6G -Xmx6G -Dfml.readTimeout=180 @java9args.txt -txt nogui 
> ```
> 
> is this a fresh install or did you upgrade? just to make sure: you downloaded the java9 version of the pack right (GT_New_Horizons_2.3.0-RC-3_SERVER_JAVA9.zip)?



I was looking through the discord trying to find people who had similar issues and saw someone say to someone to try that so I also tried it. But without it the server also wouldn't start.


> Have you changed your PATH to your java 9+ install location?

Yes and I also tried it with the JRE in a folder in the server folder and then running it with the java.exe from there.

**Comment by eigenraven** [comment]
It worked when you got the `Loading tweak class name xt Range` error - that error was because of the extra `-txt` flag which gets parsed as `--tweak-class xt`

**Comment by Jord38** [comment]
> It worked when you got the `Loading tweak class name xt Range` error - that error was because of the extra `-txt` flag which gets parsed as `--tweak-class xt`

Someone suggested that -txt flag somewhere so I tried it and must've forgot to take it out again. But still even without the server won't boot.

`C:\MC Servers\GTNH>java -Xms6G -Xmx6G -Dfml.readTimeout=180 @java9args.txt nogui
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:495)
        at java.base/java.lang.Class.forName(Class.java:474)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:21)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:11)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more

C:\MC Servers\GTNH>java -version
java version "19.0.2" 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)`

I am now however running a server on Java 8 perfectly fine so unless Java 8 support gets discontinued soon I'll close the ticket.
