### ISSUE TITLE
Crash when no audio device is enabled in Windows

### ISSUE THREAD

**Issue by LKD-PIX** [GTNewHorizons/GT-New-Horizons-Modpack#12848]
### Your Pack Version

2.2.10

### Your Server

Dedicated Self hosted

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Actions

Click a main Menu Button

### Crash Report

```
[14:37:17] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:131]: Error in class 'LibraryLWJGLOpenAL'
[14:37:17] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:132]:     Source '416dade0-65c5-4fd3-a4f7-0f1e65507b9e' was not created because a sound buffer was not found for minecraft:sounds/random/click.ogg
[14:37:17] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1654) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5104) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165) [launchwrapper-1.15.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [launchwrapper-1.15.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.HashMap.get(Object)" because "this.sourceMap" is null
	at paulscode.sound.Library.setPitch(Library.java:893) ~[Library.class:?]
	at paulscode.sound.SoundSystem.CommandSetPitch(SoundSystem.java:1918) ~[SoundSystem.class:?]
	at paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2461) ~[SoundSystem.class:?]
	at org.blockartistry.mod.DynSurround.client.sound.SoundManager.flushSound(SoundManager.java:135) ~[SoundManager.class:?]
	at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java:366) ~[btj.class:?]
	at net.minecraft.client.audio.SoundHandler.func_147682_a(SourceFile:154) ~[btp.class:?]
	at net.minecraft.client.gui.GuiButton.func_146113_a(GuiButton.java:115) ~[bcb.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:224) ~[bdw.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) ~[bdw.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) ~[bdw.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5104) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) ~[minecraft-1.7.10-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165) ~[launchwrapper-1.15.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) ~[launchwrapper-1.15.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) ~[OneSixLauncher.class:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) ~[OneSixLauncher.class:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[EntryPoint.class:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[EntryPoint.class:?]
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by AlexCatze** [comment]
[crash-2023-06-14_20.46.12-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11749349/crash-2023-06-14_20.46.12-client.txt)

Crash also happens on system with present enabled audio devices. Looks like sometimes minecraft with new java cannot get audio devices.

**Comment by xiPakuL** [comment]
Yeah this error is a bit annoying for someone with a wireless usb headset.
I get crashes all the time because my headset runs out of power and is my only activated Audio Device in windows, so GTNH just instantly crashes.
