### ISSUE TITLE
kicked when pressing crafting status in terminal with no cpus present

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#12888]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Actions

steps to reproduce:
- set up a AE system of just neutronium cell + cable + terminal
- press crafting status
- get kicked

### Crash Report

Relevant error:
```
java.lang.NullPointerException: Cannot invoke "appeng.container.implementations.CraftingCPUStatus.getServerCluster()" because the return value of "appeng.container.implementations.ContainerCPUTable.getSelectedCPU()" is null
	at appeng.core.sync.packets.PacketCraftingRemainingOperations.serverPacketData(PacketCraftingRemainingOperations.java:55) ~[PacketCraftingRemainingOperations.class:?]
	at appeng.core.sync.network.AppEngServerPacketHandler.onPacketData(AppEngServerPacketHandler.java:32) ~[AppEngServerPacketHandler.class:?]
	at appeng.core.sync.network.NetworkHandler.serverPacket(NetworkHandler.java:78) ~[NetworkHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1887_NetworkHandler_serverPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) [FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) [NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) [NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

Full Log:
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10961316/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
most likely caused by https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/261 (during feature freeze :( )
