### ISSUE TITLE
Cant launch Greg tech new horizons prism launcher

### ISSUE THREAD

**Issue by chaosblade201** [GTNewHorizons/GT-New-Horizons-Modpack#12897]
### Your GTNH Discord Username

chaosblade#6706

### Your Pack Version

2.3.0.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

fresh install of gregtech new horizons from prism launcher through Technic installed latest version of java 8 

### Crash Report

[](url)
[crash report.odt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10965365/crash.report.odt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
can't you just install the pack via mmc/prism archive on downloads.gtnewhorizons.com?

**Comment by chaosblade201** [comment]
tried that still didnt work i get the same get a different error which is the following 

'FATAL ERROR in native method: Thread[#1,Client thread,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.nglGetString(Native Method)
	at org.lwjgl.opengl.GL11C.glGetString(GL11C.java:978)
	at org.lwjgl.opengl.GL11.glGetString(GL11.java:3100)
	at org.lwjglx.opengl.GL11.glGetString(GL11.java:1009)
	at net.minecraft.client.Minecraft$7.call(Minecraft.java:2363)
	at net.minecraft.client.Minecraft$7.call(Minecraft.java:2359)
	at net.minecraft.crash.CrashReportCategory.func_71500_a(CrashReportCategory.java:102)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2358)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5097)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.lang.invoke.LambdaForm$DMH/0x0000000800c03000.invokeStatic(java.base@19.0.2/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x0000000800e42400.invoke(java.base@19.0.2/LambdaForm$MH)
	at java.lang.invoke.Invokers$Holder.invokeExact_MT(java.base@19.0.2/Invokers$Holder)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@19.0.2/Unknown Source)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@19.0.2/Unknown Source)
	at java.lang.reflect.Method.invoke(java.base@19.0.2/Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
	at java.lang.invoke.LambdaForm$DMH/0x0000000800c03400.invokeStaticInit(java.base@19.0.2/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x0000000800c03c00.invokeExact_MT(java.base@19.0.2/LambdaForm$MH)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Process crashed with exitcode 6.'

**Comment by boubou19** [comment]
if you took java 17-19 archive you must run it with java 19

**Comment by chaosblade201** [comment]
i am using jdk-19.0.2+7-jre from adoptinum

**Comment by chaosblade201** [comment]
it works now that i restarted my computer not sure why it didn't before even though i changed nothing

**Comment by chochem** [comment]
it was using java 8 with the java8 version of the pack in case neither of you looked in the log :P

This was the error in case it pops up again:
```
org.lwjgl.LWJGLException: Could not choose GLX13 config
	at org.lwjgl.opengl.LinuxDisplayPeerInfo.initDefaultPeerInfo(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.LinuxDisplayPeerInfo.<init>(LinuxDisplayPeerInfo.java:61) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.LinuxDisplay.createPeerInfo(LinuxDisplay.java:828) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
```

**Comment by eigenraven** [comment]
Ah a GLX creating error fixed by a reboot - did you run a system update that updated your kernel or gpu drivers and didn't reboot afterwards? That's the most common cause of this sort of issue

**Comment by boubou19** [comment]
> it was using java 8 with the java8 version of the pack in case neither of you looked in the log :P
> 
> This was the error in case it pops up again:
> 
> ```
> org.lwjgl.LWJGLException: Could not choose GLX13 config
> 	at org.lwjgl.opengl.LinuxDisplayPeerInfo.initDefaultPeerInfo(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
> 	at org.lwjgl.opengl.LinuxDisplayPeerInfo.<init>(LinuxDisplayPeerInfo.java:61) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
> 	at org.lwjgl.opengl.LinuxDisplay.createPeerInfo(LinuxDisplay.java:828) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
> ```

i have for principle to not open suspicious odt files when one can simply post raw text or txt file 😄
