### ISSUE TITLE
Disconnect when setting item count in pattern terminal

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12933]
### Your Pack Version

2.3.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

In rare occasions when one sets the item count for something inside of a pattern by using the middle mouse button on it and clicks set they'll get disconnected and the server logs the following error:

```
[00:26:20] [Server thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ServerCustomPacketEvent@3ccd2763:
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:424) ~[?:1.8.0_282]
	at java.util.ArrayList.get(ArrayList.java:437) ~[?:1.8.0_282]
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104) ~[zs.class:?]
	at appeng.core.sync.packets.PacketPatternValueSet.serverPacketData(PacketPatternValueSet.java:59) ~[PacketPatternValueSet.class:?]
	at appeng.core.sync.network.AppEngServerPacketHandler.onPacketData(AppEngServerPacketHandler.java:32) ~[AppEngServerPacketHandler.class:?]
	at appeng.core.sync.network.NetworkHandler.serverPacket(NetworkHandler.java:78) ~[NetworkHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1276_NetworkHandler_serverPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) [FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) [NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) [NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
	at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[00:26:20] [Server thread/ERROR] [FML/]: Index: 1 Listeners:
[00:26:20] [Server thread/ERROR] [FML/]: 0: NORMAL
[00:26:20] [Server thread/ERROR] [FML/]: 1: ASM: appeng.core.sync.network.NetworkHandler@52871ab4 serverPacket(Lcpw/mods/fml/common/network/FMLNetworkEvent$ServerCustomPacketEvent;)V
[00:26:20] [Server thread/ERROR] [FML/]: NetworkEventFiringHandler exception
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:424) ~[?:1.8.0_282]
	at java.util.ArrayList.get(ArrayList.java:437) ~[?:1.8.0_282]
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104) ~[zs.class:?]
	at appeng.core.sync.packets.PacketPatternValueSet.serverPacketData(PacketPatternValueSet.java:59) ~[PacketPatternValueSet.class:?]
	at appeng.core.sync.network.AppEngServerPacketHandler.onPacketData(AppEngServerPacketHandler.java:32) ~[AppEngServerPacketHandler.class:?]
	at appeng.core.sync.network.NetworkHandler.serverPacket(NetworkHandler.java:78) ~[NetworkHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1276_NetworkHandler_serverPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
	at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[00:26:20] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel AE2
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:424) ~[?:1.8.0_282]
	at java.util.ArrayList.get(ArrayList.java:437) ~[?:1.8.0_282]
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104) ~[zs.class:?]
	at appeng.core.sync.packets.PacketPatternValueSet.serverPacketData(PacketPatternValueSet.java:59) ~[PacketPatternValueSet.class:?]
	at appeng.core.sync.network.AppEngServerPacketHandler.onPacketData(AppEngServerPacketHandler.java:32) ~[AppEngServerPacketHandler.class:?]
	at appeng.core.sync.network.NetworkHandler.serverPacket(NetworkHandler.java:78) ~[NetworkHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1276_NetworkHandler_serverPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
	at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
This apparently occurs when the player tries to do it too quickly, potentially while something is still loading.

**Comment by Tommeh1** [comment]
Still exists in 2.3.2
