### ISSUE TITLE
Ultramine console spam \ flood

### ISSUE THREAD

**Issue by player5** [GTNewHorizons/GT-New-Horizons-Modpack#12972]
### Your Pack Version

2.3.1

### Your Server

Private ultramine

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

Problem after server loading finished

### The Reality

[20:48:29] [ERRO] Original stacktrace
java.lang.NoSuchFieldError: sRocketFuels
        at goodgenerator.blocks.tileEntity.UniversalChemicalFuelEngine.checkRecipe_EM(UniversalChemicalFuelEngine.java:251)
        at com.github.technus.tectech.thing.metaTileEntity.multi.base.GT_MetaTileEntity_MultiblockBase_EM.checkRecipe(GT_MetaTileEntity_MultiblockBase_EM.java:1051)
        at com.github.technus.tectech.thing.metaTileEntity.multi.base.GT_MetaTileEntity_MultiblockBase_EM.onPostTick(GT_MetaTileEntity_MultiblockBase_EM.java:1268)
        at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:522)
        at net.minecraft.world.World.func_72939_s(World.java:2069)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1213)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:670)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:567)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:444)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:719)

multiple times

### Your Proposal

I dont know

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by player5** [comment]
I can join to server/
