### ISSUE TITLE
Crash with better p2p

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#12996]
### Your GTNH Discord Username

Trollolol

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

I was trying to use advanced memory card to one of the me p2p in a huge network. It crashes.
![image](https://user-images.githubusercontent.com/105285781/226991507-43413f7b-4b41-4a0e-b43f-f09be0c7f98e.png)

### Crash Report

[crash-2023-03-22_13.37.09-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11043107/crash-2023-03-22_13.37.09-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by firenoo** [comment]
Try updating to the latest BetterP2P to see if this continues to happen.

**Comment by dark544** [comment]
I get the same Error. I am playing on a local Server using Java 19 and Version 2.3.0.
I tried upgrading to BetterP2P 1.1.5 but now I get this Error:
```
[10:37:56] [Client thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.IllegalAccessError: class com.projecturanus.betterp2p.client.gui.InfoWrapper tried to access protected method 'net.minecraft.util.IIcon appeng.parts.p2p.PartP2PTunnel.getTypeTexture()' (com.projecturanus.betterp2p.client.gui.InfoWrapper and appeng.parts.p2p.PartP2PTunnel are in unnamed module of loader net.minecraft.launchwrapper.LaunchClassLoader @5f4da5c3)
	at com.projecturanus.betterp2p.client.gui.InfoWrapper.<init>(InfoWrapper.kt:76) ~[InfoWrapper.class:?]
	at com.projecturanus.betterp2p.client.gui.GuiAdvancedMemoryCard.<init>(GuiAdvancedMemoryCard.kt:55) ~[GuiAdvancedMemoryCard.class:?]
	at com.projecturanus.betterp2p.network.ClientOpenGuiHandler.onMessage(ClientOpenGuiHandler.kt:18) ~[ClientOpenGuiHandler.class:?]
	at com.projecturanus.betterp2p.network.ClientOpenGuiHandler.onMessage(ClientOpenGuiHandler.kt:11) ~[ClientOpenGuiHandler.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(Unknown Source) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5104) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165) [launchwrapper-1.15.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [launchwrapper-1.15.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by dark544** [comment]
Now I upgraded the Pack to 2.3.2 and updated to BetterP2P 1.1.5.
I still get the same Error as op..

```
java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at com.projecturanus.betterp2p.item.ItemAdvancedMemoryCard.func_77648_a(ItemAdvancedMemoryCard.kt:133) ~[ItemAdvancedMemoryCard.class:?]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505) ~[ForgeHooks.class:?]
        at net.minecraft.item.ItemStack.func_77943_a(Unknown Source) ~[add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```
