### ISSUE TITLE
Advanced assembly line index out of bounds spam

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13027]
### Your Pack Version

2.3.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality
The following error is spamming the console:
```java
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.util.ArrayList.rangeCheck(ArrayList.java:659)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at java.util.ArrayList.get(ArrayList.java:435)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.glease.ggfab.mte.MTE_AdvAssLine.findRecipe(MTE_AdvAssLine.java:545)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.glease.ggfab.mte.MTE_AdvAssLine.checkRecipe(MTE_AdvAssLine.java:637)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.checkRecipe(GT_MetaTileEntity_MultiBlockBase.java:407)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.runMachine(GT_MetaTileEntity_MultiBlockBase.java:464)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:350)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:522)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.world.World.func_72939_s(World.java:1939)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at fastcraft.u.a(F:289)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at fastcraft.H.aq(F:36)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[13:07:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Harmless. It only happens when you don't add enough input bus. Still valid anyhow.

**Comment by Tommeh1** [comment]
> Harmless. It only happens when you don't add enough input bus. Still valid anyhow.

Yet the advanced assembly lines are perfectly functional, but it is absolutely flooding the console.
