### ISSUE TITLE
quest fail to reloaded

### ISSUE THREAD

**Issue by bengenie** [GTNewHorizons/GT-New-Horizons-Modpack#13020]
### Your GTNH Discord Username

bengenie#5497

### Your Pack Version

2.3.1

### Your Server

sp

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

update betterquesting to 3.3.7
try reloaded the quest book 

### The Reality

> 
> _[24/03/2023 14:46:47 PM] 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
> [24/03/2023 14:46:47 PM] 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
> [24/03/2023 14:46:47 PM] 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
> [24/03/2023 14:46:47 PM] 	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
> [24/03/2023 14:46:47 PM] 	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
> [24/03/2023 14:46:47 PM] 	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
> [24/03/2023 14:46:47 PM] 	at java.nio.file.Files.readAttributes(Files.java:1737)
> [24/03/2023 14:46:47 PM] 	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
> [24/03/2023 14:46:47 PM] 	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
> [24/03/2023 14:46:47 PM] 	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
> [24/03/2023 14:46:47 PM] 	at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:72)
> [24/03/2023 14:46:47 PM] 	at java.nio.file.Files.walk(Files.java:3574)
> [24/03/2023 14:46:47 PM] 	at java.nio.file.Files.walk(Files.java:3625)_
> [24/03/2023 14:46:47 PM] 	at betterquesting.commands.admin.QuestCommandDefaults.load(QuestCommandDefaults.java:380)
> [24/03/2023 14:46:47 PM] 	at betterquesting.commands.admin.QuestCommandDefaults.runCommand(QuestCommandDefaults.java:122)
> [24/03/2023 14:46:47 PM] 	at lokko12.CB4BQ.BlockDLB.func_149727_a(BlockDLB.java:22)
> [24/03/2023 14:46:47 PM] 	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
> [24/03/2023 14:46:47 PM] 	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
> [24/03/2023 14:46:47 PM] 	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
> [24/03/2023 14:46:47 PM] 	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
> [24/03/2023 14:46:47 PM] 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
> [24/03/2023 14:46:47 PM] 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
> [24/03/2023 14:46:47 PM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
> [24/03/2023 14:46:47 PM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
> [24/03/2023 14:46:47 PM] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
> [24/03/2023 14:46:47 PM] 	at fastcraft.u.a(F:289)
> [24/03/2023 14:46:47 PM] 	at fastcraft.H.aq(F:36)
> [24/03/2023 14:46:47 PM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
> [24/03/2023 14:46:47 PM] 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> [24/03/2023 14:46:47 PM] [Server thread/ERROR] Failed to traverse directoryconfig\betterquesting\DefaultQuests\QuestLines
> [24/03/2023 14:46:47 PM] [Client thread/INFO] [CHAT] Â§cSomething went wrong! Please check your logs.

### Your Proposal

it didn't  crash this time but it mine be the sim to #12991 and #12958

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bengenie** [comment]
issue been resaved on discord
