### ISSUE TITLE
Structure hologram packet crash

### ISSUE THREAD

**Issue by riking** [GTNewHorizons/GT-New-Horizons-Modpack#13108]
### Your GTNH Discord Username

Riking#6902

### Your Pack Version

2.3.0

### Your Server

Creative SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Created a Personal Dimension in singleplayer creative, entered it

Spawned an Algae Farm, placed it in the world

Spawned a Structure Hologram Projector, and then I forget if I right clicked or shift-right clicked.

Attempt 2:
Reloaded in the personal dim. Right clicked, worked. Shift-right clicked, worked and built the structure. FAILED TO REPRODUCE

Attempt 3: Hopped out and back in of the personal dim. Placed new algae farm, shift-right clicked. Worked and built the structure. FAILED TO REPRODUCE

### Crash Report

```
[16:59:17] [Server thread/INFO]: [BKCRMWDJVG: Given [Algae Farm] * 1 to BKCRMWDJVG]
[16:59:17] [Client thread/INFO]: [CHAT] Given [Algae Farm] * 1 to BKCRMWDJVG
[16:59:23] [Server thread/INFO]: [BKCRMWDJVG: Given [Multiblock Structure Hologram Projector] * 1 to BKCRMWDJVG]
[16:59:23] [Client thread/INFO]: [CHAT] Given [Multiblock Structure Hologram Projector] * 1 to BKCRMWDJVG
[16:59:25] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel structurelib
java.lang.NullPointerException
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:193) ~[FMLOutboundHandler$OutboundTarget$7.class:?]
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210) ~[SimpleNetworkWrapper.class:?]
	at com.gtnewhorizon.structurelib.StructureLibAPI.sendAlignment(StructureLibAPI.java:246) ~[StructureLibAPI.class:?]
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_EnhancedMultiBlockBase.setExtendedFacing(GT_MetaTileEntity_EnhancedMultiBlockBase.java:64) ~[GT_MetaTileEntity_EnhancedMultiBlockBase.class:?]
	at com.gtnewhorizon.structurelib.alignment.IAlignment.checkedSetExtendedFacing(IAlignment.java:161) ~[IAlignment.class:?]
	at com.gtnewhorizon.structurelib.alignment.IAlignment.toolSetDirection(IAlignment.java:70) ~[IAlignment.class:?]
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_EnhancedMultiBlockBase.onFacingChange(GT_MetaTileEntity_EnhancedMultiBlockBase.java:101) ~[GT_MetaTileEntity_EnhancedMultiBlockBase.class:?]
	at gregtech.api.metatileentity.BaseMetaTileEntity.setFrontFacing(BaseMetaTileEntity.java:860) ~[BaseMetaTileEntity.class:?]
	at blockrenderer6343.integration.gregtech.GT_GUI_MultiblocksHandler.placeMultiblock(GT_GUI_MultiblocksHandler.java:173) ~[GT_GUI_MultiblocksHandler.class:?]
	at blockrenderer6343.common.GUI_MultiblocksHandler.initializeSceneRenderer(GUI_MultiblocksHandler.java:262) ~[GUI_MultiblocksHandler.class:?]
	at blockrenderer6343.integration.gregtech.GT_GUI_MultiblocksHandler.loadNewMultiblock(GT_GUI_MultiblocksHandler.java:79) ~[GT_GUI_MultiblocksHandler.class:?]
	at blockrenderer6343.common.GUI_MultiblocksHandler.loadMultiblock(GUI_MultiblocksHandler.java:85) ~[GUI_MultiblocksHandler.class:?]
	at blockrenderer6343.integration.nei.GT_NEI_MultiblocksHandler.tryLoadMultiblocks(GT_NEI_MultiblocksHandler.java:138) ~[GT_NEI_MultiblocksHandler.class:?]
	at blockrenderer6343.integration.nei.GT_NEI_MultiblocksHandler.loadCraftingRecipes(GT_NEI_MultiblocksHandler.java:94) ~[GT_NEI_MultiblocksHandler.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:417) ~[TemplateRecipeHandler.class:?]
	at blockrenderer6343.integration.nei.GT_NEI_MultiblocksHandler.loadCraftingRecipes(GT_NEI_MultiblocksHandler.java:89) ~[GT_NEI_MultiblocksHandler.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:555) ~[TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.GuiCraftingRecipe.lambda$openRecipeGui$0(GuiCraftingRecipe.java:40) ~[GuiCraftingRecipe.class:?]
	at codechicken.nei.recipe.RecipeHandlerQuery.lambda$null$2(RecipeHandlerQuery.java:77) ~[RecipeHandlerQuery.class:?]

```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Nxer** [comment]
![PI87`UX`576`9PN@O3P0Q_L](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/43300390/2a9cde1d-6ca8-48ab-8887-226203851e6a)

create a new save and put a multi machine controller block then
