### ISSUE TITLE
MineTweaker script from 2.2.x crashes 2.3.x

### ISSUE THREAD

**Issue by ZenMasterSych** [GTNewHorizons/GT-New-Horizons-Modpack#13126]
### Your Pack Version

2.3.0

### Your Server

private server/SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

The issue is the same on our local MP server and in fresh SP world. I have MT script that worked perfectly in 2.2.0 (if I'm not mistaken about version). Now hitting "/mt reload" stucks the world for much longer, and although the message in chat looks fine, upon entering a modded section in thaumonomicon (we use Advanced Thaumoturgy as a base, with all items' recipes deleted/modified) the game crashes. 

[chat message](https://i.imgur.com/3hWz1nC.png)
[crash itself](https://i.imgur.com/wBhMiIH.png)

### Crash Report

[crash-2023-04-03_19.08.46-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11140261/crash-2023-04-03_19.08.46-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by ZenMasterSych** [comment]
I should also note that running Advanced Thaumaturgy on its own doesn't seem to crash the game, as well as using scripts for adding recipes in other categories. I can provide the script itself if needed.

**Comment by chochem** [comment]
we cant really debug your own custom scripts. the pack itself is enough.

**Comment by chochem** [comment]
looks like the mod is ARR, so we are not particularly interested in supporting it going forward anyway. It also looks like the mod author sadly passed away a few years ago, so that is not an option for you either.

**Comment by ZenMasterSych** [comment]
> 

ok, but is there something I can do on my end?

**Comment by boubou19** [comment]
```
java.lang.NullPointerException: Cannot read field "category" because the return value of "thaumcraft.api.research.ResearchCategories.getResearch(String)" is null
    at thaumcraft.client.gui.GuiResearchBrowser.genResearchBackground(GuiResearchBrowser.java:410)
    at thaumcraft.client.gui.GuiResearchBrowser.func_73863_a(GuiResearchBrowser.java:280)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6104)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```
I see no obvious link between that mod and the crash, so looks like we could have the same crash. @Glease any idea on that one?

**Comment by ZenMasterSych** [comment]
Problem "solved". Thaumcraft addon we have is modified partly by script1 and script2. Script one is fundamental, but has some other issues, probably GT-related (due to version update, presumably). The problem occurs while only script2 is loaded (which needs script1 for proper functioning).
