### ISSUE TITLE
AE2 Server crash loop

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13132]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Actions

Nothing, nobody was online, it simply crashed on its own a few minutes after a restart

### Crash Report

```java
java.lang.NullPointerException: Cannot invoke "appeng.api.networking.IGridNode.getGrid()" because the return value of "appeng.api.networking.crafting.ICraftingRequester.getActionableNode()" is null
	at appeng.crafting.CraftingLinkNexus.isDead(CraftingLinkNexus.java:39)
	at appeng.me.cache.CraftingGridCache.onUpdateTick(CraftingGridCache.java:122)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:30)
	at appeng.me.Grid.update(Grid.java:248)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:199)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_770_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

```

[crash-2023-04-04_15.45.44-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11150435/crash-2023-04-04_15.45.44-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Tommeh1** [comment]
The server is pretty much stuck in a crash loop due to this, crashing over 20 times already

**Comment by firenoo** [comment]
Is this ae2 beta-184? Try updating to beta-190.

**Comment by Tommeh1** [comment]
> Is this ae2 beta-184? Try updating to beta-190.

This is indeed 184, which is the default for version 2.3.2 of the pack, i'll give 190 a try

**Comment by Tommeh1** [comment]
Resolved in AE2 beta-190
