### ISSUE TITLE
Large fusion computer NPE spam, severely degrading performance

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13133]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

The following error is being spammed dozens of times a second in our console:
```java
[17:17:24] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.NullPointerException: Cannot read field "mSpecialValue" because "tRecipe" is null
[17:17:24] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at goodgenerator.blocks.tileEntity.base.LargeFusionComputerPP.checkRecipe_EM(LargeFusionComputerPP.java:429)
[17:17:24] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at com.github.technus.tectech.thing.metaTileEntity.multi.base.GT_MetaTileEntity_MultiblockBase_EM.checkRecipe(GT_MetaTileEntity_MultiblockBase_EM.java:1052)
[17:17:24] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at goodgenerator.blocks.tileEntity.base.LargeFusionComputerPP.onPostTick(LargeFusionComputerPP.java:234)
[17:17:24] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:522)
[17:17:24] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.World.func_72939_s(World.java:1939)
[17:17:24] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
[17:17:24] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[17:17:24] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[17:17:24] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[17:17:24] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at fastcraft.u.a(F:289)
[17:17:24] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at fastcraft.H.aq(F:36)
[17:17:24] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[17:17:24] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
The check also seems to severely degrade performance:
![image](https://user-images.githubusercontent.com/39203645/229882435-bb223b55-c2d0-4053-ad72-fe21b21499a1.png)
![image](https://user-images.githubusercontent.com/39203645/229882563-68f11d86-b267-46cb-9c3c-479e64e1e2d4.png)
[Snapshot.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11151772/Snapshot.zip)

**Comment by Tommeh1** [comment]
It turns out that this is all because something happened to the supply of molten enriched naquadah alloy on our mk4 fusion reactor making molten metastable oganesson.
The moment the recipe is incomplete due to something going missing this happens.

**Comment by Tommeh1** [comment]
Closing in favor of #13251
