### ISSUE TITLE
Industrial centrifuge NPE

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13143]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

```java
java.lang.NullPointerException: Cannot invoke "gregtech.api.interfaces.tileentity.IGregTechTileEntity.getStoredEU()" because the return value of "gregtech.api.metatileentity.implementations.GT_MetaTileEntity_Hatch.getBaseMetaTileEntity()" is null
	at gregtech.api.util.GT_ExoticEnergyInputHelper.drainEnergy(GT_ExoticEnergyInputHelper.java:46)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_ExtendedPowerMultiBlockBase.drainEnergyInput(GT_MetaTileEntity_ExtendedPowerMultiBlockBase.java:112)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_ExtendedPowerMultiBlockBase.onRunningTick(GT_MetaTileEntity_ExtendedPowerMultiBlockBase.java:84)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.runMachine(GT_MetaTileEntity_MultiBlockBase.java:426)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:357)
	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.onPostTick(GregtechMeta_MultiBlockBase.java:855)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:522)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at fastcraft.u.a(F:289)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
Second, likely related NPE, hinting at the cause being an industrial centrifuge:
```java
java.lang.NullPointerException: Cannot invoke "gregtech.api.interfaces.tileentity.IGregTechTileEntity.getInputVoltage()" because the return value of "gregtech.api.metatileentity.implementations.GT_MetaTileEntity_Hatch_Energy.getBaseMetaTileEntity()" is null
	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.getMaxInputEnergy(GregtechMeta_MultiBlockBase.java:502)
	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.checkRecipeGeneric(GregtechMeta_MultiBlockBase.java:525)
	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.checkRecipeGeneric(GregtechMeta_MultiBlockBase.java:488)
	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.checkRecipeGeneric(GregtechMeta_MultiBlockBase.java:458)
	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.checkRecipeGeneric(GregtechMeta_MultiBlockBase.java:449)
	at gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.processing.GregtechMetaTileEntity_IndustrialCentrifuge.checkRecipe(GregtechMetaTileEntity_IndustrialCentrifuge.java:143)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.checkRecipe(GT_MetaTileEntity_MultiBlockBase.java:416)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.runMachine(GT_MetaTileEntity_MultiBlockBase.java:473)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:357)
	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.onPostTick(GregtechMeta_MultiBlockBase.java:855)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:522)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at fastcraft.u.a(F:289)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
Same NPE for industrial macerator:
```java
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.NullPointerException: Cannot invoke "gregtech.api.interfaces.tileentity.IGregTechTileEntity.getInputVoltage()" because the return value of "gregtech.api.metatileentity.implementations.GT_MetaTileEntity_Hatch_Energy.getBaseMetaTileEntity()" is null
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.getMaxInputEnergy(GregtechMeta_MultiBlockBase.java:502)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.checkRecipeGeneric(GregtechMeta_MultiBlockBase.java:525)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.checkRecipeGeneric(GregtechMeta_MultiBlockBase.java:488)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.checkRecipeGeneric(GregtechMeta_MultiBlockBase.java:458)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.processing.GregtechMetaTileEntity_IndustrialMacerator.checkRecipe(GregtechMetaTileEntity_IndustrialMacerator.java:344)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.checkRecipe(GT_MetaTileEntity_MultiBlockBase.java:416)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.runMachine(GT_MetaTileEntity_MultiBlockBase.java:473)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:357)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.onPostTick(GregtechMeta_MultiBlockBase.java:855)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.processing.GregtechMetaTileEntity_IndustrialMacerator.onPostTick(GregtechMetaTileEntity_IndustrialMacerator.java:286)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:522)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.World.func_72939_s(World.java:1939)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at fastcraft.u.a(F:289)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at fastcraft.H.aq(F:36)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[23:45:17] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by Tommeh1** [comment]
This NPE seems to be able to affect just about ALL machines.
