### ISSUE TITLE
Encountered Exception while loading MetaTileEntity

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13226]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

```java
[18:50:29] [Server thread/ERROR]: Encountered Exception while loading MetaTileEntity.
[18:50:29] [Server thread/ERROR]: java.lang.IllegalArgumentException: No enum constant gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.production.GT4Entity_AutoCrafter.MODE.
at java.base/java.lang.Enum.valueOf(Enum.java:274)
at gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.production.GT4Entity_AutoCrafter$MODE.valueOf(GT4Entity_AutoCrafter.java:53)
at gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.production.GT4Entity_AutoCrafter.loadNBTData(GT4Entity_AutoCrafter.java:466)
at gregtech.api.metatileentity.CommonMetaTileEntity.loadMetaTileNBT(CommonMetaTileEntity.java:86)
at gregtech.api.metatileentity.BaseMetaTileEntity.setInitialValuesAsNBT(BaseMetaTileEntity.java:192)
at gregtech.common.blocks.GT_Item_Machines.placeBlockAt(GT_Item_Machines.java:330)
at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
at net.minecraft.item.ItemStack.func_77943_a(Unknown Source)
at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at fastcraft.u.a(F:289)
at fastcraft.H.aq(F:36)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
did you update your gt++ to a more recent version than 2.3.2? because the modes were only just removed a few days ago afaik

**Comment by Tommeh1** [comment]
> did you update your gt++ to a more recent version than 2.3.2? because the modes were only just removed a few days ago afaik

We have not

**Comment by chochem** [comment]
interesting. Well then I guess this might even by fixed in dev, as the modes are gone now

**Comment by Tommeh1** [comment]
> interesting. Well then I guess this might even by fixed in dev, as the modes are gone now

I do however have another issue open that reveals that just about any machine can have MetaTileEntity issues as they can all return null.
But i'll close this issue as at least this case is resolved then i suppose.
