### ISSUE TITLE
SimpleChannelHandlerWrapper NPE spam

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13220]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

The following error regularly spams the console, the trigger is unknown.
```java
[00:34:30] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: Cannot read field "field_147371_a" because "player.field_71135_a" is null
at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$4.selectNetworks(FMLOutboundHandler.java:109) ~[FMLOutboundHandler$OutboundTarget$4.class:?]
at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:?]
at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:196) [SimpleNetworkWrapper.class:?]
at thaumcraft.common.Thaumcraft.addStickyWarpToPlayer(Thaumcraft.java:332) [Thaumcraft.class:?]
at thaumcraft.common.lib.events.EventHandlerWorld.onCrafting(EventHandlerWorld.java:145) [EventHandlerWorld.class:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler_120_EventHandlerWorld_onCrafting_ItemCraftedEvent.invoke(.dynamic) [?:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
at cpw.mods.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:570) [FMLCommonHandler.class:?]
at appeng.crafting.v2.CraftingContext.simulateComplexCrafting(CraftingContext.java:200) [CraftingContext.class:?]
at appeng.crafting.v2.CraftingContext.isPatternComplex(CraftingContext.java:178) [CraftingContext.class:?]
at appeng.crafting.v2.resolvers.CraftableItemResolver.provideCraftingRequestResolvers(CraftableItemResolver.java:471) [CraftableItemResolver.class:?]
at appeng.crafting.v2.CraftingCalculations.tryResolveCraftingRequest(CraftingCalculations.java:61) [CraftingCalculations.class:?]
at appeng.crafting.v2.CraftingContext.addRequest(CraftingContext.java:129) [CraftingContext.class:?]
at appeng.crafting.v2.CraftingContext.doWork(CraftingContext.java:257) [CraftingContext.class:?]
at appeng.crafting.v2.CraftingJobV2.simulateFor(CraftingJobV2.java:97) [CraftingJobV2.class:?]
at appeng.hooks.TickHandler.onTick(TickHandler.java:177) [TickHandler.class:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler_764_TickHandler_onTick_TickEvent.invoke(.dynamic) [?:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) [FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
What TC4Tweaks version do you have? This should have been fixed in 1.4.19.

**Comment by Tommeh1** [comment]
> What TC4Tweaks version do you have? This should have been fixed in 1.4.19.

We're using 1.5.3

**Comment by Glease** [comment]
This doesn't make sense. can you try add `-Dglease.debugasm=true` to you server launch arg before `-jar` and send the `.asm/thaumcraft.common.Thaumcraft_tran.txt` file?

**Comment by Tommeh1** [comment]
> This doesn't make sense. can you try add `-Dglease.debugasm=true` to you server launch arg before `-jar` and send the `.asm/thaumcraft.common.Thaumcraft_tran.txt` file?
[thaumcraft.common.Thaumcraft_tran.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11242457/thaumcraft.common.Thaumcraft_tran.txt)

**Comment by Glease** [comment]
It appears my fix wasn't effective... sigh, will push another one.
