### ISSUE TITLE
AE2 stuff Wireless Connectors churning chunks

### ISSUE THREAD

**Issue by FlandreS** [GTNewHorizons/GT-New-Horizons-Modpack#13222]
### Your GTNH Discord Username

Flandre#6329

### Your Pack Version

2.3.0.0

### Your Server

Earthquake/Local Forge test environment

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

When leaving a dimension or area which contains no chunkloaders, or machines which are capable of self-loading (Fusion, kinetics, ender quarries, poppet shelves etc) the area un-loads.

### The Reality

While attempting to diagnose the cause of heavy chunk churning in some personal dims which drops TPS to ~2 when leaving the dimension, I've downloaded a sampler mod suggested by moronwithmachinegun in an earlier ~2020 issue.

I am seeing many things that churn chunkloading, and may add those into this issue or another, but Wireless AE has been the biggest culprit at the moment. I am not 100% sure yet if the Wireless itself is the problem, or if these AE networks would be rapidly load/unloading if wired directly but those are the largest cause I see and it can occur ~100 times per second or more.

Example chunkload due to Wireless AE:

> [05:28:08] [Server thread/INFO] [sampler/]: Chunk load detected, cause: get tileentity, dim 188, pos -1/-4.
> 	at net.bdew.lib.block.BlockRef.tile(BlockRef.scala:24)
> 	at net.bdew.lib.block.BlockRef.getTile(BlockRef.scala:34)
> 	at net.bdew.ae2stuff.machines.wireless.TileWireless$$anonfun$getLink$1.apply(TileWireless.scala:35)
> 	at net.bdew.ae2stuff.machines.wireless.TileWireless$$anonfun$getLink$1.apply(TileWireless.scala:35)
> 	at scala.Option.flatMap(Option.scala:170)
> 	at net.bdew.ae2stuff.machines.wireless.TileWireless.getLink(TileWireless.scala:35)
> 	at net.bdew.ae2stuff.machines.wireless.TileWireless.setupConnection(TileWireless.scala:68)
> 	at net.bdew.ae2stuff.machines.wireless.TileWireless$$anonfun$1.apply$mcV$sp(TileWireless.scala:42)
> 	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
> 	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
> 	at scala.collection.immutable.List.foreach(List.scala:383)
> 	at net.bdew.lib.Event0.trigger(Event.scala:19)
> 	at net.bdew.lib.tile.TileExtended.func_145845_h(TileExtended.scala:63)
> 	at net.minecraft.world.World.func_72939_s(World.java:1939)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)

### Your Proposal

Ideally, I'd hope to see investigation into the many causes of ghost loading and churn, as it's contributing to memory leaks and poor performance where high-tier bases are not only loaded 24/7, but the chunks are rapidly loaded/un-loaded causing very extreme performance degration necessitating a reboot.

I can provide world files where multiple bases have the issue if anyone is interested to test with on request.

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11239535/fml-server-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
I've already documented a bunch of ghost chunk loading cases in #12887

**Comment by OzTheM9** [comment]
We are currently having this issue with some of our bases on our server. All in PDims. Once they get unloaded after our 4 hour offline chunkloading, the server hits single digits TPS and becomes unplayable. All of them have AE2 and have wireless connectors. I'm not sure how to find more evidence for it as the chunkloading tickets are only serverutilities tickets. Its becoming a huge issue for us as these players are playing daily and once they stop playing, we basically need to restart the server after 4 hours every single time. We also dont want to supply admin anchors or infinite offline chunkloading. Does anyone have any idea how to fix this?

**Comment by FlandreS** [comment]
It's been a persistent issue for us over the years. Originally we used Thermos to disable Forge chunkload requests.

Nowadays I have started using this: https://modrinth.com/mod/alternative-chunkloading which does it better and has allowed us to return to pure Forge without custom dev.

There are notable downsides - serverutils loading works fine as noted but other Forge event loaders don't. This means TF portals will dump players into the TF without loading the far side properly. Most two way teleporters will also need to be loaded on both sides.

Examples are Stargate, teleposer, teleport pad, celestial gateway etc.

It's still a general pack issue and has been since the beginning. The personal feeling I get is that dev time to untangle the various things causing chunk churning isn't something to hold out hope for. I believe the official server solution is that bases are loaded *passively* rather than *personally* so they stay loaded until shutdown.

Personally I value tps for online players a lot more than letting high tier bases idle recipies while offline so this is the choice we've made.
