### ISSUE TITLE
CB's DepLoader unable to download Baubles mod

### ISSUE THREAD

**Issue by Brostrod** [GTNewHorizons/GT-New-Horizons-Modpack#13225]
### Your Pack Version

2.2.0.0-1.7.10 (also tested on 2.3.0)

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

Load the modpack

### Crash Report

```
[11:10:40] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[11:10:40] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[11:10:40] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[11:10:40] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[11:10:40] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at S:\Modpacks\Curseforge\Install\runtime\jre-legacy\windows-x64\jre-legacy
[11:10:40] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from AppleCore-1.7.10-3.1.9.jar
[11:10:40] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from AppleCore-1.7.10-3.2.2.jar
[11:10:40] [main/INFO]: [AppEng] Core Init
[11:10:40] [main/INFO]: [AppEng] Core Init
[11:10:40] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:10:40] [main/WARN]: The coremod mods.battlegear2.coremod.BattlegearLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:10:40] [main/WARN]: The coremod mods.battlegear2.coremod.BattlegearLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:10:40] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from bettercrashes-1.7.10-1.1.6-GTNH.jar
[11:10:40] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from BugTorch-1.1.2-GTNH.jar
[11:10:40] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from bugtorch-1.7.10-1.1.6.4-GTNH.jar
[11:10:40] [main/WARN]: Warning: version of MrTJPCore, 1.1.0.33 is newer than request 1.1.0.31
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.RuntimeException: A download error occured
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:356)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:482)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.loadDeps(DepLoader.java:468)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:451)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader.load(DepLoader.java:586)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:54)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.newInstance(Class.java:442)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[11:10:43] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:343)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 19 more
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2942)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLConnection.getContentLength(URLConnection.java:485)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:398)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:342)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 19 more
[11:10:44] [main/ERROR]: An error occurred trying to configure the minecraft home at S:\Modpacks\Curseforge\Instances\GT New Horizons for Forge Mod Loader
java.lang.RuntimeException: A download error occured
	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:356) ~[DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:482) ~[DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader$DepLoadInst.loadDeps(DepLoader.java:468) ~[DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:451) ~[DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader.load(DepLoader.java:586) ~[DepLoader.class:?]
	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:54) ~[CodeChickenCore-1.7.10-1.1.5.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_51]
	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:343) ~[DepLoader$DepLoadInst.class:?]
	... 19 more
Caused by: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2942) ~[?:1.8.0_51]
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629) ~[?:1.8.0_51]
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501) ~[?:1.8.0_51]
	at java.net.URLConnection.getContentLength(URLConnection.java:485) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:398) ~[?:1.8.0_51]
	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:342) ~[DepLoader$DepLoadInst.class:?]
	... 19 more
[11:10:44] [main/ERROR]: Unable to launch
java.lang.RuntimeException: A download error occured
	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:356) ~[DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:482) ~[DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader$DepLoadInst.loadDeps(DepLoader.java:468) ~[DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:451) ~[DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader.load(DepLoader.java:586) ~[DepLoader.class:?]
	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:54) ~[CodeChickenCore-1.7.10-1.1.5.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_51]
	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:343) ~[DepLoader$DepLoadInst.class:?]
	... 19 more
Caused by: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar
// This seems to be the problem, the dropbox link for the mod download is a 404 page.
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2942) ~[?:1.8.0_51]
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629) ~[?:1.8.0_51]
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501) ~[?:1.8.0_51]
	at java.net.URLConnection.getContentLength(URLConnection.java:485) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:398) ~[?:1.8.0_51]
	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:342) ~[DepLoader$DepLoadInst.class:?]
	... 19 more
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:971)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[11:10:44] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
I dont know what exactly the problem is here. but generally I would not recommend curseforge. check out https://gtnh.miraheze.org/wiki/Installing_and_Migrating and best use multimc or prism.

**Comment by Brostrod** [comment]
problem is DepLoader can't download Baubles mod because the dropbox link is a 404 I believe

**Comment by chochem** [comment]
looks like it yea. well the other launchers are unaffected by that

**Comment by bombcar** [comment]
Curseforge is working as well as it ever does now I believe; can this be closed?
