### ISSUE TITLE
getBaseMetaTileEntity() returning null, resulting in a wide range of errors

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13245]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### The Reality

It turns out that the error, which can affect just about any machine as mentioned in #13143 can also cause more severe issues, for example disconnecting the client like shown below.
In other cases it generally leads to random recipes failing, causing minor shortages for AE2 orders, jamming the order, or a general loss of items.
Additionally it might explain a couple of random shutdowns of machines or machines using an odd power tier until restarted as power related checks are also affected.

The cause is most likely introduced in either 2.3.1 or 2.3.2
The trigger however is unknown, given that it can even cause issues with nobody online for machines that run essentially all the time.

This also ain't limited to a single mod adding machines, Gregtech, GT++, TecTech, GoodGenerator etc are all affected.
There are also no limits as to what checks can end up having null returned by getBaseMetaTileEntity(), seemingly any check that needs it is affected.
```java
[17:46:47] [Server thread/WARN]: Failed to handle packet for /<ip>:50156
java.lang.NullPointerException: Cannot invoke "gregtech.api.interfaces.tileentity.IGregTechTileEntity.setActive(boolean)" because the return value of "com.github.technus.tectech.thing.metaTileEntity.hatch.GT_MetaTileEntity_Hatch_Holder.getBaseMetaTileEntity()" is null
at com.github.technus.tectech.thing.metaTileEntity.multi.GT_MetaTileEntity_EM_research.onRemoval(GT_MetaTileEntity_EM_research.java:576) ~[GT_MetaTileEntity_EM_research.class:?]
at gregtech.api.metatileentity.BaseMetaTileEntity.func_145843_s(BaseMetaTileEntity.java:942) ~[BaseMetaTileEntity.class:?]
at net.minecraft.world.chunk.Chunk.func_150805_f(Chunk.java:901) ~[apx.class:?]
at net.minecraft.world.World.func_147475_p(World.java:2609) ~[ahb.class:?]
at net.minecraft.block.Block.func_149749_a(Block.java:627) ~[aji.class:?]
at gregtech.common.blocks.GT_Block_Machines.func_149749_a(GT_Block_Machines.java:439) ~[GT_Block_Machines.class:?]
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600) ~[apx.class:?]
at net.minecraft.world.World.func_147465_d(World.java:451) ~[ahb.class:?]
at net.minecraft.world.World.func_147468_f(World.java:573) ~[ahb.class:?]
at gregtech.common.blocks.GT_Block_Machines.func_149636_a(GT_Block_Machines.java:469) ~[GT_Block_Machines.class:?]
at net.minecraft.server.management.ItemInWorldManager.func_73084_b(Unknown Source) ~[mx.class:?]
at net.minecraft.server.management.ItemInWorldManager.func_73074_a(Unknown Source) ~[mx.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489) ~[nh.class:?]
at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) ~[ji.class:?]
at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) ~[ji.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[17:46:47] [Server thread/INFO]: RamseySpace lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
```

### Your Proposal

Fix whatever causes getBaseMetaTileEntity() on seemingly any machine to return null at random.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
Here is another more severe example, causing a lapotronic super capacitor to freak out a few hundred times:
```java
java.lang.NullPointerException: Cannot invoke "gregtech.api.interfaces.tileentity.IGregTechTileEntity.isInvalidTileEntity()" because the return value of "com.github.technus.tectech.thing.metaTileEntity.hatch.GT_MetaTileEntity_Hatch_EnergyTunnel.getBaseMetaTileEntity()" is null
	at common.tileentities.GTMTE_LapotronicSuperCapacitor.onRunningTick(GTMTE_LapotronicSuperCapacitor.java:718)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.runMachine(GT_MetaTileEntity_MultiBlockBase.java:426)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:357)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:522)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at fastcraft.u.a(F:289)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by Tommeh1** [comment]
Another similar issue:
```java
java.lang.NullPointerException: Cannot read field "mStoredEnergy" because "this.mBaseMetaTileEntity" is null
	at gregtech.api.metatileentity.MetaTileEntity.getEUVar(MetaTileEntity.java:537)
	at com.github.bartimaeusnek.bartworks.common.tileentities.multis.GT_TileEntity_ElectricImplosionCompressor.checkRecipe(GT_TileEntity_ElectricImplosionCompressor.java:182)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.checkRecipe(GT_MetaTileEntity_MultiBlockBase.java:416)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.runMachine(GT_MetaTileEntity_MultiBlockBase.java:473)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:357)
	at com.github.bartimaeusnek.bartworks.common.tileentities.multis.GT_TileEntity_ElectricImplosionCompressor.onPostTick(GT_TileEntity_ElectricImplosionCompressor.java:245)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:522)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at fastcraft.u.a(F:289)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
