### ISSUE TITLE
Builders wand index out of bounds

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13242]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

```java
[00:04:16] [Server thread/WARN]: Failed to handle packet for /108.41.58.224:55849
java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 6
	at com.rwtema.extrautils.item.ItemBuildersWand.getPotentialBlocks(ItemBuildersWand.java:196) ~[ItemBuildersWand.class:?]
	at com.rwtema.extrautils.item.ItemBuildersWand.func_77648_a(ItemBuildersWand.java:88) ~[ItemBuildersWand.class:?]
	at com.rwtema.extrautils.item.ItemBuildersWand.onItemUseFirst(ItemBuildersWand.java:72) ~[ItemBuildersWand.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
	at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
	```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
OK, I tried looking a bit at the decompiled ExU sources and I think this occurs here (fernflower output for `com.rwtema.extrautils.item.ItemBuildersWand`):
```java
public List<ChunkPos> getPotentialBlocks(EntityPlayer player, World world, int x, int y, int z, int face) {
   // ...
   dx = Facing.offsetsXForSide[face];
   int dy = Facing.offsetsYForSide[face];
   int dz = Facing.offsetsZForSide[face];
   // ...
}
```
So `face` is somehow off by one. Don't know why though.

Without a way to reliably reproduce this, I'm unable to fix this from just the stacktrace.
