### ISSUE TITLE
Large Fusion Computer NPE

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13251]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

The following error is spammed dozens of times right after each restart, is spammed again every few hours and initially after updating from 2.3.0 to 2.3.2 also send the mspt up tenfold until fusion was restarted.
```java
java.lang.NullPointerException: Cannot read field "mSpecialValue" because "tRecipe" is null
	at goodgenerator.blocks.tileEntity.base.LargeFusionComputer.checkRecipe_EM(LargeFusionComputer.java:446)
	at com.github.technus.tectech.thing.metaTileEntity.multi.base.GT_MetaTileEntity_MultiblockBase_EM.checkRecipe(GT_MetaTileEntity_MultiblockBase_EM.java:1052)
	at goodgenerator.blocks.tileEntity.base.LargeFusionComputer.onPostTick(LargeFusionComputer.java:235)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:522)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at fastcraft.u.a(F:289)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
Slight variant of the above stacktrace:
```java
java.lang.NullPointerException: Cannot read field "mSpecialValue" because "tRecipe" is null
	at goodgenerator.blocks.tileEntity.base.LargeFusionComputerPP.checkRecipe_EM(LargeFusionComputerPP.java:429)
	at com.github.technus.tectech.thing.metaTileEntity.multi.base.GT_MetaTileEntity_MultiblockBase_EM.checkRecipe(GT_MetaTileEntity_MultiblockBase_EM.java:1052)
	at goodgenerator.blocks.tileEntity.base.LargeFusionComputerPP.onPostTick(LargeFusionComputerPP.java:234)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:522)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at fastcraft.u.a(F:289)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
	```
