### ISSUE TITLE
Server crash accessing industrial greenhouse GUI after upgrading its power input

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13265]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Actions

We upgraded an industrial greenhouse to double UMV and accessed its GUI.
Putting it on a single UMV hatch seems to make it functional again.

### Crash Report

[crash-2023-04-20_09.12.55-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11287236/crash-2023-04-20_09.12.55-server.txt)

Stacktrace only:
```java
java.lang.IllegalArgumentException: Dynamic Synced widget id must be greater than 0 and smaller than 65535 (0xFFFF)
	at com.gtnewhorizons.modularui.api.screen.ModularWindow.addDynamicSyncedWidget(ModularWindow.java:416)
	at com.gtnewhorizons.modularui.common.widget.ChangeableWidget.lambda$initQueuedChild$1(ChangeableWidget.java:103)
	at com.gtnewhorizons.modularui.api.widget.IWidgetParent.lambda$forEachByLayer$1(IWidgetParent.java:112)
	at com.gtnewhorizons.modularui.api.widget.IWidgetParent.forEachByLayer(IWidgetParent.java:84)
	at com.gtnewhorizons.modularui.api.widget.IWidgetParent.forEachByLayer(IWidgetParent.java:71)
	at com.gtnewhorizons.modularui.api.widget.IWidgetParent.forEachByLayer(IWidgetParent.java:67)
	at com.gtnewhorizons.modularui.api.widget.IWidgetParent.forEachByLayer(IWidgetParent.java:61)
	at com.gtnewhorizons.modularui.api.widget.IWidgetParent.forEachByLayer(IWidgetParent.java:111)
	at com.gtnewhorizons.modularui.common.widget.ChangeableWidget.initQueuedChild(ChangeableWidget.java:107)
	at com.gtnewhorizons.modularui.common.widget.ChangeableWidget.notifyChangeNoSync(ChangeableWidget.java:76)
	at kubatech.tileentity.gregtech.multiblock.GT_MetaTileEntity_ExtremeIndustrialGreenhouse.lambda$addUIWidgets$11(GT_MetaTileEntity_ExtremeIndustrialGreenhouse.java:625)
	at com.gtnewhorizons.modularui.common.widget.FakeSyncWidget.detectAndSendChanges(FakeSyncWidget.java:64)
	at com.gtnewhorizons.modularui.api.screen.ModularWindow.serverUpdate(ModularWindow.java:226)
	at com.gtnewhorizons.modularui.common.internal.wrapper.ModularUIContainer.lambda$detectAndSendChanges$2(ModularUIContainer.java:118)
	at com.gtnewhorizons.modularui.api.screen.ModularUIContext.forEachWindowTopToBottom(ModularUIContext.java:98)
	at com.gtnewhorizons.modularui.common.internal.wrapper.ModularUIContainer.func_75142_b(ModularUIContainer.java:115)
	at net.minecraft.entity.player.EntityPlayerMP.localOnUpdate(EntityPlayerMP.java:212)
	at api.player.server.ServerPlayerAPI.onUpdate(ServerPlayerAPI.java:6101)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Tommeh1** [comment]
Given what i assume happened i suppose it can also affect the mega apiary as that also has a GUI that scales with input power.

**Comment by Tommeh1** [comment]
Still exists in 2.3.4
