### ISSUE TITLE
IO thread NPE

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13283]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

```java
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.func_74732_a()" because "p_150298_1_" is null
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:371)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.redirect$zck000$hodgepodge$appendKeyPath(NBTTagCompound.java:552)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.redirect$zck000$hodgepodge$appendKeyPath(NBTTagCompound.java:552)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:32)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.redirect$zck000$hodgepodge$appendKeyPath(NBTTagCompound.java:552)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:32)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.redirect$zck000$hodgepodge$appendKeyPath(NBTTagCompound.java:552)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.redirect$zck000$hodgepodge$appendKeyPath(NBTTagCompound.java:552)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:149)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:139)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75821_a(AnvilChunkLoader.java:265)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:251)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:30)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:23)
[23:02:02] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.lang.Thread.run(Thread.java:1589)
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
I should note that our hodgepodge build comes from the following branch in case it's the debug having issues https://github.com/GTNewHorizons/Hodgepodge/tree/feature/save-cme-debug

**Comment by chochem** [comment]
no context whatsoever?

**Comment by Tommeh1** [comment]
> no context whatsoever?

I've got no more context to provide, all i know is that something is mad.

**Comment by Tommeh1** [comment]
3 more File IO thread errors:
```java
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.IndexOutOfBoundsException: Index 6067737 out of bounds for length 3609
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.util.Objects.checkIndex(Objects.java:385)
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.util.ArrayList.set(ArrayList.java:441)
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.chunk.storage.RegionFile.func_76706_a(RegionFile.java:239)
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.chunk.storage.RegionFile$ChunkBuffer.close(RegionFile.java:371)
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:249)
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75821_a(AnvilChunkLoader.java:266)
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:251)
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:30)
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:23)
[17:17:39] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.lang.Thread.run(Thread.java:1589)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.IndexOutOfBoundsException: Index 881872 out of bounds for length 3609
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.util.Objects.checkIndex(Objects.java:385)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.util.ArrayList.set(ArrayList.java:441)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.chunk.storage.RegionFile.func_76706_a(RegionFile.java:239)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.chunk.storage.RegionFile$ChunkBuffer.close(RegionFile.java:371)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:249)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75821_a(AnvilChunkLoader.java:266)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:251)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:30)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:23)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.lang.Thread.run(Thread.java:1589)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.IndexOutOfBoundsException: Index 466292 out of bounds for length 3609
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.util.Objects.checkIndex(Objects.java:385)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.util.ArrayList.set(ArrayList.java:441)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.chunk.storage.RegionFile.func_76706_a(RegionFile.java:239)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.chunk.storage.RegionFile$ChunkBuffer.close(RegionFile.java:371)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:249)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75821_a(AnvilChunkLoader.java:266)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:251)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:30)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:23)
[17:17:40] [File IO Thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: at java.base/java.lang.Thread.run(Thread.java:1589)
```
