### ISSUE TITLE
AE2 Error encountered when trying to generate the list of CraftingTasks

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13304]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality
The following error is currently spamming the console:
```java
[02:08:24] [Server thread/WARN]: Error encountered when trying to generate the list of CraftingTasks for crafting {}
java.lang.IllegalStateException: Invalid pattern crafting step for CraftingRequest{request=71xgt.metaitem.01@32351<Extruder Shape (Rod)>, substitutionMode=PRECISE, remainingToProcess=71, byteCost=0, wasSimulated=false}
at appeng.crafting.v2.resolvers.CraftableItemResolver$CraftFromPatternTask.<init>(CraftableItemResolver.java:109) ~[CraftableItemResolver$CraftFromPatternTask.class:?]
at appeng.crafting.v2.resolvers.CraftableItemResolver.provideCraftingRequestResolvers(CraftableItemResolver.java:477) ~[CraftableItemResolver.class:?]
at appeng.crafting.v2.CraftingCalculations.tryResolveCraftingRequest(CraftingCalculations.java:61) [CraftingCalculations.class:?]
at appeng.crafting.v2.CraftingContext.addRequest(CraftingContext.java:129) [CraftingContext.class:?]
at appeng.crafting.v2.CraftingContext.doWork(CraftingContext.java:257) [CraftingContext.class:?]
at appeng.crafting.v2.CraftingJobV2.simulateFor(CraftingJobV2.java:97) [CraftingJobV2.class:?]
at appeng.hooks.TickHandler.onTick(TickHandler.java:177) [TickHandler.class:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler_764_TickHandler_onTick_TickEvent.invoke(.dynamic) [?:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) [FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
Closing, user error, despite that stacktrace seeming unnecessary.
