### ISSUE TITLE
logspam from EOH: npe "this.currentRecipe" is null

### ISSUE THREAD

**Issue by Fiyorin** [GTNewHorizons/GT-New-Horizons-Modpack#13408]
### Your GTNH Discord Username

Fiyorin

### Your Pack Version

2.3.3-nightly

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

i'm seeing this repeatedly in the server log, roughly once a second:

![image](https://user-images.githubusercontent.com/61357/235529083-bc97d9fc-f300-4a21-80fb-dab9ebb4dc70.png)

here's a similar message in text form:

`[22:39:26] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.NullPointerException: Cannot invoke "com.github.technus.tectech.recipe.EyeOfHarmonyRecipe.getRocketTier()" because "this.currentRecipe" is null
[22:39:26] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]:  at com.github.technus.tectech.thing.metaTileEntity.multi.GT_MetaTileEntity_EM_EyeOfHarmony.outputFailedChance(GT_MetaTileEntity_EM_EyeOfHarmony.java:1228)
[22:39:26] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]:  at com.github.technus.tectech.thing.metaTileEntity.multi.GT_MetaTileEntity_EM_EyeOfHarmony.outputAfterRecipe_EM(GT_MetaTileEntity_EM_EyeOfHarmony.java:1268)
[22:39:26] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]:  at com.github.technus.tectech.thing.metaTileEntity.multi.base.GT_MetaTileEntity_MultiblockBase_EM.onPostTick(GT_MetaTileEntity_MultiblockBase_EM.java:1282)
[22:39:26] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]:  at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:524)
[22:39:26] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]:  at net.minecraft.world.World.func_72939_s(World.java:1939)
[22:39:26] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]:  at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
[22:39:26] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[22:39:26] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[22:39:26] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[22:39:26] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]:  at fastcraft.u.a(F:289)
[22:39:26] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]:  at fastcraft.H.aq(F:36)
[22:39:26] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[22:39:26] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`

### The Reality

owo

there are 3 eohs running without problems

### Your Proposal

be less verbose

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Fiyorin** [comment]
pretty uwu version 

https://user-images.githubusercontent.com/61357/235713513-8990d7ce-e572-4039-9b6e-736e51c573c1.mp4
