### ISSUE TITLE
Running `runObfClient` in GT devenv causes crash when placing/loading MuTE controller block

### ISSUE THREAD

**Issue by wlhlm** [GTNewHorizons/GT-New-Horizons-Modpack#13437]
### Your Pack Version

GT5U MuTE master branch

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Actions

MuTE controllers crash to main menu when the client was started via `runObfClient` in the GT devenv. Also applies to running `build` and pulling the jar into a regular modded instance.

To reproduce it:

1. start game via `./gradlew runObfClient` or similar methods
2. load save
3. place MuTE controller (such as the Advanced Chemical Reactor)
4. game crash to main menu, subsequent tries to load the save will result in the same crash

### Crash Report

[gt5u-runobfclient-mute-crash.log.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11412494/gt5u-runobfclient-mute-crash.log.txt)

```
java.lang.AbstractMethodError: Method gregtech/common/tileentities/machines/multiblock/AdvChemicalReactor.receiveClientEvent(II)Z is abstract
	at gregtech.common.tileentities.machines.multiblock.AdvChemicalReactor.receiveClientEvent(AdvChemicalReactor.java) ~[AdvChemicalReactor.class:?]
	at gregtech.api.net.GT_Packet_MultiTileEntity.process(GT_Packet_MultiTileEntity.java:249) ~[GT_Packet_MultiTileEntity.class:?]
	at gregtech.common.GT_Network$HandlerShared.channelRead0(GT_Network.java:163) ~[GT_Network$HandlerShared.class:?]
	at gregtech.common.GT_Network$HandlerShared.channelRead0(GT_Network.java:157) ~[GT_Network$HandlerShared.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
...
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by wlhlm** [comment]
Raven on Discord had the solution:
> if you have a non-mc interface with a method name, but then have a mc class with an identical signature the class will get obfed but the interface won't

> the obfuscator looks at superclasses to find which deobf names exist and need remapping

> basically don't put methods with identical signatures to mc classes in your own interfaces if they don't inherit from mc ones

> there is a way to fix it with custom srg files injected into the build process but I'd not recommend it :P

> mixin uses the extra srg method to remap mixin classes even though they don't inherit mc stuff

Mitch fixed the issue in MuTE master branch by renaming the method.
