### ISSUE TITLE
More world corruption

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13520]
### Your Pack Version

2.3.2

### Your Server

Private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Actions

Someone was exploring

### Crash Report

[crash-2023-05-17_17.03.58-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11501088/crash-2023-05-17_17.03.58-server.txt)

Stacktrace only:
```java
java.io.UTFDataFormatException: malformed input around byte 44
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:661)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
	at net.minecraft.nbt.NBTTagCompound.func_152448_b(NBTTagCompound.java:388)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:50)
	at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:54)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125)
	at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:120)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:121)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:20)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:343)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:313)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Hyyrokkin** [comment]
I have the same issue and my chunks keep getting corrupted.
I fixed it by deleting the corrupted chunks with MCA Selector.
It worked for like 1 day and then corrupted a chunk again.

**Comment by wlhlm** [comment]
It would be helpful to see which block has the corrupted NBT. Please provide a region file with the corrupted chunk.

**Comment by Tommeh1** [comment]
> It would be helpful to see which block has the corrupted NBT. Please provide a region file with the corrupted chunk.

Although just about all of our regions are now to some extend corrupted the moment you move just a few chunks away from our base, this case managed to log the affected region and chunk and thus already has a corrupted region attached:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12875
```
-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (1748,54,2592), Chunk: (at 4,3,0 in 109,162; contains blocks 1744,0,2592 to 1759,255,2607), Region: (3,5; contains chunks 96,160 to 127,191, blocks 1536,0,2560 to 2047,255,3071)
	```

**Comment by Tommeh1** [comment]
@wlhlm ^^
