### ISSUE TITLE
Advanced Assline NPE

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13547]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

```java
java.lang.NullPointerException: Cannot read field "mInputs" because the return value of "net.glease.ggfab.mte.MTE_AdvAssLine.access$200(net.glease.ggfab.mte.MTE_AdvAssLine)" is null
	at net.glease.ggfab.mte.MTE_AdvAssLine$Slice.start(MTE_AdvAssLine.java:830)
	at net.glease.ggfab.mte.MTE_AdvAssLine.checkRecipe(MTE_AdvAssLine.java:680)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.checkRecipe(GT_MetaTileEntity_MultiBlockBase.java:416)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.runMachine(GT_MetaTileEntity_MultiBlockBase.java:473)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:357)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:522)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at fastcraft.u.a(F:289)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by MeiTianyou** [comment]
Can you describe what you were crafting when happened? Do you get this error often?

**Comment by Tommeh1** [comment]
> Can you describe what you were crafting when happened? Do you get this error often?

The error occurred for the first time for as far as i can see and what was crafting is uncertain as nobody was online when it happened.

**Comment by bpwhelan** [comment]
This is super old, but I think this happens when using lasers of a lesser tier than what is needed. Not sure if it needs to be re-opened, but that might help with finding what's going on here
