### ISSUE TITLE
Forge debug logging broken on newer java versions

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13597]
### Your Pack Version

2.3.2

### Your Server

Private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

Ever since newer Java versions are supported using the build of a pack version that utilizes/enables this Forge debug logging immediately breaks, not even generating the log file at all.
The only noticeable irregularity being logged that might be related is this:
```java
[15:44:23] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[15:44:23] [main/INFO]: [cpw.mods.fml.common.TracingPrintStream:close:50]: Something tried to close the main output stream
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.Throwable
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.common.TracingPrintStream.close(TracingPrintStream.java:51)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:443)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/sun.nio.cs.StreamEncoder.lockedClose(StreamEncoder.java:241)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/sun.nio.cs.StreamEncoder.close(StreamEncoder.java:226)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.io.OutputStreamWriter.close(OutputStreamWriter.java:267)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.io.BufferedWriter.implClose(BufferedWriter.java:398)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.io.BufferedWriter.close(BufferedWriter.java:380)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.io.PrintWriter.implClose(PrintWriter.java:448)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.io.PrintWriter.close(PrintWriter.java:440)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.apache.commons.compress.harmony.unpack200.Segment.unpackWrite(Segment.java:473)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.apache.commons.compress.harmony.unpack200.Segment.unpack(Segment.java:438)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.apache.commons.compress.harmony.unpack200.Archive.unpack(Archive.java:156)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.apache.commons.compress.harmony.unpack200.Pack200UnpackerAdapter.unpack(Pack200UnpackerAdapter.java:49)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.common.patcher.ClassPatchManager.setup(ClassPatchManager.java:157)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:181)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:126)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:145)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:37)
[15:44:23] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:11)
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
fml logging works just fine for me on modern java

**Comment by Tommeh1** [comment]
> This log is because I worked around a bug in the apache compress library closing stderr, if that was the cause you wouldn't get this message so it must be something else going on

Any idea as to what, as both on either 2.2.9 or 2.2.10, 2.3.0 and 2.3.2 newer Java versions break it, putting it back on Java 8 instantly fixes it.

**Comment by Tommeh1** [comment]
Still exists in 2.3.4

**Comment by Tommeh1** [comment]
Also in 2.3.7...
