### ISSUE TITLE
crashing to desktop

### ISSUE THREAD

**Issue by xlk9000** [GTNewHorizons/GT-New-Horizons-Modpack#13719]
### Your Pack Version

2.3.0

### Your Server

sp

### Java Version

Java 8

### Type of Server

Open To LAN

### Your Actions

click play and it crashs

### Crash Report
<details>
<summary>log</summary>

```
[15:44:40] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[15:44:40] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[15:44:40] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[15:44:40] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[15:44:40] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\localadmin\curseforge\minecraft\Install\runtime\jre-legacy\windows-x64\jre-legacy
[15:44:40] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:44:40] [main/WARN]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:44:40] [main/INFO]: Loading tweaker fastcraft.Tweaker from fastcraft-1.25.jar
[15:44:40] [main/WARN]: The coremod lumien.hardcoredarkness.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:44:40] [main/WARN]: The coremod net.glease.healer.Healer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:44:40] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:44:40] [main/INFO]: Loading tweak class name fastcraft.Tweaker
[15:44:40] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[15:44:40] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:44:40] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:44:40] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:44:41] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.NullPointerException
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:137) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213) ~[guava-17.0.jar:?]
	at com.google.common.hash.AbstractByteHasher.putBytes(AbstractByteHasher.java:69) ~[guava-17.0.jar:?]
	at com.google.common.hash.AbstractStreamingHashFunction.hashBytes(AbstractStreamingHashFunction.java:57) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:97) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:61) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:193) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:170) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:139) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:182) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	... 2 more
[15:44:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[15:44:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[15:44:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[15:44:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
[15:44:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:971)
[15:44:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[15:44:41] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```
</details>

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
please provide logs. ideally the fml-client-latest.log from your log folder

though I should note that afaik Open To LAN can cause issues and isnt fully supported.

**Comment by xlk9000** [comment]
that the only log

**Comment by chochem** [comment]
hmm I guess it crashes instantly before even reaching that phase.

well maybe somebody else knows what this is about.
But my recommendation would just be to use a different launcher. this looks like curseforge? not that important. The most recommended ones are probably multimc and prism (https://gtnh.miraheze.org/wiki/Installing_and_Migrating).
