### ISSUE TITLE
LSC without a dynamo spams GregTech.log file with java.lang.NullPointerException

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#13791]
### Your GTNH Discord Username

hucking

### Your Pack Version

2.3.4

### Your Server

Private

### Java Version

Java 8

### Type of Server

None

### The Issue

when I make a LSC without a dynamo (there is a valid use case for this when trying to transfer energy wirelessly for example from a dyson offworld) it spams this in the GregTech.log file:
```
java.lang.NullPointerException: Cannot invoke "gregtech.api.interfaces.tileentity.IGregTechTileEntity.isInvalidTileEntity()" because the return value of "com.github.technus.tectech.thing.metaTileEntity.hatch.GT_MetaTileEntity_Hatch_DynamoTunnel.getBaseMetaTileEntity()" is null
	at common.tileentities.GTMTE_LapotronicSuperCapacitor.onRunningTick(GTMTE_LapotronicSuperCapacitor.java:757)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.runMachine(GT_MetaTileEntity_MultiBlockBase.java:455)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:384)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:531)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Miisi** [comment]
#13245

**Comment by chochem** [comment]
> #13245

I dont know. this seems way more specific and unrelated to any wider issues

**Comment by hucking** [comment]
It did not come up when I looked for "DynamoTunnel" in search, weird. probably because it wasn't in the original post for the issue.

**Comment by Miisi** [comment]
has the LSC error in its comments, could be useful to update it with this new information

**Comment by chochem** [comment]
having a problem hidden in comments is not good obviously. good to have a separate one

**Comment by chochem** [comment]
hmm looking at the code a bit. maybe this ticket is not quite right. Are you really sure its caused by not having a dynamo?
because that code only runs if there is a TT dynamo.

**Comment by hucking** [comment]
All I can say is when I add a dynamo to the LSC it does not spam it in the log file anymore... I have no idea what is actually causing it.

**Comment by chochem** [comment]
hmm. well I think I can kind of reproduce it. But its very different from what you are saying.

Basically when I **remove** a hatch, I get this error spammed in the logs for 2-3 seconds. but it stops there.

that kinda makes sense, the hatch list is only cleared on stucture check which doesnt happen every tick. will add an extra null check.
