### ISSUE TITLE
[ThaumicEnergistics] Invalid shaped ore recipe

### ISSUE THREAD

**Issue by AnrDaemon** [GTNewHorizons/GT-New-Horizons-Modpack#13806]
### Your Pack Version

Not relevant

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

No crash.

### The Reality

```
[13:24:39] [Client thread/ERROR]: The following problems were captured during this phase
[13:24:39] [Client thread/ERROR]: Caught exception from thaumicenergistics
java.lang.RuntimeException: Invalid shaped ore recipe: RTR, SQS, RPR, Q, 1xtile.appliedenergistics2.BlockQuantumLinkChamber@0, P, null, S, 1xitem.appliedenergistics2.ItemMaterial@47, T, 1xitem.ItemThaumometer@0, R, 1xtile.blockMirror@6, 1xthaumicenergistics.item.cell.microscope@0
	at thaumcraft.api.crafting.ShapedArcaneRecipe.<init>(ShapedArcaneRecipe.java:119) ~[ShapedArcaneRecipe.class:?]
	at thaumcraft.api.ThaumcraftApi.addArcaneCraftingRecipe(ThaumcraftApi.java:171) ~[ThaumcraftApi.class:?]
	at thaumicenergistics.common.features.FeatureCellMicroscope.registerCrafting(FeatureCellMicroscope.java:51) ~[FeatureCellMicroscope.class:?]
	at thaumicenergistics.common.features.ThEFeatureBase.registerFeature(ThEFeatureBase.java:60) ~[ThEFeatureBase.class:?]
	at thaumicenergistics.common.registries.FeatureRegistry.registerFeatures(FeatureRegistry.java:213) ~[FeatureRegistry.class:?]
	at thaumicenergistics.common.CommonProxy.registerFeatures(CommonProxy.java:38) ~[CommonProxy.class:?]
	at thaumicenergistics.common.ThaumicEnergistics.postInit(ThaumicEnergistics.java:154) ~[ThaumicEnergistics.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_371]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_371]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_371]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_371]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_371]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_371]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_371]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

### Your Proposal

IDK, but it shouldn't crash.
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11867495/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
they just broke it on their end. was cleared up in discord
