### ISSUE TITLE
World saving NPE spam resetting chunks after restart

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13820]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

The server is currently spamming the following error non-stop:

```java
[18:13:28] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.world.ChunkDataEvent$Save@7e71d54a:
java.lang.NullPointerException: Cannot invoke "codechicken.lib.world.ChunkExtension.saveData(net.minecraft.nbt.NBTTagCompound)" because the return value of "java.util.HashMap.get(Object)" is null
	at codechicken.lib.world.WorldExtension.saveChunkData(WorldExtension.java:46) ~[WorldExtension.class:?]
	at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkDataSave(WorldExtensionManager.java:40) ~[WorldExtensionManager$WorldExtensionEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1288_WorldExtensionEventHandler_onChunkDataSave_Save.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:198) ~[aqk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) ~[ms.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[18:13:28] [Server thread/ERROR]: Index: 9 Listeners:
[18:13:28] [Server thread/ERROR]: 0: NORMAL
[18:13:28] [Server thread/ERROR]: 1: ASM: cofh.core.world.WorldHandler@27cda022 handleChunkSaveEvent(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:13:28] [Server thread/ERROR]: 2: ASM: thaumcraft.common.lib.events.EventHandlerWorld@6d742ca chunkSave(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:13:28] [Server thread/ERROR]: 3: ASM: mods.natura.Natura@8a8a244 chunkDataSave(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:13:28] [Server thread/ERROR]: 4: ASM: com.github.technus.tectech.mechanics.data.ChunkDataHandler@4f7c99b6 handleChunkSaveEvent(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:13:28] [Server thread/ERROR]: 5: ASM: net.malisis.core.util.chunkblock.ChunkBlockHandler@34ad01ff onDataSave(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:13:28] [Server thread/ERROR]: 6: ASM: mods.natura.worldgen.retro.WorldHandler@8d8a614 handleChunkSaveEvent(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:13:28] [Server thread/ERROR]: 7: ASM: mrtjp.core.world.SimpleGenHandler$@520190bf chunkSaveEvent(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:13:28] [Server thread/ERROR]: 8: ASM: gcewing.sg.SGCraft@5dacdb7b onChunkSave(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:13:28] [Server thread/ERROR]: 9: ASM: codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler@d1ce93e onChunkDataSave(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
[18:13:28] [Server thread/ERROR]: 10: ASM: forestry.core.TickHandlerCoreServer@3641817d chunkSaveEventHandler(Lnet/minecraftforge/event/world/ChunkDataEvent$Save;)V
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
It would appear this reset a piece of terrain just north of base, which never had any machines or anything placed in it.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/39203645/0448506e-e5f6-466b-88f2-abfe9488d22f)
