### ISSUE TITLE
Openblocks Elevator crash

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#13844]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.3.0

### Your Server

dedicated server

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

I crash every time I try to use an elevator to go up. Stand on one, jump, and crash. I also crash on descent. This crashes only me, and not the server. 

### Crash Report

https://paste.ubuntu.com/p/J6fMdtZRKm/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ethryan** [comment]
Please use someplace where you don’t have to sign in to look at the logfile, pastebin is recommended.

**Comment by LazyFleshWasTaken** [comment]
[crash-2023-06-30_09.10.44-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11919406/crash-2023-06-30_09.10.44-client.txt)
[crash-2023-06-30_09.16.30-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11919407/crash-2023-06-30_09.16.30-client.txt)
[crash-2023-06-30_09.10.00-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11919408/crash-2023-06-30_09.10.00-client.txt)

**Comment by LazyFleshWasTaken** [comment]
https://pastebin.com/EDAsh1e8

**Comment by wlhlm** [comment]
```
java.lang.NoClassDefFoundError: openmods/utils/NetUtils
```
This puzzles me. Not sure why it's gone missing...

**Comment by mitchej123** [comment]
Please provide the full fml-client-latest.log with the crash; it's likely a misbehaving ASM transformer earlier, or a duplicate coremod.

**Comment by LazyFleshWasTaken** [comment]
the server isnt mine. That is the log i had on my side, from crashing. Server itself didn't crash.

**Comment by mitchej123** [comment]
I want the fml-xxx-latest.log from whichever side crashed; so in this case your client log.

**Comment by Ethryan** [comment]
It’s located in the logs folder.

**Comment by LazyFleshWasTaken** [comment]
I cant. Its too big, 106 mb.

**Comment by LazyFleshWasTaken** [comment]
here, mediafire download. I'm p sure it's safe.
https://www.mediafire.com/file/u006r3zdswc6w0a/fml-client-latest.log/file

**Comment by boubou19** [comment]
you can zip compress it as it's a text file its file size will be greatly reduced.

**Comment by LazyFleshWasTaken** [comment]
Good idea, here it is:
[fml-client-latest.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11925315/fml-client-latest.zip)

**Comment by LazyFleshWasTaken** [comment]
BTW, i probably should have mentioned this, but I was also getting random crashes when i hover over some items, likea  tic pickaxe, or an oil cell form the oil berry quest.

**Comment by chochem** [comment]
6649 entries of 

```Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@640bb21e:
java.lang.NoClassDefFoundError: Could not initialize class squeek.tictooltips.helpers.StringHelper
	at squeek.tictooltips.TooltipHandler.getMaterialTooltip(TooltipHandler.java:350) ~[TooltipHandler.class:?]
	at squeek.tictooltips.TooltipHandler.getMaterialTooltip(TooltipHandler.java:187) ~[TooltipHandler.class:?]
	at squeek.tictooltips.TooltipHandler.getMaterialTooltip(TooltipHandler.java:182) ~[TooltipHandler.class:?]
	at squeek.tictooltips.TooltipHandler.onItemTooltip(TooltipHandler.java:51) ~[TooltipHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1815_TooltipHandler_onItemTooltip_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:169) ~[ForgeEventFactory.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(Unknown Source) ~[add.class:?]
	at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:136) ~[GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.concatenatedDisplayName(GuiContainerManager.java:217) ~[GuiContainerManager.class:?]
	at codechicken.nei.api.ItemInfo.lambda$getSearchName$4(ItemInfo.java:524) ~[ItemInfo.class:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_361]
	at codechicken.nei.api.ItemInfo.getSearchName(ItemInfo.java:521) ~[ItemInfo.class:?]
	at codechicken.nei.api.ItemInfo.populateSearchMap(ItemInfo.java:171) ~[ItemInfo.class:?]
	at codechicken.nei.ItemList$1.execute(ItemList.java:230) [ItemList$1.class:?]
	at codechicken.nei.RestartableTask$1.run(RestartableTask.java:25) [RestartableTask$1.class:?]```
