### ISSUE TITLE
ModularUI packet error disconnecting players

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13861]
### Your Pack Version

2.3.4

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

```java
[08:05:49] [Server thread/ERROR]: There was a critical exception handling a packet on channel modularui
java.util.NoSuchElementException: Can't find ISyncedWidget for id 180
at com.gtnewhorizons.modularui.api.screen.ModularWindow.getSyncedWidget(ModularWindow.java:452) ~[ModularWindow.class:?]
at com.gtnewhorizons.modularui.api.screen.ModularUIContext.readClientPacket(ModularUIContext.java:377) ~[ModularUIContext.class:?]
at com.gtnewhorizons.modularui.common.internal.network.CWidgetUpdate.executeServer(CWidgetUpdate.java:43) ~[CWidgetUpdate.class:?]
at com.gtnewhorizons.modularui.common.internal.network.NetworkHandler.lambda$static$1(NetworkHandler.java:55) ~[NetworkHandler.class:?]
at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[08:05:49] [Server thread/INFO]: TheIronCove lost connection: TextComponent{text='A fatal error has occured, this connection is terminated', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
The error seems to occur from id 59 all the way to id 180, so something seems to seriously overshoot the highest id.

**Comment by miozune** [comment]
What GUI were you trying to open?

**Comment by Tommeh1** [comment]
> What GUI were you trying to open?

Idk yet, the player that got kicked ain't available right now, but i'll ask once he gets on again.

**Comment by miozune** [comment]
Unfortunately with current design it's hard to figure out offending widget just from sync id. Consistent way to reproduce the issue is needed.

**Comment by Tommeh1** [comment]
His own words: *"when you middle click on recipes to set a specific amount of items it kicks me out"*

**Comment by miozune** [comment]
uh what is it?

**Comment by Tommeh1** [comment]
> uh what is it?

I suppose it refers to either middle or right clicking in a pattern terminal

**Comment by TheEpicGamer274** [comment]
I actually have this exact issue, sometimes while encoding/reencoding patterns and I middle click it'll disconnect me

**Comment by Tommeh1** [comment]
I would try to trigger it myself, but it appears another bug prevents that, as my client is unable to middle click on an item in a pattern terminal to set a custom amount anymore.

**Comment by miozune** [comment]
Cannot reproduce. Also I have no idea how it can happen.

**Comment by firenoo** [comment]
when it happens, we need the log from the client along with the server for this to go somewhere
