### ISSUE TITLE
BetterQuesting couldn't open link

### ISSUE THREAD

**Issue by Discreater** [GTNewHorizons/GT-New-Horizons-Modpack#13916]
### Your GTNH Discord Username

discreater

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 20

### Type of Server

None

### Your Expectation

Click the URL in quest book, such as the URL in first quest 'Your First Night'. And then click the `Yes` button to open the URL. It should open the browser and navigate to the url.

### The Reality

Nothing happens in the browser.

And an error was generated in the log:
```log
[13:43:57] [Client thread/ERROR] [betterquesting]: Couldn't open link
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at betterquesting.api2.client.gui.panels.content.PanelTextBox.openURL(PanelTextBox.java:333) [PanelTextBox.class:?]
	at betterquesting.api2.client.gui.panels.content.PanelTextBox.access$100(PanelTextBox.java:32) [PanelTextBox.class:?]
	at betterquesting.api2.client.gui.panels.content.PanelTextBox$1.func_73878_a(PanelTextBox.java:311) [PanelTextBox$1.class:?]
	at net.minecraft.client.gui.GuiConfirmOpenLink.func_146284_a(SourceFile:41) [bcu.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225) [bdw.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) [bdw.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) [bdw.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5106) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165) [launchwrapper-1.15.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [launchwrapper-1.15.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:381) ~[?:?]
	at java.desktop/java.awt.Desktop.browse(Desktop.java:531) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	... 22 more
```

### Your Proposal

It should open the URL properly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
Which OS are you using? Which JDK /JRE are you using (please give exact version and distribution name)?

**Comment by Discreater** [comment]
Arch Linux X86_64.
```
> java --version
openjdk 20.0.1 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9)
OpenJDK 64-Bit Server VM (build 20.0.1+9, mixed mode, sharing)
```

**Comment by chochem** [comment]
yea the url works fine, but as you can see in your log "The BROWSE action is not supported on the current platform!"

**Comment by wlhlm** [comment]
Please install the `jre-openjdk` package.

**Comment by wlhlm** [comment]
For background, opening a link requires GUI support in the JRE, which is not available with the default -headless package.

**Comment by Discreater** [comment]
But I think I do currently use `jre-openjdk`, not the -headless one.

**Comment by wlhlm** [comment]
https://wiki.archlinux.org/title/Java#Java_applications_cannot_open_external_links

**Comment by Discreater** [comment]
Thanks!
