### ISSUE TITLE
NEI sometimes don't load the item list

### ISSUE THREAD

**Issue by Sopel97** [GTNewHorizons/GT-New-Horizons-Modpack#13949]
### Your GTNH Discord Username

sopel__

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

NEI item list loads after a few seconds.

### The Reality

Recently I had it happen twice that NEI fails to load the item list even after waiting minutes. It seems permanently stuck. The whole minecraft instance has to be restarted to fix the issue. The following log entry is present only when the error occurs:
```
[B#779]  [12:52:39] [NEI Item Loading/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@1e471a84:
[B#779]  java.lang.ThreadDeath
[B#779]      at java.lang.Thread.stop(Thread.java:850) ~[?:1.8.0_51]
[B#779]      at codechicken.nei.ThreadOperationTimer.run(ThreadOperationTimer.java:66) ~[ThreadOperationTimer.class:?]
```

### Your Proposal

I have an old PC and world load times get longer and longer (around a minute or longer to fully load). Wouldn't be surpsied if it's some dumb timeout.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
Looks like item list loading stalled ran into a timeout (500ms by default, can be configured). What are you specs?

**Comment by wlhlm** [comment]
We should not require restarting minecraft to retry loading the list when a timeout was triggered.

**Comment by Sopel97** [comment]
> Looks like item list loading stalled and ran into a timeout (500ms by default, can be configured). What are your specs?

i5-3570, running on the brink of RAM

last I tried reloading just the world it still couldn't load, maybe I was just unlucky

**Comment by wlhlm** [comment]
> could you point to where this timeout can be configured?

It's in `config/NEI/client.cfg`, option `itemLoadingTimeout` (unit is milliseconds).

**Comment by luidgeitaliano** [comment]
> I think increasing the timeout a bit won't harm. Try something like 750ms for a while and report back.

I had the same problem. Your solution was great! Thank you a lot) 750ms is quite enough

**Comment by Leopardo1313** [comment]
Hello, I seem to have the same problem and even after changing the the loading timeout it was still happening. I have tried restarting and it didnt work.

**Comment by chochem** [comment]
Leopardo1313 read the above or when that does not help, make a ticket with actual usual information about your problem. This on was resolved a long time ago.
