### ISSUE TITLE
Thermos (v58/57 1614) refuses to launch with Java 17-20 (GT 2.3.0) - java.lang.NoSuchFieldError: defman

### ISSUE THREAD

**Issue by MOBO-Timmy** [GTNewHorizons/GT-New-Horizons-Modpack#14003]
### Your GTNH Discord Username

__equilibrium__

### Your Pack Version

2.3.0

### Your Server

Dedicated machine... Ubuntu

### Java Version

Java 19

### Type of Server

Thermos

### Your Actions

Just launching with any hybrid forge / bukkit gives **java.lang.NoSuchFieldError: defman**

### Crash Report

sh startserver-java9.sh 
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0

[12:01:44] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
null
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:125)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:37)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:11)
Caused by: java.lang.NoSuchFieldError: defman
        at cpw.mods.fml.common.launcher.FMLTweaker.<init>(FMLTweaker.java:36)
        at cpw.mods.fml.common.launcher.FMLServerTweaker.<init>(FMLServerTweaker.java:6)
        ... 13 more
[12:01:44] [main/ERROR]: Unable to launch
If you want to completely stop the server process now, press Ctrl+C before the time is up!
Rebooting in:
12...

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by MOBO-Timmy** [comment]
"__equilibrium__"

**Comment by MOBO-Timmy** [comment]
Any help would be greatly appreciated

**Comment by MOBO-Timmy** [comment]
If you could just describe how you get java 19 and thermos to work together, i'll just copy that ;)

**Comment by ChrisJStone** [comment]
I would take a look at the readme for [lwjgl3ify](https://github.com/GTNewHorizons/lwjgl3ify) especially the [server](https://github.com/GTNewHorizons/lwjgl3ify#server) portion.

**Comment by eigenraven** [comment]
Thermos is not supported at all, it is effectively a forge fork so would need its own patches instead of the forge patches lwjgl3ify provides.

**Comment by MOBO-Timmy** [comment]
it's not what the top-dev said ?!
he told me explicitly "we run thermaos and java 19, post on reddit")

**Comment by boubou19** [comment]
> it's not what the top-dev said ?! he told me explicitly "we run thermos and java 19, post on reddit")

If Raven says it's not supported, it's not. If they run thermos and java 19 via lwjgl3ify, they are either lying or they did patch stuff. Raven is the author of lwjgl3ify, she knows what she says.

**Comment by MOBO-Timmy** [comment]
![Capture d'écran 2023-07-23 143453](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10128559/ad1916db-14b9-433d-bea3-7c3ca7be96e0)

**Comment by MOBO-Timmy** [comment]
Just saying !

**Comment by MOBO-Timmy** [comment]
(thanks for nothing)

**Comment by eigenraven** [comment]
To be clear, this is probably a mistake/misunderstanding by Dream, the officials run on Java 8+Thermos currently.

**Comment by Dream-Master** [comment]
dint we update zeta to newer jave @boubou19 ?

**Comment by Dream-Master** [comment]
nevermind i was wrong
