### ISSUE TITLE
NPE of Advanced Assembly Line

### ISSUE THREAD

**Issue by ChifengSouthSt** [GTNewHorizons/GT-New-Horizons-Modpack#14080]
### Your GTNH Discord Username

ND4

### Your Pack Version

2.3.5

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

try to make a Circuit Assembling Line by Advanced Assembling Line

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/119904245/620664da-dd4a-41a7-9420-95e6697fd071)

There are some issues with the flash memory recipe of Circuit Assembling Line. And there was an error message in the background，
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.glease.ggfab.mte.MTE_AdvAssLine$Slice.start(MTE_AdvAssLine.java:794)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.glease.ggfab.mte.MTE_AdvAssLine.checkRecipe(MTE_AdvAssLine.java:636)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_ExtendedPowerMultiBlockBase.checkProcessing(GT_MetaTileEntity_ExtendedPowerMultiBlockBase.java:139)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.checkRecipe(GT_MetaTileEntity_MultiBlockBase.java:478)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.runMachine(GT_MetaTileEntity_MultiBlockBase.java:555)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:398)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:534)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fastcraft.u.a(F:289)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fastcraft.H.aq(F:36)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[12:42:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

### Your Proposal

that is all 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
What particular recipes are present on the data sticks?

**Comment by ChifengSouthSt** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/119904245/578076d9-bc48-40ae-ba03-92f5eec1e6b0)
OK,it seems like a bug,T4 rockat Heavy-Duty Plate can't make.

**Comment by ChifengSouthSt** [comment]
I just tested it,if the recipe need a zpm votlage, but the Advanced Assembly Line installed a Luv 4096A laser hatch,so this recipe can't running.Is this a special machine setting?

**Comment by King65868** [comment]
This is intended, you need a zpm laser there or higher

**Comment by RiderisPr** [comment]
In the case of high voltage, the recipe for low voltage will also have this error
