### ISSUE TITLE
java.lang.NoClassDefFoundError with bukkit plugins

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#14136]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.3.0.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

Updated from ver2.2 to ver2.3 and started the server (plugins, etc. are still the same).

### The Reality

The "Plan" plugin can no longer be loaded with the following error

```
[19:25:58] [pool-35-thread-1/WARN]: 

The current build of DiscordSRV is outdated by 109 commits! Get the latest build at your favorite distribution center.

Spigot: https://www.spigotmc.org/resources/discordsrv.18494/
Github: https://github.com/DiscordSRV/DiscordSRV/releases
Direct Download: https://get.discordsrv.com

[19:25:58] [Server thread/ERROR]: Error occurred while enabling Plan v5.4 build 1633 (Is it up to date?)
java.lang.NoClassDefFoundError: mt
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_372]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_372]
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048) ~[?:1.8.0_372]
	at java.lang.Class.getMethod0(Class.java:3018) ~[?:1.8.0_372]
	at java.lang.Class.getMethod(Class.java:1784) ~[?:1.8.0_372]
	at com.djrapitops.plan.gathering.BukkitSensor.hasPaperMethod(BukkitSensor.java:116) ~[?:?]
	at com.djrapitops.plan.gathering.BukkitSensor.<init>(BukkitSensor.java:41) ~[?:?]
	at com.djrapitops.plan.gathering.BukkitSensor_Factory.newInstance(BukkitSensor_Factory.java:39) ~[?:?]
	at com.djrapitops.plan.gathering.BukkitSensor_Factory.get(BukkitSensor_Factory.java:31) ~[?:?]
	at com.djrapitops.plan.gathering.BukkitSensor_Factory.get(BukkitSensor_Factory.java:11) ~[?:?]
	at plan.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
	at com.djrapitops.plan.delivery.rendering.json.ServerOverviewJSONCreator_Factory.get(ServerOverviewJSONCreator_Factory.java:59) ~[?:?]
	at com.djrapitops.plan.delivery.rendering.json.ServerOverviewJSONCreator_Factory.get(ServerOverviewJSONCreator_Factory.java:17) ~[?:?]
	at plan.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
	at com.djrapitops.plan.delivery.webserver.resolver.json.RootJSONResolver_Factory.get(RootJSONResolver_Factory.java:123) ~[?:?]
	at com.djrapitops.plan.delivery.webserver.resolver.json.RootJSONResolver_Factory.get(RootJSONResolver_Factory.java:19) ~[?:?]
	at plan.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
	at com.djrapitops.plan.delivery.export.PlayerPageExporter_Factory.get(PlayerPageExporter_Factory.java:49) ~[?:?]
	at com.djrapitops.plan.delivery.export.PlayerPageExporter_Factory.get(PlayerPageExporter_Factory.java:15) ~[?:?]
	at plan.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
	at com.djrapitops.plan.delivery.export.Exporter_Factory.get(Exporter_Factory.java:51) ~[?:?]
	at com.djrapitops.plan.delivery.export.Exporter_Factory.get(Exporter_Factory.java:11) ~[?:?]
	at plan.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
	at com.djrapitops.plan.gathering.listeners.bukkit.PlayerOnlineListener_Factory.get(PlayerOnlineListener_Factory.java:76) ~[?:?]
	at com.djrapitops.plan.gathering.listeners.bukkit.PlayerOnlineListener_Factory.get(PlayerOnlineListener_Factory.java:21) ~[?:?]
	at com.djrapitops.plan.gathering.listeners.BukkitListenerSystem_Factory.get(BukkitListenerSystem_Factory.java:64) ~[?:?]
	at com.djrapitops.plan.gathering.listeners.BukkitListenerSystem_Factory.get(BukkitListenerSystem_Factory.java:17) ~[?:?]
	at com.djrapitops.plan.PlanSystem_Factory.get(PlanSystem_Factory.java:135) ~[?:?]
	at com.djrapitops.plan.PlanSystem_Factory.get(PlanSystem_Factory.java:33) ~[?:?]
	at plan.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
	at com.djrapitops.plan.DaggerPlanBukkitComponent.system(DaggerPlanBukkitComponent.java:983) ~[?:?]
	at com.djrapitops.plan.Plan.onEnable(Plan.java:74) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-staging-3aba0ea3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:362) [JavaPluginLoader.class:1.7.10-staging-3aba0ea3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411) [SimplePluginManager.class:1.7.10-staging-3aba0ea3]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:403) [CraftServer.class:1.7.10-staging-3aba0ea3]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:337) [CraftServer.class:1.7.10-staging-3aba0ea3]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:516) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:490) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:450) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:367) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:644) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]
[19:25:59] [Server thread/INFO]: Patching net.minecraft.world.World
[19:25:59] [Server thread/INFO]: Removed 0 occurrence of LinkedHashList::push
```

### Your Proposal

The issue didn't occur with the Reflex version of Crucible, so I assume it is a mixin-related problem.
"Plan" is a great server monitoring plugin and Crucible(Normal version) is a great performance server, so I don't want to throw either one away..

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
bukkit plugins are not supported. Try updating discordSRV to see if it fixes the issues. For reference, we do use the 1.26.0 version on zeta since monthes now, without any issue.

**Comment by yukieiji** [comment]
Plan v5.4 build 1633 also works with Java 8(https://github.com/plan-player-analytics/Plan/issues/2838 )

**Comment by paulzzh** [comment]
I fixed it by catching `NoClassDefFoundError` .
https://github.com/paulzzh/Plan/commit/1917849385438ab92e2431bcbc8109d1224d9cfe
It works now.
