### ISSUE TITLE
NHCore has some issues with its thaumcraft compat

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#14162]
### Your GTNH Discord Username

boubou_19

### Your Pack Version

2.3.6

### Your Server

zeta

### Java Version

Java 8

### Type of Server

Thermos

### Issue

Some issues i found in the logs of 2.3.6 on zeta during boot

<details>

<summary> logs </summary>

```
[16:03:03] [Server thread/WARN] [/dreamcraft]: java.lang.NullPointerException
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at net.minecraft.item.ItemStack.func_77960_j(Unknown Source)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at com.dreammaster.thaumcraft.TCLoader.checkRecipeProblems(TCLoader.java:64)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at com.dreammaster.main.MainRegistry.CompleteLoad(MainRegistry.java:469)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:745)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:288)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:648)
[16:03:03] [Server thread/WARN] [/dreamcraft]: 	at java.lang.Thread.run(Thread.java:748)
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:0 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:1 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:2 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:3 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:4 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:5 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:6 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:7 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:8 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:9 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:10 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:11 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:12 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:13 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:14 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for ThaumicExploration:chestSeal:15 has invalid research name (CHESTSEAL)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for WitchingGadgets:WG_RoseVine:0 has invalid research name (ROSEVINE.1)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for WitchingGadgets:WG_RoseVine:0 has invalid research name (ROSEVINE.2)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for WitchingGadgets:WG_RoseVine:0 has invalid research name (ROSEVINE.3)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for WitchingGadgets:WG_WoodenDevice:1 has invalid research name (SNOWBALLER)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for WitchingGadgets:WG_WallMirror:0 has invalid research name (WALLMIRROR)!
[16:03:03] [Server thread/WARN] [DREAMCRAFT/dreamcraft]: WARNING!! Thaumcraft recipe for gregtech:gt.metaitem.01:5057 has invalid research name (UU-MatterInfusion)!
```

</details>

**Comment by Chaoschaot232** [comment]
I can confirm that and it was present also in 2.3.4 but have noticed it a bit later and currently I am not doing any TC
