### ISSUE TITLE
OmniOcular & ModularUI Incompatible

### ISSUE THREAD

**Issue by DarkLei** [GTNewHorizons/GT-New-Horizons-Modpack#14189]
### Your Pack Version

2.3.6 java20

### Your Server

sp

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

trying to open multi gui，game crash！

### Crash Report

`Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "me.exz.omniocular.handler.JSHandler.engine" is null
    at me.exz.omniocular.handler.JSHandler.getBody(JSHandler.java:44)
    at me.exz.omniocular.handler.TooltipHandler.handleItemTooltip(TooltipHandler.java:32)
    at com.gtnewhorizons.modularui.api.drawable.GuiHelper.applyNEITooltipHandler(GuiHelper.java:478)
    at com.gtnewhorizons.modularui.api.drawable.GuiHelper.getItemTooltip(GuiHelper.java:468)
    at com.gtnewhorizons.modularui.common.internal.wrapper.ModularGui.renderToolTip(ModularGui.java:416)
    at com.gtnewhorizons.modularui.common.internal.wrapper.ModularGui.func_146979_b(ModularGui.java:289)
    at com.gtnewhorizons.modularui.common.internal.wrapper.ModularGui.func_73863_a(ModularGui.java:158)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5106)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)`

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Hikari1nVoid** [comment]
No I don't think OO has been offically added to GTNH yet.

**Comment by boubou19** [comment]
and we don't intend to officially support it. I'm closing this. Maybe if you feel like it you can reopen it @miozune

**Comment by miozune** [comment]
- I don't think it can be fixed on MUI side other than just try-catching.
- OmniOcular released Java17 compat patch on April, so the author is still active. You can ask them.
