### ISSUE TITLE
Dynamic Lights causes Abrupt Disconnect

### ISSUE THREAD

**Issue by lancylot2004** [GTNewHorizons/GT-New-Horizons-Modpack#14366]
### Your GTNH Discord Username

.sleepbot

### Your Pack Version

2.4.0RC1

### Your Server

Self-Hosted Oracle

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

Adding `Dynamic+Lights-1.3.9a-MC1.7.10` makes it impossible for a client to connect to a server. Neither the client nor the server crashes, but the connection is broken as soon as it is established. The few seconds of log from `fml-client-latest` is as below.

The mod was only added to the client side, as adding it to the server prevented server startup.

The only other modification to the game is the addition of the non-fairplay version of journeymap, installed according to guidance on the wiki by removing both jars on server and client, then only adding the non-fairplay jar to client side.

The issue resolves itself as soon as dynamic lights is removed from the client.

If relevant, the client is an M2 Mac.

### Crash Report
```
[10:31:13] [Netty IO #3/TRACE] [FML/]: $ClientHello->FMLHandshakeServerState$2:HELLO
[10:31:13] [Netty IO #3/INFO] [FML/]: Client protocol version 2
[10:31:13] [Netty IO #3/TRACE] [FML/]: $ModList:302 mods->FMLHandshakeServerState$2:HELLO
[10:31:13] [Netty IO #3/INFO] [FML/]: Client attempting to join with 302 mods : BuildCraft|Silicon@7.1.36,AromaBackup@0.1.0.0,notenoughIDs@1.4.6,ProjRed|Expansion@4.7.12-GTNH,ExtraBees@2.1.10,DynamicLights@1.3.9a,HardcoreEnderExpansion@1.9.7-GTNH,blocklimiter@0.55,MouseTweaks@2.4.9-GTNH,Botany@2.1.10,dreamcraft@2.1.109,endercore@0.2.17,travellersgearneo@1.0,mixinbooterlegacy@1.2.1,BWCore@0.0.1,BuildCraft|Robotics@7.1.36,kubatech@0.12.7,irontank@1.2.6,forgelin@1.9.6-GTNH,galacticgreg@1.0.10,Ic2Nei@1.2.1,openglasses@1.3.1-GTNH,GalaxySpace@1.2.6-GTNH,betterbuilderswands@0.9.6-GTNH,BiomesOPlenty@2.1.0,LunatriusCore@1.1.7-GTNH,bettercrashes@1.2.2-GTNH,openmodularturrets@2.2.11-247,gtnhtcwands@1.3.1,ForgeMultipart@1.3.4,hodgepodge@2.2.30,lootgames@2.0.8,malisisdoors@1.13.7-GTNH,berriespp@1.4.1,BrandonsCore@1.0.0.13-GTNH,CoFHCore@1.7.10R3.1.4,malisiscore@0.14.9,catwalks@2.0.4,defaultkeys@1.1.2,ExtraTrees@2.1.10,ae2fc@1.1.41-gtnh,StorageDrawers@1.12.0-GTNH,gendustry@1.6.5.5-GTNH,TGregworks@GTNH-1.0.24,enhancedlootbags@1.1.0,BuildCraft|Energy@7.1.36,modtweaker2@0.9.10,IC2@2.2.828-experimental,WitcheryExtras_ASM@0.1-Beta,IguanaTweaksTConstruct@2.3.0,FML@7.10.99.99,Natura@2.5.7,modularui@1.1.16,defaultserverlist@1.4.0,NEIAddons|Forestry@1.12.22,ThE-core@1.0.0.1,BiblioWoodsNatura@1.5,<CoFH ASM>@000,NettyPatch@0.3.1,Automagy@0.28.2,ProjRed|Illumination@4.7.12-GTNH,hydroenergy@1.1.0,TMechworks@0.2.16.4,LogisticsPipes@1.0.6-GTNH,thaumicinsurgence@0.2.6,NotEnoughItems@2.3.83-GTNH,Thaumcraft@4.2.3.5,opensecurity@1.0.120-GTNH,Waila@1.6.0,eternalsingularity@1.1.0,PlayerAPI@1.4.2,unimixins-compat@0.1.11,appliedenergistics2-core@rv3-beta-250-GTNH,NEIAddons@1.12.22,StorageDrawersForestry@1.11.17-GTNH,BiblioCraft@1.11.7,WarpTheory@1.2.16-GTNH,BuildCraft|Core@7.1.36,custommainmenu@1.9.4,OpenModsCore@0.10.6,betterloadingscreen@1.4.4-GTNH,bdlib@1.9.8-GTNH,NEIAddons|Developer@1.12.22,tcinventoryscan@1.0.12-GTNH,ProjRed|Transmission@4.7.12-GTNH,naturescompass@1.3.6-GTNH,WR-CBE|Logic@1.4.8,DummyCore@1.17.0,WitcheryExtras@1.1.14,RWG@alpha-1.3.3.2,BetterAchievements@0.1.3,MobiusCore@1.3.8-mapless,inventorytweaks@1.5.16,defaultworldgenerator@0.2,InGameInfoXML@2.8.4,EMT@1.3.3,findit@1.1.0,GT++_Preloader@0.5-Beta,OpenBlocks@1.7.0-GTNH,harvestthenether@1.7.10,GoodGenerator@0.6.40,gasstation@0.5.1,EnderStorage@1.4.12,ForbiddenMagic@0.6.7-GTNH,alchgrate@1.0.3-GTNH,gregtech@MC1710,CropLoadCoreASM@0.0.2,CarpentersBlocks@3.4.0-GTNH,EnderIO@2.4.24,Translocator@1.1.2.21,blockrenderer6343@1.0.3,InfernalMobs@1.7.9-GTNH,neiintegration@1.3.3,miscutils@1.9.83,MrTJPCoreMod@1.1.4,Roguelike@1.5.3-GTNH,SpecialMobs@3.4.3,NEIAddons|Botany@1.12.22,Opis@1.3.8-mapless,sleepingbag@0.1.4,gtnhlanth@0.10.8,thaumicenergistics@1.4.13-GTNH,Aroma1997Core@1.0.2.16,CodeChickenCore@1.1.11,mobsinfo@0.1.6-GTNH,YAMCore@0.5.86,MineTweaker3@3.2.13,openprinter@0.1.3-GTNH,GTTweaker@2.0.1,ThaumicTinkerer-preloader@0.1,oauth@1.06.1-GTNH,structurelib@1.2.8,bartworks@0.7.39,gtnhmixins@2.1.13,NodalMechanics@1.1.-6-GTNH,TravellersGear@1.16.6,adventurebackpack@1.0.14-GTNH,gtneioreplugin@1.1.3,gadomancy@1.1.3,betterp2p@1.1.20,Baubles@1.0.1.16,ProjRed|Core@4.7.12-GTNH,gtnhintergalactic@1.1.28,mxrandom@0.2.0,FloodLights@1.2.9,TML@4.1.0-GTNH,ArchitectureCraft@1.8.6,ProjRed|Exploration@4.7.12-GTNH,holoinventory@2.2.3-GTNH,Forestry@4.6.14,ae2wct@1.9.4,Schematica@1.9.3-GTNH,OpenMods@0.10.6,ifu@1.9.6,RIO@2.4.8,tcneiadditions@1.2.2,GalacticraftCore@3.0.73-GTNH,BiblioWoodsBoP@1.9,torohealthmod@1.0.1,tc4tweak@1.5.15,p455w0rdslib@1.0.4,tcnodetracker@1.1.7,netherportalfix@1.1.2,questbook@3.3.27-GTNH,battlegear2@1.2.0,ForgeMicroblock@1.3.4,botanichorizons@1.0.15-GTNH,Ztones@1.7.10,ThaumicExploration@1.1.94-GTNH,duradisplay@1.0.10,EnderZoo@1.0.23,MagicBees@2.6.6-GTNH,ProjRed|Integration@4.7.12-GTNH,betterquesting@3.3.27-GTNH,controlling@1.0.0.5,cookingforblockheads@1.2.16-GTNH,txloader@1.5.3,compactkineticgenerators@1.7.10-1.0,ae2stuff@0.5.7-GTNH,mixinextras@0.1.11,OpenComputers@1.9.14-GTNH,McMultipart@1.3.4,kekztech@0.8.9,gravisuiteneo@1.0.15,ProjRed|Fabrication@4.7.12-GTNH,SuperTic@1.2.5,ExtraUtilities@1.2.12,Railcraft@9.14.9,detravscannermod@1.7.2,bq_standard@3.3.27-GTNH,WR-CBE|Addons@1.4.8,IC2NuclearControl@2.4.19,StevesCarts@2.0.2,MCFrames@0.0.3,ThaumicHorizons@1.3.5,BiblioWoodsForestry@1.7,ironchestminecarts@1.0.8,structurecompat@0.4.0,FastCraft@1.25,Forge@10.13.4.1614,avaritiaddons@1.5.5-GTNH,croploadcore@0.1.10,HardcoreDarkness@1.7,tinkersdefense@1.2,OpenComputers|Core@@VERSION@,ThaumicTinkerer@2.7.0-1-gc762ad9.dirty,ThaumcraftResearchTweaks@1.0.4,OilTweak@1.0.4,AdvancedSolarPanel@1.7.10-3.5.1,AFSU@1.2.6-GTNH,JABBA@1.2.22,angermod@0.6.3,ProjRed|Transportation@4.7.12-GTNH,mixingasm@0.2.2,AppleCore@3.2.11,cb4bq@3.3.27-GTNH,bartworkscrossmod@0.7.39,TiCTooltips@1.2.11,universalsingularities@8.6.7,supersolarpanel@1.7.10-1.1.1-GT-NH-Mod,GalacticraftAmunRa@0.4.36,HungerOverhaul@1.0.4-GTNH,gtnhlib@0.0.13,visualprospecting@1.1.13,ThaumicMachina@0.2.1,NEIAddons|ExNihilo@1.12.22,NEIAddons|CraftingTables@1.12.22,WailaHarvestability@1.1.10-GTNH,unimixins@0.1.11,Botania@1.9.24-GTNH,bartworkscrossmodtgregworkscontainer@0.7.39,personalspace@1.0.26,beebetteratbees@0.3.1-GTNH,Avaritia@1.45,craftpresence@2.2.1,ForgeRelocation@0.0.3,ProjRed|Compatibility@4.7.12-GTNH,TConstruct@1.9.39-GTNH,asielib@0.5.4,StevesFactoryManager@1.1.7-GTNH,BinnieCore@2.1.10,inpure|core@1.1.5-GTNH,sharewhereiam@0.2.0,RelocationFMP@0.0.4,wawla@1.1.3-GTNH,Genetics@2.1.10,mcp@9.05,unimixins-mixin@0.1.11,Mantle@0.3.7,journeymap@5.1.4p6,appliedenergistics2@rv3-beta-250-GTNH,SGCraft@1.3.13-GTNH,thaumcraftneiplugin@@VERSION@,AromaBackupRecovery@1.0,DraconicEvolution@1.1.19-GTNH,WR-CBE|Core@1.4.8,StorageDrawersMisc@1.11.18-GTNH,harvestcraft@1.1.1-GTNH,TaintedMagic@r7.6,TwilightForest@2.4.5,BuildCraft|Factory@7.1.36,ProjectBlue@1.1.12-GTNH,computronics@1.7.1-GTNH,GraviSuite@1.7.10-2.0.3,nutrition@0.0.4,NEIAddons|AppEng@1.12.22,neicustomdiagram@1.5.11,NettyPatch_ASM@0.3.1,GalacticraftMars@3.0.73-GTNH,BuildCraft|Compat@7.1.14,wailaplugins@0.2.8,HelpFixer@1.1.0,itlt@1.0.4,neenergistics@1.4.2,AWWayofTime@1.4.3,IronChest@6.0.71,RandomThings@2.4.5,creativecore@1.3.31-GTNH,bugtorch@1.2.10-GTNH,thaumicbases@1.5.4,SpiceOfLife@2.1.0-carrot,thaumicboots@0.0.1,StorageDrawersNatura@1.11.17-GTNH,spongemixins@2.0.1,BuildCraft|Transport@7.1.36,StorageDrawersBop@1.11.17-GTNH,wanionlib@1.8.4,Aroma1997CoreHelper@1.0.2.16,chisel@2.11.4-GTNH,StevesAddons@0.10.27,Backpack@2.2.11-GTNH,ToxicEverglades@1.9.83,ThaumcraftMobAspects@1.0.0-GTNH,witchery@0.24.1,overloadedarmorbar@1.0.1,WitchingGadgets@1.3.4-GTNH,BuildCraft|Builders@7.1.36,ggfab@0.2.4,chiseltones@1.0.4-GTNH,littletiles@1.2.9-GTNH,tectech@5.2.40,BloodArsenal@1.2.11
[10:31:13] [Netty IO #3/INFO] [FML/]: Attempting connection with missing mods [Morpheus] at CLIENT
[10:31:13] [Netty IO #3/TRACE] [FML/]: $HandshakeAck:{2}->FMLHandshakeServerState$3:WAITINGCACK
[10:31:13] [Netty IO #3/DEBUG] [OpenMods/]: openmods.network.IdSyncManager$InboundHandler.userEventTriggered(IdSyncManager.java:74): Sending id data for player: EntityPlayerMP['Lancy2004'/34651477, l='World', x=739.50, y=77.00, z=66.50]
[10:31:14] [Netty IO #3/TRACE] [FML/]: $HandshakeAck:{3}->FMLHandshakeServerState$4:COMPLETE
[10:31:14] [Netty IO #3/TRACE] [FML/]: $HandshakeAck:{4}->FMLHandshakeServerState$5:DONE
[10:31:14] [Server thread/INFO] [FML/]: [Server thread] Server side modded connection established
[10:31:14] [Server thread/INFO] [Adventure Backpack/]: Joined EntityPlayer of name: Lancy2004
[10:31:14] [Netty IO #3/TRACE] [FML/]: $HandshakeAck:{5}->FMLHandshakeServerState$5:DONE
[10:31:14] [Server thread/INFO] [EnderCore/]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[10:31:14] [Server thread/INFO] [kubatech/]: Sending config to Lancy2004
[10:31:14] [Server thread/INFO] [mobsinfo/]: Sending config to Lancy2004
[10:31:14] [Server thread/INFO] [EnderCore/]: Sending server configs to client for tterrag.wailaplugins.config.WPConfigHandler
[10:31:14] [Server thread/DEBUG] [NotEnoughItems/]: Loading Player: Lancy2004
[10:31:14] [Server thread/DEBUG] [NotEnoughItems/]: Sending serverside check to: Lancy2004
[10:31:14] [Server thread/INFO] [Waila/]: Player EntityPlayerMP['Lancy2004'/34651477, l='World', x=394.70, y=60.00, z=54.59] connected. Sending ping
[10:31:14] [Server thread/DEBUG] [hydroenergy/]: [HydroEnergy] Sent synchronize packet to player Lancy2004
[10:31:19] [Netty IO #3/ERROR] [FML/]: NetworkDispatcher exception
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_332]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_332]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_332]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_332]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[?:1.8.0_332]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
[10:31:19] [Server thread/DEBUG] [NotEnoughItems/]: Unloading Player: Lancy2004
```
### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by lancylot2004** [comment]
Thanks! Can you tell me which specific version? 1.7.10 E7 crashes the client on launch for me...

**Comment by boubou19** [comment]
looks like it's caused by your mac then, because optifine E7 is for sure working on both java 8 and java 17-20 pack instances.
