### ISSUE TITLE
CurseForge version of v2.4.0.0 doesn't boot

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#14420]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.4.0.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

After installing and downloading(first boo) GTNV v2.4.0.0, I tried to launch it in CurseForge, but it crashed.

### Crash Report

[08:48:01] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoSuchFieldError: throwEnderPearlsInCreativeMode
[08:48:01] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at jss.bugtorch.mixinplugin.BugTorchEarlyMixins.getMixins(BugTorchEarlyMixins.java:51)
[08:48:01] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.gtnewhorizon.gtnhmixins.core.GTNHMixinsCore.injectData(GTNHMixinsCore.java:115)
[08:48:01] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.github.legacymoddingmc.unimixins.all.AllCore.injectData(AllCore.java:67)
[08:48:01] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:119)
[08:48:01] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.inject(MixinPlatformAgentFMLLegacy.java:320)
[08:48:01] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.launch.platform.MixinContainer.inject(MixinContainer.java:143)
[08:48:01] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197)
[08:48:01] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[08:48:01] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.launch.MixinTweaker.injectIntoClassLoader(MixinTweaker.java:64)
[08:48:01] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[08:48:01] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I've changed the config of BugTorch and other things, but it didn't change.
![BugTorch](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40425798/895c2fbd-1006-41a0-a84b-f1b6fba24e20)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment]
Cannot reproduce, please post full log

**Comment by boubou19** [comment]
reinstall it, looks like something got corrupted during download of the mods. Dream and I tested the 2.4.0 on CF and we got it to work, so it must be something on your hand. alternatively if it doesn't work after a reinstallation, consider using an alternative way of installing the pack such as Technic launcher or MMC/Prism instance download.

**Comment by Dream-Master** [comment]
@yukieiji maybe you loaded a early version. check if unimixin is in the pack. If not redownloaded it.

**Comment by yukieiji** [comment]
I looked in the mods folder and found some of the same mods, so I reinstalled them and they worked correctly!
Sorry for the trouble.
