### ISSUE TITLE
Gadomancy

### ISSUE THREAD

**Issue by brandyyn** [GTNewHorizons/GT-New-Horizons-Modpack#14466]
### Your GTNH Discord Username

brandyyn

### Your Pack Version

gadomancy-1.1.3 (GTNH)

### Your Server

Private modpack

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

x posted from https://github.com/FalsePattern/EndlessIDs/issues/145 because I don't know which mod or if both are causing this problem

[millenaire.log](https://github.com/FalsePattern/EndlessIDs/files/12537092/millenaire.log)

[latest.log](https://github.com/FalsePattern/EndlessIDs/files/12537105/latest.log)

Caused by: java.lang.UnsupportedOperationException: A mod that is incompatible with EndlessIDs has tried to access the biome array of a chunk like in vanilla! Crashing in fear of potential world corruption!
Please report this issue on https://github.com/FalsePattern/EndlessIDs ASAP!
at net.minecraft.world.chunk.Chunk.emergencyCrash(Chunk.java:1628)
at net.minecraft.world.chunk.Chunk.handler$zcg000$endlessids$crashGetBiomeArray(Chunk.java:1642)
at net.minecraft.world.chunk.Chunk.func_76605_m(Chunk.java)
at makeo.gadomancy.common.utils.world.ChunkProviderTCOuter.func_73154_d(ChunkProviderTCOuter.java:188)
at net.minecraft.world.gen.ChunkProviderServer.redirect$zjb000$archaicfix$populateChunkWithBiomes(ChunkProviderServer.java:532)
at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
at net.minecraft.world.World.func_72964_e(World.java:419)
at net.minecraft.world.World.func_147438_o(World.java:2536)
at org.millenaire.common.Point.getMillChest(Point.java:332)
at org.millenaire.common.building.Building.countGoods(Building.java:1801)
at org.millenaire.common.building.Building.canAffordBuild(Building.java:1323)
at org.millenaire.common.building.Building.findBuildingConstruction(Building.java:2521)
at org.millenaire.common.building.Building.updateTownHall(Building.java:6452)
at org.millenaire.common.building.Building.updateBuildingServer(Building.java:5873)
at org.millenaire.common.MillWorld.updateWorldServer(MillWorld.java:1066)
at org.millenaire.common.forge.ServerTickHandler.tickStart(ServerTickHandler.java:18)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_3312_ServerTickHandler_tickStart_ServerTickEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
... 2 more

to add to this in the log it says

[13:04:36] [Server thread/WARN]: ****************************************
[13:04:36] [Server thread/WARN]: * There is an attempt to load a chunk (39,-47) in dimension -88 that is already being loaded. This will cause weird chunk breakages.
[13:04:36] [Server thread/WARN]: * at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:154)
[13:04:36] [Server thread/WARN]: * at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
[13:04:36] [Server thread/WARN]: * at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[13:04:36] [Server thread/WARN]: * at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[13:04:36] [Server thread/WARN]: * at net.minecraft.world.World.func_72964_e(World.java:419)
[13:04:36] [Server thread/WARN]: * at net.minecraft.world.World.func_147438_o(World.java:2536)...
[13:04:36] [Server thread/WARN]: ****************************************

This is the dimension ID for Gadomancy
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11356565/7bdfc21e-00d3-44d2-ad80-4f4c8e13a8ca)

### The Reality

this only happens after REJOINING a world, in which the chat and log are spammed every second

### Your Proposal

this seems like a gadomancy problem as i've never seen this anywhere else

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
not gadomancy.

**Comment by Glease** [comment]
Actually, it's indeed gadomancy and endlessid. Still, we don't make fixes for unsupported mods. Either find someone to code a fix into gadomancy and we will merge it (*), find someone to make a compat mod, or get rid of one of the mods.

*: under the condition that the fix to gadomancy does not make the code inefficient, difficult to read or any other way that make maintaining it harder.

**Comment by brandyyn** [comment]
sure endlessids isn’t supported but gadomancy is?

**Comment by Glease** [comment]
gadomancy is only supported when you stay within the gtnh. we don't fix issues caused by adding custom mods.
