### ISSUE TITLE
Game won't start and I am dumb

### ISSUE THREAD

**Issue by Schoology-Assignment** [GTNewHorizons/GT-New-Horizons-Modpack#14615]
### Your Pack Version

2.1.1.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I just press play for the first time and when it was starting up it said it couldn't get anymore additional files. Windows 11, Curse

### Crash Report

[12:18:13] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[12:18:13] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[12:18:13] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[12:18:13] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[12:18:13] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\schu.nich396\curseforge\minecraft\Install\runtime\jre-legacy\windows-x64\jre-legacy
[12:18:13] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from +unimixins-all-1.7.10-0.1.11.jar
[12:18:13] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:18:13] [main/WARN]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:18:13] [main/INFO]: Loading tweaker fastcraft.Tweaker from fastcraft-1.25.jar
[12:18:13] [main/WARN]: The coremod lumien.hardcoredarkness.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:18:13] [main/WARN]: The coremod net.glease.healer.Healer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:18:13] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:18:13] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[12:18:13] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/schu.nich396/curseforge/minecraft/Instances/GT%20New%20Horizons/mods/+unimixins-all-1.7.10-0.1.11.jar Service=LaunchWrapper Env=CLIENT
[12:18:13] [main/DEBUG]: Instantiating coremod class AllCore
[12:18:14] [main/INFO]: MixinBootstrap Initializing...
[12:18:14] [main/INFO]: Compatibility level set to JAVA_8
[12:18:14] [main/INFO]: Initializing GasStationCore
[12:18:14] [main/INFO]: Initializing GTNHMixins Core
[12:18:14] [main/DEBUG]: The coremod io.github.legacymoddingmc.unimixins.all.AllCore requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
[12:18:14] [main/INFO]: Instantiating AllCore
[12:18:14] [main/INFO]: Instantiating CompatCore
[12:18:14] [main/INFO]: Instantiating MixinExtrasCore
[12:18:14] [main/DEBUG]: Enqueued coremod AllCore
[12:18:14] [main/INFO]: Loading tweak class name fastcraft.Tweaker
[12:18:14] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[12:18:14] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:18:14] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:18:14] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:18:14] [main/DEBUG]: Injecting coremod FMLCorePlugin {cpw.mods.fml.relauncher.FMLCorePlugin} class transformers
[12:18:14] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.MarkerTransformer
[12:18:14] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.SideTransformer
[12:18:14] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
[12:18:14] [main/DEBUG]: Injection complete
[12:18:14] [main/DEBUG]: Running coremod plugin for FMLCorePlugin {cpw.mods.fml.relauncher.FMLCorePlugin}
[12:18:14] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[12:18:14] [main/DEBUG]: Read 527 binary patches
[12:18:15] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[12:18:15] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[12:18:15] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[12:18:15] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:18:15] [main/DEBUG]: Injecting coremod FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin} class transformers
[12:18:15] [main/TRACE]: Registering transformer net.minecraftforge.classloading.FluidIdTransformer
[12:18:15] [main/DEBUG]: Injection complete
[12:18:15] [main/DEBUG]: Running coremod plugin for FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin}
[12:18:15] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[12:18:15] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[12:18:15] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:18:15] [main/DEBUG]: Injecting coremod CoreMod {aroma1997.core.coremod.CoreMod} class transformers
[12:18:15] [main/DEBUG]: Injection complete
[12:18:15] [main/DEBUG]: Running coremod plugin for CoreMod {aroma1997.core.coremod.CoreMod}
[12:18:15] [main/DEBUG]: Running coremod plugin CoreMod
[12:18:15] [main/INFO]: Finished data injection.
[12:18:15] [main/INFO]: Finished data injection.
[12:18:15] [main/DEBUG]: Coremod plugin class CoreMod run successfully
[12:18:15] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:18:15] [main/DEBUG]: Injecting coremod DreamCoreMod {com.dreammaster.coremod.DreamCoreMod} class transformers
[12:18:15] [main/TRACE]: Registering transformer com.dreammaster.coremod.DreamClassTransformer
[12:18:15] [main/DEBUG]: Injection complete
[12:18:15] [main/DEBUG]: Running coremod plugin for DreamCoreMod {com.dreammaster.coremod.DreamCoreMod}
[12:18:15] [main/DEBUG]: Running coremod plugin DreamCoreMod
[12:18:15] [main/INFO]: Found 220 dependencies. 0 are disabled, 0 are found.
[12:18:15] [main/INFO]: 218 dependencies to download.
[12:18:15] [Thread-5/INFO]: Downloading http://downloads.gtnewhorizons.com/Mods_for_Twitch/adventurebackpack-1.0.14-GTNH.jar to mods/adventurebackpack-1.0.14-GTNH.jar
[12:18:20] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Launch cancelled by user
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:137) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Launch cancelled by user
	at com.dreammaster.coremod.DepLoader.call(DepLoader.java:177) ~[DepLoader.class:?]
	at com.dreammaster.coremod.DepLoader.call(DepLoader.java:30) ~[DepLoader.class:?]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:133) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	... 2 more
[12:18:20] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[12:18:20] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[12:18:20] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[12:18:20] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
[12:18:20] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:971)
[12:18:20] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[12:18:20] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dr-Nye** [comment]
please give relevant information like OS launcher etc.

**Comment by bombcar** [comment]
[12:18:15] [main/INFO]: 218 dependencies to download.
[12:18:15] [Thread-5/INFO]: Downloading http://downloads.gtnewhorizons.com/Mods_for_Twitch/adventurebackpack-1.0.14-GTNH.jar to mods/adventurebackpack-1.0.14-GTNH.jar

This looks very bad - and the version is old. Did you install from one of the recommended methods or try to use curse?

https://wiki.gtnewhorizons.com/wiki/Installing_and_Migrating

**Comment by Nikorasuwastaken** [comment]
> [12:18:15] [main/INFO]: 218 dependencies to download. [12:18:15] [Thread-5/INFO]: Downloading http://downloads.gtnewhorizons.com/Mods_for_Twitch/adventurebackpack-1.0.14-GTNH.jar to mods/adventurebackpack-1.0.14-GTNH.jar
> 
> This looks very bad - and the version is old. Did you install from one of the recommended methods or try to use curse?
> 
> https://wiki.gtnewhorizons.com/wiki/Installing_and_Migrating

So I shouldn't use curse to start the game, that makes more sense thank you.
