### ISSUE TITLE
BetterCrash Crash at launch

### ISSUE THREAD

**Issue by Hikari1nVoid** [GTNewHorizons/GT-New-Horizons-Modpack#14702]
### Your GTNH Discord Username

Hiakri1nVoid#9527

### Your Pack Version

nightly-173

### Your Server

zeta

### Java Version

Java 20

### Type of Server

None

### Your Actions

Launch client with Java 20.

### Crash Report

[14:55:48] [main/INFO] [mixin]: Instancing error handler class io.github.legacymoddingmc.unimixins.compat.MixinErrorHandler
[14:55:48] [main/FATAL] [mixin]: Mixin apply for mod bettercrashes failed mixins.bettercrashes.early.json:MinecraftMixin from mod bettercrashes -> net.minecraft.client.Minecraft: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method startGame in mixins.bettercrashes.early.json:MinecraftMixin from mod bettercrashes was not located in the target class net.minecraft.client.Minecraft. No refMap loaded.
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method startGame in mixins.bettercrashes.early.json:MinecraftMixin from mod bettercrashes was not located in the target class net.minecraft.client.Minecraft. No refMap loaded.
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[-unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412) ~[-unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340) ~[-unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[-unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[-unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[-unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[-unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[-unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[-unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [-unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [-unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [-unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [-unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:367) [lwjgl3ify-1.5.2-forgePatches.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:198) [lwjgl3ify-1.5.2-forgePatches.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) [?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:72) [Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165) [lwjgl3ify-1.5.2-forgePatches.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [lwjgl3ify-1.5.2-forgePatches.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at net.minecraft.client.main.Main.main(SourceFile:72)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:224)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 11 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:367)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:198)
	... 13 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.bettercrashes.early.json:MinecraftMixin from mod bettercrashes] from phase [DEFAULT] in config [mixins.bettercrashes.early.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method startGame in mixins.bettercrashes.early.json:MinecraftMixin from mod bettercrashes was not located in the target class net.minecraft.client.Minecraft. No refMap loaded.
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 18 more
[14:55:48] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165) [lwjgl3ify-1.5.2-forgePatches.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [lwjgl3ify-1.5.2-forgePatches.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:224) ~[lwjgl3ify-1.5.2-forgePatches.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	... 9 more
... (73 lines left)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alexdoru** [comment]
for some reason it didn't include the refmap when compiling, use the older version of better crashes
