### ISSUE TITLE
NEI data dump of items returns blank CSV, tracebacks

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#14711]
### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

I wanted to export Items from NEI via datadump, and look at the CSV

### The Reality

I got lots of tracebacks in the logs like this:

`[10:12:30] [Client thread/ERROR] [NotEnoughItems]: Error dumping Items mode: 0
java.lang.IndexOutOfBoundsException: Index -1000 out of bounds for length 6
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.base/java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at gtPlusPlus.core.item.base.BaseEuItem.func_77613_e(BaseEuItem.java:124) ~[BaseEuItem.class:?]
	at com.enderio.core.common.transform.EnderCoreMethods.getItemRarity(EnderCoreMethods.java:43) ~[EnderCoreMethods.class:?]
	at net.minecraft.item.ItemStack.func_77953_t(Unknown Source) ~[add.class:?]
	at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:155) ~[GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameShort(GuiContainerManager.java:220) ~[GuiContainerManager.class:?]
	at codechicken.nei.api.ItemInfo$1.dump(ItemInfo.java:193) ~[ItemInfo$1.class:?]
	at codechicken.nei.api.ItemInfo$1.dump(ItemInfo.java:181) ~[ItemInfo$1.class:?]
	at codechicken.nei.config.RegistryDumper.dump(RegistryDumper.java:19) ~[RegistryDumper.class:?]
	at codechicken.nei.config.DataDumper.dumpTo(DataDumper.java:68) ~[DataDumper.class:?]
	at codechicken.nei.config.DataDumper.dumpFile(DataDumper.java:41) [DataDumper.class:?]
	at codechicken.nei.config.DataDumper.mouseClicked(DataDumper.java:138) [DataDumper.class:?]
	at codechicken.nei.config.GuiOptionList$OptionScrollSlot.slotClicked(GuiOptionList.java:129) [GuiOptionList$OptionScrollSlot.class:?]
	at codechicken.core.gui.GuiScrollSlot.slotUp(GuiScrollSlot.java:122) [GuiScrollSlot.class:?]
	at codechicken.core.gui.GuiScrollPane.mouseMovedOrUp(GuiScrollPane.java:143) [GuiScrollPane.class:?]
	at codechicken.core.gui.GuiScreenWidget.func_146286_b(GuiScreenWidget.java:80) [GuiScreenWidget.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306) [bdw.class:?]
	at codechicken.core.gui.GuiScreenWidget.func_146274_d(GuiScreenWidget.java:103) [GuiScreenWidget.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) [bdw.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5106) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165) [launchwrapper-1.15.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [launchwrapper-1.15.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

and a empty (null length) CSV.

### Your Proposal

not traceback?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12909903/fml-client-latest.log)
