### ISSUE TITLE
betterquesting can get defeated by Mac files in its quest folder

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#14806]
### Your GTNH Discord Username

bombcar

### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

Tried to load my world

somehow a weird file had appeared, and I got a lockup (this would loop forever apparently)

there were 32,852 of these files, apparently it creates one for each file it can't read, and it can't read .DS_Store, and then can't read the malformed file, etc etc.,

The oldest was 
[malformed_.DS_Store0.json](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13221305/malformed_.DS_Store0.json)

and it tried to read that one each time, I guess, and the error file created also caused it, until eventually load times were so long I noticed because it never loaded.

Root cause - copying in BetterQuesting directory from GitHub on a Mac brings along "Mac junk" like .DS_Store 

However, BQ shouldn't try to read non-json files, and it shouldn't output errors about malformed json files as malformed json files it tries to then read next load.

Seriously `malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_.DS_Store3.json1.json1.json0.json0.json1.json0.json0.json0.json0.json0.json0.json0.json0.json0.json` is of no help to nobody :) 

### Crash Report

[15:49:30] [pool-11-thread-1/ERROR] [betterquesting]: Creating backup at: /Applications/MultiMC.app/Data/instances/GT_New_Horizons_2.4.1_Java_17-20/.minecraft/config/betterquesting/DefaultQuests/Quests/malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_.DS_Store0.json1.json1.json2.json2.json1.json1.json0.json
[15:49:30] [pool-11-thread-1/ERROR] [betterquesting]: An error occured while loading JSON from file:
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 146
	at com.google.gson.Gson.assertFullConsumption(Gson.java:779) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:742) ~[Gson.class:?]
	at betterquesting.api.utils.JsonHelper.lambda$ReadFromFile$0(JsonHelper.java:175) ~[JsonHelper.class:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 146
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:531) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:414) ~[JsonReader.class:?]
	at com.google.gson.Gson.assertFullConsumption(Gson.java:775) ~[Gson.class:?]
	... 6 more
[15:49:30] [pool-11-thread-1/ERROR] [betterquesting]: Creating backup at: /Applications/MultiMC.app/Data/instances/GT_New_Horizons_2.4.1_Java_17-20/.minecraft/config/betterquesting/DefaultQuests/Quests/malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_malformed_.DS_Store0.json2.json0.json0.json0.json0.json0.json0.json0.json0.json0.json2.json0.json0.json

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13221330/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
workaround for Mac

`find . -name ".DS_Store" -depth -exec rm {} \;` from the BQ directory after clearing out all the bad json malformities.

**Comment by bombcar** [comment]
Suggestions:

1. BetterQuesting should ignore non .json files (though it apparently uses at least one .txt)
2. If it finds a malformed json file it should move it OUTSIDE of where it will see it next time
3. maybe it should just crash hard on the first malformed json

**Comment by Mobius0526** [comment]
I'm also having this kind of issue
It's taking longer and longer for me to enter the world
Once, I waited for 30 minutes and didn't go in
The fml-client-1 .log file size reaches 400MB，Far beyond the normal size。
There are a lot of files like *.json1.json1.json2.json2.json1.json1.json0.json in config/betterquesting/DefaultQuests/Quests
The volume of this folder is close to 2g
