### ISSUE TITLE
Using a NEI "virtual" stack of fluid cells on a fluid filter on a nonuple pipe crashes out

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#14993]
### Your GTNH Discord Username

bombcar

### Your Pack Version

2.4.2-pre-mixed

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

Had an empty nonuple pipe run into an iron Railcraft tank. Added a fluid filter to it, went to add a filter type by trying to draw from NEI (a virtual stack) and instead got an error crashing out to the multiplayer screen (lol)

### Crash Report

`[14:57:11] [Client thread/INFO]: [CHAT] Connected
[14:57:13] [Client thread/INFO]: [CHAT] Disconnected
[15:01:27] [Client thread/INFO]: [CHAT] Connected
[15:01:28] [Client thread/INFO]: [CHAT] Input disabled
[15:02:09] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.IndexOutOfBoundsException: readerIndex(12) + length(2) exceeds writerIndex(12): UnpooledHeapByteBuf(ridx: 12, widx: 12, cap: 12/14)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1160) ~[AbstractByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:581) ~[AbstractByteBuf.class:?]
	at net.minecraft.network.PacketBuffer.readShort(SourceFile:506) ~[et.class:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(SourceFile:85) ~[et.class:?]
	at com.gtnewhorizons.modularui.common.internal.network.NetworkUtils.readItemStack(NetworkUtils.java:127) ~[NetworkUtils.class:?]
	at com.gtnewhorizons.modularui.common.widget.SlotWidget.readOnServer(SlotWidget.java:321) ~[SlotWidget.class:?]
	at com.gtnewhorizons.modularui.api.screen.ModularUIContext.readClientPacket(ModularUIContext.java:383) ~[ModularUIContext.class:?]
	at com.gtnewhorizons.modularui.common.internal.network.CWidgetUpdate.executeServer(CWidgetUpdate.java:43) ~[CWidgetUpdate.class:?]
	at com.gtnewhorizons.modularui.common.internal.network.NetworkHandler.lambda$static$1(NetworkHandler.java:55) ~[NetworkHandler.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) [bsx.class:?]
	at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
	at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[15:02:09] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel modularui
java.lang.IndexOutOfBoundsException: readerIndex(12) + length(2) exceeds writerIndex(12): UnpooledHeapByteBuf(ridx: 12, widx: 12, cap: 12/14)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1160) ~[AbstractByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:581) ~[AbstractByteBuf.class:?]
	at net.minecraft.network.PacketBuffer.readShort(SourceFile:506) ~[et.class:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(SourceFile:85) ~[et.class:?]
	at com.gtnewhorizons.modularui.common.internal.network.NetworkUtils.readItemStack(NetworkUtils.java:127) ~[NetworkUtils.class:?]
	at com.gtnewhorizons.modularui.common.widget.SlotWidget.readOnServer(SlotWidget.java:321) ~[SlotWidget.class:?]
	at com.gtnewhorizons.modularui.api.screen.ModularUIContext.readClientPacket(ModularUIContext.java:383) ~[ModularUIContext.class:?]
	at com.gtnewhorizons.modularui.common.internal.network.CWidgetUpdate.executeServer(CWidgetUpdate.java:43) ~[CWidgetUpdate.class:?]
	at com.gtnewhorizons.modularui.common.internal.network.NetworkHandler.lambda$static$1(NetworkHandler.java:55) ~[NetworkHandler.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) [bsx.class:?]
	at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
	at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[15:02:09] [Netty Client IO #1/INFO] [THAUMCRAFT]: Restoring client configs.`

https://paste.ee/p/TDQom

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
Interesting, on reload it HAD the fluid set:

<img width="379" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/533931/4f72e905-c359-459b-91ef-836825ee500b">

**Comment by bombcar** [comment]
Reproducible:

<img width="582" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/533931/f420beba-a22e-4bf0-9918-f95e9eb0e841">

At least _sweet dreams_ starts playing

**Comment by bombcar** [comment]
If I bookmark the _fluid_ (so I get a 1L of it in bookmarks, NEI hides the fluids by default) and apply that, it works fine:

<img width="533" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/533931/ac9fd7bc-4fbf-4b97-96d2-4877ca45d5e3">
