### ISSUE TITLE
JustEnoughCalculation doesn't work with 2.5.0

### ISSUE THREAD

**Issue by maskota** [GTNewHorizons/GT-New-Horizons-Modpack#15116]
### Your GTNH Discord Username

maskot.

### Your Pack Version

2.5.0

### Your Server

Private

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Trying to add GT recipe to JEC with shif+click.

### The Reality

On NEI recipe there isn't a 'plus' sign to add it to calculator.

### Your Proposal

The problem is with new version of codechicken. On 2.4.0 it was working.
The stack trace of the error:

`[14:05:57] [Client thread/INFO]: [CHAT] Calculator: Sorry, the recipe cannot be transferred to the calculator. It would be great if you could provide log files to help us fix it
[14:05:57] [Client thread/ERROR] [jecalculation]: Exception when handling recipe: codechicken.nei.recipe.ShapedRecipeHandler
[14:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[14:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at me.towdium.jecalculation.nei.adapter.GregTech.handleRecipe(GregTech.java:65)
[14:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at me.towdium.jecalculation.nei.Adapter.handleRecipe(Adapter.java:85)
[14:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at me.towdium.jecalculation.nei.JecaOverlayHandler.convertRecipe(JecaOverlayHandler.java:47)
[14:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at me.towdium.jecalculation.nei.JecaOverlayHandler.overlayRecipe(JecaOverlayHandler.java:34)
[14:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.GuiRecipe.overlayRecipe(GuiRecipe.java:562)
[14:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.GuiRecipe.func_146284_a(GuiRecipe.java:490)
[14:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
[14:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:326)
[14:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.GuiRecipe.func_73864_a(GuiRecipe.java:439)`

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by maskota** [comment]
Just found the duplicate.
