### ISSUE TITLE
Traceback on load around spongepowered Error at instruction 436

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#15147]
### Your GTNH Discord Username

bombcar

### Your Pack Version

2.5.0-post-nightly

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Not traceback during ASM/mixin loading

### The Reality

```
[09:34:05] [Client thread/INFO] [ProgressBarSpeedup]: TRANSFORMING cpw.mods.fml.client.FMLClientHandler
[09:34:05] [Client thread/INFO] [ProgressBarSpeedup]: Speeding up stripSpecialChars
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: org.spongepowered.asm.lib.tree.analysis.AnalyzerException: Error at instruction 436: Cannot invoke "org.spongepowered.asm.mixin.transformer.ClassInfo.hasSuperClass(org.spongepowered.asm.mixin.transformer.ClassInfo)" because the return value of "org.spongepowered.asm.mixin.transformer.ClassInfo.forType(org.spongepowered.asm.lib.Type, org.spongepowered.asm.mixin.transformer.ClassInfo$TypeLookup)" is null
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.lib.tree.analysis.Analyzer.analyze(Analyzer.java:273)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.util.Locals.generateLocalVariableTable(Locals.java:859)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.util.Locals.getGeneratedLocalVariableTable(Locals.java:828)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:782)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:752)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:529)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:336)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.initLocals(LocalVariableDiscriminator.java:154)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.<init>(LocalVariableDiscriminator.java:148)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.llamalad7.mixinextras.versions.MixinVersionImpl_v0_8_4.makeLvtContext(MixinVersionImpl_v0_8_4.java:19)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.llamalad7.mixinextras.utils.CompatibilityHelper.makeLvtContext(CompatibilityHelper.java:25)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.llamalad7.mixinextras.sugar.impl.LocalSugarApplicator.getOrCreateLocalContext(LocalSugarApplicator.java:129)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.llamalad7.mixinextras.sugar.impl.LocalSugarApplicator.validate(LocalSugarApplicator.java:40)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.llamalad7.mixinextras.sugar.impl.SugarInjector.validateApplicators(SugarInjector.java:171)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.llamalad7.mixinextras.sugar.impl.SugarInjector.prepareSugar(SugarInjector.java:153)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperImpl.prepare(SugarWrapperImpl.java:67)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.prepare(WrapperInjectionInfo.java:57)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:367)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:198)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at ReflectorMethod.getMethods(ReflectorMethod.java:168)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at ReflectorMethod.getTargetMethod(ReflectorMethod.java:68)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at ReflectorMethod.<init>(ReflectorMethod.java:48)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at ReflectorMethod.<init>(ReflectorMethod.java:25)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Reflector.<clinit>(Reflector.java:105)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at ReflectorForge.putLaunchBlackboard(ReflectorForge.java:50)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Config.initGameSettings(Config.java:194)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.client.settings.GameSettings.<init>(GameSettings.java:389)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:378)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3099)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: Caused by: java.lang.NullPointerException: Cannot invoke "org.spongepowered.asm.mixin.transformer.ClassInfo.hasSuperClass(org.spongepowered.asm.mixin.transformer.ClassInfo)" because the return value of "org.spongepowered.asm.mixin.transformer.ClassInfo.forType(org.spongepowered.asm.lib.Type, org.spongepowered.asm.mixin.transformer.ClassInfo$TypeLookup)" is null
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.util.asm.MixinVerifier.isAssignableFrom(MixinVerifier.java:104)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.lib.tree.analysis.SimpleVerifier.isSubTypeOf(SimpleVerifier.java:212)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.lib.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:400)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.lib.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:44)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.lib.tree.analysis.Frame.executeInvokeInsn(Frame.java:682)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.lib.tree.analysis.Frame.execute(Frame.java:609)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at org.spongepowered.asm.lib.tree.analysis.Analyzer.analyze(Analyzer.java:165)
[09:34:06] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	... 54 more
[09:34:06] [Client thread/INFO] [lwjgl3ify]: Dynamicized enum ahn=net.minecraft.world.EnumSkyBlock
[09:34:06] [Client thread/INFO] [HardcoreDarkness]: Found EntityRenderer Class: net/minecraft/client/renderer/EntityRenderer
[09:34:06] [Client thread/INFO] [HardcoreDarkness]:  - Patched Nightvision Potion
```

### Your Proposal

Something (not sure what) is trying to ASM (or mixin) and is failing as above.

it is NOT the progress bar speed up (turning that off in hodgebodge gets the same error) with 

```
[09:40:58] [Client thread/INFO] [lwjgl3ify]: Dynamicized enum ahk=net.minecraft.world.WorldSettings$GameType
[09:40:58] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: org.spongepowered.asm.lib.tree.analysis.AnalyzerException: Error at instruction 436: Cannot invoke "org.spongepowered.asm.mixin.transformer.ClassInfo.hasSuperClass(org.spongepowered.asm.mixin.transformer.ClassInfo)" because the return value of "org.spongepowered.asm.mixin.transformer.ClassInfo.forType(org.spongepowered.asm.lib.Type, org.spongepowered.asm.mixin.transformer.ClassInfo$TypeLookup)" is null
...
[09:40:58] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	... 54 more
[09:40:58] [Client thread/INFO] [lwjgl3ify]: Dynamicized enum ahn=net.minecraft.world.EnumSkyBlock
```

so maybe it's in lwjg3ify

Java 21 on Mac

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Also occurs on J17
