### ISSUE TITLE
Server Connection Lost on "/help 3" command (/toolxp)

### ISSUE THREAD

**Issue by Novie53** [GTNewHorizons/GT-New-Horizons-Modpack#15145]
### Your GTNH Discord Username

Quintus#6363

### Your Pack Version

2.5.0

### Your Server

Private server

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

I am disconnected("Connection Lost") from my private server when I use the "/help 3" chat command. (Has to be OP on the server)

https://imgur.com/eNuaAnA

[Error 1](https://pastebin.com/Z1anAbQW)

[Error 2](https://pastebin.com/JpUydfeK)

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Novie53** [comment]
a NullPointerException is also thrown when I use "help 5" in the server console

`[15:50:11] [Server thread/ERROR]: Couldn't process command: 'help 5'
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769) ~[?:?]
	at java.base/java.util.regex.Matcher.reset(Matcher.java:415) ~[?:?]
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:252) ~[?:?]
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134) ~[?:?]
	at net.minecraft.util.ChatComponentTranslation.func_150269_b(SourceFile:61) ~[fr.class:?]
	at net.minecraft.util.ChatComponentTranslation.func_150270_g(SourceFile:48) ~[fr.class:?]
	at net.minecraft.util.ChatComponentTranslation.iterator(SourceFile:147) ~[fr.class:?]
	at net.minecraft.util.ChatComponentStyle.func_150260_c(SourceFile:63) ~[fe.class:?]
	at net.minecraft.server.MinecraftServer.func_145747_a(MinecraftServer.java:849) ~[MinecraftServer.class:?]
	at net.minecraft.command.CommandHelp.func_71515_b(SourceFile:72) ~[au.class:?]
	at serverutils.ranks.CommandOverride.func_71515_b(CommandOverride.java:70) ~[CommandOverride.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:370) [lt.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]`
