### ISSUE TITLE
Internal sever error Battlegear2 1.3.0

### ISSUE THREAD

**Issue by simbiant** [GTNewHorizons/GT-New-Horizons-Modpack#15226]
### Your GTNH Discord Username

SimbiAnT29#7106

### Your Pack Version

2.5.1

### Your Server

private server ultra mine

### Java Version

Java 8

### Type of Server

None

### Your Actions

Click right mouse button on block while in dual wielding

### Crash Report

Server kick me with internal error

```
java.lang.NullPointerException
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:637)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(C08PacketPlayerBlockPlacement.java:65)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(C08PacketPlayerBlockPlacement.java:110)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:231)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:567)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:444)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:719)
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
please post the full crash report, or latest.log

**Comment by simbiant** [comment]
Looks like I choose wrong category. I does the full log 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24406976/9530150c-6d74-4320-a0d9-c2eb4e5f7c32)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24406976/c9579889-fe9b-4343-9455-c05810678b36)

It just kicks player from server on every right click on block

**Comment by simbiant** [comment]
If you insist I can send full log from the very start of server

**Comment by Ethryan** [comment]
Do that, the error shown tells us nothing about the cause.

**Comment by simbiant** [comment]
[latest.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13779876/latest.zip)

**Comment by Caedis** [comment]
Ultramine is not supported. We only support pure forge servers (and thermos, but only just cause of the official servers)

**Comment by simbiant** [comment]
Ok, but on 1.2.0 it works perfectly, so I think someone broke it. Still think it's problem of the mod, but fine. I'll play on Battlegear2 1.2.0
