### ISSUE TITLE
java.lang.NoClassDefFoundError: gregtech/api/enums/Mods with gtPlusPlus

### ISSUE THREAD

**Issue by UberAffe** [GTNewHorizons/GT-New-Horizons-Modpack#15404]
### Your GTNH Discord Username

uberaffe

### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

This crash is happening with a new server that is running in BisectHosting. I downloaded the latest java17 server.zip from technic, unzipped and uploaded everything to the host, then changed the forgePatches.jar name to customjava17.jar so that it would run with java 17.

I have tried replacing GT++,  appliedenergistics, and bartworks mods with fresh downloads incase something was corrupted but that didn't help.

Any help would be greatly appreciated.

### Crash Report

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 1/24/24, 1:07 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: gregtech/api/enums/Mods
	at gtPlusPlus.preloader.asm.Preloader_DummyContainer.<init>(Preloader_DummyContainer.java:32)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at cpw.mods.fml.common.Loader.identifyMods(Loader.java:340)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:489)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: gregtech.api.enums.Mods
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:224)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 15 more
Caused by: java.lang.NullPointerException: Class gregtech.api.enums.Mods|gregtech.api.enums.Mods is null after running transformers
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:203)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 4.15.0-213-generic
	Java Version: 17.0.8, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 380630128 bytes (362 MB) / 536870912 bytes (512 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 2 total; -Xmx10240M -Xms512M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 13 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
		FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
		Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
		appliedenergistics2-core{rv3-beta-292-GTNH} [Applied Energistics 2 Core] (minecraft.jar) 
		CodeChickenCore{1.1.13} [CodeChicken Core] (minecraft.jar) 
		CropLoadCoreASM{0.0.2} [CroploadCore ASM Core] (minecraft.jar) 
		NotEnoughItems{2.4.13-GTNH} [NotEnoughItems] (NotEnoughItems-2.4.13-GTNH.jar) 
		OpenComputers|Core{@VERSION@} [OpenComputers (Core)] (minecraft.jar) 
		MobiusCore{1.3.9-mapless} [MobiusCore] (minecraft.jar) 
		PlayerAPI{1.4.3} [Player API] (minecraft.jar) 
		ThE-core{1.0.0.1} [Thaumic Energistics Core] (minecraft.jar) 
		OpenModsCore{0.10.6} [OpenModsCore] (minecraft.jar) 
		<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
Technic does not provide java 17 version. Also this seems like some corruption happened, try redownloading the pack.

**Comment by UberAffe** [comment]
Technicpack linked to https://downloads.gtnewhorizons.com/ServerPacks/ which is where I downloaded it from.

I downloaded a fresh copy and slowly replaced every file, trying to launch the server between each. This issue is still occurring, its possible that the download/unzip corrupted something both times but there was no service issue that I could notice during the download.

I noticed that BisecHosting is using Java 17.0.8 while the serverpack shows 17-21, is that a likely cause?

**Comment by UberAffe** [comment]
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14042902/fml-server-latest.log)

**Comment by UberAffe** [comment]
Thanks to Lyft in Discord, it looks like the issue is that I didn't have the jvm arguments. Unfortunately BisectHosting doesn't allow for those arguments, so I think the java 17 version out of the question for me.

I tried a fresh install of the java 8 version and that does work with BisectHosting. So now this is just information for anyone trying to use BisectHosting.
