### ISSUE TITLE
Large Essentia Generator randomly turns off because of a "crash"

### ISSUE THREAD

**Issue by the-bukkit** [GTNewHorizons/GT-New-Horizons-Modpack#15508]
### Your GTNH Discord Username

the_bukkit

### Your Pack Version

2.5.1

### Your Server

Private server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

I have built a Large Essentia Generator out of:
- **EV Dynamo Hatch [Buffered]** but I had the issue with a **HV Dynamo Hatch [Buffered]** as well
- **Novice Essentia Diffusion Cells**
- **Input Hatch (LV)**
- **Maintenance Hatch** with Duct Tape used on it
- **Essentia Input Hatch**

It has no upgrade installed and I am feeding it **Herba** and **Praecantatio** essentia.

I expect it to run without turning itself off.

### The Reality

It seems to turn itself off when:
- Seemingly after a server restart (I have my server setup to do a daily restart)
- Sometimes after turning it on and leaving the interface
- Just at random

![Screenshot_20240209_150503](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/23724545/d77d4092-2cb5-4dd9-b781-aca06f112229)

I noticed this error in the server console every time it happens:

> [05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: java.util.ConcurrentModificationException
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:778)
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at goodgenerator.blocks.tileEntity.LargeEssentiaGenerator.setEssentiaToEUVoltageAndAmp(LargeEssentiaGenerator.java:428)
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at goodgenerator.blocks.tileEntity.LargeEssentiaGenerator.checkProcessing_EM(LargeEssentiaGenerator.java:229)
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at com.github.technus.tectech.thing.metaTileEntity.multi.base.GT_MetaTileEntity_MultiblockBase_EM.checkProcessing(GT_MetaTileEntity_MultiblockBase_EM.java:948)
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.checkRecipe(GT_MetaTileEntity_MultiBlockBase.java:492)
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at com.github.technus.tectech.thing.metaTileEntity.multi.base.GT_MetaTileEntity_MultiblockBase_EM.onPostTick(GT_MetaTileEntity_MultiblockBase_EM.java:1128)
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:547)
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[05:02:31] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

### Your Proposal

Fix the bug causing it to turn off or a clearer error message if caused by me

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by the-bukkit** [comment]
In case someone has the same problem, I've discovered a sort of workaround.

By attaching a Machine Controller Cover and feeding it a redstone signal, like from a lever or block of redstone, it seems to instantly turn itself on again after it "crashes".
