### ISSUE TITLE
Chemical Plant Recipe not found

### ISSUE THREAD

**Issue by zTotto** [GTNewHorizons/GT-New-Horizons-Modpack#15574]
### Your GTNH Discord Username

totto.

### Your Pack Version

2.5.0 (i'm using a more recent gregtech mod version from your repo)

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Trying to look up the recipe for ExxonMobil Chemical plant works correctly and shows me the recipe.

### The Reality

The recipe is shown but an error is displayed in chat:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49115537/8cd7ebeb-277a-49bc-950a-a86032cbd9f5)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49115537/1d7577d7-8b76-4c32-adee-16bf8753baa0)

I'm using this version of gregtech:
https://github.com/GTNewHorizons/GT5-Unofficial/commit/467ed303919c45483b4db2a4895fdeb580aadd20

### Your Proposal

Show the recipe without the error

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
please post your logs from the log folder. like fmlclientlatest.

**Comment by chochem** [comment]
though if you just updated one mod manually you probably have dependency issues. you shouldnt do that.

**Comment by zTotto** [comment]
Oh yeah i totally forgot to post the log (i already had it open lol)

[19:39:51] [ForkJoinPool-1-worker-15/ERROR] [NotEnoughItems/]: Error while looking up crafting recipe
[19:39:51] [ForkJoinPool-1-worker-15/ERROR] [NotEnoughItems/]: outputId: item
[19:39:51] [ForkJoinPool-1-worker-15/ERROR] [NotEnoughItems/]: results: [1xgt.blockmachines@998]
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.NoSuchMethodError: 'gregtech.api.logic.ProcessingLogic gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.production.chemplant.GregtechMTE_ChemicalPlant$2.setMaxParallelSupplier(java.util.function.Supplier)'
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.production.chemplant.GregtechMTE_ChemicalPlant.createProcessingLogic(GregtechMTE_ChemicalPlant.java:613)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.<init>(GT_MetaTileEntity_MultiBlockBase.java:168)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_TooltipMultiBlockBase.<init>(GT_MetaTileEntity_TooltipMultiBlockBase.java:25)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_EnhancedMultiBlockBase.<init>(GT_MetaTileEntity_EnhancedMultiBlockBase.java:45)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_ExtendedPowerMultiBlockBase.<init>(GT_MetaTileEntity_ExtendedPowerMultiBlockBase.java:39)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.<init>(GregtechMeta_MultiBlockBase.java:121)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.production.chemplant.GregtechMTE_ChemicalPlant.<init>(GregtechMTE_ChemicalPlant.java:100)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.production.chemplant.GregtechMTE_ChemicalPlant.newMetaEntity(GregtechMTE_ChemicalPlant.java:125)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gregtech.api.metatileentity.CommonMetaTileEntity.createNewMetatileEntity(CommonMetaTileEntity.java:41)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gregtech.api.metatileentity.BaseMetaTileEntity.setInitialValuesAsNBT(BaseMetaTileEntity.java:172)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gregtech.common.blocks.GT_Item_Machines.placeBlockAt(GT_Item_Machines.java:301)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at blockrenderer6343.integration.gregtech.GT_GUI_MultiblocksHandler.placeMultiblock(GT_GUI_MultiblocksHandler.java:187)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at blockrenderer6343.common.GUI_MultiblocksHandler.initializeSceneRenderer(GUI_MultiblocksHandler.java:280)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at blockrenderer6343.integration.gregtech.GT_GUI_MultiblocksHandler.loadNewMultiblock(GT_GUI_MultiblocksHandler.java:104)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at blockrenderer6343.common.GUI_MultiblocksHandler.loadMultiblock(GUI_MultiblocksHandler.java:102)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at blockrenderer6343.integration.nei.GT_NEI_MultiblocksHandler.tryLoadMultiblocks(GT_NEI_MultiblocksHandler.java:147)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at blockrenderer6343.integration.nei.GT_NEI_MultiblocksHandler.loadCraftingRecipes(GT_NEI_MultiblocksHandler.java:102)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:418)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at blockrenderer6343.integration.nei.GT_NEI_MultiblocksHandler.loadCraftingRecipes(GT_NEI_MultiblocksHandler.java:97)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:556)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at codechicken.nei.recipe.GuiCraftingRecipe.lambda$getCraftingHandlers$0(GuiCraftingRecipe.java:69)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at codechicken.nei.recipe.RecipeHandlerQuery.lambda$null$2(RecipeHandlerQuery.java:77)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[19:39:51] [ForkJoinPool-1-worker-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

Just in case i'll update GT++ and i'll update the issue

**Comment by chochem** [comment]
yea that looks very much like a dependency problem. And there is likely going to be more. just updating one mod like this is just not a good idea.

**Comment by zTotto** [comment]
It was a GT++ update problem, my bad thanks!
