### ISSUE TITLE
ProjectRed lamps causing crash

### ISSUE THREAD

**Issue by Hikari1nVoid** [GTNewHorizons/GT-New-Horizons-Modpack#15588]
### Your Pack Version

nightly-353

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Actions

Place a PR invert cyan lamp on ground.
Game freezes with thousands lines of error logs .
seems like mrtjp.projectred.core.renderHalo is unhappy with the light.

### Crash Report

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14393338/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Hikari1nVoid** [comment]
[16:43:46] [Server thread/INFO]: [KurisuMakise_AI: Given [Inverted Cyan Lamp] * 64 to KurisuMakise_AI]
[16:43:46] [Client thread/INFO]: [CHAT] Given [Inverted Cyan Lamp] * 64 to KurisuMakise_AI
[16:43:51] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.RenderWorldLastEvent@1add78cc:
java.lang.NullPointerException: Cannot invoke "mrtjp.core.color.Colors$Color.rgba()" because the return value of "mrtjp.core.color.Colors$.apply(int)" is null
	at RFB-Launch//mrtjp.projectred.core.RenderHalo$.renderHalo(RenderHalo.scala:124) ~[RenderHalo$.class:?]
	at RFB-Launch//mrtjp.projectred.core.RenderHalo$.renderHalo(RenderHalo.scala:109) ~[RenderHalo$.class:?]
	at RFB-Launch//mrtjp.projectred.core.RenderHalo$.onRenderWorldLast(RenderHalo.scala:72) ~[RenderHalo$.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_2142_RenderHalo$_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic) ~[?:?]
	at RFB-Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at RFB-Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at RFB-Launch//net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:261) [ForgeHooksClient.class:?]
	at RFB-Launch//net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1354) [blt.class:?]
	at RFB-Launch//net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011) [blt.class:?]
	at RFB-Launch//net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
	at RFB-Launch//net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:4110) [bao.class:?]
	at RFB-Launch//net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at RFB-System//net.minecraft.launchwrapper.Launch.realLaunch(Launch.java:248) [Launch.class:?]
	at RFB-System//net.minecraft.launchwrapper.Launch.launch(Launch.java:35) [Launch.class:?]
	at RFB-System//net.minecraft.launchwrapper.Launch.main(Launch.java:60) [Launch.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:219) [lwjgl3ify-2.0.0-alpha-7-forgePatches.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at RFB-System//org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at RFB-System//org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at RFB-System//org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at RFB-System//org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[16:43:51] [Client thread/ERROR] [FML]: Index: 40 Listeners:
[16:43:51] [Client thread/ERROR] [FML]: 0: NORMAL
[16:43:51] [Client thread/ERROR] [FML]: 1: ASM: fastcraft.d@7ab7c6e6 a(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 2: ASM: appeng.client.ClientHelper@f0de539 renderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 3: ASM: thaumcraft.client.lib.RenderEventHandler@41a4e99f renderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 4: ASM: thaumcraft.client.fx.ParticleEngine@49a2feb6 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 5: ASM: mcp.mobius.waila.overlay.DecoratorRenderer@1e5bd407 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 6: ASM: chylex.hee.render.OverlayManager@16474d07 onRenderTick(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 7: ASM: vazkii.botania.common.item.ItemCraftingHalo@1fe9d528 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 8: ASM: com.gtnewhorizon.structurelib.ClientProxy$ForgeEventHandler@5fdd15a7 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 9: ASM: gregtech.common.tileentities.debug.GT_MetaTileEntity_AdvDebugStructureWriter$ForgeEventHandler@2054dd78 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 10: ASM: lumien.randomthings.Handler.RTEventHandler@2d8cdf35 renderWorldPost(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 11: ASM: mcp.mobius.opis.events.OpisClientEventHandler@2fe2ac48 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 12: ASM: com.kentington.thaumichorizons.client.lib.RenderEventHandler@4f5c79a0 renderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 13: ASM: codechicken.wirelessredstone.core.WRCoreEventHandler@5043a293 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 14: ASM: codechicken.nei.ClientHandler@2844e1f7 renderLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 15: ASM: net.bdew.ae2stuff.misc.OverlayRenderHandler$@662e8e97 onRenderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 16: ASM: mcp.mobius.waila.overlay.DecoratorRenderer@120bc1b5 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 17: ASM: WayofTime.alchemicalWizardry.client.renderer.RitualDivinerRender@4e413b75 render(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 18: ASM: crazypants.enderio.teleport.TravelController@2078db23 onRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 19: ASM: tuhljin.automagy.lib.events.AutomagyRenderEventHandler@438e0ed6 renderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 20: ASM: vazkii.botania.client.core.handler.LightningHandler@12a061f1 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 21: ASM: vazkii.botania.client.core.handler.BoundTileRenderer@7f884469 onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 22: ASM: vazkii.botania.client.core.handler.SubTileRadiusRenderHandler@3f2b66b9 onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 23: ASM: vazkii.botania.client.core.handler.MultiblockRenderHandler@5823319e onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 24: ASM: vazkii.botania.client.render.world.SkyblockRenderEvents@3565dae8 onRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 25: ASM: li.cil.oc.client.renderer.MFUTargetRenderer$@69ba1e28 onRenderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 26: ASM: li.cil.oc.client.renderer.WirelessNetworkDebugRenderer$@105a71a5 onRenderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 27: ASM: thaumic.tinkerer.client.core.handler.kami.PlacementMirrorPredictionRenderer@2755d597 onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 28: ASM: openblocks.client.SoundEventsManager@37097866 renderEvents(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 29: ASM: openblocks.client.model.ModelCraneBackpack@3f906766 renderFppArm(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 30: ASM: openblocks.client.renderer.entity.EntitySelectionHandler@112f9148 renderEvents(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 31: ASM: flaxbeard.thaumicexploration.event.TXEventHandler@62af0975 renderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 32: ASM: net.dries007.holoInventory.client.Renderer@1f26ddc2 optifineIsAnnoying(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 33: ASM: atomicstryker.infernalmobs.client.RendererBossGlow@601c570d onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 34: ASM: com.bymarcin.openglasses.surface.ClientSurface@842867c renderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 35: ASM: com.github.lunatrius.schematica.client.renderer.RendererSchematicGlobal@129b1b51 onRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 36: ASM: stevesaddons.threading.ThreadSafeHandler@3208d64 renderEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 37: ASM: tmechworks.client.SignalTetherWorldOverlayRenderer@3af4d01 onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 38: ASM: mrtjp.core.world.Messenger$@5e1316db renderMessages(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 39: ASM: mrtjp.projectred.core.libmc.fx.ParticleManagement@1433461c onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 40: ASM: mrtjp.projectred.core.RenderHalo$@4d9c5c45 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 41: ASM: mrtjp.core.fx.FXEngine$@7650c46d onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 42: ASM: com.projecturanus.betterp2p.client.render.RenderHandler@256d13fb renderOverlays(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 43: ASM: mrtjp.relocation.RelocationClientEventHandler$@3edfca0b onRenderWorld(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 44: ASM: makeo.gadomancy.client.effect.EffectHandler@6b6ab674 onRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 45: ASM: makeo.gadomancy.client.events.RenderEventHandler@4ac44132 worldRenderEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 46: ASM: journeymap.client.forge.event.WaypointBeaconHandler@592e5ba5 onRenderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/ERROR] [FML]: 47: ASM: com.muxiu1997.sharewhereiam.event.EventHandler@6e8bb01e handleRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[16:43:51] [Client thread/INFO] [BetterCrashes]: Downloading MCP method mappings to deobfuscate stacktrace

**Comment by Hikari1nVoid** [comment]
Fixed by https://github.com/GTNewHorizons/ProjectRed/pull/32
