### ISSUE TITLE
Game broke midway through loading

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#15824]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.6.0 Beta 1

### Your Server

N/A

### Java Version

Java 17

### Type of Server

None

### Your Expectation

I have previously loaded this game instance on several occasions without problems, so I expected it *not* to glitch out this time.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/65d39c4c-a036-4677-9b43-451bb3365297)
This happened midway through game load. The game then froze and I was forced to kill it with task manager.

See attached log:
[crash-2024-03-25_17.54.15-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14747719/crash-2024-03-25_17.54.15-client.txt)

### Your Proposal

Determine the source of the issue and resolve it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment]
```
java.lang.IllegalArgumentException: newPosition > limit: (4194304 > 3686400)
    at java.nio.Buffer.createPositionException(Buffer.java:341)
    at java.nio.Buffer.position(Buffer.java:316)
    at java.nio.IntBuffer.position(IntBuffer.java:1516)
    at java.nio.IntBuffer.put(IntBuffer.java:1183)
    at net.minecraft.client.renderer.texture.TextureUtil.copyToBufferPos(TextureUtil.java:336)
    at net.minecraft.client.renderer.texture.TextureUtil.uploadTextureSub(TextureUtil.java:186)
    at net.minecraft.client.renderer.texture.TextureUtil.uploadTexture(TextureUtil.java:51)
    at net.minecraft.client.renderer.texture.DynamicTexture.updateDynamicTexture(SourceFile:35)
    at net.minecraft.client.renderer.texture.DynamicTexture.<init>(SourceFile:18)
    at net.malisis.core.renderer.font.MalisisFont.loadTexture(MalisisFont.java:619)
    at net.malisis.core.renderer.font.MalisisFont.<init>(MalisisFont.java:106)
    at net.malisis.core.renderer.font.MalisisFont.<init>(MalisisFont.java:88)
 ```

**Comment by mitchej123** [comment]
Are you running any additional addons?  What resource pack resolution are you using? 16x? 32x? 512x?

**Comment by hallucinogender** [comment]
The only additional mod is Better Foliage. I have updated Thaumic Inventory Scanning to 1.1.4, which is a patch created the other day to fix a crash related to the thaumometer.

The resource pack I am using is UU-Tex, which is 16x.

This issue did not reoccur after I reopened the modpack.
