### ISSUE TITLE
Game crash; seems to be related to Sodium and Ender IO

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#15866]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.6.0 Beta 1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

N/A

### The Reality

Game crashed seemingly at random. I did not do anything particularly unique at the time of the crash; I was flying away and then back toward my base to make some mobs despawn (which is something I have done many times before without the game crashing).

Here is the crash log: 
[crash-2024-03-29_09.33.48-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14802264/crash-2024-03-29_09.33.48-client.txt)

I restarted the modpack instance and tried to load back into my world. The game crashed again both times I tried to load the world: 
[crash-2024-03-29_09.40.40-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14802319/crash-2024-03-29_09.40.40-client.txt)
[crash-2024-03-29_09.42.07-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14802330/crash-2024-03-29_09.42.07-client.txt)

### Your Proposal

The crash reports mention Sodium, and something to do with chunk rendering. They also mention Ender IO conduits. It looks as if there may be a catastrophic interaction between the two. I have been working with conduits today, so my base has a lot more of them than it did before I began to experience this recurring crash.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by hallucinogender** [comment]
I just updated my save to GTNH-2024-03-29+417-mmcprism-new-java and I'm no longer experiencing this crash - well, not within the short time I've been testing, but previously I was unable to access my save _at all_ so something is clearly quite different. Additionally, my allocated RAM does not _seem_ to be getting rapidly clogged, as has been happening lately. I suspect the two may be related, and it seems that _something_ between 2.6.0 Beta 1 and GTNH-2024-03-29+417-mmcprism-new-java has either resolved or substantially mitigated the problem.

**Comment by hallucinogender** [comment]
I decided to try updating my Java version from 17 to 21. While this bug seemed to be vanished on the aforementioned nightly build, it reoccurred after the Java update. Crash log here: 
[crash-2024-03-29_12.09.13-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14804063/crash-2024-03-29_12.09.13-client.txt)

**Comment by hallucinogender** [comment]
Another update: following the previous crash, I reverted back to Java 17. I experienced a near-identical crash, which again happened almost immediately after loading in to the world:
[crash-2024-03-29_12.15.15-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14804103/crash-2024-03-29_12.15.15-client.txt)

However, after _this_ crash I tried deactivating the UU-Tex resource pack. The crash did not reoccur immediately upon re-entering my world after this action. I will update this further if the crash does reoccur.

**Comment by mitchej123** [comment]
```
Caused by: java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
    at java.util.ArrayList$Itr.next(ArrayList.java:967)
    at crazypants.enderio.conduit.render.ConduitBundleRenderer.renderConduits(ConduitBundleRenderer.java:228)
    at crazypants.enderio.conduit.render.ConduitBundleRenderer.renderWorldBlock(ConduitBundleRenderer.java:144)
    at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
    at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
    at net.minecraft.client.renderer.RenderBlocks.renderBlockByRenderType(RenderBlocks.java:296)
```

**Comment by hallucinogender** [comment]
Just got another one of these on nightly 489, after a while without seeing the same issue and assuming it must be resolved. Crash report attached.
[crash-2024-05-30_15.09.43-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15501094/crash-2024-05-30_15.09.43-client.txt)

**Comment by Sanduhr32** [comment]
Hi, i am having the same crash in 3 variants on 2.6.1
