### ISSUE TITLE
EBF Suddenly Crashed without warning

### ISSUE THREAD

**Issue by Imagine0123** [GTNewHorizons/GT-New-Horizons-Modpack#15970]
### Your GTNH Discord Username

imagination12

### Your Pack Version

2.6.0-beta3

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Trying to smelt Silicon Boules and it finishing the smelt

### The Reality

EBF Crashed without actually voiding the recipe, just stopped with a message
![2024-04-13_18 34 19](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127961339/fd5bcad7-d060-4556-aefa-9da0ff74433c)
![2024-04-13_18 34 23](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127961339/e29c325e-5260-46a8-909d-8cae735d9a32)
![2024-04-13_18 33 41](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127961339/6814e8cd-5a84-4466-bb24-0ce0d9f49e08)

### Your Proposal

Multiblock not crashing

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Imagine0123** [comment]
Logs over here
[message.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14967255/message.txt)

With more specifically pointed out by Staffish in Discord
[18:31:19] java.lang.NullPointerException
[18:31:19]     at java.base/java.util.Objects.requireNonNull(Objects.java:233)
[18:31:19]     at RFB-Launch//gregtech.api.util.GT_ChunkAssociatedData$SuperRegion.get(GT_ChunkAssociatedData.java:326)
[18:31:19]     at RFB-Launch//gregtech.api.util.GT_ChunkAssociatedData.get(GT_ChunkAssociatedData.java:142)
[18:31:19]     at RFB-Launch//gregtech.common.GT_Pollution.mutatePollution(GT_Pollution.java:351)
[18:31:19]     at RFB-Launch//gregtech.common.GT_Pollution.addPollution(GT_Pollution.java:346)
[18:31:19]     at RFB-Launch//gregtech.common.GT_Pollution.addPollution(GT_Pollution.java:327)
[18:31:19]     at RFB-Launch//gregtech.common.GT_Pollution.addPollution(GT_Pollution.java:309)
[18:31:19]     at RFB-Launch//gregtech.api.metatileentity.implementations.GT_MetaTileEntity_BasicGenerator.onPostTick(GT_MetaTileEntity_BasicGenerator.java:222)
[18:31:19]     at RFB-Launch//gregtech.common.tileentities.generators.GT_MetaTileEntity_DieselGenerator.onPostTick(GT_MetaTileEntity_DieselGenerator.java:135)
[18:31:19]     at RFB-Launch//gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:553)
[18:31:19]     at RFB-Launch//net.minecraft.world.World.func_72939_s(World.java:1939)
[18:31:19]     at RFB-Launch//net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[18:31:19]     at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[18:31:19]     at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[18:31:19]     at RFB-Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[18:31:19]     at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[18:31:19]     at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by AbdielKavash** [comment]
FWIW, this does not seem to be related to the EBF, but to chunk loading or corruption.

Have you made any manual edits to your save file, or any strange config changes?

Does the game crash again when you load back in?

**Comment by chochem** [comment]
might be related to the rather extreme lag that the log points out too

**Comment by Imagine0123** [comment]
> FWIW, this does not seem to be related to the EBF, but to chunk loading or corruption.
> 
> Have you made any manual edits to your save file, or any strange config changes?
> 
> Does the game crash again when you load back in?

I haven't done anything, most config I changed is in ServerUtil for chunkloading and claiming and GT config to turn off use_machine_metal_tint




> might be related to the rather extreme lag that the log points out too

That can also be related since I use a rather heavy texpack with only 6144 of RAM

**Comment by Imagine0123** [comment]
EBF started normally after game reset and breaking and placing it again

**Comment by GirixK** [comment]
Can no longer reproduce, if the issue reappears in a newer version, open a new issue
