### ISSUE TITLE
Rapidly breaking AE2 Cables with a GregTech Wrench may cause client to be disconnected

### ISSUE THREAD

**Issue by norbby42** [GTNewHorizons/GT-New-Horizons-Modpack#16025]
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.6.0-beta3

### Your Server

Private Dedicated

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

1. Connect to a dedicated server
2. Preplace a line of AE2 Dense Cable
3. Acquire a GT Wrench with a high mining speed
4. Facing diagonally down the line
5. Rapidly break cables while strafing
6. Observe that you may be disconnected from the server

<details>
<summary><b>Crash Report</b></summary>

Stacktrace output to the server log:

[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$BreakEvent@56d54546:
[20.04 17:59:31] [Server] java.lang.NullPointerExceptionCannot read field "field_72310_e" because the return value of "appeng.util.Platform.rayTrace(net.minecraft.entity.player.EntityPlayer, boolean, boolean)" is null
[20.04 17:59:31] [Server] 	at RFB-Launch//gregtech.common.tools.GT_Tool_Wrench.onBreakBlock(GT_Tool_Wrench.java:214) ~[GT_Tool_Wrench.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//gregtech.common.GT_Proxy.onBlockBreakingEvent(GT_Proxy.java:1634) ~[GT_Proxy.class:?]
[20.04 17:59:31] [Server] 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_13_GT_Proxy_onBlockBreakingEvent_BreakEvent.invoke(.dynamic) ~[?:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:467) [ForgeHooks.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:259) [mx.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:186) [mx.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489) [nh.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) [ji.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) [ji.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: Index: 3 Listeners:
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 0: HIGHEST
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 1: ASM: serverutils.handlers.ServerUtilitiesPlayerEventHandler@59d5a31a onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 2: NORMAL
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 3: ASM: gregtech.common.GT_Server@6712cda1 onBlockBreakingEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 4: ASM: team.chisel.item.chisel.ChiselController@e389f60 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 5: ASM: crazypants.enderio.machine.spawner.BlockPoweredSpawner@70dbe8cc onBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 6: ASM: vazkii.botania.common.item.relic.ItemLokiRing@144d9838 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 7: ASM: lumien.randomthings.Handler.RTEventHandler@127f5ce9 breakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 8: ASM: pcl.opensecurity.util.OSBreakEvent@76437fcd onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 9: ASM: serverutils.handlers.ServerUtilitiesPlayerEventHandler@59d5a31a onBlockBreakLog(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 10: ASM: twilightforest.TFEventListener@1feea8bd breakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 11: ASM: com.enderio.core.common.handlers.XPBoostHandler@696c6df9 handleBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 12: ASM: com.github.namikon.angermod.events.BlockBreakEvent@1d8bcd23 onBreakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 13: ASM: tuhljin.automagy.lib.events.AutomagyEventHandler@5786fdb3 onBreakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 14: ASM: li.cil.oc.common.EventHandler$@4f0fbe83 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 15: ASM: thaumic.tinkerer.common.enchantment.ModEnchantmentHandler@72e8bdb4 onBreakBlock(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 16: ASM: com.carpentersblocks.util.handler.EventHandler@6bbb274c onBlockBreakEvent(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 17: ASM: makeo.gadomancy.common.events.EventHandlerWorld@1e454dc onBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 18: ASM: stevesaddons.naming.EventHandler@4e1efdc3 blockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 19: ASM: gregtech.common.misc.GlobalMetricsCoverDatabase@7a1602b5 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 20: ASM: fox.spiteful.avaritia.achievements.AchievementTrigger@28171131 onBorken(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 21: ASM: buildcraft.robotics.map.MapManager@7886f755 blockBroken(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 22: ASM: gregtech.common.GT_Server@6712cda1 onBlockEvent(Lnet/minecraftforge/event/world/BlockEvent;)V
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 23: LOWEST
[20.04 17:59:31] [Server] [Server thread/ERROR] [FML]: 24: ASM: bq_standard.handlers.EventHandler@657df800 onBlockBreak(Lnet/minecraftforge/event/world/BlockEvent$BreakEvent;)V
[20.04 17:59:31] [Server] [Server thread/WARN]: Failed to handle packet for /99.109.17.0:51667
[20.04 17:59:31] [Server] java.lang.NullPointerExceptionCannot read field "field_72310_e" because the return value of "appeng.util.Platform.rayTrace(net.minecraft.entity.player.EntityPlayer, boolean, boolean)" is null
[20.04 17:59:31] [Server] 	at RFB-Launch//gregtech.common.tools.GT_Tool_Wrench.onBreakBlock(GT_Tool_Wrench.java:214) ~[GT_Tool_Wrench.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//gregtech.common.GT_Proxy.onBlockBreakingEvent(GT_Proxy.java:1634) ~[GT_Proxy.class:?]
[20.04 17:59:31] [Server] 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_13_GT_Proxy_onBlockBreakingEvent_BreakEvent.invoke(.dynamic) ~[?:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:467) ~[ForgeHooks.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:259) ~[mx.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:186) ~[mx.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489) ~[nh.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) ~[ji.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) ~[ji.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[20.04 17:59:31] [Server] 	at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

</details>

----

Yeah... appeng's Platform.rayTrace can return a null value.  GT_Tool_Wrench is assuming it never does.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by AbdielKavash** [comment]
Confirming the same issue with singleplayer, java 21.

**Comment by combusterf** [comment]
Confirming the same issue on Delta
