### ISSUE TITLE
Crash on 2.6.0 involving AE2 and Angelica

### ISSUE THREAD

**Issue by QuantumBlink1337** [GTNewHorizons/GT-New-Horizons-Modpack#16075]
### Your GTNH Discord Username

quantumblink

### Your Pack Version

2.6.0 release

### Your Server

SMP Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

Traversing my base as normal, with a large AE2 system. 

### Crash Report

https://gist.github.com/QuantumBlink1337/ba0e8be111c9f2ef3b9bf4b6e417fa2a

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

https://drive.google.com/file/d/1dKPGJQJ-cYogQLpPk9zivj8HcHZve-Aj/view?usp=sharing

Here is a copy of our world to investigate with.

**Comment by budak7273** [comment]
Our base has some storage monitors, I wonder if they could be at play here?

**Comment by apple7449** [comment]
similar issue 
[crash-2024-04-28_16.11.02-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15144254/crash-2024-04-28_16.11.02-client.txt)

**Comment by VladiSl4ve** [comment]
same (just stay afk)
[crash-2024-04-29_02.33.00-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15144376/crash-2024-04-29_02.33.00-client.txt)
[crash-2024-04-29_02.47.35-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15144377/crash-2024-04-29_02.47.35-client.txt)

**Comment by AbdielKavash** [comment]
I don't know if this helps, but I got a similar crash. I can give all information I can to help track this down. Java 21, freshly installed GTNH 2.6.0, no changes in default Angelica configs. Game crashed to main menu, upon reentering the game everything seems fine.

Crash report: https://mclo.gs/nRwL1TY 
DXdiag with system specs if this is helpful: [Google drive link](https://drive.google.com/file/d/1GZJOTiKuihJ6-IBRmOY26EyBH8jJPl4X/view?usp=sharing)
World upload immediately after the crash (I have trimmed all other dimensions to reduce file size, since this is rendering-related that shouldn't matter): [Google drive link, ~200 MB](https://drive.google.com/file/d/1_vu403Aga5YrEvLHI03GREvEw0WoBens/view?usp=sharing)

**Comment by combusterf** [comment]
I get a slightly different stacktrace than those above, but with essentially the same suspects: AE2, Angelica and what looks to be a null icon.

The crash to menu triggers randomly just by AFKing in my base, and I also have storage monitors in the area as budak7273 mentioned

Crash excerpt: ```
Caused by: java.lang.NullPointerException: Cannot invoke "appeng.client.texture.FlippableIcon.setFlip(boolean, boolean)" because "ico" is null
    at appeng.parts.networking.PartCable.renderSmartConnection(PartCable.java:702)
    at appeng.parts.networking.PartDenseCable.renderStatic(PartDenseCable.java:183)
    at appeng.client.render.CableRenderHelper.renderStatic(CableRenderHelper.java:57)
    at appeng.parts.CableBusContainer.renderStatic(CableBusContainer.java:731)
    at appeng.client.render.blocks.RendererCableBus.renderInWorld(RendererCableBus.java:47)
    at appeng.client.render.blocks.RendererCableBus.renderInWorld(RendererCableBus.java:26)
    at appeng.client.render.WorldRender.renderWorldBlock(WorldRender.java:50)
    at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
    at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
    at net.minecraft.client.renderer.RenderBlocks.renderBlockByRenderType(RenderBlocks.java:296)
    at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:95)
    at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:161)
    at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:409)
    at java.lang.Thread.run(Thread.java:833)
```
Full report here: [crash-2024-04-29_08.40.00-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15145927/crash-2024-04-29_08.40.00-client.txt)

**Comment by Proficus** [comment]
I tired from this bug. All time kicks, items disappeared...

https://mclo.gs/H2TuSBs

**Comment by Lyfts** [comment]
@Proficus then update AE2 https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/releases/tag/rv3-beta-400-GTNH

**Comment by Proficus** [comment]
> @Proficus then update AE2 https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/releases/tag/rv3-beta-400-GTNH

Its need update on Eta server 
@Dream-Master @boubou19
