### ISSUE TITLE
Cannot invoke "net.minecraftforge.fluids.FluidStack.copy()" because "mOutputFluids2[i]" is null

### ISSUE THREAD

**Issue by elak93** [GTNewHorizons/GT-New-Horizons-Modpack#16104]
### Your GTNH Discord Username

elak93#1348

### Your Pack Version

2.6.0

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

No error message 3 times a second. New backup with a fresh 2.6 server install using keztech 0.10.5 to fix our uuid issue, backup is from crucible server and world thats been running for the last year. no plugins or their data has been transferred. Server runs, just unsure if I should actually be concerned by this message/corruption.

### The Reality

Error message occurring 3 times a second as below 

[16:00:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.NullPointerException: Cannot invoke "net.minecraftforge.fluids.FluidStack.copy()" because "mOutputFluids2[i]" is null
[16:00:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//com.github.bartimaeusnek.bartworks.common.tileentities.multis.mega.GT_TileEntity_MegaDistillTower.addFluidOutputs(GT_TileEntity_MegaDistillTower.java:418)
[16:00:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.runMachine(GT_MetaTileEntity_MultiBlockBase.java:548)
[16:00:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:411)
[16:00:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:557)
[16:00:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.world.World.func_72939_s(World.java:1939)
[16:00:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[16:00:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[16:00:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[16:00:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[16:00:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[16:00:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

### Your Proposal
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15159064/fml-server-latest.log)

Tried breaking a few mega DTS to see if it would stop. any help would be greatly appreciated to get the aus server back up and running

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by elak93** [comment]
Finally found the issue one mega distillation tower had become unusable block, deleting it has fixed the issue
