### ISSUE TITLE
"Error during loading recipes" when browsing certain GT++ material recipes

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#16204]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

Nightly 463

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

I was browsing a few GT++ materials in NEI and encountered several instances of this message in the game chat:
"There was an error during loading recipe. Please check log for details".

This has happened when searching for uses of blood steel frame boxes, and for recipes for potin blocks. There may be other similar errors with GT++ materials.

After some difficulty finding out _where_ I am actually supposed to be checking (it turned out to be the console output), I was able to find the error log.

### The Reality

[02:48:35] [ForkJoinPool-1-worker-6/ERROR] [NotEnoughItems]: Error while looking up crafting recipe
[02:48:35] [ForkJoinPool-1-worker-6/ERROR] [NotEnoughItems]: outputId: item
[02:48:35] [ForkJoinPool-1-worker-6/ERROR] [NotEnoughItems]: results: [1xblock.Potin.standard@0]
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "te" is null
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at RFB-Launch//blockrenderer6343.integration.structurelib.StructureCompatNEIHandler.tryLoadingMultiblock(StructureCompatNEIHandler.java:40)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at RFB-Launch//blockrenderer6343.integration.nei.MultiblockHandler.loadCraftingRecipes(MultiblockHandler.java:41)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at RFB-Launch//codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:466)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at RFB-Launch//blockrenderer6343.integration.nei.MultiblockHandler.loadCraftingRecipes(MultiblockHandler.java:36)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at RFB-Launch//codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:605)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at RFB-Launch//codechicken.nei.recipe.GuiCraftingRecipe.lambda$getCraftingHandlers$1(GuiCraftingRecipe.java:97)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at RFB-Launch//codechicken.nei.recipe.RecipeHandlerQuery.lambda$null$3(RecipeHandlerQuery.java:91)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[02:48:35] [ForkJoinPool-1-worker-6/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[02:48:35] [Client thread/INFO]: [CHAT] There was error during loading recipe. Please check log for details.

### Your Proposal

Fix the issue. Please let me know if I can provide any additional data.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
seems related to https://github.com/GTNewHorizons/BlockRenderer6343/pull/14 @Lyfts

**Comment by hallucinogender** [comment]
This appears to happen specifically when checking recipes of blocks or frame boxes (both placeable objects) made with GT++ materials, if that helps.
