### ISSUE TITLE
ME Digital Singularity Cell breaks

### ISSUE THREAD

**Issue by SIlestia** [GTNewHorizons/GT-New-Horizons-Modpack#16264]
### Your GTNH Discord Username

Ne Vyacheslav Ukraincev

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/84074497/0c6bb404-2a28-4790-923a-b2f90d4fc44d)

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/84074497/f8105dc1-b0d8-48f0-931b-fa88a246d5df)

### Your Proposal

the card possibly become "Unnamed" if there are already exists another card with same filter in the me network

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Quetz4l** [comment]
I have singularity disks with filters and regular disks for 63 items without any filters. The singularity disks also break. I think this happens when the item count decreases to 0 plus some other factor. 

I saw a similar problem with 3 other guys. 

The bug is still present in version 2.6.1.

**Comment by Quetz4l** [comment]
When a player interacts with the disk, it can causes a crash on the client (the server doesn't crash).
```
java.lang.NullPointerException: Cannot invoke "appeng.api.storage.data.IAEItemStack.getItemStack()" because the return value of "appeng.api.storage.data.IItemList.getFirstItem()" is null
    at appeng.items.storage.ItemExtremeStorageCell.addCheckedInformation(ItemExtremeStorageCell.java:95)
    at appeng.items.AEBaseItem.addInformation(AEBaseItem.java:70)
    at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:525)
    at net.minecraft.client.gui.GuiScreen.renderToolTip(GuiScreen.java:104)
    at serverutils.lib.gui.GuiWrapper.drawScreen(GuiWrapper.java:125)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5110)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:60)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:219)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by dahgul333** [comment]
![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/35747549/84a3337f-6adb-4c24-b603-a24c0384c8a2)
On Eta(2.6.1) it It's happening too. 
no see duplicated filters on my base ...
