### ISSUE TITLE
Kick from server with Internal server error when rightclicking with battlegears to non-GUI block

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/GT-New-Horizons-Modpack#16293]
### Your GTNH Discord Username

skproch

### Your Pack Version

2.6.0

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Ultramine

### Your Expectation

When you choose battlegears hands and try to right click on block which doesn't has GUI on right click (e.g. stone) nothing should happens.

### The Reality

I've has been kicked from server with Internal server error. Exception displayed in server logs:

```
java.lang.NullPointerException
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:637)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(C08PacketPlayerBlockPlacement.java:65)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(C08PacketPlayerBlockPlacement.java:110)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:231)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:567)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:444)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:719)
```

Seems like client doesn't has any exception in the logs (except Angelica's chunk building cancellation)

### Your Proposal

This should kick you from server.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
no kick really happens on a vanilla forge server.. ultramine problem? in any case ask your server owner first I guess

**Comment by SKProCH** [comment]
Actually, I'm my server owner 😃. If this isn't reproduceable I'm vanilla we can probably close the issue as you don't support ultramine.

**Comment by TimeConqueror** [comment]
Should be fixed by https://github.com/GTNewHorizons/Battlegear2/pull/28

**Comment by SKProCH** [comment]
Thanks. @TimeConqueror!
