### ISSUE TITLE
Log spaming when using TC Golem

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#16419]
### Your GTNH Discord Username

yukieji

### Your Pack Version

2.6.0.0

### Your Server

private server

### Java Version

Java 21

### Type of Server

Crucible

### Your Expectation

use TC Golem

### The Reality

log spamimg with stacktrace error.
and can't conect servers... 

 - stacktrace errors
```
[13:55:39] [Server thread/WARN] [coretweaks]: Detected duplicate DataWatcher object registration for entity thaumcraft.common.entities.golems.EntityGolemBase at already occupied ID 16. Things are likely going to break! Enable `detectDataWatcherIdConflictCulprit` to gather more information.
[13:55:39] [Server thread/WARN] [coretweaks]: Last registration stack trace:
java.lang.Throwable
	at net.minecraft.entity.DataWatcher.handler$zzm000$coretweaks$monitorTypedObjectAddition(DataWatcher.java:1042)
	at net.minecraft.entity.DataWatcher.func_82709_a(DataWatcher.java)
	at thaumcraft.common.entities.golems.EntityGolemBase.updateCarried(EntityGolemBase.java:939)
	at thaumcraft.common.entities.ai.inventory.AIEmptyPlace.func_75249_e(AIEmptyPlace.java:154)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(EntityAITasks.java:111)
	at makeo.gadomancy.common.entities.golems.cores.EntityAITasksWrapper.func_75774_a(EntityAITasksWrapper.java:83)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:582)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2120)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388)
	at thaumcraft.common.entities.golems.EntityGolemBase.func_70636_d(EntityGolemBase.java:354)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1953)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
	at net.minecraft.world.World.func_72866_a(World.java:2724)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:873)
	at net.minecraft.world.World.func_72870_g(World.java:2662)
	at net.minecraft.world.World.func_72939_s(World.java:2463)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:989)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:845)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:695)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Your Proposal

fix it, It worked fine in v2.4.0.0

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Fixed by latest TC4Tweaks

**Comment by Glease** [comment]
Actually, nevermind, it hasn't been published yet

**Comment by Glease** [comment]
fixed by https://github.com/Glease/TC4Tweaks/commit/7b5a5bed43e9d5ae612f87b4b77e37914f27f996
