### ISSUE TITLE
Crash caused by NULL item in AE2 crafting calculation

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#16481]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Calculate the craft for an octuple compressed solar panel. AE tells me that I am missing 684.000 of `** NULL`.
When holding down shift to get more info about this item, the game crashed.
![2024-06-07_22 34 05](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/64365566/37ceb78c-f2bb-46d3-b4d8-1a9abf2e2fbf)
Every time I let AE calculate the craft, the following message appears in fml-client-latest.log:
`[22:29:21] [Client thread/ERROR] [AE2:C/]: Could not deserialize crafting tree sent by the server.
java.lang.UnsupportedOperationException: Illegal pattern type 1xthaumicenergistics.item.knowledge.core@0
	at RFB-Launch//appeng.crafting.v2.CraftingTreeSerializer.readPattern(CraftingTreeSerializer.java:229) ~[CraftingTreeSerializer.class:?]
	at RFB-Launch//appeng.crafting.v2.resolvers.CraftableItemResolver$CraftFromPatternTask.<init>(CraftableItemResolver.java:158) ~[CraftableItemResolver$CraftFromPatternTask.class:?]
	at RFB-Launch//appeng.crafting.v2.CraftingTreeSerializer.readSerializableAndQueueChildren(CraftingTreeSerializer.java:161) ~[CraftingTreeSerializer.class:?]
	at RFB-Launch//appeng.crafting.v2.CraftingTreeSerializer.lambda$readSerializableAndQueueChildren$1(CraftingTreeSerializer.java:170) ~[CraftingTreeSerializer.class:?]
	at RFB-Launch//appeng.crafting.v2.CraftingTreeSerializer.doWork(CraftingTreeSerializer.java:316) ~[CraftingTreeSerializer.class:?]
	at RFB-Launch//appeng.crafting.v2.CraftingJobV2.deserialize(CraftingJobV2.java:100) ~[CraftingJobV2.class:?]
	at RFB-Launch//appeng.core.sync.packets.PacketCraftingTreeData.onFullClientData(PacketCraftingTreeData.java:142) [PacketCraftingTreeData.class:?]
	at RFB-Launch//appeng.core.sync.packets.PacketCraftingTreeData.clientPacketData(PacketCraftingTreeData.java:106) [PacketCraftingTreeData.class:?]
	at RFB-Launch//appeng.core.sync.network.AppEngClientPacketHandler.onPacketData(AppEngClientPacketHandler.java:35) [AppEngClientPacketHandler.class:?]
	at RFB-Launch//appeng.core.sync.network.NetworkHandler.clientPacket(NetworkHandler.java:85) [NetworkHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1980_NetworkHandler_clientPacket_ClientCustomPacketEvent.invoke(.dynamic) [?:?]
	at RFB-Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at RFB-Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at RFB-Launch//cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) [FMLEventChannel.class:?]
	at RFB-Launch//cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) [NetworkEventFiringHandler.class:?]
	at RFB-Launch//cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) [NetworkEventFiringHandler.class:?]
	at RFB-Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [netty-all-4.0.10.Final.jar:?]
	at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at RFB-Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [netty-all-4.0.10.Final.jar:?]
	at RFB-Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [netty-all-4.0.10.Final.jar:?]
	at RFB-Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at RFB-Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at RFB-Launch//net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at RFB-Launch//net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at RFB-Launch//net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at RFB-Launch//net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5110) [bao.class:?]
	at RFB-Launch//net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at RFB-System//net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250) [Launch.class:?]
	at RFB-System//net.minecraft.launchwrapper.Launch.launch(Launch.java:35) [Launch.class:?]
	at RFB-System//net.minecraft.launchwrapper.Launch.main(Launch.java:60) [Launch.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:219) [lwjgl3ify-2.0.9-forgePatches.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at RFB-System//org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at RFB-System//org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at RFB-System//org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at RFB-System//org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

### Crash Report

[crash-2024-06-07_22.09.31-client.txt](https://github.com/user-attachments/files/15744693/crash-2024-06-07_22.09.31-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by GTNH-Afx237v7** [comment]
After LOTS of digging through AE2 recipes it turns out that the NULL item is an invalid fluid drop caused by an (apparently) changed/broken recipe to Terephthalic Acid. The 1,4Dimethylbenzene was not properly encoded. Making a new pattern fixed this.
Would have been nice to see this recipe mark in the interface terminal when looking for invalid patterns.
