### ISSUE TITLE
Changing the value of a Volumetric Flask force disconnects the client

### ISSUE THREAD

**Issue by Sirheavens** [GTNewHorizons/GT-New-Horizons-Modpack#16494]
### Your GTNH Discord Username

sirheavens

### Your Pack Version

2.6.1

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

I tried to set the value of a volumetric flask using the suggested method "Rightclick on air to set volume". This opens this dialog box: 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/42445273/b50a9d39-c57f-4275-828b-ddf22a5da3e4)

### The Reality

Exiting this menu with ESC closes the menu as normal without issue. Clicking 'Confirm', regardless of value in the dialog box, causes the client to be disconnected from the server with the message "A fatal error has occured, this connection is terminated". Within the server terminal, the following exception appears: 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/42445273/b0fea6ca-9a5c-43fe-b686-2ca7c71f18db)

After reconnecting, the flask does appear to be set to the specified value. So it is possible to set the value, but the client is disconnected each time you change the value.

### Your Proposal

The client should not be disconnected when setting the value of a volumetric flask.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kde99** [comment]
Same happens under GraalVM 22.0.1+8.1 (server) and GraalVM 21.0.3+7.1 (client side).

I am running base pack with JustEnoughCalculation-1.7.10-3.8.6 and VeinMiner-1.7.10-0.36.0.496+28a7f13.

Exception appears on server side only. Client side logs so nothing.
```
[11:51:07] [Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
java.lang.NoSuchMethodError: 'void com.gtnewhorizons.modularui.api.widget.Widget.onRemoveFocus()'
        at RFB-Launch//com.gtnewhorizons.modularui.common.widget.textfield.BaseTextFieldWidget.onRemoveFocus(BaseTextFieldWidget.java:308) ~[BaseTextFieldWidget.class:?]
        at RFB-Launch//com.gtnewhorizons.modularui.common.widget.textfield.NumericWidget.onRemoveFocus(NumericWidget.java:300) ~[NumericWidget.class:?]
        at RFB-Launch//gregtech.common.items.GT_VolumetricFlask$VolumetricFlaskUIFactory.lambda$createWindow$2(GT_VolumetricFlask.java:345) ~[GT_VolumetricFlask$VolumetricFlaskUIFactory.class:?]
        at RFB-Launch//com.gtnewhorizons.modularui.common.widget.ButtonWidget.readOnServer(ButtonWidget.java:118) ~[ButtonWidget.class:?]
        at RFB-Launch//com.gtnewhorizons.modularui.api.screen.ModularUIContext.readClientPacket(ModularUIContext.java:383) ~[ModularUIContext.class:?]
        at RFB-Launch//com.gtnewhorizons.modularui.common.internal.network.CWidgetUpdate.executeServer(CWidgetUpdate.java:43) ~[CWidgetUpdate.class:?]
        at RFB-Launch//com.gtnewhorizons.modularui.common.internal.network.NetworkHandler.lambda$static$1(NetworkHandler.java:55) ~[NetworkHandler.class:?]
        at RFB-Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
        at RFB-Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
        at RFB-Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at RFB-Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at RFB-Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[11:51:07] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel modularui
java.lang.NoSuchMethodError: 'void com.gtnewhorizons.modularui.api.widget.Widget.onRemoveFocus()'
        at RFB-Launch//com.gtnewhorizons.modularui.common.widget.textfield.BaseTextFieldWidget.onRemoveFocus(BaseTextFieldWidget.java:308) ~[BaseTextFieldWidget.class:?]
        at RFB-Launch//com.gtnewhorizons.modularui.common.widget.textfield.NumericWidget.onRemoveFocus(NumericWidget.java:300) ~[NumericWidget.class:?]
        at RFB-Launch//gregtech.common.items.GT_VolumetricFlask$VolumetricFlaskUIFactory.lambda$createWindow$2(GT_VolumetricFlask.java:345) ~[GT_VolumetricFlask$VolumetricFlaskUIFactory.class:?]
        at RFB-Launch//com.gtnewhorizons.modularui.common.widget.ButtonWidget.readOnServer(ButtonWidget.java:118) ~[ButtonWidget.class:?]
        at RFB-Launch//com.gtnewhorizons.modularui.api.screen.ModularUIContext.readClientPacket(ModularUIContext.java:383) ~[ModularUIContext.class:?]
        at RFB-Launch//com.gtnewhorizons.modularui.common.internal.network.CWidgetUpdate.executeServer(CWidgetUpdate.java:43) ~[CWidgetUpdate.class:?]
        at RFB-Launch//com.gtnewhorizons.modularui.common.internal.network.NetworkHandler.lambda$static$1(NetworkHandler.java:55) ~[NetworkHandler.class:?]
        at RFB-Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
        at RFB-Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
        at RFB-Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[minecraft_server.1.7.10.jar:?]
        at RFB-Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at RFB-Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at RFB-Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by Trompettesib** [comment]
Hi,
I have the exact same issue.
Version 2.6.1

**Comment by JasonBourne999** [comment]
Also having this issue. 
Version 2.6.1
