### ISSUE TITLE
AE Interface terminal interaction

### ISSUE THREAD

**Issue by LjeDamos** [GTNewHorizons/GT-New-Horizons-Modpack#16560]
### Your GTNH Discord Username

ljedamos

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 20

### Type of Server

Ultramine

### Your Actions

1. Open pattern terminal;
2. Take pattern, "accidentally" insert it slightly lower than pattern slot;
3. Get kicked from server;
4. Join back, open interface to which you "put" pattern and it will jump out from this interface.

### Crash Report

Full file - [fml-client-latest.log](https://github.com/user-attachments/files/15909325/fml-client-latest.log)
Short version:
```
[09:01:34] [Client thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ClientCustomPacketEvent@653b7d34:
java.lang.ArrayIndexOutOfBoundsException
[09:01:34] [Client thread/ERROR] [FML]: Index: 1 Listeners:
[09:01:34] [Client thread/ERROR] [FML]: 0: NORMAL
[09:01:34] [Client thread/ERROR] [FML]: 1: ASM: appeng.core.sync.network.NetworkHandler@6ce0e569 clientPacket(Lcpw/mods/fml/common/network/FMLNetworkEvent$ClientCustomPacketEvent;)V
[09:01:34] [Client thread/ERROR] [FML]: NetworkEventFiringHandler exception
java.lang.ArrayIndexOutOfBoundsException
[09:01:34] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel AE2
java.lang.ArrayIndexOutOfBoundsException
```

Video record:

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/20936024/0252f8fc-3626-4be9-9ece-149a279202bd

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
interesting part:
```[08:56:02] [Chunk Render Task Executor #5/DEBUG] [FML/]: Bar Finished: Loading Resource - LiquidConduitRenderer took 0.000s
[08:56:28] [Client thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ClientCustomPacketEvent@7fececa6:
java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9
	at RFB-Launch//appeng.tile.inventory.AppEngInternalInventory.func_70301_a(AppEngInternalInventory.java:72) ~[AppEngInternalInventory.class:?]
	at RFB-Launch//appeng.client.gui.implementations.GuiInterfaceTerminal$InterfaceTerminalEntry.setItemInSlot(GuiInterfaceTerminal.java:1299) ~[GuiInterfaceTerminal$InterfaceTerminalEntry.class:?]
	at RFB-Launch//appeng.client.gui.implementations.GuiInterfaceTerminal$InterfaceTerminalEntry.partialItemUpdate(GuiInterfaceTerminal.java:1294) ~[GuiInterfaceTerminal$InterfaceTerminalEntry.class:?]
	at RFB-Launch//appeng.client.gui.implementations.GuiInterfaceTerminal.parsePacketCmd(GuiInterfaceTerminal.java:856) ~[GuiInterfaceTerminal.class:?]
	at RFB-Launch//appeng.client.gui.implementations.GuiInterfaceTerminal.postUpdate(GuiInterfaceTerminal.java:823) ~[GuiInterfaceTerminal.class:?]
	at RFB-Launch//appeng.core.sync.packets.PacketInterfaceTerminalUpdate.clientPacketData(PacketInterfaceTerminalUpdate.java:183) ~[PacketInterfaceTerminalUpdate.class:?]
	at RFB-Launch//appeng.core.sync.network.AppEngClientPacketHandler.onPacketData(AppEngClientPacketHandler.java:35) ~[AppEngClientPacketHandler.class:?]
	at RFB-Launch//appeng.core.sync.network.NetworkHandler.clientPacket(NetworkHandler.java:85) ~[NetworkHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1981_NetworkHandler_clientPacket_ClientCustomPacketEvent.invoke(.dynamic) ~[?:?]```

**Comment by lordIcocain** [comment]
fixed by https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/693
