### ISSUE TITLE
The specified class 'gregtech.api.GregTech_API' was not found

### ISSUE THREAD

**Issue by SanorusVentus** [GTNewHorizons/GT-New-Horizons-Modpack#16587]
### Your GTNH Discord Username

SanorusVentus

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Launched the game via the CurseForge. It works on my PC but crashes on my laptop. There's no crash log, Minecraft just say that the error code is "1". But there is a lot of info in the log file that I wasn't able to understand. 

### Crash Report

[23:23:22] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[23:23:22] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[23:23:22] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[23:23:22] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[23:23:22] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Veter\curseforge\minecraft\Install\runtime\jre-legacy\windows-x64\jre-legacy
[23:23:22] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from +unimixins-all-1.7.10-0.1.17.jar
[23:23:23] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:23:23] [main/WARN]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:23:23] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from GTNewHorizonsCoreMod-2.3.54.jar
[23:23:23] [main/WARN]: The coremod lumien.hardcoredarkness.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:23:23] [main/WARN]: The coremod net.glease.healer.Healer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:23:23] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:23:23] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[23:23:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Veter/curseforge/minecraft/Instances/GT%20New%20Horizons/mods/+unimixins-all-1.7.10-0.1.17.jar Service=LaunchWrapper Env=CLIENT
[23:23:23] [main/DEBUG]: Instantiating coremod class AllCore
[23:23:23] [main/INFO]: MixinBootstrap Initializing...
[23:23:23] [main/INFO]: Compatibility level set to JAVA_8
[23:23:23] [main/INFO]: Initializing GasStationCore
[23:23:23] [main/INFO]: Initializing GTNHMixins Core
[23:23:24] [main/DEBUG]: The coremod io.github.legacymoddingmc.unimixins.all.AllCore requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
[23:23:24] [main/INFO]: Instantiating AllCore
[23:23:24] [main/INFO]: Instantiating CompatCore
[23:23:24] [main/INFO]: Instantiating MixinExtrasCore
[23:23:24] [main/DEBUG]: Added access transformer class io.github.legacymoddingmc.unimixins.all.AllCore$CombinedAccessTransformer to enqueued access transformers
[23:23:24] [main/DEBUG]: Enqueued coremod AllCore
[23:23:24] [main/DEBUG]: Instantiating coremod class DreamCoreMod
[23:23:24] [main/TRACE]: coremod named DreamCoreMod is loading
[23:23:24] [main/DEBUG]: The coremod com.dreammaster.coremod.DreamCoreMod requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
[23:23:24] [main/DEBUG]: Enqueued coremod DreamCoreMod
[23:23:24] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[23:23:24] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[23:23:24] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:23:24] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:23:24] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:23:24] [main/DEBUG]: Injecting coremod FMLCorePlugin {cpw.mods.fml.relauncher.FMLCorePlugin} class transformers
[23:23:24] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.MarkerTransformer
[23:23:24] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.SideTransformer
[23:23:24] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
[23:23:24] [main/DEBUG]: Injection complete
[23:23:24] [main/DEBUG]: Running coremod plugin for FMLCorePlugin {cpw.mods.fml.relauncher.FMLCorePlugin}
[23:23:24] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[23:23:25] [main/DEBUG]: Read 527 binary patches
[23:23:26] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[23:23:26] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[23:23:26] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[23:23:26] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:23:26] [main/DEBUG]: Injecting coremod FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin} class transformers
[23:23:26] [main/TRACE]: Registering transformer net.minecraftforge.classloading.FluidIdTransformer
[23:23:26] [main/DEBUG]: Injection complete
[23:23:26] [main/DEBUG]: Running coremod plugin for FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin}
[23:23:26] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[23:23:26] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[23:23:26] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:23:26] [main/DEBUG]: Injecting coremod CoreMod {aroma1997.core.coremod.CoreMod} class transformers
[23:23:26] [main/DEBUG]: Injection complete
[23:23:26] [main/DEBUG]: Running coremod plugin for CoreMod {aroma1997.core.coremod.CoreMod}
[23:23:26] [main/DEBUG]: Running coremod plugin CoreMod
[23:23:26] [main/INFO]: Finished data injection.
[23:23:26] [main/INFO]: Finished data injection.
[23:23:26] [main/DEBUG]: Coremod plugin class CoreMod run successfully
[23:23:26] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[23:23:26] [main/INFO]: Initialised Mixin FML Remapper Adapter with cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@ecf9049
[23:23:26] [main/DEBUG]: Injecting coremod AllCore {io.github.legacymoddingmc.unimixins.all.AllCore} class transformers
[23:23:26] [main/TRACE]: Registering transformer io.github.legacymoddingmc.unimixins.compat.asm.EnhanceCrashReportsTransformer
[23:23:26] [main/DEBUG]: Injection complete
[23:23:26] [main/DEBUG]: Running coremod plugin for AllCore {io.github.legacymoddingmc.unimixins.all.AllCore}
[23:23:26] [main/DEBUG]: Running coremod plugin AllCore
[23:23:27] [main/INFO]: Examining core mod list
[23:23:27] [main/INFO]: LoadedCoreMods [aroma1997.core.coremod.CoreMod, cpw.mods.fml.relauncher.FMLCorePlugin, io.github.legacymoddingmc.unimixins.all.AllCore, org.spongepowered.asm.launch.MixinTweaker, lumien.hardcoredarkness.asm.LoadingPlugin, net.glease.tc4tweak.asm.LoadingPlugin, net.blay09.mods.craftingtweaks.coremod.CraftingTweaksLoadingPlugin, net.glease.healer.Healer, net.minecraftforge.classloading.FMLForgePlugin, cpw.mods.fml.common.launcher.FMLDeobfTweaker, com.dreammaster.coremod.DreamCoreMod, cofh.asm.LoadingPlugin]
[23:23:27] [main/INFO]: Loading [mixins.dreamcraft.early.json] MixinMinecraft_ConfirmExit
[23:23:27] [main/INFO]: Loading [mixins.dreamcraft.early.json] MixinMinecraft_PackIcon
[23:23:27] [main/INFO]: Loading [mixins.dreamcraft.early.json] MixinTileEntityBeacon
[23:23:27] [main/DEBUG]: Coremod plugin class AllCore run successfully
[23:23:27] [main/DEBUG]: Injecting coremod DreamCoreMod {com.dreammaster.coremod.DreamCoreMod} class transformers
[23:23:27] [main/TRACE]: Registering transformer com.dreammaster.coremod.DreamClassTransformer
[23:23:27] [main/DEBUG]: Injection complete
[23:23:27] [main/DEBUG]: Running coremod plugin for DreamCoreMod {com.dreammaster.coremod.DreamCoreMod}
[23:23:27] [main/DEBUG]: Running coremod plugin DreamCoreMod
[23:23:27] [main/INFO]: No dependencies found.
[23:23:27] [main/DEBUG]: Coremod plugin class DreamCoreMod run successfully
[23:23:27] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[23:23:27] [main/DEBUG]: Loaded 57 rules from AccessTransformer config file fml_at.cfg
[23:23:27] [main/DEBUG]: Loaded 89 rules from AccessTransformer config file forge_at.cfg
[23:23:27] [main/DEBUG]: Loaded 6 rules from AccessTransformer config file aroma1997core_at.cfg
[23:23:27] [main/DEBUG]: Loaded 2 rules from AccessTransformer mod jar file C:\Users\Veter\curseforge\minecraft\Instances\GT New Horizons\mods\HungerOverhaul-1.7.10-1.0.0.jenkins104.jar!META-INF/HungerOverhaul_at.cfg

[23:23:27] [main/DEBUG]: Loaded 7 rules from AccessTransformer mod jar file C:\Users\Veter\curseforge\minecraft\Instances\GT New Horizons\mods\craftingtweaks-mc1.7.10-1.0.88.jar!META-INF/craftingtweaks_at.cfg

[23:23:27] [main/DEBUG]: Loaded 5 rules from AccessTransformer mod jar file C:\Users\Veter\curseforge\minecraft\Instances\GT New Horizons\mods\CraftPresence-2.3.9+1.7.10.jar!META-INF/accesstransformer.cfg

[23:23:27] [main/DEBUG]: Loaded 6 rules from AccessTransformer mod jar file C:\Users\Veter\curseforge\minecraft\Instances\GT New Horizons\mods\witchery-1.7.10-0.24.1.jar!META-INF/witchery_at.cfg

[23:23:27] [main/DEBUG]: Loaded 2 rules from AccessTransformer mod jar file C:\Users\Veter\curseforge\minecraft\Instances\GT New Horizons\mods\journeymap-1.7.10-5.2.3-fairplay.jar!META-INF/journeymap_at.cfg

[23:23:27] [main/DEBUG]: Validating minecraft
[23:23:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:23:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:23:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:23:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:23:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:23:27] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[23:23:27] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[23:23:27] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[23:23:27] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[23:23:27] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[23:23:28] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[23:23:28] [main/INFO]: Found World Class: net/minecraft/world/World
[23:23:28] [main/INFO]:  - Patched minimal sky light (1)
[23:23:28] [main/INFO]:  - Patched minimal sky light (2)
[23:23:28] [main/INFO]: CraftingTweaks will now patch func_146274_d in bdw...
[23:23:28] [main/INFO]: CraftingTweaks successfully patched func_146274_d in bdw!
[23:23:29] [main/INFO]: Setting user: SanorusVentus
[23:23:30] [main/WARN]: Error loading class: gregtech/api/GregTech_API (java.lang.ClassNotFoundException: The specified class 'gregtech.api.GregTech_API' was not found)
[23:23:30] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/tileentity/TileEntityBeacon
	at net.minecraft.block.Block.func_149671_p(Block.java:349) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.tileentity.TileEntityBeacon
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.block.Block.func_149671_p(Block.java:349) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.block.Block.func_149671_p(Block.java:349) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for mixins.dreamcraft.early.json:MixinTileEntityBeacon from mod dreamcraft during activity: [Transform -> Method dreamcraft$countEternalBlocks(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IIIZIILnet/minecraft/block/Block;Lcom/llamalad7/mixinextras/sugar/ref/LocalIntRef;)V -> GETSTATIC -> gregtech/api/GregTech_API::sBlockMetal9:Lnet/minecraft/block/Block;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.block.Block.func_149671_p(Block.java:349) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: gregtech.api.GregTech_API
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:777) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:740) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.block.Block.func_149671_p(Block.java:349) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: gregtech.api.GregTech_API
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:777) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:740) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[+unimixins-all-1.7.10-0.1.17.jar:0.13.0+mixin.0.8.5]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.block.Block.func_149671_p(Block.java:349) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
[23:23:30] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:23:30] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[23:23:30] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[23:23:30] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
[23:23:30] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:971)
[23:23:30] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[23:23:30] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
can you post the full log as file?

also, ideally dont use curseforge but something like prism https://gtnh.miraheze.org/wiki/Installing_and_Migrating

**Comment by SanorusVentus** [comment]
[latest.log](https://github.com/user-attachments/files/15975091/latest.log)

**Comment by SanorusVentus** [comment]
> can you post the full log as file?
> 
> also, ideally dont use curseforge but something like prism https://gtnh.miraheze.org/wiki/Installing_and_Migrating

Posted above

**Comment by chochem** [comment]
ok there was a lot less in there than I expected. so is it straight-up missing gregtech in the mod folder? that is what it sounds like.

yea best solution would be to not use curseforge.

**Comment by BlueHero233** [comment]
@SanorusVentus can this be marked as resolved?

**Comment by BlueHero233** [comment]
Closed, no further response from author

**Comment by SanorusVentus** [comment]
> [@SanorusVentus](https://github.com/SanorusVentus) can this be marked as resolved?

Yes, I managed to get it working with Prism Launcher
