### ISSUE TITLE
Crash time for time when AE calculate crafts

### ISSUE THREAD

**Issue by Sheodar** [GTNewHorizons/GT-New-Horizons-Modpack#16642]
### Your GTNH Discord Username

sheodar

### Your Pack Version

nightly-538

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Tried to init craft (Essentia Provider). Time for time game just crash with log.

### Crash Report

```
Time: 2024-07-01 01:15:23 EEST
Description: Rendering screen

java.lang.IndexOutOfBoundsException
    at io.netty.buffer.EmptyByteBuf.readByte(EmptyByteBuf.java:439)
    at appeng.util.item.AEItemStack.loadItemStackFromPacket(AEItemStack.java:129)
    at appeng.core.api.ApiStorage.readItemFromPacket(ApiStorage.java:71)
    at appeng.container.implementations.ContainerCraftConfirm.getItemToCraft(ContainerCraftConfirm.java:255)
    at appeng.container.implementations.ContainerCraftConfirm.cpuCraftingSameItem(ContainerCraftConfirm.java:264)
    at appeng.container.implementations.ContainerCraftConfirm.cpuMatches(ContainerCraftConfirm.java:271)
    at appeng.client.gui.widgets.GuiCraftingCPUTable.drawFG(GuiCraftingCPUTable.java:110)
    at appeng.client.gui.implementations.GuiCraftConfirm.drawFG(GuiCraftConfirm.java:390)
    at appeng.client.gui.AEBaseGui.drawGuiContainerForegroundLayer(AEBaseGui.java:347)
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:119)
    at appeng.client.gui.AEBaseGui.drawScreen(AEBaseGui.java:146)
    at appeng.client.gui.implementations.GuiCraftConfirm.drawScreen(GuiCraftConfirm.java:324)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5110)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Screen render details --
Details:
    Screen name: com.glodblock.github.client.gui.GuiFluidCraftConfirm
    Mouse location: Scaled: (605, 9). Absolute: (1210, 1343)
    Screen size: Scaled: (1280, 681). Absolute: (2560, 1361). Scale factor of 2
Stacktrace:
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1067)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5110)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
    ```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by srdr2k3** [comment]
Can confirm this happens, downgrading ae2 to rc 405 fixes it, so it probably has to do with merge crafting jobs.
