### ISSUE TITLE
crash from description formatting

### ISSUE THREAD

**Issue by GamePlay677** [GTNewHorizons/GT-New-Horizons-Modpack#16686]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

When I started it 1 time everything was fine, but when I tried to start it 2 times the game froze on loading. Using the logs I found out that the game froze after "Sound engine started"

### Crash Report

[fml-client-latest.log](https://github.com/user-attachments/files/16113212/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
that says nothing about sounds engine, no. it says

```[22:21:25] [Client thread/ERROR] [FML/]: Caught exception from gregtech
java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_221]
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_221]
	at java.lang.String.format(Unknown Source) ~[?:1.8.0_221]
	at gregtech.common.blocks.GT_Item_Machines.addDescription(GT_Item_Machines.java:178) ~[GT_Item_Machines.class:?]```

**Comment by GamePlay677** [comment]
@chochem how can I fix this?

**Comment by chochem** [comment]
If I knew I would have said. :)

**Comment by Eldrinn-Elantey** [comment]
I ran into the same problem today

**Comment by Eldrinn-Elantey** [comment]
@GamePlay677 Did you change any of the GregTech.lang?
