### ISSUE TITLE
EIO‘s ArrayIndexOutOfBoundsException crash

### ISSUE THREAD

**Issue by NealDeal34** [GTNewHorizons/GT-New-Horizons-Modpack#16801]
### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

Maybe try to visit or search this item

### Crash Report

Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 4
	at crazypants.enderio.item.darksteel.upgrade.EnergyUpgrade.getAbsorptionRatio(EnergyUpgrade.java:262)
	at crazypants.enderio.item.darksteel.upgrade.EnergyUpgrade.addDetailedEntries(EnergyUpgrade.java:225)
	at crazypants.enderio.item.darksteel.DarkSteelRecipeManager.addAdvancedTooltipEntries(DarkSteelRecipeManager.java:206)
	at crazypants.enderio.item.darksteel.ItemDarkSteelPickaxe.addDetailedEntries(ItemDarkSteelPickaxe.java:317)
	at com.enderio.core.client.handlers.SpecialTooltipHandler.hasDetailedTooltip(SpecialTooltipHandler.java:142)
	at com.enderio.core.client.handlers.SpecialTooltipHandler.addInformation(SpecialTooltipHandler.java:124)
	at com.enderio.core.client.handlers.SpecialTooltipHandler.addTooltip(SpecialTooltipHandler.java:63)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_421_SpecialTooltipHandler_addTooltip_ItemTooltipEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:169)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:626)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:378)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:350)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73866_w_(GuiContainerCreative.java:262)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146280_a(GuiContainer.java)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73866_w_(SourceFile:34)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146280_a(GuiContainer.java)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1895)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:4506)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at crazypants.enderio.item.darksteel.upgrade.EnergyUpgrade.getAbsorptionRatio(EnergyUpgrade.java:262)
	at crazypants.enderio.item.darksteel.upgrade.EnergyUpgrade.addDetailedEntries(EnergyUpgrade.java:225)
	at crazypants.enderio.item.darksteel.DarkSteelRecipeManager.addAdvancedTooltipEntries(DarkSteelRecipeManager.java:206)
	at crazypants.enderio.item.darksteel.ItemDarkSteelPickaxe.addDetailedEntries(ItemDarkSteelPickaxe.java:317)
	at com.enderio.core.client.handlers.SpecialTooltipHandler.hasDetailedTooltip(SpecialTooltipHandler.java:142)
	at com.enderio.core.client.handlers.SpecialTooltipHandler.addInformation(SpecialTooltipHandler.java:124)
	at com.enderio.core.client.handlers.SpecialTooltipHandler.addTooltip(SpecialTooltipHandler.java:63)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_421_SpecialTooltipHandler_addTooltip_ItemTooltipEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:169)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:626)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:378)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:350)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73866_w_(GuiContainerCreative.java:262)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146280_a(GuiContainer.java)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73866_w_(SourceFile:34)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146280_a(GuiContainer.java)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by AnrDaemon** [comment]
Creative spawned End Steel armor crashes the game.
Seems to be the same stack trace.

[crash-2024-09-28_13.01.28-server.txt](https://github.com/user-attachments/files/17173982/crash-2024-09-28_13.01.28-server.txt)

**Comment by AnrDaemon** [comment]
Sure?
