### ISSUE TITLE
TravellersGear accesses IIconRegister on a dedicated server when trying an invalid item in slots

### ISSUE THREAD

**Issue by OvermindDL1** [GTNewHorizons/GT-New-Horizons-Modpack#16877]
### Your GTNH Discord Username

overminddl1

### Your Pack Version

2.6.1_java_17-21 release

### Your Server

Household dedicated server, not public

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

Was just quickly going through the travellers gear slots on that yellow inventory page when you click the icon to the top-left of your person in your inventory, grabbed my new AR OC Glasses and just trying it in random slots and first click crashed the server with the following stacktrace.

I have tried it multiple times and it crashes my server every single time reliably, just taking my AR Glasses and clicking in random travelers gear slots, such as glove, the storage one, etc...

### Crash Report

```java
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/IIconRegister
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
        at java.base/java.lang.Class.getMethodsRecursive(Class.java:3719)
        at java.base/java.lang.Class.getMethod0(Class.java:3705)
        at java.base/java.lang.Class.getMethod(Class.java:2393)
        at RFB-Launch//travellersgear.common.util.ModCompatability.canEquipTConAccessory(ModCompatability.java:48)
        at RFB-Launch//travellersgear.common.inventory.SlotRestricted.func_75214_a(SlotRestricted.java:53)
        at RFB-Launch//net.minecraft.inventory.Container.func_75144_a(SourceFile:239)
        at RFB-Launch//travellersgear.common.inventory.ContainerTravellersInv.func_75144_a(ContainerTravellersInv.java:299)
        at RFB-Launch//net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883)
        at RFB-Launch//net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32)
        at RFB-Launch//net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10)
        at RFB-Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
        at RFB-Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
        at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.IIconRegister in invalid class cache
        at RFB-System//net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:213)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 19 more
```

Interestingly this was only printed in the crash-reports directory, it did not appear in any log file in the normal logs directory although it was printed to the terminal just fine.  Pretty obvious crash at least, server-side should not be accessing client-side only classes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by OvermindDL1** [comment]
Also discovered that putting them in the correct slot also crashes, some weird interaction with AR Glasses and TGear?

**Comment by Darkenlord1** [comment]
You should put them in amulet slot
![image](https://github.com/user-attachments/assets/5b264a45-8192-4680-bdce-91e96f40921d) ![image](https://github.com/user-attachments/assets/a081d8e7-df9b-492b-83a1-ae3047eb5db0)

Also:
#15150
#11786

**Comment by OvermindDL1** [comment]
Ah I figured it was the same that the holo lenses went in, convenient there, worth losing my talisman most of the time.  Thanks, just tested, it does indeed work in that slot.

I completely missed those issues as I searched for IIconRegistry and other such stacktrace related keywords... which they seem to be entirely missing, fun fun...

**Comment by Ruling-0** [comment]
AR goggles should probably be usable in the mask slot, but it definitely shouldn't crash on invalid slot. Definitely still occurs on recent versions (personally had it in 2.7.2).

**Comment by barsikus007** [comment]
happen to me at Delta (https://discord.com/channels/181078474394566657/240526986211098624/1348187679334076506)

also it removed my UHV capacitor and personal nanohealing somehow

**Comment by chochem** [comment]
the mod is removed.
