### ISSUE TITLE
Subsequent SP load impossible and prevents graceful exit

### ISSUE THREAD

**Issue by Ruling-0** [GTNewHorizons/GT-New-Horizons-Modpack#16972]
### Your GTNH Discord Username

ruling_

### Your Pack Version

Nightly 563

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Actions

Hard to tell if crash or bug, but it does prevent the game session from continuing without force kill, so I think this qualifies as crash tag.

1. Entered a world
2. Exited the world
3. Created new world
4. Was forced to main menu
5. Tried to enter old world
6. Was also forced to main menu

Also happens if you skip the new world creation part, as in
1. Enter world
2. Exit World
3. Try to re-enter world
4. Back to main menu

Further, on closing the game, it must be killed because though the window closes the process does not actually exit

### Crash Report

This part seems to be the relevant bit
```
[01:23:05] [Server thread/TRACE] [coretweaks/]: Prevented crash while trying to log stack trace (java.lang.NoClassDefFoundError: net/minecraft/entity/EntityList$EntityEggInfo). Trying again using printStackTrace.
[01:23:05] [Server thread/ERROR] [FML/]: Caught exception from hodgepodge
java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.Monster.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.Monster.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}" at id stat.killEntity.Monster
	at Launch//net.minecraft.stats.StatBase.func_75971_g(SourceFile:42)
	at Launch//net.minecraft.stats.StatList.func_151182_a(StatList.java:212)
	at Launch//net.minecraft.entity.EntityList$EntityEggInfo.<init>(EntityList.java:321)
	at Launch//com.mitchej123.hodgepodge.util.StatHandler$EntityInfo.<init>(StatHandler.java:132)
	at Launch//com.mitchej123.hodgepodge.util.StatHandler.addEntityStats(StatHandler.java:91)
	at Launch//com.mitchej123.hodgepodge.Hodgepodge.onServerStarted(Hodgepodge.java:100)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at Launch//cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at System//com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at System//com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at System//com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at System//com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at System//com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at Launch//cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at Launch//cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at System//com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at System//com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at System//com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at System//com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at System//com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at Launch//cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at Launch//cpw.mods.fml.common.Loader.serverStarted(Loader.java:802)
	at Launch//cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:283)
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:389)
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
	
https://mclo.gs/uH7hfmr

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
does this still happen?

**Comment by Ruling-0** [comment]
Haven't noticed for a while.
