### ISSUE TITLE
Botania spreader ticking tile entity crashes world

### ISSUE THREAD

**Issue by Qmphcm5l** [GTNewHorizons/GT-New-Horizons-Modpack#17017]
### Your Pack Version

2.6.0

### Your Server

sp

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Left world running with me standing in my secure base, chunk loaded and protected(through server utilities) and went away, when i came back, game crashed and world now crashes on load.
World also crashes on 2.6.1

### Crash Report

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-08-15 22:29:02 CEST
Description: Ticking block entity

java.lang.ClassCastException: class vazkii.botania.common.block.tile.mana.TileSpreader cannot be cast to class gcewing.architecture.common.tile.TileShape (vazkii.botania.common.block.tile.mana.TileSpreader and gcewing.architecture.common.tile.TileShape are in unnamed module of loader 'RFB-Launch' @445b295b)
    at gcewing.architecture.common.block.BlockShape.getGlobalCollisionBoxes(BlockShape.java:151)
    at gcewing.architecture.common.block.BlockShape.collisionRayTrace(BlockShape.java:88)
    at gcewing.architecture.common.block.BlockArchitecture.collisionRayTrace(BlockArchitecture.java:517)
    at vazkii.botania.common.entity.EntityManaBurst.clip(EntityManaBurst.java:235)
    at vazkii.botania.common.entity.EntityManaBurst.superUpdate(EntityManaBurst.java:158)
    at vazkii.botania.common.entity.EntityManaBurst.onUpdate(EntityManaBurst.java:361)
    at vazkii.botania.common.entity.EntityManaBurst.getCollidedTile(EntityManaBurst.java:418)
    at vazkii.botania.common.block.tile.mana.TileSpreader.checkForReceiver(TileSpreader.java:458)
    at vazkii.botania.common.block.tile.mana.TileSpreader.updateEntity(TileSpreader.java:203)
    at net.minecraft.world.World.updateEntities(World.java:1939)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block entity being ticked --
Details:
    Name: botania:spreader // vazkii.botania.common.block.tile.mana.TileSpreader
    Block type: ID #1591 (tile.architecturecraft:shapeSE // gcewing.architecture.common.block.BlockShape)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-723,67,150), Chunk: (at 13,4,6 in -46,9; contains blocks -736,0,144 to -721,255,159), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
    Actual block type: ID #1591 (tile.architecturecraft:shapeSE // gcewing.architecture.common.block.BlockShape)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at RFB-Launch//net.minecraft.world.World.func_72939_s(World.java:1944)
    at RFB-Launch//net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at RFB-Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
-- Affected level --
Details:
    Level name: World
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 830 Drop: 0
    Level seed: -2940991287403842682
    Level generator: ID 04 - RWG, ver 0. Features enabled: true
    Level generator options: 2;1x7,52x24,1x3:2,;2;biome_1,village
    Level spawn location: World: (-247,64,36), Chunk: (at 9,4,4 in -16,2; contains blocks -256,0,32 to -241,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 15270060 game time, 24483881 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 61066 (now: false), thunder time: 17710 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 6.10.4-arch2-1
    Java Version: 17.0.12, Arch Linux
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Arch Linux
    Memory: 1299023552 bytes (1238 MB) / 4307550208 bytes (4108 MB) up to 8589934592 bytes (8192 MB)
    JVM Flags: 2 total; -Xms512m -Xmx8192m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 408
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Angelica 1.0.0-alpha50 
    Suspected Mods: ArchitectureCraft (ArchitectureCraft), Botania (Botania)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Pxx500** [comment]
1) don't paste logs directly into github
2) did you bother testing new pack versions before submitting a bug report for an old version?

**Comment by Qmphcm5l** [comment]
Well i tried 2.6.1 but not the nightly ones
