### ISSUE TITLE
BetterQuesting crashes when using wildcard damage

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#17093]
### Your GTNH Discord Username

chochem

### Your Pack Version

nightly-593 mostly

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

tried to use 32767 damage value for tinkers construct tool forge task in the quest.

It does seem to work, indeed BQ supports this for the most part. but then the game suddenly hangs fully. It seems like some rendering code does not support it.

### Crash Report

`Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 32676 out of bounds for length 14
	at tconstruct.tools.blocks.ToolForgeBlock.getIcon(ToolForgeBlock.java:77) ~[ToolForgeBlock.class:?]
	at tconstruct.tools.model.TableRender.renderStandardInvBlock(TableRender.java:96) ~[TableRender.class:?]
	at tconstruct.tools.model.TableRender.renderInventoryBlock(TableRender.java:33) ~[TableRender.class:?]
	at cpw.mods.fml.client.registry.RenderingRegistry.renderInventoryBlock(RenderingRegistry.java:125) ~[RenderingRegistry.class:?]
	at FMLRenderAccessLibrary.renderInventoryBlock(FMLRenderAccessLibrary.java:59) ~[FMLRenderAccessLibrary.class:?]
	at net.minecraft.client.renderer.RenderBlocks.renderBlockAsItem(RenderBlocks.java:8145) ~[blm.class:?]
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446) ~[bny.class:?]
	at net.minecraft.client.renderer.entity.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:565) ~[bny.class:?]
	at betterquesting.api.utils.RenderUtils.RenderItemStack(RenderUtils.java:80) ~[RenderUtils.class:?]
	at betterquesting.api2.client.gui.resources.textures.ItemTexture.drawTexture(ItemTexture.java:80) ~[ItemTexture.class:?]
	at betterquesting.api2.client.gui.resources.textures.ItemTexture.drawTexture(ItemTexture.java:49) ~[ItemTexture.class:?]
	at betterquesting.api2.client.gui.resources.textures.SlideShowTexture.drawTexture(SlideShowTexture.java:26) ~[SlideShowTexture.class:?]
	at betterquesting.api2.client.gui.controls.PanelButton.drawPanel(PanelButton.java:195) ~[PanelButton.class:?]
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:60) ~[CanvasEmpty.class:?]
	at betterquesting.api2.client.gui.panels.CanvasEmpty.drawPanel(CanvasEmpty.java:60) ~[CanvasEmpty.class:?]
	at betterquesting.api2.client.gui.panels.CanvasTextured.drawPanel(CanvasTextured.java:27) ~[CanvasTextured.class:?]
	at betterquesting.api2.client.gui.GuiScreenCanvas.drawPanel(GuiScreenCanvas.java:290) ~[GuiScreenCanvas.class:?]
	at betterquesting.api2.client.gui.GuiScreenCanvas.drawScreen(GuiScreenCanvas.java:202) ~[GuiScreenCanvas.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1061) ~[blt.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:5110) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) ~[minecraft-1.7.10-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250) ~[lwjgl3ify-2.1.2-forgePatches.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:35) ~[lwjgl3ify-2.1.2-forgePatches.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:60) ~[lwjgl3ify-2.1.2-forgePatches.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:207) ~[lwjgl3ify-2.1.2-forgePatches.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[StandardLauncher.class:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[EntryPoint.class:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[EntryPoint.class:?]`

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Cardinalstars** [comment]
This fix might be related: https://github.com/GTNewHorizons/BetterQuesting/pull/150 I've yet to replicate this exception though exactly.

**Comment by Baerschen** [comment]
I think we can close this. Did some testing on newest nightly with https://github.com/GTNewHorizons/BetterQuesting/pull/150 merged and there have been no issued whatsoever. We can properly do the quest with a wildcard now and possible other wildcards where applicable. Thanks for the quick fix @Cardinalstars
