### ISSUE TITLE
"Modelview matrix stack too deep"

### ISSUE THREAD

**Issue by riking** [GTNewHorizons/GT-New-Horizons-Modpack#17133]
### Your GTNH Discord Username

kanepyork

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

This is likely related to setting up my first Extreme Entity Crusher.

Put a Redcap Sapper powered spawner in and power it.

### The Reality

When standing in front of the EEC with the animation on, viewing the Mob Drops NEI page for the Redcap Sapper results in bad GUI glitching:

![image](https://github.com/user-attachments/assets/35ce6eb8-abbf-444a-a07a-91aea4f7177f)

Additionally, after leaving the area and interacting with inventories in some way, the chat starts reporting item rendering failures:

```
[20:13:17] [Client thread/INFO] [STDERR]: [codechicken.nei.NEIClientUtils:reportErrorBuffered:459]: Error while rendering: 1xtile.blockCosmeticSlabStone@0
...
[20:13:17] [Client thread/INFO] [STDERR]: [codechicken.nei.NEIClientUtils:reportErrorBuffered:459]: Error while rendering: 1xtile.blockCosmeticDoubleSlabStone@0
...
[20:13:17] [Client thread/INFO] [STDERR]: [codechicken.nei.NEIClientUtils:reportErrorBuffered:459]: Error while rendering: 1xtile.blockLootUrn@0
...
[20:13:17] [Client thread/INFO] [STDERR]: [codechicken.nei.NEIClientUtils:reportErrorBuffered:459]: Error while rendering: 1xtile.blockCosmeticDoubleSlabWood@0
...
[20:13:17] [Client thread/INFO]: [CHAT] There was error during rendering item. Please check log for details.§7 (48)
[20:13:17] [Client thread/INFO] [STDERR]: [codechicken.nei.NEIClientUtils:reportErrorBuffered:459]: Error while rendering: 1xtile.blockLootUrn@1
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.IllegalStateException: Modelview matrix stack too deep
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:308)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:256)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:252)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.guihook.GuiContainerManager.drawItem(GuiContainerManager.java:248)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.ItemsGrid.drawItem(ItemsGrid.java:377)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.ItemsGrid.drawItems(ItemsGrid.java:315)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.ItemsGrid.draw(ItemsGrid.java:362)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.PanelWidget.draw(PanelWidget.java:182)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.LayoutManager.renderObjects(LayoutManager.java:264)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.guihook.GuiContainerManager.renderObjects(GuiContainerManager.java:501)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:120)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5110)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.main.Main.main(SourceFile:148)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//net.minecraft.launchwrapper.Launch.main(Launch.java:60)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:219)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[20:13:17] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
[20:13:17] [Client thread/INFO]: [CHAT] There was error during rendering item. Please check log for details.§7 (49)
```

### Your Proposal

stop leaking entries into the model view matrix stack

Possibly related but reports an OpenComputers fix: GTNewHorizons/GT-New-Horizons-Modpack#14311

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by riking** [comment]
Oh also, the error first appeared 4 times at once then later 49 times at once. I suspect the items mentioned in the error logs are "victim items" failing due to an earlier leak related to rendering the same mob in the EEC and NEI at the same time.
