### ISSUE TITLE
GregTech global_energy rework / fix gt global_energy_join

### ISSUE THREAD

**Issue by Tctcl** [GTNewHorizons/GT-New-Horizons-Modpack#17151]
### Your GTNH Discord Username

tctcl

### Your Pack Version

2.6.1

### Your Proposal

The current `/gt global_energy_join` / `add` / `set` commands can be a bit confusing and have some minor bugs and annoyances in them. Some examples include the `global_energy_join` teams resetting on server reboot, `global_energy_join` only working if you've got OP permissions and the chat messages when executing those commands not being correct. I want to rework that system slightly and fix those bugs.

My proposal is this:

Introduce 4 new non-op commands:

- /sp info
 - displays all team members and stored global energy

- /sp kick [username]
 - kick someone from your team

- /sp disband
 - kick all team members

 - /gt global_energy members [team]
 - displays all team members of team
 
 Change the current commands to follow this scheme:
 
 - /gt global_energy join [team] [user]
 - adds user to team forcibly

- /gt global_energy set [user] [eu]
 - set teams eu to [eu]

- /gt global_energy add [user] [eu]
 - add [eu] to team (can be negative numbers)
 
 Fix bugs:
 
 - ~~teams resetting on server restart~~ fixed
 
 
 I'm willing to make these changes myself and have already forked the repo / started working on it. Just want to confirm if this is something others want to see.

### Your Goal

The system is currently confusing and bugged and thus annoying me as a server host a lot.

### Your Vision

The system would be easy to understand and do exactly what you expect it to do.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Tctcl** [comment]
I've also found that the commands don't check if the command arguments have been passed and can thus be executed without them resulting in an error:

```
gt global_energy_join
[01:40:01] [Server thread/INFO]: An unknown error occurred while attempting to perform this command
[01:40:01] [Server thread/ERROR]: Couldn't process command: 'gt global_energy_join'
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at RFB-Launch//gregtech.common.misc.GT_Command.func_71515_b(GT_Command.java:261) ~[GT_Command.class:?]
        at RFB-Launch//serverutils.ranks.CommandOverride.func_71515_b(CommandOverride.java:70) ~[CommandOverride.class:?]
        at RFB-Launch//net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
        at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:370) [lt.class:?]
        at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335) [lt.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by ExileWeirdo** [comment]
Very cool yesyes me support

**Comment by Tctcl** [comment]
Networks resetting has been fixed with https://github.com/GTNewHorizons/GT5-Unofficial/pull/3000
