### ISSUE TITLE
Various Antimatter Forge bugs

### ISSUE THREAD

**Issue by Miklebe** [GTNewHorizons/GT-New-Horizons-Modpack#17322]
### Your GTNH Discord Username

mike_be

### Your Pack Version

nightly 644

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Everything works without any problems no matter what hatch is used/how multi is rotated. :clueless:

### The Reality

Will contain a various list of bugs found/suggested changes when done more testing, will most likely expand later (too laze to make new tickets each time):

- [x] Render of dripping fluid (protonmatter) doesn't care about rotation.
<details>
  <summary>Example</summary>
<img src="https://github.com/user-attachments/assets/1315e020-7632-4f98-b052-18648cf4da60">
</details>

- [x] Hologram projection doesn't mention the use for 3 dot hint blocks (the 2 dot blocks got thanos snapped).
<details>
  <summary>Example</summary>
<img src="https://github.com/user-attachments/assets/3f3130eb-aa5f-44b7-b35b-edbd3da94110">
</details>

- [x] (found by bright0422 on discord) When using Advanced Stocking Input Hatches to supply Stabilization fluids with autopull, the forge crashes with error.
<details>
  <summary>Crash log</summary>

```java
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 2
    at Launch//goodgenerator.blocks.tileEntity.AntimatterForge.setModifiers(AntimatterForge.java:466)
    at Launch//goodgenerator.blocks.tileEntity.AntimatterForge.checkProcessing(AntimatterForge.java:527)
    at Launch//gregtech.api.metatileentity.implementations.MTEMultiBlockBase.checkRecipe(MTEMultiBlockBase.java:540)
    at Launch//gregtech.api.metatileentity.implementations.MTEMultiBlockBase.runMachine(MTEMultiBlockBase.java:639)
    at Launch//gregtech.api.metatileentity.implementations.MTEMultiBlockBase.onPostTick(MTEMultiBlockBase.java:472)
    at Launch//goodgenerator.blocks.tileEntity.AntimatterForge.onPostTick(AntimatterForge.java:424)
    at Launch//gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:568)
    at Launch//net.minecraft.world.World.func_72939_s(World.java:1939)
    at Launch//net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)```
</details>

### Your Proposal

Is it possible for render to know, where the hatches are placed? Like let it drip depending on where there are input hatches.
If not, just make it working with rotations :D

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Miklebe** [comment]
With the release of 2.7.0 beta, all mentioned issues were fixed.
