### ISSUE TITLE
OpenModularTurrets

### ISSUE THREAD

**Issue by AsimutMLS** [GTNewHorizons/GT-New-Horizons-Modpack#17355]
### Your GTNH Discord Username

asimut

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

I put the base from the turret and now no one can enter the server

### Crash Report

[15:48:38] [Client thread/INFO] [TC4TweakTransformer]: Transforming class thaumcraft.client.gui.MappingThread
[15:48:38] [Thread-40/INFO] [TC4Tweaks]: TC4 Mapping start. 14058 entries to work with.
[15:48:39] [Thread-40/INFO] [TC4Tweaks]: TC4 Mapping finish. Took 576240900ns. Priority boosted: true
[15:48:39] [Client thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: java.io.EOFException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [netty-all-4.0.10.Final.jar:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5110) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_361]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_361]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_361]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_361]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at launcher.IIIIiiiiiiIiIiIiIIiiIIIiIiIiiIIIiIIIIIIIIiIiiIiIiiIIiIIiIIIIiIiIIIiiiIIIIIiiiiIiiiIIIIiiIIiIiiiiiiiiIIIiiiiiiiiiiIIIiiIIiIIiIIIIiiiiIiIIIIIIiiiIiIiIiiiiIIIIIiIiiiiIiIIiiiIiiIiiiIIIiIiIIIIiiiIIIIiiiIIIiIIiiIiiIiIiIiiIiIIIIiIiIIiIIIiiiiiIiiIIIiiiIIiIIIIiiIiiIIiiiiiIIiiiiiIiiiiiIiIiiIiIIiIiIIIIiiiiiIiiiIiIIiIiIIiiiiiIIIiIIiIIIIiiiiIIiiIIIIIiiiiIIiiiIiiiIIiiiiiiIiiiIIiiiIiIiiiIIIIIIiiiiiIiiiIIIIIiiiIiIiIIIiiIIIiIiIIiiIIIiiIiiiIIIiiIiIIIIiIIIIiIiIiiiiiIIiiIiIiIIiIIIiiIIIIIiIiIiiIIiIIIIIiiIIIiIIIiiIiI.IiIIiIIiiiIiIiiIiiIIIIiiiiiIiiIIiiiiIiIiiIiiIiIIiIiiIIIIIiIiiIiIIIIIiiIIiIiIiIiiIIiIIIiiiiiiiiiIIiIIiIIIIIIIiiIIIIIIIiIIiIiIiIiiIIIIIiiiIiiiiIiIiIiiIiiiiiiiIIiiIiiiIiIiIiIiiiIIIIiiIiIiIiiiiIIIiIiiIIIiiiIiIiiiIiIIiIiiiiiIiIIiiiIIIiiIIiiiiiIiIiiIIIiIIIiIiIiiiiiiIIIIiIiiIiIIiiiiIiiIiiiiiIIiiIiIiIiiIiiIIiiiIIIiIiiiiiIiiIIiIIIIIIIiiiIiiiIiIiIiIIiiIiIIIIIIiiIiiiiIiiIIiIIiIiIiIIIIiiiiIiiIiIIiIIIIIIIiiiiIiIiIIIiIIiiIIiiiIIiiiiiiiiIIiiIiIIiiiIIIIIiIiIiiIiIIiiIIiIIIiiiiiIiIIiIIIiIiIiiiIiiIiiIIiiIiIIiIiIIi(Unknown Source) [Next-Mine.exe:?]
	at launcher.IIIIiiiiiiIiIiIiIIiiIIIiIiIiiIIIiIIIIIIIIiIiiIiIiiIIiIIiIIIIiIiIIIiiiIIIIIiiiiIiiiIIIIiiIIiIiiiiiiiiIIIiiiiiiiiiiIIIiiIIiIIiIIIIiiiiIiIIIIIIiiiIiIiIiiiiIIIIIiIiiiiIiIIiiiIiiIiiiIIIiIiIIIIiiiIIIIiiiIIIiIIiiIiiIiIiIiiIiIIIIiIiIIiIIIiiiiiIiiIIIiiiIIiIIIIiiIiiIIiiiiiIIiiiiiIiiiiiIiIiiIiIIiIiIIIIiiiiiIiiiIiIIiIiIIiiiiiIIIiIIiIIIIiiiiIIiiIIIIIiiiiIIiiiIiiiIIiiiiiiIiiiIIiiiIiIiiiIIIIIIiiiiiIiiiIIIIIiiiIiIiIIIiiIIIiIiIIiiIIIiiIiiiIIIiiIiIIIIiIIIIiIiIiiiiiIIiiIiIiIIiIIIiiIIIIIiIiIiiIIiIIIIIiiIIIiIIIiiIiI.main(Unknown Source) [Next-Mine.exe:?]
Caused by: java.lang.RuntimeException: java.io.EOFException
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.network.ByteBufUtils.readItemStack(ByteBufUtils.java:172) ~[ByteBufUtils.class:?]
	at openmodularturrets.network.messages.MessageTurretBase.fromBytes(MessageTurretBase.java:91) ~[MessageTurretBase.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[netty-all-4.0.10.Final.jar:?]
	... 20 more
Caused by: java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.readUShort(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_361]
	at net.minecraft.nbt.CompressedStreamTools.func_152457_a(CompressedStreamTools.java:60) ~[du.class:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(SourceFile:963) ~[et.class:?]
	at net.minecraft.network.PacketBuffer.func_150791_c(SourceFile:116) ~[et.class:?]
	at cpw.mods.fml.common.network.ByteBufUtils.readItemStack(ByteBufUtils.java:168) ~[ByteBufUtils.class:?]
	at openmodularturrets.network.messages.MessageTurretBase.fromBytes(MessageTurretBase.java:91) ~[MessageTurretBase.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[netty-all-4.0.10.Final.jar:?]
	... 20 more
[15:48:39] [Client thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: java.io.EOFException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [netty-all-4.0.10.Final.jar:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5110) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_361]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_361]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_361]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_361]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at launcher.IIIIiiiiiiIiIiIiIIiiIIIiIiIiiIIIiIIIIIIIIiIiiIiIiiIIiIIiIIIIiIiIIIiiiIIIIIiiiiIiiiIIIIiiIIiIiiiiiiiiIIIiiiiiiiiiiIIIiiIIiIIiIIIIiiiiIiIIIIIIiiiIiIiIiiiiIIIIIiIiiiiIiIIiiiIiiIiiiIIIiIiIIIIiiiIIIIiiiIIIiIIiiIiiIiIiIiiIiIIIIiIiIIiIIIiiiiiIiiIIIiiiIIiIIIIiiIiiIIiiiiiIIiiiiiIiiiiiIiIiiIiIIiIiIIIIiiiiiIiiiIiIIiIiIIiiiiiIIIiIIiIIIIiiiiIIiiIIIIIiiiiIIiiiIiiiIIiiiiiiIiiiIIiiiIiIiiiIIIIIIiiiiiIiiiIIIIIiiiIiIiIIIiiIIIiIiIIiiIIIiiIiiiIIIiiIiIIIIiIIIIiIiIiiiiiIIiiIiIiIIiIIIiiIIIIIiIiIiiIIiIIIIIiiIIIiIIIiiIiI.IiIIiIIiiiIiIiiIiiIIIIiiiiiIiiIIiiiiIiIiiIiiIiIIiIiiIIIIIiIiiIiIIIIIiiIIiIiIiIiiIIiIIIiiiiiiiiiIIiIIiIIIIIIIiiIIIIIIIiIIiIiIiIiiIIIIIiiiIiiiiIiIiIiiIiiiiiiiIIiiIiiiIiIiIiIiiiIIIIiiIiIiIiiiiIIIiIiiIIIiiiIiIiiiIiIIiIiiiiiIiIIiiiIIIiiIIiiiiiIiIiiIIIiIIIiIiIiiiiiiIIIIiIiiIiIIiiiiIiiIiiiiiIIiiIiIiIiiIiiIIiiiIIIiIiiiiiIiiIIiIIIIIIIiiiIiiiIiIiIiIIiiIiIIIIIIiiIiiiiIiiIIiIIiIiIiIIIIiiiiIiiIiIIiIIIIIIIiiiiIiIiIIIiIIiiIIiiiIIiiiiiiiiIIiiIiIIiiiIIIIIiIiIiiIiIIiiIIiIIIiiiiiIiIIiIIIiIiIiiiIiiIiiIIiiIiIIiIiIIi(Unknown Source) [Next-Mine.exe:?]
	at launcher.IIIIiiiiiiIiIiIiIIiiIIIiIiIiiIIIiIIIIIIIIiIiiIiIiiIIiIIiIIIIiIiIIIiiiIIIIIiiiiIiiiIIIIiiIIiIiiiiiiiiIIIiiiiiiiiiiIIIiiIIiIIiIIIIiiiiIiIIIIIIiiiIiIiIiiiiIIIIIiIiiiiIiIIiiiIiiIiiiIIIiIiIIIIiiiIIIIiiiIIIiIIiiIiiIiIiIiiIiIIIIiIiIIiIIIiiiiiIiiIIIiiiIIiIIIIiiIiiIIiiiiiIIiiiiiIiiiiiIiIiiIiIIiIiIIIIiiiiiIiiiIiIIiIiIIiiiiiIIIiIIiIIIIiiiiIIiiIIIIIiiiiIIiiiIiiiIIiiiiiiIiiiIIiiiIiIiiiIIIIIIiiiiiIiiiIIIIIiiiIiIiIIIiiIIIiIiIIiiIIIiiIiiiIIIiiIiIIIIiIIIIiIiIiiiiiIIiiIiIiIIiIIIiiIIIIIiIiIiiIIiIIIIIiiIIIiIIIiiIiI.main(Unknown Source) [Next-Mine.exe:?]
Caused by: java.lang.RuntimeException: java.io.EOFException
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.network.ByteBufUtils.readItemStack(ByteBufUtils.java:172) ~[ByteBufUtils.class:?]
	at openmodularturrets.network.messages.MessageTurretBase.fromBytes(MessageTurretBase.java:91) ~[MessageTurretBase.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[netty-all-4.0.10.Final.jar:?]
	... 20 more
Caused by: java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.readUShort(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_361]
	at net.minecraft.nbt.CompressedStreamTools.func_152457_a(CompressedStreamTools.java:60) ~[du.class:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(SourceFile:963) ~[et.class:?]
	at net.minecraft.network.PacketBuffer.func_150791_c(SourceFile:116) ~[et.class:?]
	at cpw.mods.fml.common.network.ByteBufUtils.readItemStack(ByteBufUtils.java:168) ~[ByteBufUtils.class:?]
	at openmodularturrets.network.messages.MessageTurretBase.fromBytes(MessageTurretBase.java:91) ~[MessageTurretBase.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[netty-all-4.0.10.Final.jar:?]
	... 20 more
[15:48:39] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel openmodularturrets
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: java.io.EOFException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[netty-all-4.0.10.Final.jar:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5110) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_361]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_361]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_361]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_361]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at launcher.IIIIiiiiiiIiIiIiIIiiIIIiIiIiiIIIiIIIIIIIIiIiiIiIiiIIiIIiIIIIiIiIIIiiiIIIIIiiiiIiiiIIIIiiIIiIiiiiiiiiIIIiiiiiiiiiiIIIiiIIiIIiIIIIiiiiIiIIIIIIiiiIiIiIiiiiIIIIIiIiiiiIiIIiiiIiiIiiiIIIiIiIIIIiiiIIIIiiiIIIiIIiiIiiIiIiIiiIiIIIIiIiIIiIIIiiiiiIiiIIIiiiIIiIIIIiiIiiIIiiiiiIIiiiiiIiiiiiIiIiiIiIIiIiIIIIiiiiiIiiiIiIIiIiIIiiiiiIIIiIIiIIIIiiiiIIiiIIIIIiiiiIIiiiIiiiIIiiiiiiIiiiIIiiiIiIiiiIIIIIIiiiiiIiiiIIIIIiiiIiIiIIIiiIIIiIiIIiiIIIiiIiiiIIIiiIiIIIIiIIIIiIiIiiiiiIIiiIiIiIIiIIIiiIIIIIiIiIiiIIiIIIIIiiIIIiIIIiiIiI.IiIIiIIiiiIiIiiIiiIIIIiiiiiIiiIIiiiiIiIiiIiiIiIIiIiiIIIIIiIiiIiIIIIIiiIIiIiIiIiiIIiIIIiiiiiiiiiIIiIIiIIIIIIIiiIIIIIIIiIIiIiIiIiiIIIIIiiiIiiiiIiIiIiiIiiiiiiiIIiiIiiiIiIiIiIiiiIIIIiiIiIiIiiiiIIIiIiiIIIiiiIiIiiiIiIIiIiiiiiIiIIiiiIIIiiIIiiiiiIiIiiIIIiIIIiIiIiiiiiiIIIIiIiiIiIIiiiiIiiIiiiiiIIiiIiIiIiiIiiIIiiiIIIiIiiiiiIiiIIiIIIIIIIiiiIiiiIiIiIiIIiiIiIIIIIIiiIiiiiIiiIIiIIiIiIiIIIIiiiiIiiIiIIiIIIIIIIiiiiIiIiIIIiIIiiIIiiiIIiiiiiiiiIIiiIiIIiiiIIIIIiIiIiiIiIIiiIIiIIIiiiiiIiIIiIIIiIiIiiiIiiIiiIIiiIiIIiIiIIi(Unknown Source) [Next-Mine.exe:?]
	at launcher.IIIIiiiiiiIiIiIiIIiiIIIiIiIiiIIIiIIIIIIIIiIiiIiIiiIIiIIiIIIIiIiIIIiiiIIIIIiiiiIiiiIIIIiiIIiIiiiiiiiiIIIiiiiiiiiiiIIIiiIIiIIiIIIIiiiiIiIIIIIIiiiIiIiIiiiiIIIIIiIiiiiIiIIiiiIiiIiiiIIIiIiIIIIiiiIIIIiiiIIIiIIiiIiiIiIiIiiIiIIIIiIiIIiIIIiiiiiIiiIIIiiiIIiIIIIiiIiiIIiiiiiIIiiiiiIiiiiiIiIiiIiIIiIiIIIIiiiiiIiiiIiIIiIiIIiiiiiIIIiIIiIIIIiiiiIIiiIIIIIiiiiIIiiiIiiiIIiiiiiiIiiiIIiiiIiIiiiIIIIIIiiiiiIiiiIIIIIiiiIiIiIIIiiIIIiIiIIiiIIIiiIiiiIIIiiIiIIIIiIIIIiIiIiiiiiIIiiIiIiIIiIIIiiIIIIIiIiIiiIIiIIIIIiiIIIiIIIiiIiI.main(Unknown Source) [Next-Mine.exe:?]
Caused by: java.lang.RuntimeException: java.io.EOFException
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.network.ByteBufUtils.readItemStack(ByteBufUtils.java:172) ~[ByteBufUtils.class:?]
	at openmodularturrets.network.messages.MessageTurretBase.fromBytes(MessageTurretBase.java:91) ~[MessageTurretBase.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[netty-all-4.0.10.Final.jar:?]
	... 20 more
Caused by: java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.readUShort(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_361]
	at net.minecraft.nbt.CompressedStreamTools.func_152457_a(CompressedStreamTools.java:60) ~[du.class:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(SourceFile:963) ~[et.class:?]
	at net.minecraft.network.PacketBuffer.func_150791_c(SourceFile:116) ~[et.class:?]
	at cpw.mods.fml.common.network.ByteBufUtils.readItemStack(ByteBufUtils.java:168) ~[ByteBufUtils.class:?]
	at openmodularturrets.network.messages.MessageTurretBase.fromBytes(MessageTurretBase.java:91) ~[MessageTurretBase.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[netty-all-4.0.10.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[netty-all-4.0.10.Final.jar:?]
	... 20 more
[15:48:39] [Netty Client IO #1/INFO] [THAUMCRAFT]: Restoring client configs.
[15:48:39] [Netty Client IO #1/INFO] [EnderCore]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[15:48:39] [Netty Client IO #1/INFO] [EnderCore]: Reset configs to client values for tterrag.wailaplugins.config.WPConfigHandler

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Cardinalstars** [comment]
Just to be clear, this isn't crashing your server, but your client is crashing or just getting rejected when joining the server?

**Comment by AsimutMLS** [comment]
> Just to be clear, this isn't crashing your server, but your client is crashing or just getting rejected when joining the server? If you could provide some more information on what kind of turret you placed, and what items might be inside of it. I'm having a really hard time reproducing this one.
> 
> I am assuming you used a Camo upgrade on one of the turret bases. If you didn't that's important to know.

This crash was caused by incorrectly written network packages.
they were over the reading limit.
