### ISSUE TITLE
Crash with Amun-Ra mod

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#17362]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I exited my world, entered it and got crash.
Before I was testing Amun-Ra Mothership in **another** world and left it on orbit of Proxima Centaura which is unpossible to land on (report says that "Mothership with dim ID 9 has no celestial body. This is bad!").
May be close to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16605

### Crash Report

[crash-2024-09-16_16.04.51-server.txt](https://github.com/user-attachments/files/17013623/crash-2024-09-16_16.04.51-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Quaerere-Git** [comment]
I have encounted the same crash just when I re-entered a world in SP even without using actual mothership.
I am on 2.7.0-beta2 on Java 19.

**Comment by Ya9yu** [comment]
I had a similar crash as in the situation above 2.7.0 java 21
[crash-2024-12-15_21.31.28-server.txt](https://github.com/user-attachments/files/18140859/crash-2024-12-15_21.31.28-server.txt)
[crash-2024-12-15_21.29.48-server.txt](https://github.com/user-attachments/files/18140862/crash-2024-12-15_21.29.48-server.txt)

**Comment by Armelia-William** [comment]
When I play a save file for a long time and then return to the main menu and enter any save file again, this problem will be triggered.
2.70,2.71 and 2.72 Java8
[01:42:59] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[01:42:59] [Server thread/INFO]: Generating keypair
[01:43:00] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: java.lang.RuntimeException: Mothership with dim ID 6 has no celestial body. This is bad!
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:304) ~[DimensionManager.class:?]
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160) ~[aqo.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) ~[mt.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14) ~[mm.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65) ~[bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.RuntimeException: Mothership with dim ID 6 has no celestial body. This is bad!
	at de.katzenpapst.amunra.mothership.MothershipWorldProvider.setDimension(MothershipWorldProvider.java:172) ~[MothershipWorldProvider.class:?]
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:292) ~[DimensionManager.class:?]
	... 7 more
[01:43:00] [Server thread/ERROR]: This crash report has been saved to: F:\Minecraft\混合\.minecraft\versions\GTNH 2.7.2\crash-reports\crash-2025-01-04_01.43.00-server.txt
[01:43:08] [Client thread/INFO]: Stopping!

**Comment by Armelia-William** [comment]
When I play a save file for a long time and then return to the main menu and enter any save file again, this problem will be triggered.
2.70,2.71 and 2.72 Java 8

[01:42:59] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[01:42:59] [Server thread/INFO]: Generating keypair
[01:43:00] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: java.lang.RuntimeException: Mothership with dim ID 6 has no celestial body. This is bad!
at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:304) ~[DimensionManager.class:?]
at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160) ~[aqo.class:?]
at net.minecraft.world.WorldServer.(WorldServer.java:97) ~[mt.class:?]
at net.minecraft.world.WorldServerMulti.(WorldServerMulti.java:14) ~[mm.class:?]
at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65) ~[bsx.class:?]
at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) ~[bsx.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.RuntimeException: Mothership with dim ID 6 has no celestial body. This is bad!
at de.katzenpapst.amunra.mothership.MothershipWorldProvider.setDimension(MothershipWorldProvider.java:172) ~[MothershipWorldProvider.class:?]
at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:292) ~[DimensionManager.class:?]
... 7 more
[01:43:00] [Server thread/ERROR]: This crash report has been saved to: F:\Minecraft\minecraft\versions\GTNH 2.7.2\crash-reports\crash-2025-01-04_01.43.00-server.txt
[01:43:08] [Client thread/INFO]: Stopping!

**Comment by RecursivePineapple** [comment]
Another crash (not mine): https://mclo.gs/h6T0ub8

**Comment by Yoshy2002** [comment]
still exists in 856 and probably later

**Comment by glacialvitality** [comment]
not sure if this is the original report, but can confirm on 2.8-RC1

Client Log (snippet of it from last world exit to game crash): https://mclo.gs/3RhMGbT
Crash Report: https://mclo.gs/0Mtopza

**Comment by Flakxo** [comment]
Still exists as of daily 184, i can consistently trigger it by joining a singleplayer world that has a mothership, leaving, joining my main singleplayer world that does not have/has never created a mothership, leaving that, then rejoining my main singleplayer world

https://mclo.gs/PZQes9O - crash
https://mclo.gs/TpmWAjV - fml client latest(from a long play session, sorry, look around line 173187)
https://mclo.gs/QaZd7oC - latest(shows me entering both worlds)
