### ISSUE TITLE
Server crashed when /home at DIM1

### ISSUE THREAD

**Issue by XeonKA** [GTNewHorizons/GT-New-Horizons-Modpack#17459]
### Your GTNH Discord Username

XeonKA

### Your Pack Version

2.7.0 beta1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Actions

1.At DIM1,enter command/home to teleport personalDIM.
Server Crashed.
/cofh tpx works fine.
2.After removing Morpheus,doing the same thing at DIM1:
![QQ20240926-005334](https://github.com/user-attachments/assets/675432d2-697e-44d2-8443-7165f3cd3ca4)
3.After step2,enter /home again,works fine.

### Crash Report

[crash-2024-09-25_20.42.27-server.txt](https://github.com/user-attachments/files/17135296/crash-2024-09-25_20.42.27-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by XeonKA** [comment]
2.8.0 beta1 still have this issue.

**Comment by paulzzh** [comment]
Still appearing in 2.7.2 when `/home`
```
java.lang.NullPointerException: Cannot invoke "net.quetzi.morpheus.world.WorldSleepState.isPlayerSleeping(String)" because the return value of "java.util.HashMap.get(Object)" is null
        at net.quetzi.morpheus.SleepChecker.updatePlayerStates(SleepChecker.java:26)
        at net.quetzi.morpheus.MorpheusEventHandler.worldTickEvent(MorpheusEventHandler.java:61)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_1502_MorpheusEventHandler_worldTickEvent_WorldTickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:61)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:183)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:259)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1009)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:845)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:695)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```
https://mclo.gs/ZEffGkt
