### ISSUE TITLE
ConcurrentModificationException when joining world

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#17529]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

GTNH 2.7.0 beta 2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

join world and crash

### Crash Report

```[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.FuelBurnTimeEvent@1dee314d:
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_421]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_421]
	at gtPlusPlus.core.handler.BurnableFuelHandler.getBurnTime(BurnableFuelHandler.java:16) ~[BurnableFuelHandler.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.getFuelValue(GameRegistry.java:314) ~[GameRegistry.class:?]
	at com.dreammaster.modfixes.minetweaker.MinetweakerFurnaceFix.onFuelBurnTime(MinetweakerFurnaceFix.java:52) ~[MinetweakerFurnaceFix.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_2106_MinetweakerFurnaceFix_onFuelBurnTime_FuelBurnTimeEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.getFuelBurnTime(ForgeEventFactory.java:141) ~[ForgeEventFactory.class:?]
	at net.minecraft.tileentity.TileEntityFurnace.func_145952_a(TileEntityFurnace.java:307) ~[apg.class:?]
	at crazypants.enderio.gui.TooltipHandlerBurnTime.shouldHandleItem(TooltipHandlerBurnTime.java:51) ~[TooltipHandlerBurnTime.class:?]
	at com.enderio.core.client.handlers.SpecialTooltipHandler.addTooltip(SpecialTooltipHandler.java:80) ~[SpecialTooltipHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1306_SpecialTooltipHandler_addTooltip_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:169) ~[ForgeEventFactory.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:626) ~[add.class:?]
	at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:154) ~[GuiContainerManager.class:?]
	at codechicken.nei.search.TooltipFilter.getTooltip(TooltipFilter.java:73) ~[TooltipFilter.class:?]
	at codechicken.nei.search.TooltipFilter.lambda$getSearchTooltip$0(TooltipFilter.java:69) ~[TooltipFilter.class:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_421]
	at codechicken.nei.search.TooltipFilter.getSearchTooltip(TooltipFilter.java:69) ~[TooltipFilter.class:?]
	at codechicken.nei.search.TooltipFilter.matches(TooltipFilter.java:55) ~[TooltipFilter.class:?]
	at codechicken.nei.ItemList$AnyMultiItemFilter.matches(ItemList.java:153) ~[ItemList$AnyMultiItemFilter.class:?]
	at codechicken.nei.ItemList$AllMultiItemFilter.matches(ItemList.java:129) ~[ItemList$AllMultiItemFilter.class:?]
	at codechicken.nei.SearchTokenParser$IsRegisteredItemFilter.matches(SearchTokenParser.java:85) ~[SearchTokenParser$IsRegisteredItemFilter.class:?]
	at codechicken.nei.ItemList$AllMultiItemFilter.matches(ItemList.java:129) ~[ItemList$AllMultiItemFilter.class:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) [?:1.8.0_421]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) [?:1.8.0_421]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_421]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) [?:1.8.0_421]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source) [?:1.8.0_421]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source) [?:1.8.0_421]
	at java.util.stream.AbstractTask.compute(Unknown Source) [?:1.8.0_421]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_421]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_421]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_421]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_421]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_421]
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: Index: 3 Listeners:
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 0: NORMAL
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 1: ASM: biomesoplenty.common.eventhandler.misc.FurnaceBurnTimeEventHandler@34fb113 onFurnaceBurnTime(Lnet/minecraftforge/event/FuelBurnTimeEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 2: ASM: Arboriculture Plugin fuelBurnTimeEvent(Lnet/minecraftforge/event/FuelBurnTimeEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 3: ASM: com.dreammaster.modfixes.minetweaker.MinetweakerFurnaceFix@32dcf96d onFuelBurnTime(Lnet/minecraftforge/event/FuelBurnTimeEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@6dc5c384:
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_421]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_421]
	at gtPlusPlus.core.handler.BurnableFuelHandler.getBurnTime(BurnableFuelHandler.java:16) ~[BurnableFuelHandler.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.getFuelValue(GameRegistry.java:314) ~[GameRegistry.class:?]
	at com.dreammaster.modfixes.minetweaker.MinetweakerFurnaceFix.onFuelBurnTime(MinetweakerFurnaceFix.java:52) ~[MinetweakerFurnaceFix.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_2106_MinetweakerFurnaceFix_onFuelBurnTime_FuelBurnTimeEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.getFuelBurnTime(ForgeEventFactory.java:141) ~[ForgeEventFactory.class:?]
	at net.minecraft.tileentity.TileEntityFurnace.func_145952_a(TileEntityFurnace.java:307) ~[apg.class:?]
	at crazypants.enderio.gui.TooltipHandlerBurnTime.shouldHandleItem(TooltipHandlerBurnTime.java:51) ~[TooltipHandlerBurnTime.class:?]
	at com.enderio.core.client.handlers.SpecialTooltipHandler.addTooltip(SpecialTooltipHandler.java:80) ~[SpecialTooltipHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1306_SpecialTooltipHandler_addTooltip_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:169) ~[ForgeEventFactory.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:626) ~[add.class:?]
	at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:154) ~[GuiContainerManager.class:?]
	at codechicken.nei.search.TooltipFilter.getTooltip(TooltipFilter.java:73) ~[TooltipFilter.class:?]
	at codechicken.nei.search.TooltipFilter.lambda$getSearchTooltip$0(TooltipFilter.java:69) ~[TooltipFilter.class:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_421]
	at codechicken.nei.search.TooltipFilter.getSearchTooltip(TooltipFilter.java:69) ~[TooltipFilter.class:?]
	at codechicken.nei.search.TooltipFilter.matches(TooltipFilter.java:55) ~[TooltipFilter.class:?]
	at codechicken.nei.ItemList$AnyMultiItemFilter.matches(ItemList.java:153) ~[ItemList$AnyMultiItemFilter.class:?]
	at codechicken.nei.ItemList$AllMultiItemFilter.matches(ItemList.java:129) ~[ItemList$AllMultiItemFilter.class:?]
	at codechicken.nei.SearchTokenParser$IsRegisteredItemFilter.matches(SearchTokenParser.java:85) ~[SearchTokenParser$IsRegisteredItemFilter.class:?]
	at codechicken.nei.ItemList$AllMultiItemFilter.matches(ItemList.java:129) ~[ItemList$AllMultiItemFilter.class:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) [?:1.8.0_421]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) [?:1.8.0_421]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_421]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) [?:1.8.0_421]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source) [?:1.8.0_421]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source) [?:1.8.0_421]
	at java.util.stream.AbstractTask.compute(Unknown Source) [?:1.8.0_421]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_421]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_421]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_421]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_421]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_421]
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: Index: 34 Listeners:
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 0: HIGHEST
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 1: ASM: galaxyspace.core.handler.GSSpaceSuitHandler@3919e34a onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 2: ASM: vazkii.botania.client.core.handler.TooltipHandler@42520fda onTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 3: ASM: bartworks.client.ClientEventHandler.TooltipEventHandler@36afcc91 getTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 4: ASM: witchinggadgets.client.ClientEventHandler@21ae86e7 getTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 5: ASM: iguanaman.iguanatweakstconstruct.tweaks.handlers.StoneToolHandler@566a00fa onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 6: HIGH
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 7: ASM: iguanaman.iguanatweakstconstruct.leveling.handlers.LevelingToolTipHandler@536eecae onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 8: NORMAL
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 9: ASM: gregtech.common.GTClient@3f6be272 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 10: ASM: thaumcraft.common.lib.events.EventHandlerRunic@438627be tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 11: ASM: net.bdew.lib.tooltip.TooltipHandler$@673a1581 handleTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 12: ASM: buildcraft.core.list.ListTooltipHandler@519462b3 itemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 13: ASM: mods.battlegear2.client.BattlegearClientEvents@5c67697 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 14: ASM: com.rwtema.extrautils.modintegration.TConEvents@38767f1e unstableTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 15: ASM: micdoodle8.mods.galacticraft.core.event.EventHandlerGC@21989c9f onItemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 16: ASM: forestry.apiculture.EventHandlerApiculture@21fc372e addFrameTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 17: ASM: crazypants.enderio.machine.painter.BlockPaintedGlowstone$PainterTemplate@49967084 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 18: ASM: com.pam.harvestcraft.PamTooltipEventHandler@52322835 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 19: ASM: minetweaker.mc1710.ForgeEventHandler@39a6aff onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 20: ASM: DummyCore.Utils.DummyEventHandler@27131cde onDescrAdded(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 21: ASM: com.brandon3055.draconicevolution.common.handler.MinecraftForgeEventHandler@1a92e008 itemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 22: ASM: lumien.randomthings.Handler.RTEventHandler@4e379bb3 toolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 23: ASM: openblocks.enchantments.flimflams.LoreFlimFlam$DisplayHandler@47ae3186 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 24: ASM: mcp.mobius.betterbarrels.bspace.BBEventHandler@5429e37 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 25: ASM: tonius.neiintegration.mods.mcforge.MCForgeTooltipHandler@1606301b onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 26: ASM: remoteio.client.handler.TooltipEventHandler@5595bf16 itemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 27: ASM: serverutils.handlers.ServerUtilitiesClientEventHandler@38244062 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 28: ASM: com.Zoko061602.SuperTic.SuperEventHandler@5a90b0a5 Tooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 29: ASM: jcm2606.thaumicmachina.client.event.RenderEventHandler@23e90c0a onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 30: ASM: net.darkhax.wawla.addons.generic.AddonGenericTooltips@5e36fd53 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 31: ASM: com.rwtema.extrautils.EventHandlerClient@21630cca generatorTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 32: ASM: buildcraft.builders.BuilderTooltipHandler@2b20e4e4 itemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 33: ASM: com.enderio.core.client.handlers.EnchantTooltipHandler@6815f862 handleTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 34: ASM: INSTANCE addTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 35: ASM: com.enderio.core.client.handlers.OreDictTooltipHandler@650991ff onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 36: ASM: crazypants.enderio.conduit.item.filter.ClearFilterRecipe@4adda0df onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 37: ASM: crazypants.enderio.machine.ClearConfigRecipe@3ac28026 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 38: ASM: com.dreammaster.modctt.CustomToolTipsHandler@13bd5620 onToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 39: ASM: fox.spiteful.avaritia.LudicrousEvents@14d543df onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 40: ASM: fox.spiteful.forbidden.FMEventHandler@52a1023f onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 41: ASM: eu.usrv.enhancedlootbags.core.LootGroupsHandler@3f6e6137 onToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 42: ASM: makeo.gadomancy.common.events.EventHandlerWorld@5313e205 on(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 43: ASM: gtPlusPlus.core.handler.events.MolecularTransformerTooltipNotice@1551f34b molecularTransformer(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 44: ASM: taintedmagic.common.handler.TaintedMagicEventHandler@6461ad39 tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 45: ASM: invtweaks.forge.ClientProxy@ebb2dfe onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 46: ASM: modtweaker2.ClientEvents@7265e15b onDrawTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 47: ASM: ca.wescook.nutrition.events.EventTooltip@26d9ec8b tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 48: ASM: squeek.spiceoflife.gui.TooltipHandler@3d7b2a12 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 49: ASM: net.blay09.mods.tcinventoryscan.client.ClientProxy@5bf3dc50 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 50: ASM: squeek.tictooltips.TooltipHandler@2c637b05 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 51: ASM: com.gtnewhorizon.gtnhlib.util.AnimatedTooltipHandler@556f2f3a renderTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 52: ASM: tconstruct.achievements.AchievementEvents@d462386 tooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 53: ASM: tconstruct.tools.TFToolEvents@1f112085 tooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 54: ASM: alkalus.main.core.util.TooltipHandler@2a77c4e9 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 55: ASM: iguanaman.iguanatweakstconstruct.harvestlevels.VanillaToolTipHandler@29535449 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 56: ASM: iguanaman.iguanatweakstconstruct.leveling.handlers.MobHeadTooltipHandler@2d845bb9 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 57: ASM: iguanaman.iguanatweakstconstruct.tweaks.handlers.VanillaToolNerfHandler@4dcf8be5 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 58: ASM: iguanaman.iguanatweakstconstruct.tweaks.handlers.VanillaHoeNerfHandler@54fe585b onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 59: ASM: iguanaman.iguanatweakstconstruct.tweaks.handlers.VanillaSwordNerfHandler@46223063 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 60: ASM: iguanaman.iguanatweakstconstruct.restriction.PartRestrictionHandler@8ad9d89 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 61: ASM: speiger.src.crops.IC2NeiPlugin@76b03c2 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 62: LOW
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 63: ASM: iguanaman.iguanatweakstconstruct.replacing.PartToolTipHandler@3dcaaf1b onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 64: LOWEST
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 65: ASM: net.glease.tc4tweak.ClientProxy@54c424e8 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 66: ASM: com.mitchej123.hodgepodge.client.PollutionTooltip@3133ce7c getTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 67: ASM: makeo.gadomancy.common.events.EventHandlerGolem@159e6f16 on(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 68: ASM: travellersgear.client.ClientProxy@19532935 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[22:04:46] [ForkJoinPool-1-worker-2/ERROR] [FML]: 69: ASM: iguanaman.hungeroverhaul.util.IguanaEventHook@3d6bdbde renderTooltips(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alexdoru** [comment]
Might be related to this https://github.com/GTNewHorizons/GT5-Unofficial/pull/3269 @Cleptomania
