### ISSUE TITLE
Game crashes when looking towards draconic placed item

### ISSUE THREAD

**Issue by BlueHero233** [GTNewHorizons/GT-New-Horizons-Modpack#17602]
### Your GTNH Discord Username

BlueHero233

### Your Pack Version

2.7 beta-2

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

look around in texture dev world

### Crash Report

[fml-client-latest.log](https://github.com/user-attachments/files/17320135/fml-client-latest.log)

```
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.util.IIcon.func_94212_f()" because "tIcon" is null
    at bartworks.client.renderer.BWItemRenderer.renderItem(BWItemRenderer.java:104)
    at net.minecraftforge.client.ForgeHooksClient.renderEntityItem(ForgeHooksClient.java:136)
    at net.minecraft.client.renderer.entity.RenderItem.doRender(RenderItem.java:93)
    at net.minecraft.client.renderer.entity.RenderItem.doRender(RenderItem.java:746)
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
    at net.minecraft.client.renderer.entity.RenderManager.renderEntityWithPosYaw(RenderManager.java:276)
    at com.brandon3055.draconicevolution.client.render.tile.RenderTilePlacedItem.renderItem(RenderTilePlacedItem.java:77)
    at com.brandon3055.draconicevolution.client.render.tile.RenderTilePlacedItem.renderTileEntityAt(RenderTilePlacedItem.java:35)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.renderTileEntityAt(SourceFile:100)
    at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:43)
    at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.renderTileEntity(SourceFile:92)
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTE(SodiumWorldRenderer.java:354)
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:374)
    at net.minecraft.client.renderer.RenderGlobal.handler$zfe000$angelica$sodium$renderTileEntities(RenderGlobal.java:5783)
    at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:476)
    at net.minecraft.client.renderer.EntityRenderer.redirect$zbp000$hydroenergy$redirectRenderEntities(EntityRenderer.java:7079)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1224)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1011)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5110)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:60)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:207)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alexdoru** [comment]
seems that the draconic code needs to be modified to properly handle items that got deleted from the game in between versions 
![image](https://github.com/user-attachments/assets/ab479be9-b85c-4616-a887-2c835e9681bc)

**Comment by BlueHero233** [comment]
Looks fixed by https://github.com/GTNewHorizons/Draconic-Evolution/pull/55

**Comment by Alexdoru** [comment]
no it's not, in this case here the item exists and the tile entity is created but then it doesn't exists in bartworks' registery and can't find an icon to render it

**Comment by Dream-Master** [comment]
Are the Bartworks circuit not removed ?

**Comment by Alexdoru** [comment]
> Are the Bartworks circuit not removed ?

yes they are , as a result it can't find the icon to render the item and it crashes
