### ISSUE TITLE
GT++ Toxic Everglade Sickblaze fireballs causing crash

### ISSUE THREAD

**Issue by Hikari1nVoid** [GTNewHorizons/GT-New-Horizons-Modpack#17627]
### Your GTNH Discord Username

Hiakri1nVoid#9527

### Your Pack Version

2.7.0beta2

### Your Server

zeta

### Java Version

Java 21

### Type of Server

Thermos

### Your Actions

Visiting toxic Everglade.Game returned to title(no crash but with connection lost error msgs)

### Crash Report

23:02:10] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel FML
java.lang.RuntimeException: java.lang.NoSuchMethodException: gtPlusPlus.core.entity.projectile.EntityToxinballSmall.<init>(net.minecraft.world.World)
	at System//com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-17.0.jar:?]
	at Launch//cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:126) ~[EntitySpawnHandler.class:?]
	at Launch//cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) ~[EntitySpawnHandler.class:?]
	at Launch//cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) ~[EntitySpawnHandler.class:?]
	at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at Launch//net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at Launch//net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at Launch//net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at Launch//net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5110) [bao.class:?]
	at Launch//net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at System//net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250) [Launch.class:?]
	at System//net.minecraft.launchwrapper.Launch.launch(Launch.java:35) [Launch.class:?]
	at System//net.minecraft.launchwrapper.Launch.main(Launch.java:60) [Launch.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:207) [lwjgl3ify-2.1.3-forgePatches.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at System//org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at System//org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at System//org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at System//org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoSuchMethodException: gtPlusPlus.core.entity.projectile.EntityToxinballSmall.<init>(net.minecraft.world.World)
	at java.base/java.lang.Class.getConstructor0(Class.java:3761) ~[?:?]
	at java.base/java.lang.Class.getConstructor(Class.java:2442) ~[?:?]
	at Launch//cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:77) ~[EntitySpawnHandler.class:?]
	... 32 more

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
looks like colen randomly deleted the constructor :(
