### ISSUE TITLE
Can't launch server

### ISSUE THREAD

**Issue by XeonKA** [GTNewHorizons/GT-New-Horizons-Modpack#17706]
### Your GTNH Discord Username

XeonKA

### Your Pack Version

2.7.0 nightly #705

### Your Server

private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Actions

Start Server

### Crash Report

[latest.log](https://github.com/user-attachments/files/17462278/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
Seems to be a bad crucible setup.

``|
22:13:34] [main/FATAL]: Failed to start the minecraft server
java.lang.NullPointerException
	at org.bukkit.Bukkit.getLogger(Bukkit.java:314) ~[Bukkit.class:1.7.10-staging-fdd020e3]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:185) ~[YamlConfiguration.class:1.7.10-staging-fdd020e3]
	at net.minecraftforge.cauldron.configuration.ConfigBase.<init>(ConfigBase.java:29) ~[ConfigBase.class:1.7.10-staging-fdd020e3]
	at net.minecraftforge.cauldron.configuration.CauldronConfig.<init>(CauldronConfig.java:76) ~[CauldronConfig.class:1.7.10-staging-fdd020e3]
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:250) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:73) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1731)
```
