### ISSUE TITLE
AE2 has no protection for  too big packets

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#17830]
in 2.6.1, i attempted to make a fake pattern with as output a very big NBT. As soon as i try to craft it, i get kicked with this log:
```
[21:43:39] [Netty Client IO #4/ERROR]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32k
    at RFB-Launch//net.minecraft.network.play.client.C17PacketCustomPayload.<init>(SourceFile:38) ~[iz.class:?]
    at RFB-Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:120) ~[FMLProxyPacket.class:?]
    at RFB-Launch//cpw.mods.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:434) ~[NetworkDispatcher.class:?]
    at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[netty-all-4.0.10.Final.jar:?]
    at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[netty-all-4.0.10.Final.jar:?]
    at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[netty-all-4.0.10.Final.jar:?]
    at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[netty-all-4.0.10.Final.jar:?]
    at RFB-Launch//io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[netty-all-4.0.10.Final.jar:?]
    at RFB-Launch//io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[netty-all-4.0.10.Final.jar:?]
    at RFB-Launch//net.minecraft.network.NetworkManager$1.run(NetworkManager.java:174) ~[ek.class:?]
    at RFB-Launch//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) ~[netty-all-4.0.10.Final.jar:?]
    at RFB-Launch//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) ~[netty-all-4.0.10.Final.jar:?]
    at RFB-Launch//io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) ~[netty-all-4.0.10.Final.jar:?]
    at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```
and a nice error message: 
![image](https://github.com/user-attachments/assets/f2c2be08-22cd-4d15-85b0-c705e1861ba1)

According to Raven:
> Ah nvm I have never patched this particular packet type to support more data
needs a patch like the s3f packet: https://github.com/GTNewHorizons/Hodgepodge/blob/master/src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/packets/MixinS3FPacketCustomPayload_LengthLimit.java
Probably with a different config setting for the limit than the server, because client->server packets are a lot more dangerous security-wise than the other way around (for ddos prevention)

**Comment by boubou19** [comment]
probably fixed by https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/683
