### ISSUE TITLE
Crashing when switching dimensions and loading different saves.

### ISSUE THREAD

**Issue by Starcluster0** [GTNewHorizons/GT-New-Horizons-Modpack#17981]
### Your GTNH Discord Username

Starcluster#3252

### Your Pack Version

2.7.0-beta 3

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

I tried to travel to the nether, and crashed. This issue however also occurs when traveling to other dimensions, and when switching from one save to another. This has occurred when loading my main save, then quitting, and loading a test world save. This crash also occurs when traveling to and from the twilight forest at times. The specific reason sited for the crash is:
"A fatal error has occurred during the network handshake, this connection is terminated. Check the log for details. The exception caught was: java.lang.NullPointerException: Cannot read field "field_147371_a" because "player.field_71135_a" is null".

### Crash Report

[fml-server-latest.log](https://github.com/user-attachments/files/17758856/fml-server-latest.log)
[crash-2024-10-27_14.40.31-server.txt](https://github.com/user-attachments/files/17759132/crash-2024-10-27_14.40.31-server.txt)

```
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "gregtech.api.metatileentity.MetaTileEntity.onExplosion()" because "this.mMetaTileEntity" is null
    at gregtech.api.metatileentity.BaseMetaTileEntity.doExplosion(BaseMetaTileEntity.java:1405)
    at gregtech.api.metatileentity.BaseMetaTileEntity.doEnergyExplosion(BaseMetaTileEntity.java:1383)
    at gregtech.common.blocks.BlockMachines.dropBlockAsItemWithChance(BlockMachines.java:544)
    at net.minecraft.world.Explosion.doExplosionB(Explosion.java:212)
    at net.minecraft.world.WorldServer.newExplosion(WorldServer.java:902)
    at net.minecraft.world.World.createExplosion(World.java:2403)
    at net.minecraft.entity.item.EntityTNTPrimed.explode(SourceFile:87)
    at net.minecraft.entity.item.EntityTNTPrimed.onUpdate(SourceFile:77)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2070)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:648)
    at net.minecraft.world.World.updateEntity(World.java:2034)
    at net.minecraft.world.World.updateEntities(World.java:1887)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
Details:
    Entity Type: PrimedTnt (net.minecraft.entity.item.EntityTNTPrimed)
    Entity ID: 378013
    Entity Name: Block of TNT
    Entity's Exact location: 72.51, 182.49, -1522.51
    Entity's Block location: World: (72,182,-1523), Chunk: (at 8,11,13 in 4,-96; contains blocks 64,0,-1536 to 79,255,-1521), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
    Entity's Momentum: -0.07, -0.00, 0.35
Stacktrace:
    at Launch//net.minecraft.world.World.func_72939_s(World.java:1892)
    at Launch//net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alexdoru** [comment]
there isn't the NullPointerException in the log that you provided, can you give the crashlog instead please ?

**Comment by Starcluster0** [comment]
[crash-2024-10-27_14.40.31-server.txt](https://github.com/user-attachments/files/17759132/crash-2024-10-27_14.40.31-server.txt)
Here is the crash log

**Comment by Alexdoru** [comment]
do you have the setting to "machineWireFire" off ?

**Comment by Starcluster0** [comment]
Posted the wrong discord username, and I will check to see if so

**Comment by Starcluster0** [comment]
No, I have machineWireFire on, and I updated the discord username so you can message me on that.
B:machineWireFire=true

**Comment by Starcluster0** [comment]
To top that all off as well, I have every single wire covered by some kind of block.

**Comment by ClassixX** [comment]
I can confirm this, happens frequently when loading into my single player worlds. I'm not sure how wires might be related, but the world is in the stone age, so there are no wires.

**Comment by Starcluster0** [comment]
As of 2.7.0 beta-4 this issue with a java.lang.NullPointerException has appeared to resolve itself. I cannot replicate this in beta-4.
