### ISSUE TITLE
Waterline Turning off after first cycle after Server Restart

### ISSUE THREAD

**Issue by Yoshy2002** [GTNewHorizons/GT-New-Horizons-Modpack#17994]
### Your GTNH Discord Username

yoshy1952

### Your Pack Version

Nightly 732

### Your Server

private Server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Waterline continuing to work after Server Restart

### The Reality

After stopping the server with Waterline Running, starting it again will cause it to end its current cycle and then stop. All of the Purification Units are stuck on 100%, the Plant just turned off.
![image](https://github.com/user-attachments/assets/010fb332-0dda-46db-97ea-5eef82eb4419)
![image](https://github.com/user-attachments/assets/a1a8308d-47ce-4139-a008-bca079444a78)

Getting this error in Server Console when the Plant finishes its currently running cycle:
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]: java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//gregtech.api.metatileentity.implementations.MTEMultiBlockBase.addItemOutputs(MTEMultiBlockBase.java:1341)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationUnitBase.addRecipeOutputs(MTEPurificationUnitBase.java:420)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationUnitPlasmaHeater.addRecipeOutputs(MTEPurificationUnitPlasmaHeater.java:429)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationUnitBase.endCycle(MTEPurificationUnitBase.java:432)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.endCycle(MTEPurificationPlant.java:462)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.updateCycleProgress(MTEPurificationPlant.java:407)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.runMachine(MTEPurificationPlant.java:378)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//gregtech.api.metatileentity.implementations.MTEMultiBlockBase.onPostTick(MTEMultiBlockBase.java:472)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.onPostTick(MTEPurificationPlant.java:355)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:568)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//net.minecraft.world.World.func_72939_s(World.java:1939)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[15:42:36] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:763]:         at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

### Your Proposal

Fix this Bug.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by RAFAEL-SOSA-UH** [comment]
seems to be fixed in #17655 by " fix waterline cycle breaking on reload #3420"

**Comment by Yoshy2002** [comment]
The bugfix was 3 weeks ago, im playing oon 732 from a few days ago

**Comment by Ruling-0** [comment]
Also occurring on my N732 world
