### ISSUE TITLE
Client Crash to Main Menu after clicking on Waterline Plant Status

### ISSUE THREAD

**Issue by Yoshy2002** [GTNewHorizons/GT-New-Horizons-Modpack#17995]
### Your GTNH Discord Username

yoshy1952

### Your Pack Version

Nightly 732

### Your Server

private Server

### Java Version

Java 17

### Type of Server

None

### Your Actions

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17994
After Server restart, Waterline crashes after the first cycle. If i then open its GUI and click on the Status Button, my client crashes to main menu
![image](https://github.com/user-attachments/assets/de510b21-ebcb-40e2-8932-536b95af820f)

### Crash Report

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.makeUnitStatusWidget(MTEPurificationPlant.java:692) ~[MTEPurificationPlant.class:?]
        at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.createStatusWindow(MTEPurificationPlant.java:646) ~[MTEPurificationPlant.class:?]
        at Launch//com.gtnewhorizons.modularui.api.screen.ModularUIContext.openWindow(ModularUIContext.java:197) ~[ModularUIContext.class:?]
        at Launch//com.gtnewhorizons.modularui.api.screen.ModularUIContext.openSyncedWindow(ModularUIContext.java:181) ~[ModularUIContext.class:?]
        at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.lambda$makeStatusWindowButton$27(MTEPurificationPlant.java:663) ~[MTEPurificationPlant.class:?]
        at Launch//com.gtnewhorizons.modularui.common.widget.ButtonWidget.readOnServer(ButtonWidget.java:118) ~[ButtonWidget.class:?]
        at Launch//com.gtnewhorizons.modularui.api.screen.ModularUIContext.readClientPacket(ModularUIContext.java:395) ~[ModularUIContext.class:?]
        at Launch//com.gtnewhorizons.modularui.common.internal.network.CWidgetUpdate.executeServer(CWidgetUpdate.java:43) ~[CWidgetUpdate.class:?]
        at Launch//com.gtnewhorizons.modularui.common.internal.network.NetworkHandler.lambda$static$1(NetworkHandler.java:55) ~[NetworkHandler.class:?]
        at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
        at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
        at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [minecraft_server.1.7.10.jar:?]
        at Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: Exception caught while transforming class net.minecraft.client.Minecraft
        at System//net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:294) ~[LaunchClassLoader.class:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 28 more
Caused by: java.lang.RuntimeException: Attempted to load class bao for invalid side SERVER
        at Launch//cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
        at Launch//makamys.coretweaks.optimization.transformerproxy.TransformerProxy.invokeNextHandler(TransformerProxy.java:44) ~[CoreTweaks-1.7.10-0.3.3.2+nomixin.jar:?]
        at Launch//makamys.coretweaks.optimization.ForgeFastWildcardTransformers$PatternConditionalTransformerWrapper.wrapTransform(ForgeFastWildcardTransformers.java:53) ~[CoreTweaks-1.7.10-0.3.3.2+nomixin.jar:?]
        at Launch//makamys.coretweaks.optimization.transformerproxy.TransformerProxy.invokeNextHandler(TransformerProxy.java:46) ~[CoreTweaks-1.7.10-0.3.3.2+nomixin.jar:?]
        at Launch//makamys.coretweaks.optimization.transformercache.lite.CachedTransformerWrapper.wrapTransform(CachedTransformerWrapper.java:24) ~[CoreTweaks-1.7.10-0.3.3.2+nomixin.jar:?]
        at Launch//makamys.coretweaks.optimization.transformerproxy.TransformerProxy.invokeNextHandler(TransformerProxy.java:46) ~[CoreTweaks-1.7.10-0.3.3.2+nomixin.jar:?]
        at Launch//makamys.coretweaks.optimization.transformerproxy.TransformerProxy.transform(TransformerProxy.java:27) ~[CoreTweaks-1.7.10-0.3.3.2+nomixin.jar:?]
        at System//net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:405) ~[LaunchClassLoader.class:?]
        at System//net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:292) ~[LaunchClassLoader.class:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 28 more
[15:43:05] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel modularui
java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.makeUnitStatusWidget(MTEPurificationPlant.java:692) ~[MTEPurificationPlant.class:?]
        at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.createStatusWindow(MTEPurificationPlant.java:646) ~[MTEPurificationPlant.class:?]
        at Launch//com.gtnewhorizons.modularui.api.screen.ModularUIContext.openWindow(ModularUIContext.java:197) ~[ModularUIContext.class:?]
        at Launch//com.gtnewhorizons.modularui.api.screen.ModularUIContext.openSyncedWindow(ModularUIContext.java:181) ~[ModularUIContext.class:?]
        at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.lambda$makeStatusWindowButton$27(MTEPurificationPlant.java:663) ~[MTEPurificationPlant.class:?]
        at Launch//com.gtnewhorizons.modularui.common.widget.ButtonWidget.readOnServer(ButtonWidget.java:118) ~[ButtonWidget.class:?]
        at Launch//com.gtnewhorizons.modularui.api.screen.ModularUIContext.readClientPacket(ModularUIContext.java:395) ~[ModularUIContext.class:?]
        at Launch//com.gtnewhorizons.modularui.common.internal.network.CWidgetUpdate.executeServer(CWidgetUpdate.java:43) ~[CWidgetUpdate.class:?]
        at Launch//com.gtnewhorizons.modularui.common.internal.network.NetworkHandler.lambda$static$1(NetworkHandler.java:55) ~[NetworkHandler.class:?]
        at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
        at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
        at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[minecraft_server.1.7.10.jar:?]
        at Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: Exception caught while transforming class net.minecraft.client.Minecraft
        at System//net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:294) ~[LaunchClassLoader.class:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 28 more
Caused by: java.lang.RuntimeException: Attempted to load class bao for invalid side SERVER
        at Launch//cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
        at Launch//makamys.coretweaks.optimization.transformerproxy.TransformerProxy.invokeNextHandler(TransformerProxy.java:44) ~[CoreTweaks-1.7.10-0.3.3.2+nomixin.jar:?]
        at Launch//makamys.coretweaks.optimization.ForgeFastWildcardTransformers$PatternConditionalTransformerWrapper.wrapTransform(ForgeFastWildcardTransformers.java:53) ~[CoreTweaks-1.7.10-0.3.3.2+nomixin.jar:?]
        at Launch//makamys.coretweaks.optimization.transformerproxy.TransformerProxy.invokeNextHandler(TransformerProxy.java:46) ~[CoreTweaks-1.7.10-0.3.3.2+nomixin.jar:?]
        at Launch//makamys.coretweaks.optimization.transformercache.lite.CachedTransformerWrapper.wrapTransform(CachedTransformerWrapper.java:24) ~[CoreTweaks-1.7.10-0.3.3.2+nomixin.jar:?]
        at Launch//makamys.coretweaks.optimization.transformerproxy.TransformerProxy.invokeNextHandler(TransformerProxy.java:46) ~[CoreTweaks-1.7.10-0.3.3.2+nomixin.jar:?]
        at Launch//makamys.coretweaks.optimization.transformerproxy.TransformerProxy.transform(TransformerProxy.java:27) ~[CoreTweaks-1.7.10-0.3.3.2+nomixin.jar:?]
        at System//net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:405) ~[LaunchClassLoader.class:?]
        at System//net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:292) ~[LaunchClassLoader.class:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 28 more

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Yoshy2002** [comment]
Still happening in beta4, not sure why you cant reproduce this, maybe someone else can try to reproduce this?

**Comment by Ngar1** [comment]
May be in relation to this failure:
 2.7.0-beta-4
 crash if Status of linked Water Purification Plant was clicked:
 https://paste.atlauncher.com/view/1a72e7c4-76e6-4ec3-98f3-b65f0e654148

**Comment by Yoshy2002** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/3558 fixed the Waterline Crash on Server Restart, however im still getting put into Main Menu with 2.7.0 RC-1 with newest gt5 whenever pressing the Status Button

**Comment by chochem** [comment]
the reproducing problem was just about SP. this is a server-only crash, SP is fine

**Comment by chochem** [comment]
caused by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3428 doing client stuff on the server I guess
