### ISSUE TITLE
DETECTED ILLEGAL ITEM

### ISSUE THREAD

**Issue by Lennartos** [GTNewHorizons/GT-New-Horizons-Modpack#18028]
### Your GTNH Discord Username

Lennart#9359

### Your Pack Version

2.7 Beta 3

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

After update all was ok, we started to migrate to the new recipies.

### The Reality

A few days ago we start to notice server slowdown and when i check, the log gets flooded with FATAL: DETECTED ILLEGAL ITEM TO BE INSERTED IN STORAGE CELL, PLEASE REPORT TO GITHUB.
This happens A LOT, server speed is abysmal and logs get to GB size in minutes.
We noticed a few weird issues, like corrupted fluid packets in storage (which we deleted with a trash can), and one item cell with droplets in it, that would not move to fluid storage.
Threw that in trash can as well... but no change.
Error persists.

![image](https://github.com/user-attachments/assets/c19478c2-b404-4399-8e50-f89abec2fba3)

### Your Proposal

use the stack trace to find the issue, or extend the error message so it tells us the type and location of the offending item so we can kill it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lennartos** [comment]
I think i found it.
A storage cell was programmed with a oredict, and what was in it was not what it was programmed with.
once i removed that from the network it was fixed

**Comment by Lennartos** [comment]
![image](https://github.com/user-attachments/assets/3c309db8-6f8a-4b48-a7e6-3eaf6c3b6b8f)
I think something broke after the update / upgrade... some cells show this oredict, even when there is nothing in them.

**Comment by Lennartos** [comment]
Just saw a cell that is completely clean cause the bug when sucking nether quartz dust in a IO port from the main storage.
The cell did not show a dust* as i expected.

**Comment by Semetix** [comment]
The error occurs for me when I put in a disk in an IO Port and when all items are pulled and the disk keeps pulling it spams my console full with:

[23:22:31] [Server thread/ERROR] [AE2:S]: FATAL: DETECTED ILLEGAL ITEM TO BE INSERTED ON STORAGE CELL, PLEASE REPORT ON GITHUB! STACKTRACE:
java.lang.Throwable
        at Launch//appeng.me.storage.CellInventory.injectItems(CellInventory.java:190) [CellInventory.class:?]
        at Launch//appeng.me.storage.CellInventory.injectItems(CellInventory.java:43) [CellInventory.class:?]
        at Launch//appeng.me.storage.MEPassThrough.injectItems(MEPassThrough.java:44) [MEPassThrough.class:?]
        at Launch//appeng.me.storage.MEInventoryHandler.injectItems(MEInventoryHandler.java:100) [MEInventoryHandler.class:?]
        at Launch//appeng.tile.storage.TileIOPort.transferContents(TileIOPort.java:395) [TileIOPort.class:?]
        at Launch//appeng.tile.storage.TileIOPort.tickingRequest(TileIOPort.java:329) [TileIOPort.class:?]
        at Launch//appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:77) [TickManagerCache.class:?]
        at Launch//appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:30) [GridCacheWrapper.class:?]
        at Launch//appeng.me.Grid.update(Grid.java:257) [Grid.class:?]
        at Launch//appeng.hooks.TickHandler.onTick(TickHandler.java:192) [TickHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_841_TickHandler_onTick_TickEvent.invoke(.dynamic) [?:?]
        at Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
        at Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
        at Launch//cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) [FMLCommonHandler.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by archieonic** [comment]
Same error, saw for the first time today. I'm inclined to say it was when I was using the IO Port as Semetix mentioned above. I didn't exactly catch it at the time it happened but I know for a fact I was reformatting some drives and using the IO Port. 

[19:45:08] [Server thread/ERROR] [AE2:S/]: FATAL: DETECTED ILLEGAL ITEM TO BE INSERTED ON STORAGE CELL, PLEASE REPORT ON GITHUB! STACKTRACE:
java.lang.Throwable
	at Launch//appeng.me.storage.CellInventory.injectItems(CellInventory.java:190) [CellInventory.class:?]
	at Launch//appeng.me.storage.CellInventory.injectItems(CellInventory.java:43) [CellInventory.class:?]
	at Launch//appeng.me.storage.MEPassThrough.injectItems(MEPassThrough.java:44) [MEPassThrough.class:?]
	at Launch//appeng.me.storage.MEInventoryHandler.injectItems(MEInventoryHandler.java:100) [MEInventoryHandler.class:?]
	at Launch//appeng.tile.storage.TileIOPort.transferContents(TileIOPort.java:395) [TileIOPort.class:?]
	at Launch//appeng.tile.storage.TileIOPort.tickingRequest(TileIOPort.java:329) [TileIOPort.class:?]
	at Launch//appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:77) [TickManagerCache.class:?]
	at Launch//appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:30) [GridCacheWrapper.class:?]
	at Launch//appeng.me.Grid.update(Grid.java:257) [Grid.class:?]
	at Launch//appeng.hooks.TickHandler.onTick(TickHandler.java:192) [TickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_819_TickHandler_onTick_TickEvent.invoke(.dynamic) [?:?]
	at Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at Launch//cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) [FMLCommonHandler.class:?]
	at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[19:45:08] [Server thread/ERROR] [AE2:S/]: FATAL: DETECTED ILLEGAL ITEM TO BE INSERTED ON STORAGE CELL, PLEASE REPORT ON GITHUB! STACKTRACE:
java.lang.Throwable
	at Launch//appeng.me.storage.CellInventory.injectItems(CellInventory.java:190) [CellInventory.class:?]
	at Launch//appeng.me.storage.CellInventory.injectItems(CellInventory.java:43) [CellInventory.class:?]
	at Launch//appeng.me.storage.MEPassThrough.injectItems(MEPassThrough.java:44) [MEPassThrough.class:?]
	at Launch//appeng.me.storage.MEInventoryHandler.injectItems(MEInventoryHandler.java:100) [MEInventoryHandler.class:?]
	at Launch//appeng.tile.storage.TileIOPort.transferContents(TileIOPort.java:395) [TileIOPort.class:?]
	at Launch//appeng.tile.storage.TileIOPort.tickingRequest(TileIOPort.java:329) [TileIOPort.class:?]
	at Launch//appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:77) [TickManagerCache.class:?]
	at Launch//appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:30) [GridCacheWrapper.class:?]
	at Launch//appeng.me.Grid.update(Grid.java:257) [Grid.class:?]
	at Launch//appeng.hooks.TickHandler.onTick(TickHandler.java:192) [TickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_819_TickHandler_onTick_TickEvent.invoke(.dynamic) [?:?]
	at Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at Launch//cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) [FMLCommonHandler.class:?]
	at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by lc-1337** [comment]
Should be already fixed.
