### ISSUE TITLE
Large Molecular Assembler shuts down immediately after loading the world

### ISSUE THREAD

**Issue by Kogepan229** [GTNewHorizons/GT-New-Horizons-Modpack#18092]
### Your GTNH Discord Username

kogepan229

### Your Pack Version

2.7.0-beta4

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Won't shut down

### The Reality

The following error appears in the logs and the machine shuts down.
Remove the connected AE2 Cable, turn the machine on, and then place the cable to make it work. (However, the same issue occurs when reopening the world.)

[fml-client-latest.log](https://github.com/user-attachments/files/17892398/fml-client-latest.log)
```
[16:33:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException: detail must not be null
[16:33:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//com.muxiu1997.mxrandom.metatileentity.MTELargeMolecularAssembler.getPatternRaw(MTELargeMolecularAssembler.kt:635)
[16:33:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//com.muxiu1997.mxrandom.metatileentity.MTELargeMolecularAssembler.getPattern(MTELargeMolecularAssembler.kt:626)
[16:33:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//com.muxiu1997.mxrandom.metatileentity.MTELargeMolecularAssembler.issuePatternChangeIfNeeded(MTELargeMolecularAssembler.kt:389)
[16:33:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//com.muxiu1997.mxrandom.metatileentity.MTELargeMolecularAssembler.onPostTick(MTELargeMolecularAssembler.kt:251)
[16:33:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:565)
[16:33:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//net.minecraft.world.World.func_72939_s(World.java:1939)
[16:33:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[16:33:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[16:33:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[16:33:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[16:33:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[16:33:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Kogepan229** [comment]
I noticed that an Invalid Pattern remained in the Input Bus.
Strangely, even after deleting it, it would reappear when I reopened the world.
Replacing the LMA, initializing the Data Orb, and restarting Minecraft fixed all the issues.
