### ISSUE TITLE
Server kick when breaking AE2 ME cable with GT wrench via right click while looking through an Iron chest

### ISSUE THREAD

**Issue by leumasme** [GTNewHorizons/GT-New-Horizons-Modpack#18161]
### Your GTNH Discord Username

leumasme

### Your Pack Version

2.6.1

### Your Server

Private

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Player is able to break an Applied energistics 2 ME cable with a Gregtech wrench with shift-rightclick

### The Reality

When shift-rightclicking an AE2 ME cable with a Gregtech wrench while looking through the corner of a Chest from iron Chest, a server error is caused and the player is kicked.

Log:
```
[08:58:46] [Server thread/ERROR] [FML]: NetworkEventFiringHandler exception
java.lang.NullPointerException: Cannot read field "field_72310_e" because the return value of "appeng.util.Platform.rayTrace(net.minecraft.entity.player.EntityPlayer, boolean, boolean)" is null
        at RFB-Launch//gregtech.common.tools.GT_Tool_Wrench.onBreakBlock(GT_Tool_Wrench.java:214) ~[GT_Tool_Wrench.class:?]
        at RFB-Launch//gregtech.common.GT_Proxy.onBlockBreakingEvent(GT_Proxy.java:1634) ~[GT_Proxy.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_12_GT_Proxy_onBlockBreakingEvent_BreakEvent.invoke(.dynamic) ~[?:?]
        at RFB-Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at RFB-Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at RFB-Launch//appeng.parts.PartPlacement.place(PartPlacement.java:106) ~[PartPlacement.class:?]
        at RFB-Launch//appeng.core.sync.packets.PacketPartPlacement.serverPacketData(PacketPartPlacement.java:59) ~[PacketPartPlacement.class:?]
        at RFB-Launch//appeng.core.sync.network.AppEngServerPacketHandler.onPacketData(AppEngServerPacketHandler.java:32) ~[AppEngServerPacketHandler.class:?]
        at RFB-Launch//appeng.core.sync.network.NetworkHandler.serverPacket(NetworkHandler.java:78) ~[NetworkHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_1329_NetworkHandler_serverPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
        at RFB-Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at RFB-Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at RFB-Launch//cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
        at RFB-Launch//cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
        at RFB-Launch//cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
        at RFB-Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [minecraft_server.1.7.10.jar:?]
        at RFB-Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at RFB-Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at RFB-Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[08:58:46] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel AE2
java.lang.NullPointerException: Cannot read field "field_72310_e" because the return value of "appeng.util.Platform.rayTrace(net.minecraft.entity.player.EntityPlayer, boolean, boolean)" is null
        at RFB-Launch//gregtech.common.tools.GT_Tool_Wrench.onBreakBlock(GT_Tool_Wrench.java:214) ~[GT_Tool_Wrench.class:?]
        at RFB-Launch//gregtech.common.GT_Proxy.onBlockBreakingEvent(GT_Proxy.java:1634) ~[GT_Proxy.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_12_GT_Proxy_onBlockBreakingEvent_BreakEvent.invoke(.dynamic) ~[?:?]
        at RFB-Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at RFB-Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at RFB-Launch//appeng.parts.PartPlacement.place(PartPlacement.java:106) ~[PartPlacement.class:?]
        at RFB-Launch//appeng.core.sync.packets.PacketPartPlacement.serverPacketData(PacketPartPlacement.java:59) ~[PacketPartPlacement.class:?]
        at RFB-Launch//appeng.core.sync.network.AppEngServerPacketHandler.onPacketData(AppEngServerPacketHandler.java:32) ~[AppEngServerPacketHandler.class:?]
        at RFB-Launch//appeng.core.sync.network.NetworkHandler.serverPacket(NetworkHandler.java:78) ~[NetworkHandler.class:?]
```
The Situation in which this consistently happens looks as follows:
![0033674](https://github.com/user-attachments/assets/71b42524-efde-4d1c-ab65-e1c1c6c27f42)
Note that the player is looking through the chest block, which is possible as it's not a full block.
This doesn't seem to happen when looking through some other things like flowers.

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leumasme** [comment]
Probably duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16025
