### ISSUE TITLE
Console throws Warn after opening Jetpack Crafting Plan in NEI

### ISSUE THREAD

**Issue by Semetix** [GTNewHorizons/GT-New-Horizons-Modpack#18175]
### Your GTNH Discord Username

Semetix

### Your Pack Version

2.7.0-beta-3

### Your Server

Private Server

### Java Version

Other versions in between

### Type of Server

Don't know

### Your Expectation

No Error

### The Reality

[17:01:32] [Server thread/WARN] [IC2.Item]: Detected invalid armor damage application:
java.lang.Throwable
        at Launch//ic2.core.item.armor.ItemArmorElectric.setDamage(ItemArmorElectric.java:154) [ItemArmorElectric.class:?]
        at Launch//net.minecraft.item.ItemStack.func_77964_b(ItemStack.java:222) [add.class:?]
        at Launch//logisticspipes.utils.item.ItemIdentifier.getUndamaged(ItemIdentifier.java:411) [ItemIdentifier.class:?]
        at Launch//logisticspipes.utils.item.ItemIdentifierInventory.updateContents(ItemIdentifierInventory.java:367) [ItemIdentifierInventory.class:?]
        at Launch//logisticspipes.utils.item.ItemIdentifierInventory.func_70299_a(ItemIdentifierInventory.java:131) [ItemIdentifierInventory.class:?]
        at Launch//logisticspipes.pipes.PipeBlockRequestTable.handleNEIRecipePacket(PipeBlockRequestTable.java:503) [PipeBlockRequestTable.class:?]
        at Launch//logisticspipes.network.packets.NEISetCraftingRecipe.processPacket(NEISetCraftingRecipe.java:40) [NEISetCraftingRecipe.class:?]
        at Launch//logisticspipes.network.PacketInboundHandler.channelRead0(PacketInboundHandler.java:20) [PacketInboundHandler.class:?]
        at Launch//logisticspipes.network.PacketInboundHandler.channelRead0(PacketInboundHandler.java:15) [PacketInboundHandler.class:?]
        at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [minecraft_server.1.7.10.jar:?]
        at Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[17:01:32] [Server thread/WARN] [IC2.Item]: Detected invalid armor damage application:
java.lang.Throwable
        at Launch//ic2.core.item.armor.ItemArmorElectric.setDamage(ItemArmorElectric.java:154) [ItemArmorElectric.class:?]
        at Launch//net.minecraft.item.ItemStack.func_77964_b(ItemStack.java:222) [add.class:?]
        at Launch//logisticspipes.utils.item.ItemIdentifier.getUndamaged(ItemIdentifier.java:411) [ItemIdentifier.class:?]
        at Launch//logisticspipes.utils.item.ItemIdentifierInventory.updateContents(ItemIdentifierInventory.java:373) [ItemIdentifierInventory.class:?]
        at Launch//logisticspipes.utils.item.ItemIdentifierInventory.func_70299_a(ItemIdentifierInventory.java:131) [ItemIdentifierInventory.class:?]
        at Launch//logisticspipes.pipes.PipeBlockRequestTable.handleNEIRecipePacket(PipeBlockRequestTable.java:503) [PipeBlockRequestTable.class:?]
        at Launch//logisticspipes.network.packets.NEISetCraftingRecipe.processPacket(NEISetCraftingRecipe.java:40) [NEISetCraftingRecipe.class:?]
        at Launch//logisticspipes.network.PacketInboundHandler.channelRead0(PacketInboundHandler.java:20) [PacketInboundHandler.class:?]
        at Launch//logisticspipes.network.PacketInboundHandler.channelRead0(PacketInboundHandler.java:15) [PacketInboundHandler.class:?]
        at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [minecraft_server.1.7.10.jar:?]
        at Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

### Your Proposal

There should be no error

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Semetix** [comment]
Doesnt throw this error anymore, seems fixed. Stable 2.8.0
