### ISSUE TITLE
Golden Nugget Usage Recipe ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by r2go-beep** [GTNewHorizons/GT-New-Horizons-Modpack#18229]
### Your GTNH Discord Username

r2go

### Your Pack Version

2.7.0-RC2

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Tried to look up usage for a golden nuget.

### The Reality

[10:34:06] [NEI-worker-thread-44/ERROR] [NotEnoughItems]: Error while looking up usage recipe
[10:34:06] [NEI-worker-thread-44/ERROR] [NotEnoughItems]: inputId: item
[10:34:06] [NEI-worker-thread-44/ERROR] [NotEnoughItems]: ingredients: [60xitem.goldNugget@0]
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//binnie.core.nei.PositionedFluidTank.<init>(PositionedFluidTank.java:36)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//binnie.core.nei.PositionedFluidTank.<init>(PositionedFluidTank.java:43)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//binnie.genetics.nei.PolymeriserRecipeHandler$CachedPolymeriserRecipe.<init>(PolymeriserRecipeHandler.java:162)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//binnie.genetics.nei.PolymeriserRecipeHandler.loadAllRecipes(PolymeriserRecipeHandler.java:72)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//binnie.genetics.nei.PolymeriserRecipeHandler.loadUsageRecipes(PolymeriserRecipeHandler.java:88)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:484)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//binnie.core.nei.RecipeHandlerBase.loadUsageRecipes(RecipeHandlerBase.java:70)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:611)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//codechicken.nei.recipe.TemplateRecipeHandler.getUsageAndCatalystHandler(TemplateRecipeHandler.java:635)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//codechicken.nei.recipe.GuiUsageRecipe.getUsageOrCatalystHandler(GuiUsageRecipe.java:96)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//codechicken.nei.recipe.GuiUsageRecipe.lambda$getUsageHandlers$0(GuiUsageRecipe.java:52)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//codechicken.nei.recipe.RecipeHandlerQuery.lambda$getHandlersWithRecipes$3(RecipeHandlerQuery.java:98)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.base/java.util.stream.AbstractTask.compute(Unknown Source)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[10:34:06] [NEI-worker-thread-44/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

### Your Proposal

Threw error above

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
![image](https://github.com/user-attachments/assets/08e49f11-be0b-4a5c-817c-b6db467acdd6)

I can reproduce this just fine by clicking uses here on RC3

**Comment by chochem** [comment]
to be precise, you get this in chat:
![image](https://github.com/user-attachments/assets/e67d6df3-92d0-4c48-86ae-584a387cfeb4)


and this in the log:
```[16:08:11] [NEI-worker-thread-15/ERROR] [NotEnoughItems/]: Error while looking up usage recipe
[16:08:11] [NEI-worker-thread-15/ERROR] [NotEnoughItems/]: inputId: item
[16:08:11] [NEI-worker-thread-15/ERROR] [NotEnoughItems/]: ingredients: [1xitem.goldNugget@0]
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//binnie.core.nei.PositionedFluidTank.<init>(PositionedFluidTank.java:36)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//binnie.core.nei.PositionedFluidTank.<init>(PositionedFluidTank.java:43)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//binnie.genetics.nei.PolymeriserRecipeHandler$CachedPolymeriserRecipe.<init>(PolymeriserRecipeHandler.java:162)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//binnie.genetics.nei.PolymeriserRecipeHandler.loadAllRecipes(PolymeriserRecipeHandler.java:72)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//binnie.genetics.nei.PolymeriserRecipeHandler.loadUsageRecipes(PolymeriserRecipeHandler.java:88)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:484)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//binnie.core.nei.RecipeHandlerBase.loadUsageRecipes(RecipeHandlerBase.java:70)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:611)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//codechicken.nei.recipe.TemplateRecipeHandler.getUsageAndCatalystHandler(TemplateRecipeHandler.java:635)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//codechicken.nei.recipe.GuiUsageRecipe.getUsageOrCatalystHandler(GuiUsageRecipe.java:96)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//codechicken.nei.recipe.GuiUsageRecipe.lambda$getUsageHandlers$0(GuiUsageRecipe.java:52)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//codechicken.nei.recipe.RecipeHandlerQuery.lambda$getHandlersWithRecipes$3(RecipeHandlerQuery.java:98)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:08:11] [NEI-worker-thread-15/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)```

**Comment by slprime** [comment]
2 broken recipes (i set custom fluid to see this recipes)
![image](https://github.com/user-attachments/assets/23307704-0bca-4601-88fe-83c460626ad7)

**Comment by OneEyeMaker** [comment]
@slprime These recipes aren't broken. Binnie mods use NEI to search for every serum (one is registered for every bee/tree) and uses this item to construct recipes. But currently serum and serum array are *hidden* in NEI, so Binnie mods can't construct any *valid* recipe. 
When you manually modify fluid part of these recipes you just see partially valid recipe.

**Comment by OneEyeMaker** [comment]
For more context: https://github.com/GTNewHorizons/Binnie/blob/master/src/main/java/binnie/genetics/nei/PolymeriserRecipeHandler.java#L141
