### ISSUE TITLE
Missing texture for loading splash art

### ISSUE THREAD

**Issue by vunxix** [GTNewHorizons/GT-New-Horizons-Modpack#18271]
### Your GTNH Discord Username

riley.alexion

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Launch v2.7.0 through the Prism Launcher and look at splash art

### The Reality

Launched v2.7.0 through the Prism Launcher, looked at splash art and a missing texture
![missing-splash-texture](https://github.com/user-attachments/assets/4b75a107-ff11-4ab4-998a-05836085c719)

### Your Proposal

Fix the broken texture at your leisure. Thanks for the work, you all deserve a rest.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
Huh, that's weird. The loading screens are located in `config/txloader/forceload/betterloadingscreen/textures/backgrounds`. Can you check if you have all the files in there? Should be 37 files of which 35 are the loading screens. Can you also provide the log of that specific launch where the loading screen was missing?

**Comment by vunxix** [comment]
Yup, all 37 are present. Is the correct path for that log
.minecraft/logs/latest.log? If so, I have that file attached to this email.

**Comment by vunxix** [comment]
Sorry, I'm not used to github. I'm attaching the file here
[latest.log](https://github.com/user-attachments/files/18053984/latest.log)

**Comment by wlhlm** [comment]
Thanks, unfortunately this does not have all the information that I'm interested in. Please check the `.minecraft/logs` folder for files called `fml-client-*.log`, where `*` is either a number or `latest`. Please upload the one which you think might correspond to the launch with the missing texture (if you rebooted the pack multiple times since then, if not then it should be in `latest`).

**Comment by vunxix** [comment]
I'm fairly certain this is the one you need.
[fml-client-3.log](https://github.com/user-attachments/files/18054514/fml-client-3.log)

**Comment by wlhlm** [comment]
Hmm not really sure what the issue here is. The long doesn't indicate anything that's missing. We were speculating that this could be a slow storage device and that maybe the loading screen just wasn't loaded at that point, but I tried simulating this on Linux with dm-delay. making a device with 5 second latency, but all that did was increase mc loading time before the windows appears with the loading screen.

**Comment by boubou19** [comment]
could it be that it gets somehow trashed by the gc collector?

**Comment by wlhlm** [comment]
Got another report on Discord: https://mclo.gs/5ciRgbU

This includes the following stacktrace:
```
[08:03:14] [BLS Splash renderer/WARN]: Failed to load texture: betterloadingscreen:textures/backgrounds/background33.png
java.io.FileNotFoundException: betterloadingscreen:textures/backgrounds/background33.png
	at Launch//net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
	at Launch//net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:67) ~[brg.class:?]
	at Launch//net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
	at Launch//net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89) ~[bqf.class:?]
	at Launch//net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:45) ~[bqf.class:?]
	at Launch//alexiil.mods.load.MinecraftDisplayer.bindTexture(MinecraftDisplayer.java:1424) ~[MinecraftDisplayer.class:?]
	at Launch//alexiil.mods.load.MinecraftDisplayer.drawImageRender(MinecraftDisplayer.java:1377) ~[MinecraftDisplayer.class:?]
	at Launch//alexiil.mods.load.MinecraftDisplayer.displayProgressInWorkerThread(MinecraftDisplayer.java:1143) ~[MinecraftDisplayer.class:?]
	at Launch//alexiil.mods.load.MinecraftDisplayer$4.run(MinecraftDisplayer.java:798) ~[MinecraftDisplayer$4.class:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

But not sure why it wasn't able to find it. The player confirmed the existence of the file and tx-loader doesn't seem to log anything for it. This was just for a single background image. It was replaced by a working background image soon thereafter.
