### ISSUE TITLE
-Djava.system.class.loader=com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader to your JVM flags         at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:140)

### ISSUE THREAD

**Issue by brotherman123** [GTNewHorizons/GT-New-Horizons-Modpack#18280]
### Your Pack Version

2.7.0

### Your Server

private server

### Java Version

Other versions in between

### Type of Server

None

### Your Actions

While trying to host a server gave me error -Djava.system.class.loader=com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader to your JVM flags
        at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:140)
I removed -Djava.system.class.loader=com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader from java9args.txt as the server told me to. This caused this error what do i do?

### Crash Report

-Djava.system.class.loader=com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader to your JVM flags
        at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:140)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by brotherman123** [comment]
started the server is now kicking me out
