### ISSUE TITLE
[Command] - /railcraft help broken

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/GT-New-Horizons-Modpack#18320]
### Your GTNH Discord Username

Ethryan

### Your Pack Version

2.7.0

### Your Server

SP/ Private Server

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

To get a list of commands from the entered command.

### The Reality

[13:18:37] [Server thread/ERROR]: Couldn't process command: 'railcraft help'
java.lang.AbstractMethodError: Receiver class mods.railcraft.common.commands.RootCommand does not define or inherit an implementation of the resolved method 'abstract int getRequiredPermissionLevel()' of interface mods.railcraft.common.commands.IModCommand.
    at Launch//mods.railcraft.common.commands.CommandHelpers.printHelp(CommandHelpers.java:103) ~[CommandHelpers.class:?]
    at Launch//mods.railcraft.common.commands.RootCommand.printHelp(RootCommand.java:76) ~[RootCommand.class:?]
    at Launch//mods.railcraft.common.commands.CommandHelpers.processStandardCommands(CommandHelpers.java:122) ~[CommandHelpers.class:?]
    at Launch//mods.railcraft.common.commands.RootCommand.func_71515_b(RootCommand.java:66) ~[RootCommand.class:?]
    at Launch//net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
    at Launch//net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
    at Launch//net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
    at Launch//net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
    at Launch//net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
    at Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

### Your Proposal

A fix would be helpful.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
I don't think this is SU related because I can't reproduce it with just SU & railcraft.
