### ISSUE TITLE
Crash + world corruption due to machine cover

### ISSUE THREAD

**Issue by CondoSlime** [GTNewHorizons/GT-New-Horizons-Modpack#18343]
### Your GTNH Discord Username

CondoSlime

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Placing a machine with an inventory cover attached and quickly opening the machine interface and clicking where the cover button should appear crashes the game. Relogging the world constantly crashes too.
Edit: After messing around with a couple other worlds again, my world seemingly un-broke itself somehow and doesn't crash upon startup anymore.

### Crash Report

https://mclo.gs/Wr2JkDq

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by RainVaporeon** [comment]
can reproduce at 2.7.0, the cover correctly appears (alongside the button in the gui) and will crash the client upon interaction; does not crash the server.
logs: https://mclo.gs/OSK3tFE

**Comment by Dream-Master** [comment]
@Glease @miozune any idea. Is that an issue with the chest cover and mui integration ?

**Comment by YannickMG** [comment]
If I had to guess I'd say the reason we're seeing this is https://github.com/GTNewHorizons/GT5-Unofficial/pull/2496

I'm not saying we should go back to having a 2.5s delay before we can interact with a machine. A proper fix would be to either:
- Replace the delay by a hook to make the MTE interactible as soon as the last important bit of state is loaded.
- Allow the UI to dynamically load changes to the state while the MTE is being set up.

**Comment by YannickMG** [comment]
There's also a related crash if you shift-rightclick a cover right after the block was placed down but before the cover appears on the block.

As soon as the cover visually appears on the block, neither bug will occur.

```java
[12:06:12] [Client thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
java.util.NoSuchElementException: Can't find ISyncedWidget for id 0
	at Launch//com.gtnewhorizons.modularui.api.screen.ModularWindow.getSyncedWidget(ModularWindow.java:452) ~[ModularWindow.class:?]
	at Launch//com.gtnewhorizons.modularui.api.screen.ModularUIContext.readServerPacket(ModularUIContext.java:415) ~[ModularUIContext.class:?]
	at Launch//com.gtnewhorizons.modularui.common.internal.network.SWidgetUpdate.executeClient(SWidgetUpdate.java:44) ~[SWidgetUpdate.class:?]
	at Launch//com.gtnewhorizons.modularui.common.internal.network.NetworkHandler.lambda$static$0(NetworkHandler.java:50) ~[NetworkHandler.class:?]
	at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [netty-all-4.0.10.Final.jar:?]
	at Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [netty-all-4.0.10.Final.jar:?]
	at Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.processPacket(FMLProxyPacket.java:86) [FMLProxyPacket.class:?]
	at Launch//net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241) [NetworkManager.class:?]
	at Launch//net.minecraft.client.multiplayer.PlayerControllerMP.updateController(PlayerControllerMP.java:317) [PlayerControllerMP.class:?]
	at Launch//net.minecraft.client.Minecraft.runTick(Minecraft.java:1693) [Minecraft.class:?]
	at Launch//net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1039) [Minecraft.class:?]
	at Launch//net.minecraft.client.Minecraft.run(Minecraft.java:10654) [Minecraft.class:?]
	at Launch//net.minecraft.client.main.Main.main(Main.java:164) [Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at System//net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250) [Launch.class:?]
	at System//net.minecraft.launchwrapper.Launch.launch(Launch.java:35) [Launch.class:?]
	at System//net.minecraft.launchwrapper.Launch.main(Launch.java:60) [Launch.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:207) [lwjgl3ify-2.1.5-forgePatches.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at System//net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:99) [mclauncher-1.7.10.jar:?]
	at System//GradleStart.main(GradleStart.java:40) [?:?]
```

**Comment by YannickMG** [comment]
There's also a link to the  Metrics Transmitter Cover which uses the cover tooltip as it's main UI.

![Image](https://github.com/user-attachments/assets/7a467a3a-05d1-4f56-821b-3e9334a0b847)

**Comment by serenibyss** [comment]
@YannickMG does https://github.com/GTNewHorizons/GT5-Unofficial/pull/3873 resolve this issue?

**Comment by YannickMG** [comment]
Yes I forgot to write as such on the PR.
