### ISSUE TITLE
malis doors

### ISSUE THREAD

**Issue by Thefurrybox** [GTNewHorizons/GT-New-Horizons-Modpack#18409]
### Your GTNH Discord Username

TheFurryBox

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Don't know

### Your Actions

i just / home and then crashes
![image_2024-12-16_140604535](https://github.com/user-attachments/assets/9157b139-c5e9-4935-ba56-97383304c1d8)

### Crash Report

https://mclo.gs/8vxCaDi

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by PLASMAchicken** [comment]
> Can confirm on 2.6.1. Placing an "Iron Vanishing Frame" and putting a block on it crashes other players on my MP server who are a few chunks away. https://mclo.gs/0egK78k
> 
> ```
> java.lang.NullPointerException: Cannot invoke "net.minecraft.world.World.getSkyColorBody(net.minecraft.entity.Entity, float)" because "this.original" is null
>     at net.malisis.doors.ProxyAccess$ProxyWorld.getSkyColorBody(ProxyAccess.java:138)
> ```
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16097#issuecomment-2346509637

**Comment by PLASMAchicken** [comment]
Still happens in 2.8.1 
Stacktrace from [#22802](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/22802)
```
java.lang.NullPointerException
at net.malisis.doors.ProxyAccess$ProxyWorld.drawCloudsBody(ProxyAccess.java:138)
at net.minecraft.world.WorldProvider.drawClouds(WorldProvider.java:405)
at net.minecraft.world.World.getCloudColour(World.java:1676)
at com.gtnewhorizons.angelica.render.CloudRenderer.render(CloudRenderer.java:317)
at net.minecraft.client.renderer.RenderGlobal.renderClouds(RenderGlobal.java:3054)
at net.minecraft.client.renderer.EntityRenderer.renderCloudsCheck(EntityRenderer.java:1383)
at net.minecraft.client.renderer.EntityRenderer.mixinextras$bridge$func_82829_a$94(EntityRenderer.java)
at net.minecraft.client.renderer.EntityRenderer$$Lambda$5942/29018391.call(Unknown Source)
at net.minecraft.client.renderer.EntityRenderer.wrapOperation$zfo000$angelica$iris$clouds(EntityRenderer.java:4645)
at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1200)
at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1011)
at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1001)
at net.minecraft.client.Minecraft.run(Minecraft.java:9340)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by Luigionnaire** [comment]
I have a similar crash:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.World.getBiomeGenForCoordsBody(int, int)" because "this.original" is null
    at net.malisis.doors.ProxyAccess$ProxyWorld.getBiomeGenForCoordsBody(ProxyAccess.java:138)
    at net.minecraft.world.WorldProvider.getBiomeGenForCoords(WorldProvider.java:365)
    at net.minecraft.world.World.getBiomeGenForCoords(World.java:130)
    at biomesoplenty.client.fog.FogHandler.getFogBlendColour(FogHandler.java:304)
    at biomesoplenty.client.fog.FogHandler.onGetFogColour(FogHandler.java:58)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_384_FogHandler_onGetFogColour_FogColors.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.client.renderer.EntityRenderer.updateFogColor(EntityRenderer.java:1831)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1154)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1011)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.run(Minecraft.java:7610)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:60)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:207)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```
It usually happens when first logging in after starting minecraft, occasionally happens multiple times.
Multiple clients affected, can't recreate it, full filelogs: 

[crash-2025-12-23_17.56.20-client.txt](https://github.com/user-attachments/files/24341169/crash-2025-12-23_17.56.20-client.txt)
[crash-2025-12-24_16.03.32-client.txt](https://github.com/user-attachments/files/24341170/crash-2025-12-24_16.03.32-client.txt)
[crash-2025-12-25_23.46.24-client.txt](https://github.com/user-attachments/files/24341167/crash-2025-12-25_23.46.24-client.txt)
[crash-2025-12-23_00.21.22-client.txt](https://github.com/user-attachments/files/24341165/crash-2025-12-23_00.21.22-client.txt)
[crash-2025-12-23_00.22.33-client.txt](https://github.com/user-attachments/files/24341168/crash-2025-12-23_00.22.33-client.txt)
[crash-2025-12-23_11.16.01-client.txt](https://github.com/user-attachments/files/24341166/crash-2025-12-23_11.16.01-client.txt)

**Comment by PLASMAchicken** [comment]
@Luigionnaire you just gotta remove all malisis doors blocks, the people in the chunk are usually not affected, its mostly the people a few chunks away

**Comment by PLASMAchicken** [comment]
### Your GTNH Discord Username

@DawnBroke114

### Your Pack Version

2.8.3

### Your Server

private server

### Java Version

Java 21

### Type of Server

Don't know

### Your Actions

The crash is client-side only and can be consistently reproduced. When any player (myself or my friend) attempts to log into the server and is within the loaded area of my base, their client crashes immediately and reliably. The server itself remains running without issues.

In my base, I have extensive automation utilizing many Railcraft locomotives and carts to compensate for the low throughput of LV conveyor belts and to distribute items evenly. I suspect this may be related, although crash logs never directly point to Railcraft—instead, each crash cites a different mod or an unknown cause.

The server is set up using the official GTNH server files. The only modifications are language-related mods and a localization pack (Chinese); no other gameplay-altering mods are installed.

(Note: This description was translated with AI assistance due to my limited English proficiency.)

### Crash Report

[crash-2026-02-02_00.04.03-client.txt](https://github.com/user-attachments/files/25025294/crash-2026-02-02_00.04.03-client.txt)

[crash-2026-02-02_00.08.23-client.txt](https://github.com/user-attachments/files/25025295/crash-2026-02-02_00.08.23-client.txt)

[crash-reports.zip](https://github.com/user-attachments/files/24993964/crash-reports.zip)

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by AstroCatTBC** [comment]
Oop, yep, this is the same issue. This title wasn't very descriptive so it didn't tip me off as related.
