### ISSUE TITLE
Crushed when using machines in forestry.genetics

### ISSUE THREAD

**Issue by Timistra** [GTNewHorizons/GT-New-Horizons-Modpack#18407]
### Your GTNH Discord Username

none

### Your Pack Version

2.7.0 release

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

We just waiting for the DNA analyze and do nothing.

### Crash Report

java.lang.NullPointerException: Cannot invoke "forestry.api.genetics.IChromosome.getInactiveAllele()" because "this.chromosomes[forestry.api.genetics.IChromosomeType.ordinal()]" is null
	at Launch//forestry.core.genetics.Genome.getInactiveAllele(Genome.java:292)
	at Launch//binnie.genetics.machine.isolator.IsolatorComponentLogic.onFinishTask(IsolatorComponentLogic.java:83)
	at Launch//binnie.core.machines.power.ComponentProcess.onUpdate(ComponentProcess.java:40)
	at Launch//binnie.core.machines.Machine.onUpdate(Machine.java:150)
	at Launch//binnie.core.machines.TileEntityMachine.func_145845_h(TileEntityMachine.java:20)
	at Launch//net.minecraft.world.World.func_72939_s(World.java:1939)
	at Launch//net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Victor-Laurence** [comment]
I am definitely able to replicate this bug. Running 2.7.0 release version. Attached is my full crash report.

[crash-2025-01-31_00.28.13-server.txt](https://github.com/user-attachments/files/18614063/crash-2025-01-31_00.28.13-server.txt)

**Steps to Reproduce**
1. Use the Genetics Isolator and Analyzer machines
2. Power using an energy conduit and an Ender IO capacitor bank
3. Try to extract genes with any drone, larva, or princess. 
4. Doesn't happen immediately but usually within about 5-10 minutes it'll hard crash your server.

I was almost feeling like Larvae were a workaround for this bug because I didn't get a crash for a while, but I even got a crash with a Larvae from the Alveary Hatchery. Unsure if it's an issue with the Isolator or Analyzer, but most likely based on the description of the crash it sounds like it's the Isolator when it's trying to make an Apiarist DNA Sequence using a Null Allele (which should never be). 

Apparently there was some chatter I saw by searching the discord about talk about an updated version of one of the mods removing certain error handling which has caused this. 

I could limp along without Genetics until I get to Gendustry, but really would love to take advantage of my bee lab setup and start modifying traits on bees I'm breeding and putting into production.

**Comment by GamerSocke** [comment]
Got the same crash 4 times at the end of isolation of a Wintry Drone.

**Comment by RichmondD** [comment]
Getting the same issue for my server.
Discord Username: Nacnudd
Your Pack Version: 2.7.1
Your Server: Private server
Java Version: Java 17
Type of Server: Vanilla Forge

I wasn't the player individually doing this, but can speak for them. This started as soon as they started doing forestry genetics and the error above matches their experience.

[crash-2025-03-24_21.30.02-server.txt](https://github.com/user-attachments/files/19440360/crash-2025-03-24_21.30.02-server.txt)

**Comment by jay-sharma1** [comment]
Discord Username: Zepherox
Your Pack Version: 2.7.4
Your Server: Private server
Java Version: Java 17
Type of Server: Vanilla Forge


Previously had this issue in Pack Version 2.7.0, but upon updating to Pack Version 2.7.4 the issue seems to have resolved itself. I would suggest replacing the mods folder in _Instances/instance_name/.minecraft/_ with a fresh one from the website of the same pack version. 

If the issue is resolved then something went wrong while running the pack and could happen again even after updating to the newest version. 

If the issue is not resolved, then it is more likely that there was a bugfix deployed within one of those newer updates.

**Comment by PLASMAchicken** [comment]
Assuming fixed with latest Version. Feel free to comment with more Info to reopen the Issue.
