### ISSUE TITLE
Smelting items in TC Smeltery crashes server

### ISSUE THREAD

**Issue by lailani-f** [GTNewHorizons/GT-New-Horizons-Modpack#18513]
### Your GTNH Discord Username

cure.starlight

### Your Pack Version

2.8.x-nightly-789 + WitchingGadgets-1.5.21-GTNH.pre

### Your Server

Zeta

### Java Version

Java 20

### Type of Server

Don't know

### Your Actions

build smeltery, put in iron dust (or any other smeltable item), watch it crash as the recipe finishes

### Crash Report

[crash-2024-12-25_22.17.25-server.txt](https://github.com/user-attachments/files/18247266/crash-2024-12-25_22.17.25-server.txt)

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-12-25 22:17:25 CET
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.minecraftforge.fluids.FluidStack.isFluidEqual(net.minecraftforge.fluids.FluidStack)" because "mixer" is null
    at tconstruct.library.crafting.AlloyMix.mix(AlloyMix.java:28)
    at tconstruct.library.crafting.Smeltery.mixMetals(Smeltery.java:177)
    at tconstruct.smeltery.logic.SmelteryLogic.heatItems(SmelteryLogic.java:435)
    at tconstruct.smeltery.logic.SmelteryLogic.updateEntity(SmelteryLogic.java:304)
    at net.minecraft.world.World.updateEntities(World.java:1939)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by lailani-f** [comment]
I've added some logging to track where the invalid recipe comes from and it's giving me this:

```
[00:46:51] [Client thread/ERROR] [TConstruct]: Fluid '<FLUIDSTACK IS NULL>' has inputs '<FLUIDSTACK IS NULL>', fluid.copper.molten'
[00:46:51] [Client thread/ERROR] [TConstruct]: [java.base/java.lang.Thread.getStackTrace(Thread.java:2450), Launch//tconstruct.library.crafting.AlloyMix.log(AlloyMix.java:69), Launch//tconstruct.library.crafting.AlloyMix.<init>(AlloyMix.java:19), Launch//tconstruct.library.crafting.Smeltery.addAlloyMixing(Smeltery.java:119), Launch//com.dreammaster.scripts.ScriptProjectRed.loadRecipes(ScriptProjectRed.java:164), Launch//com.dreammaster.scripts.ScriptLoader.run(ScriptLoader.java:136),
```

it refers to this line but I have no idea what the problem with it is https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/master/src/main/java/com/dreammaster/scripts/ScriptProjectRed.java#L164
