### ISSUE TITLE
NetworkDispatcher exception java.lang.IllegalArgumentException: Payload may not be larger than 32k

### ISSUE THREAD

**Issue by lexx1191** [GTNewHorizons/GT-New-Horizons-Modpack#3327]
#### Which modpack version are you using?
#2.0.4.6

#### If in multiplayer; On which server does this happen? 

# single
#### What did you try to do, and what did you expect to happen?

#craft luv buffer (gt++), crash
#### What happend instead? (Attach screenshots if needed)
[latest.log](https://github.com/GTNewHorizons/NewHorizons/files/2206113/latest.log)

[Netty Client IO #1/ERROR]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32k
	at net.minecraft.network.play.client.C17PacketCustomPayload.<init>(SourceFile:38) ~[iz.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:120) ~[FMLProxyPacket.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:434) ~[NetworkDispatcher.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at net.minecraft.network.NetworkManager$1.run(NetworkManager.java:174) [ek.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [SingleThreadEventExecutor.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by alphaNOVAircraft** [comment]
did you have bagpacks with you or a chest inside a dolly with some stuff in it? iirc i had a similar error when i picked up the wrong chest (full with ae2 drives) because the players.dat cant store that much data

**Comment by lexx1191** [comment]
this happens when crafting buffer luv
