### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/GT-New-Horizons-Modpack#4936]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
Private

#
#### What did you try to do, and what did you expect to happen?
Walking around base (
[crash-2019-08-14_13.22.45-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/3502475/crash-2019-08-14_13.22.45-server.txt)

----

Immediatly after reload set game to peaceful and got this crash a  few seconds later
[crash-2019-08-14_14.03.39-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/3502476/crash-2019-08-14_14.03.39-server.txt)
[crash-2019-08-14_14.03.57-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/3502490/crash-2019-08-14_14.03.57-client.txt)

----

Hit my unknown mob effect at range
[crash-2019-08-14_17.50.02-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/3502479/crash-2019-08-14_17.50.02-server.txt)

**Comment by richardhendricks** [comment]
Your first two crashes are caused by a spider and a pig, respectively.  I'd start with a fresh install just to make sure there isn't anything corrupt going on with your files on client and server.

**Comment by drayath** [comment]
This appears to be due to the Magic Bees beejar (with a beatify bee in it)
-
Had other crashes until finally could not enter game without reproducible immediate crash. Using a save editor to delete the bee jar resolved the issue and i have has no more crashs since i have stopped using the bee jar.

Got one error that seemed to show slightly more info, though the mobs affects should be well outside the jars range (should be approx 5 range with this bee, erroring mobs over 20 distance away)

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:600)
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1490)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1814)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.passive.EntityBat.func_70071_h_(SourceFile:109)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
