### ISSUE TITLE
Avaritia and related addons textures bugged

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5962]
#### Which modpack version are you using?
2.0.9.0 DEV (Persists in earlier versions though)
#
For some reason certain Avaritia items do not render correctly, see below screenshots for examples.

<img width="523" alt="Screenshot 2020-04-22 at 09 11 25" src="https://user-images.githubusercontent.com/54497873/79957382-65ad8000-8479-11ea-858f-3a58e22357bc.png">

As can be seen above the entire infinity set and the sword is bugged along with the bow and matter cluster but other tools seem to render properly.

Additionally all textures from the "eternal singularities" addon are broken.

<img width="274" alt="Screenshot 2020-04-22 at 09 14 21" src="https://user-images.githubusercontent.com/54497873/79957582-ab6a4880-8479-11ea-8adc-6ba0965b0021.png">

Also i've noticed that the infinity armour renders wrong when worn and doesn't seem to line up with the player if that makes sense?

![2020-04-22_09 19 55](https://user-images.githubusercontent.com/54497873/79959877-9511bc00-847c-11ea-9e17-859ec0218a98.png)

![2020-04-22_09 19 58_2](https://user-images.githubusercontent.com/54497873/79959899-9e9b2400-847c-11ea-8f61-b8ea0d0167c6.png)

It's quite a shame these are a bit bugged, they seem to work perfectly fine for some people but others get this issue it seems to be related to operating system (MacOS gets this).

For reference items should look as shown below:

<img width="347" alt="Screenshot 2020-04-22 at 09 42 38" src="https://user-images.githubusercontent.com/54497873/79960724-a8715700-847d-11ea-9d53-23f7fb88791c.png">

**Comment by Dream-Master** [comment]
@GTNH-Colen are you using any additional ressoucepack or texture pack? whit optifine or without? shader?

**Comment by GTNH-Colen** [comment]
> @GTNH-Colen are you using any additional ressoucepack or texture pack? whit optifine or without? shader?

No texture/resource pack, no shaders, not got any optifine either this is just default.

**Comment by Prometheus0000** [comment]
They all look fine in 2.0.8.8 to me? I turned off all my texturepacks.
![temp2](https://user-images.githubusercontent.com/8517039/79982991-1ebd8b80-8475-11ea-975e-74552a649e83.png)

**Comment by GTNH-Colen** [comment]
> They all look fine in 2.0.8.8 to me? I turned off all my texturepacks.
> ![temp2](https://user-images.githubusercontent.com/8517039/79982991-1ebd8b80-8475-11ea-975e-74552a649e83.png)

Some people seem to get it and some don't, I'm not entirely sure why though. I asked around before and most peoples seem ok but mine and a few others render this way.

**Comment by Prometheus0000** [comment]
Maybe it's based on the launcher? I'm using MMC.

**Comment by GTNH-Colen** [comment]
> Maybe it's based on the launcher? I'm using MMC.

Tested on technic and multi MC, same issue. Seems like something computer wise that isn't quite behaving correctly but as to what I have no clue.

**Comment by draknyte1** [comment]
Probably OS related. Linux follows capitalisation whilst windows doesn’t.

**Comment by leagris** [comment]
Or locale related if resource-location is wrongly computed from localized name.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/80126491-75b98280-8593-11ea-83fd-31f860d13d72.png)

**Comment by GTNH-Colen** [comment]
I've asked around on eta and it seems to occur on MacOS, unsure about linux. It is a very minor thing in the grand scheme just these textures are quite pretty so would be nice if they showed correctly.

**Comment by paciello1040** [comment]
i have the same problem is there any way to solve?

**Comment by bombcar** [comment]
I can reproduce on Mac; I will track it down.

![image](https://user-images.githubusercontent.com/533931/146971888-1d67dc04-7ca9-4ad5-8e01-2f388c8da547.png)

it loads ... something as that's not the "invalid texture" image.

**Comment by leagris** [comment]
Minecraft stores the tessellator's GL instructions into a byte array in Java Heap space. Depending on some configurations, memory settings, GFX Card type and driver, the GL Engine may have issues accessing these GL Instructions. Possibly alignment or fragmentation related or part of the texture data is not in heap and belong to an object that got flushed away
I had rendering bugs affecting Thaumcraft nodes with an older Nvidia card when Max Memory was equal to Initial Memory.

The rendering bug described in this issue looks similar. This could be also GFX driver related.

**Comment by bombcar** [comment]
Can someone who DOES get this see if 

```
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.RuntimeException: Error creating shader "/assets/avaritia/shader/cosmic.frag": ERROR: 0:1: '' :  version '130' is not supported

[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at fox.spiteful.avaritia.render.ShaderHelper.createShader(ShaderHelper.java:117)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at fox.spiteful.avaritia.render.ShaderHelper.createProgram(ShaderHelper.java:79)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at fox.spiteful.avaritia.render.ShaderHelper.initShaders(ShaderHelper.java:38)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at fox.spiteful.avaritia.ClientProxy.makeThingsPretty(ClientProxy.java:69)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at fox.spiteful.avaritia.Avaritia.midGame(Avaritia.java:73)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at java.lang.reflect.Method.invoke(Method.java:498)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at java.lang.reflect.Method.invoke(Method.java:498)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at java.lang.reflect.Method.invoke(Method.java:498)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at net.minecraft.client.Minecraft.startGame(Minecraft.java:597)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at net.minecraft.client.Minecraft.run(Minecraft.java:942)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at net.minecraft.client.main.Main.main(Main.java:164)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at java.lang.reflect.Method.invoke(Method.java:498)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
[14:24:02] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at GradleStart.main(Unknown Source)
```

is in their log, and someone who does NOT get this, see if it is missing?

**Comment by bombcar** [comment]
That appears not to be it, I forcefully disabled the shader and it still happens.

**Comment by bombcar** [comment]
I got to here:

![image](https://user-images.githubusercontent.com/533931/147006610-4159bd52-26cf-4a50-8674-41fb5d83ceb1.png)

can someone on a _working_ system do a short screen record of what it should be animated?

**Comment by bombcar** [comment]
https://images-ext-1.discordapp.net/external/0g54BLbHBi8PEQC2Aj57BR6tPmKN47H8QtTS7ELDaDI/https/giant.gfycat.com/BelovedHideousCoati.mp4
