### ISSUE TITLE
Brocken Opis

### ISSUE THREAD

**Issue by PredVesTNiK2142** [GTNewHorizons/GT-New-Horizons-Modpack#6317]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
SP and MP
#
#### What did you try to do, and what did you expect to happen?
Broke in the Opis mod update. The MP does not display almost no information. The SP now just crashes the client.

[Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at mcp.mobius.opis.data.profilers.ProfilerEvent.stop(ProfilerEvent.java:43) ~[ProfilerEvent.class:?]
	at mcp.mobius.mobiuscore.profiler.ProfilerSection.stop(ProfilerSection.java:128) ~[ProfilerSection.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:335) ~[FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:999) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

Server on Forge. On 2.0.8.8, everything still works fine.
#

**Comment by PredVesTNiK2142** [comment]
Can you take a problem to work? So the status is critical. Broke the admin utility.

**Comment by PredVesTNiK2142** [comment]
I found out that Opis is breaking the new BugTorch mod. Please fix it.

**Comment by Dream-Master** [comment]
@jss2a98aj can you check it if this is opis or bug torch fault? thanks

**Comment by PredVesTNiK2142** [comment]
I tested it in more detail - I found that Opis stops working normally on the server if I add TickProfiler-1.7.10.jenkins.38.jar along with BugTorch. However, uninstalling BugTorch still solves the problem completely.

**Comment by boubou19** [comment]
We had an issue on the officials where more than half of the "Server timing" tab was broken: the lists were empty. Removing bugtorch 1.0.2 fixed the issue.

**Comment by Dream-Master** [comment]
@jss2a98aj we need a fix for thermos here or i am forced to remove the mod next update. Any idea to fix this ?

**Comment by jss2a98aj** [comment]
One or more of the mixins in bugtorch are conflicting. I don't know what ones, but all of them can be turned off for testing.

**Comment by jss2a98aj** [comment]
Where can I get a copy of "TickProfiler-1.7.10.jenkins.38.jar" for testing?

**Comment by leagris** [comment]
> Where can I get a copy of "TickProfiler-1.7.10.jenkins.38.jar" for testing?

https://jenkins.nallar.me/job/TickProfiler/job/1.7.10/
