### ISSUE TITLE
Rocket dissapearing

### ISSUE THREAD

**Issue by viljar290** [GTNewHorizons/GT-New-Horizons-Modpack#6332]
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
ETA
#
#### What did you try to do, and what did you expect to happen?
Used my T3 rocket to fly from my base to asteroids, then tried to use it to fly back to overworld.
#
#### What happened instead? (Attach screenshots if needed)
I landed 20000m from my base at the edge of the world. no parachest as far as I can find so rocket has gone missing. 
This is the 2nd time my t3 rocket has gone missing on landing in the overworld.
#
#### What do you suggest instead/what changes do you propose?
figure out why this keeps happening. or maybe make it land like the rocket does in a pod in asteroids and such instead of the parachest that may or may not appear...

**Comment by Regian24** [comment]
The rocket escape pod sounds like a good idea.

**Comment by Prometheus0000** [comment]
Try using the launch controller (look at the quest for info).

**Comment by viljar290** [comment]
im not sure how the launch controller would help.

**Comment by Prometheus0000** [comment]
The rocket teleports between launch pads with it set up.

**Comment by FlandreS** [comment]
Occasionally reproducibly in my server, players will disconnect while starting the parachute sequence. This causes the parachest to never spawn and effectively deletes their rocket/launch pad.

This issue also happens in 2.1.1.0 & 2.1.2.1 in a "standard" GTNH configuration, and I've lost a few rockets in the past from this, it's a bummer that it affects such a big-ticket item.

The biggest issue is that the launch controller isn't a solution at the moment. A player must still make multiple trips to the moon/mars before they can craft a launch controller meaning there are multiple instances that a rocket can be lost. If the issue can't be fixed, maybe we can start a thread to remove the desh requirement on the controller to let players use it on their first T1 rocket mission?

Server errors point to something wrong with Waila, perhaps explaining why it's a somewhat random issue to experience, could it have something to do with a player's facing upon re-entry?

Error when players disconnect:
```
[19:39:24] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel Waila
java.lang.NullPointerException
	at mcp.mobius.waila.network.Message0x03EntRequest.channelRead0(Message0x03EntRequest.java:70) ~[Message0x03EntRequest.class:?]
	at mcp.mobius.waila.network.Message0x03EntRequest.channelRead0(Message0x03EntRequest.java:24) ~[Message0x03EntRequest.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-5.3]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```
