### ISSUE TITLE
Help crash

### ISSUE THREAD

**Issue by Besstyzhiy** [GTNewHorizons/GT-New-Horizons-Modpack#6339]
#### Which modpack version are you using?
GTNewHorizonsServer-1.7.10-2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Thermos 1614
#
#### What did you try to do, and what did you expect to happen?
Craft

#
#### What happened instead? (Attach screenshots if needed)
java.lang.ClassCastException: bq_standard.handlers.PlayerContainerListener cannot be cast to net.minecraft.entity.player.EntityPlayerMP
        at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:105) ~[aap.class:?]
        at net.minecraft.inventory.InventoryCrafting.func_70299_a(InventoryCrafting.java:153) ~[aae.class:?]
        at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77) ~[aay.class:?]
        at net.minecraft.inventory.Container.func_75144_a(Container.java:418) ~[zs.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2075) ~[nh.class:?]
        at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
        at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
#

**Comment by shawnbyday** [comment]
@Besstyzhiy I realize this is a late response but did you get this working? If not and you're still actively trying to get it to work can you post a full log? If no response within a few days will just assume it's safe to close.

**Comment by juanmuscaria** [comment]
It's a thermos bug, it does not check if the inventory listener is a player or not, see Funwayguy/BetterQuesting#605
I made a fix for it a while ago https://github.com/juanmuscaria/Gambiarra-BetterQuesting

**Comment by Dream-Master** [comment]
And we fork this
https://github.com/GTNewHorizons/BQ3-Thermos-patch

**Comment by BreakingLead** [comment]
Why not close this issue?
