### ISSUE TITLE
Client Crash: caused by "Inverted White Lamp Slab/Panel/Cover"

### ISSUE THREAD

**Issue by iBattery355** [GTNewHorizons/GT-New-Horizons-Modpack#6419]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Personal server by using MSCS.
#
#### What did you try to do, and what did you expect to happen?
I tried to break and collect "Inverted White Lamp Slab/Panel/Cover".

"Inverted White Lamp" from "ProjectRed Illumination"
![image](https://user-images.githubusercontent.com/36044216/88079317-87d39e80-cb4b-11ea-83bc-3cf3c5a11c1e.png)

"Inverted White Lamp Slab/Panel/Cover" from "ForgeMicroblocks"
![image](https://user-images.githubusercontent.com/36044216/88079910-58716180-cb4c-11ea-900e-c5c9da393411.png)

#
#### What happened instead? (Attach screenshots if needed)
Client crash immediately when left clicking the "Inverted White Lamp Slab/Panel/Cover". 

Server is still running but with error report:

`
java.lang.ArrayIndexOutOfBoundsException: 16
        at net.minecraft.block.Block.getHarvestLevel(Block.java:2211) ~[aji.class:?]
        at iguanaman.iguanatweakstconstruct.override.ExtraHarvestLevelHandler.breakSpeed(ExtraHarvestLevelHandler.java:22) ~[ExtraHarvestLevelHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_1346_ExtraHarvestLevelHandler_breakSpeed_BreakSpeed.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:89) ~[ForgeEventFactory.class:?]
        at net.minecraft.entity.player.EntityPlayer.getBreakSpeed(Unknown Source) ~[yz.class:?]
        at codechicken.microblock.BlockMicroMaterial.getStrength(BlockMicroMaterial.scala:98) ~[BlockMicroMaterial.class:?]
        at codechicken.microblock.Microblock.getStrength(Microblock.scala:44) ~[Microblock.class:?]
        at codechicken.multipart.BlockMultipart.func_149737_a(BlockMultipart.scala:205) ~[BlockMultipart.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73074_a(Unknown Source) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489) ~[nh.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) ~[ji.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) ~[ji.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

`
![image](https://user-images.githubusercontent.com/36044216/88081716-c61e8d00-cb4e-11ea-8670-9da0eac29d66.png)
#
#### What did you do? 
I have tested solely for "ProjectRed Illumination" and "ForgeMicroblocks" and they seem to work without any similar problems.

**Comment by Dream-Master** [comment]
We have project red repo. @repo-alt can you help us because its written in scala. Thanks

**Comment by repo-alt** [comment]
Looks like iguana tweaks issue

**Comment by boubou19** [comment]
maybe related to this one: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/359

**Comment by Dream-Master** [comment]
we have inguana source so feel free to fix if it is possible

**Comment by Jimbno** [comment]
Also this to note, this doesn't happen in creative mode  since you can insta-break them

**Comment by mitchej123** [comment]
Fixed here - https://github.com/GTNewHorizons/ForgeMultipart/commit/ad1ad6da380dbfab949abfc3a4f3dac298941a90

**Comment by mitchej123** [comment]
[ForgeMultipart-1.7.10-1.2.0.348-universal.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6097697/ForgeMultipart-1.7.10-1.2.0.348-universal.zip)

Rename to jar
