### ISSUE TITLE
looking usage of some bartworks fluids crash the game

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6439]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
wanted to look usage of molten Eximite and molten scandium
#
#### What happened instead? (Attach screenshots if needed)
i crashed for both. here is the stacktrace in the crashes: <details><summary>stacktrace</summary> java.lang.NullPointerException: Rendering item
	at com.github.bartimaeusnek.bartworks.system.material.GT_Enhancement.BWGTMetaItems.getIconContainerBartWorks(BWGTMetaItems.java:104)
	at com.github.bartimaeusnek.bartworks.system.material.GT_Enhancement.BWGTMetaItems.getIconContainer(BWGTMetaItems.java:88)
	at gregtech.common.render.GT_MetaGenerated_Item_Renderer.renderItem(GT_MetaGenerated_Item_Renderer.java:66)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:202)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:498)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1400)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) </details>

**Comment by Dream-Master** [comment]
Not sure if BW or nei or both cause it.

**Comment by mitchej123** [comment]
Is this still an issue?
