### ISSUE TITLE
motion sensor from opencomputers will corrupt the chunk you place it in

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6484]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
i placed a motion sensor
#
#### What happened instead? (Attach screenshots if needed)
delta crashed
<details>
    <summary>stack trace</summary>
<pre><code>Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.func_70666_h(F)Lnet/minecraft/util/Vec3;
    at li.cil.oc.server.component.MotionSensor.li$cil$oc$server$component$MotionSensor$$isVisible(MotionSensor.scala:114)
    at li.cil.oc.server.component.MotionSensor$$anonfun$2.apply(MotionSensor.scala:72)
    at li.cil.oc.server.component.MotionSensor$$anonfun$2.apply(MotionSensor.scala:72)
    at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
    at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
    at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
    at li.cil.oc.server.component.MotionSensor.update(MotionSensor.scala:72)
    at li.cil.oc.common.tileentity.MotionSensor.func_145845_h(MotionSensor.scala:16)
    at net.minecraft.world.World.func_72939_s(World.java:2583)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
    at java.lang.Thread.run(Thread.java:748)</code></pre></details>

**Comment by Dream-Master** [comment]
@repo-alt any idea ?

**Comment by repo-alt** [comment]
Can't reproduce that with OC alone, some other mod is breaking things

**Comment by repo-alt** [comment]
Doesn't crash w/o Thermos

**Comment by boubou19** [comment]
did you tried with computronics and opensecurity too?

**Comment by repo-alt** [comment]
I tried with full pack

**Comment by repo-alt** [comment]
The bug is in obfuscated name mismatch, That is - something has fucked up EntityLivingBase.getPosition SRG name. I don't even know how is that possible, w/o breaking up everything else
