### ISSUE TITLE
Client crash on using custom launcher

### ISSUE THREAD

**Issue by BlayzerQ** [GTNewHorizons/GT-New-Horizons-Modpack#6490]
When i run 1.7.10-2.0.9.0QF4 version of GT NH on a third-party launcher (sashok724`s launcher) and the online mod is on, a client crash occurs (For a long time using the launcher, on any other assemblies such a problem did not arise. Ony on GT NH). 

If i disable all mods - no problem. Do any mods affect authorization? Have any authorization patches been applied to them?

java.lang.NoClassDefFoundError: launcher/LoLkekCHebuREk
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.joinServer(SourceFile:140)
	at net.minecraft.client.network.NetHandlerLoginClient.func_147389_a(NetHandlerLoginClient.java:62)
	at net.minecraft.network.login.server.S01PacketEncryptionRequest.func_148833_a(SourceFile:41)
	at net.minecraft.network.login.server.S01PacketEncryptionRequest.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

[crash-2020-07-25_10.19.56-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5048233/crash-2020-07-25_10.19.56-client.txt)

**Comment by boubou19** [comment]
only technic launcher, twitch launcher and multimc launcher are supported. Also, we don't help players to get rid of the licensing system. If you have a genuine minecraft account, pls use one of the listed launchers. I you don't own a genuine account, we cannot do anything for you.
