### ISSUE TITLE
Minetweaker: Hazmat repair recipe crashes client side

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#6973]
#### Which modpack version are you using?
 2.0.9.3A
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Repair hazmat pants with a glue bucket
#
#### What happened instead? (Attach screenshots if needed)
java.lang.NullPointerException: Updating screen events
	at ZenClassIC23.process(Unknown Source)
	at minetweaker.api.recipes.ShapedRecipe.doRecipe(ShapedRecipe.java:292)
	at minetweaker.api.recipes.ShapedRecipe.getCraftingResult(ShapedRecipe.java:163)
	at minetweaker.mc1710.recipes.ShapedRecipeOre.func_77572_b(ShapedRecipeOre.java:37)
	at com.github.bartimaeusnek.ASM.BWCoreStaticReplacementMethodes.findCachedMatchingRecipe(BWCoreStaticReplacementMethodes.java:112)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java)
	at tconstruct.tools.inventory.CraftingStationContainer.func_75130_a(CraftingStationContainer.java:119)
	at tconstruct.tools.inventory.InventoryCraftingStation.func_70299_a(InventoryCraftingStation.java:121)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(Unknown Source)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:513)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)

**Comment by repo-alt** [comment]
@mitchej123

**Comment by Dream-Master** [comment]
[CraftTweaker-1.7.10-3.2.0-GTNH.4-legacy.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5577421/CraftTweaker-1.7.10-3.2.0-GTNH.4-legacy.zip)
@repo-alt try with mitch new version not sure if that helps

**Comment by Glease** [comment]
Fixed by #6974

**Comment by repo-alt** [comment]
Now it does not crash, but looks like it returns an extra bucket.

**Comment by Prometheus0000** [comment]
Wonderful! Another bucket dupe issue that will cause dozens of tickets and persist for years!

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/101093427-ce420b00-35cb-11eb-9a91-78914342de26.png)

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/101093473-df8b1780-35cb-11eb-91c6-b47573d12d3e.png)

**Comment by Dream-Master** [comment]
maybe we need to add a additional empty bucket to recipe
