### ISSUE TITLE
Crash burning Oak Sapling in Witches Oven (ticking block entity)

### ISSUE THREAD

**Issue by PPKFS** [GTNewHorizons/GT-New-Horizons-Modpack#7154]
#### Which modpack version are you using?
2.1.0.0, both (locally hosted) server and SSP.
#
#### What did you try to do, and what did you expect to happen?
Placed oak sapling in witches oven with fuel (tested with both coal dust and coal) and clay jars.
This was found in my own world, but was reproducible in a creative test world (giving the player a witches oven, oak sapling, and fuel).
#
#### What happened instead? (Attach screenshots if needed)
Crash to desktop. Server attempts to restart but immediately crashes on load.
https://media.discordapp.net/attachments/181078474394566657/791799067373862922/2020-12-24-224640_1190x329_scrot.png?width=942&height=260

```
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at alkalus.main.core.util.WitchesOvenUtils.canSmelt(WitchesOvenUtils.java:197)
	at com.emoniph.witchery.blocks.BlockWitchesOven$TileEntityWitchesOven.canSmelt(BlockWitchesOven.java:155)
	at com.emoniph.witchery.blocks.BlockWitchesOven$TileEntityWitchesOven.func_145845_h(BlockWitchesOven.java:414)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at alkalus.main.core.util.WitchesOvenUtils.canSmelt(WitchesOvenUtils.java:197)
	at com.emoniph.witchery.blocks.BlockWitchesOven$TileEntityWitchesOven.canSmelt(BlockWitchesOven.java:155)
	at com.emoniph.witchery.blocks.BlockWitchesOven$TileEntityWitchesOven.func_145845_h(BlockWitchesOven.java:414)

-- Block entity being ticked --
Details:
	Name: witchery:witchesovenidle // com.emoniph.witchery.blocks.BlockWitchesOven.TileEntityWitchesOven
	Block type: ID #1910 (tile.witchery:witchesovenidle // com.emoniph.witchery.blocks.BlockWitchesOven)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (427,78,-520), Chunk: (at 11,4,8 in 26,-33; contains blocks 416,0,-528 to 431,255,-513), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Actual block type: ID #1910 (tile.witchery:witchesovenidle // com.emoniph.witchery.blocks.BlockWitchesOven)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 659 Drop: 0
	Level seed: 6972190577020307205
	Level generator: ID 04 - RWG, ver 0. Features enabled: true
	Level generator options: 2;1x7,52x24,1x3:2,;2;biome_1,village
	Level spawn location: World: (194,64,31), Chunk: (at 2,4,15 in 12,1; contains blocks 192,0,16 to 207,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 14708205 game time, 17330603 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 52830 (now: false), thunder time: 161723 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by PPKFS** [comment]
https://github.com/alkcorp/WitcheryExtras/issues/9

fairly sure this is the cause - no null checking means if there are no items in the output, it's gonna throw NPEs when checking if the input items smelt to the existing output.

**Comment by Dream-Master** [comment]
@draknyte1 are you able to fix this ?

**Comment by draknyte1** [comment]
Yes. I was under the impression someone else was going to though. 🤷🏻‍♀️

**Comment by Glease** [comment]
I found a way to fix it, but didn't got the time to test it. 🤷

**Comment by Fatherlumberjack** [comment]
It doesn't look like there is a .jar file for WitcheryExtras, and I've had a lot of trouble with exporting the changed files in eclipse. could someone help we with getting my hands on an edited jar file or fixing the export process?

**Comment by boubou19** [comment]
DM on discord, i have a fix for it, but can't share it here, because github doesn't allow us to post jar file

**Comment by Prometheus0000** [comment]
The built mods are found on our jenkins http://jenkins.usrv.eu:8080/. In addition, you can post a jar if you zip it first.

**Comment by Dream-Master** [comment]
http://jenkins.usrv.eu:8080/job/Witchery-Extras/
