### ISSUE TITLE
NEI 'usage' function does not work in 2.1.0.0

### ISSUE THREAD

**Issue by HenadziStantchik** [GTNewHorizons/GT-New-Horizons-Modpack#7180]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
In single player
#
#### What did you try to do, and what did you expect to happen?
Try to check on usage of an item in crafting recipes by right-clicking/pressing `U` key/pressing `shift + R` combination. (NEI recipe mode)
#
#### What happened instead? (Attach screenshots if needed)
The recipes in which the item is used did not show up. Actually, nothing happens even with basic items such as stone and etc.
#

IMO this is important feature that allows new player (like me for example) to investigate what can he do with specific gas/liquid/ore/item. This is the second important thing after BQ for learning the pack

**Comment by Prometheus0000** [comment]
Did you check your keybinds? Pretty sure it works.

**Comment by HenadziStantchik** [comment]
> Did you check your keybinds? Pretty sure it works.

Restarted the game and it works now. O_o

I guess this was a random thing. The issue can be closed now, sorry to bother

**Comment by Dream-Master** [comment]
Had this issue before. Happend random times but not very often.

**Comment by mitchej123** [comment]
If you can reproduce this, please indicate the steps.  Also check for any related logs when it's not working.

**Comment by mitchej123** [comment]
I was able to reproduce once locally.  I'll try to reproduce again.  It happened after joining a local MP server, accidently hitting disconnect, and then reconnecting.  It looks like it _might_ be related to the forkjoinpool not getting cleaned up properly, or something incorrectly being cached between sessions

The stacktrace was as follows:
```
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:26)
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:21)
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:310)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:484)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:469)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IndexOutOfBoundsException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	... 28 more
Caused by: java.lang.IndexOutOfBoundsException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at codechicken.nei.recipe.GuiUsageRecipe.lambda$openRecipeGui$2(GuiUsageRecipe.java:26)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
Caused by: java.lang.IndexOutOfBoundsException: Index: 44769, Size: 44769
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at net.minecraftforge.oredict.OreDictionary.getOreID(OreDictionary.java:277)
	at net.minecraftforge.oredict.OreDictionary.getOres(OreDictionary.java:378)
	at team.chisel.compat.nei.RecipeHandlerChisel.getVariationStacks(RecipeHandlerChisel.java:180)
	at team.chisel.compat.nei.RecipeHandlerChisel.loadUsageRecipes(RecipeHandlerChisel.java:145)
	at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:358)
	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:480)
	at codechicken.nei.recipe.GuiUsageRecipe.lambda$null$0(GuiUsageRecipe.java:24)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	... 2 more
```

**Comment by mitchej123** [comment]
Possibly addressed with https://github.com/GTNewHorizons/NotEnoughItems/pull/33  Needs testing.  If not, I'll pull the patch from https://github.com/Glease/OreDictBandAid into NEI ASM
