### ISSUE TITLE
Witchery Oven crash

### ISSUE THREAD

**Issue by ZyniX69** [GTNewHorizons/GT-New-Horizons-Modpack#7272]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Private lan server
#
#### What did you try to do, and what did you expect to happen?
Throw birch saplings into witches oven to create breath of the goddess.
#
#### What happened instead? (Attach screenshots if needed)
Server goes down. If we reload the server it crashes immediately when anyone loads the chunk that contains the oven.
#
#### What do you suggest instead/what changes do you propose?
Not sure but I have a snip from the crashlog:

java.lang.NullPointerException: Ticking block entity
	at alkalus.main.core.util.WitchesOvenUtils.canSmelt(WitchesOvenUtils.java:197)
	at com.emoniph.witchery.blocks.BlockWitchesOven$TileEntityWitchesOven.canSmelt(BlockWitchesOven.java:155)
	at com.emoniph.witchery.blocks.BlockWitchesOven$TileEntityWitchesOven.func_145845_h(BlockWitchesOven.java:414)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7183
