### ISSUE TITLE
Game crashes when mining diatomite ore

### ISSUE THREAD

**Issue by detrumi** [GTNewHorizons/GT-New-Horizons-Modpack#7289]
#### Which modpack version are you using?
2.1.0.0

#
#### What did you try to do, and what did you expect to happen?
I tried mining diatomite ore (overworld, cassiterite vein) with a pickaxe.
Mining other ores works like normal.

#
#### What happened instead? (Attach screenshots if needed)
The game crashed with the following stacktrace:
```
java.lang.IndexOutOfBoundsException: Index: 44842, Size: 44838
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraftforge.oredict.OreDictionary.getOreID(OreDictionary.java:277)
	at net.minecraftforge.oredict.OreDictionary.getOres(OreDictionary.java:378)
	at gregtech.api.util.GT_OreDictUnificator.getOres(GT_OreDictUnificator.java:467)
	at gregtech.api.util.GT_OreDictUnificator.getFirstOre(GT_OreDictUnificator.java:84)
	at gregtech.api.util.GT_OreDictUnificator.get(GT_OreDictUnificator.java:109)
	at gregtech.api.util.GT_OreDictUnificator.get(GT_OreDictUnificator.java:102)
	at gregtech.common.blocks.GT_TileEntity_Ores.getDrops(GT_TileEntity_Ores.java:220)
	at gregtech.common.blocks.GT_Block_Ores_Abstract.getDrops(GT_Block_Ores_Abstract.java:244)
	at net.minecraft.block.Block.func_149690_a(Block.java:655)
	at net.minecraft.block.Block.func_149697_b(Block.java:648)
	at net.minecraft.block.Block.func_149636_a(Block.java:974)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(Unknown Source)
	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(Unknown Source)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Trying the same thing again resulted in another crash (with the same stacktrace).
For some reason, after mining some other ores (including small diatomite ore), the game stopped crashing.

**Comment by PoS1TiX** [comment]
[crash-2021-02-21_21.08.32-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6018298/crash-2021-02-21_21.08.32-server.txt) me too

**Comment by mitchej123** [comment]
If this is SP or on a server you control, can you swap out NEI with the latest version and see if the problem persists (2.0.11)?  I've included an oredict patch from glease that locks usage of the oredict and should hopefully prevent stuff from being swapped out while in use.

**Comment by Prometheus0000** [comment]
Is this fixed then? Also #7126, #7224? @mitchej123

**Comment by Prunebane** [comment]
Moved here from #7126, Checked back in on the issue, found the mention of updating NEI to 2.0.11, and am using it as of yesterday.
Went on a mineral hunt for testing's sake, but it's gonna be difficult to prove - the bug was sporadic, so if it doesn't crash, I can only say it's fine with a certain measure of confidence.

So far so good, though - had my world on for several hours now, mined quite some small ores (30+, roughly 7 different types), no crash thus far.
Will follow up later if I do crash.

**Comment by Prometheus0000** [comment]
@mitchej123 Can we consider all of these fixed now?
