### ISSUE TITLE
NEI find usage NPE within fuel recipe handler

### ISSUE THREAD

**Issue by Glease** [GTNewHorizons/GT-New-Horizons-Modpack#7313]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
private
#
#### What did you try to do, and what did you expect to happen?
Disconnected and reconnected for a few times. Try find usage on any item.
#
#### What happened instead? (Attach screenshots if needed)
Nothing happens and log gives this
<details>
  <summary>Log entries with junk prefix removed</summary>

```
[Client thread/INFO]java.util.concurrent.ExecutionException: java.lang.NullPointerException
[Client thread/INFO]	at java.util.concurrent.ForkJoinTask.get(Unknown Source)
[Client thread/INFO]	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:26)
[Client thread/INFO]	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:21)
[Client thread/INFO]	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:310)
[Client thread/INFO]	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
[Client thread/INFO]	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
[Client thread/INFO]	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
[Client thread/INFO]	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:484)
[Client thread/INFO]	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:469)
[Client thread/INFO]	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
[Client thread/INFO]	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
[Client thread/INFO]	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
[Client thread/INFO]	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[Client thread/INFO]	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[Client thread/INFO]	at net.minecraft.client.main.Main.main(SourceFile:148)
[Client thread/INFO]	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Client thread/INFO]	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[Client thread/INFO]	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[Client thread/INFO]	at java.lang.reflect.Method.invoke(Unknown Source)
[Client thread/INFO]	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[Client thread/INFO]	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[Client thread/INFO]	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Client thread/INFO]	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[Client thread/INFO]	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[Client thread/INFO]	at java.lang.reflect.Method.invoke(Unknown Source)
[Client thread/INFO]	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[Client thread/INFO]	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[Client thread/INFO]	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[Client thread/INFO]	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[Client thread/INFO]Caused by: java.lang.NullPointerException
[Client thread/INFO]	at sun.reflect.GeneratedConstructorAccessor435.newInstance(Unknown Source)
[Client thread/INFO]	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[Client thread/INFO]	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[Client thread/INFO]	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
[Client thread/INFO]	... 29 more
[Client thread/INFO]Caused by: java.lang.NullPointerException
[Client thread/INFO]	at sun.reflect.GeneratedConstructorAccessor435.newInstance(Unknown Source)
[Client thread/INFO]	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[Client thread/INFO]	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[Client thread/INFO]	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
[Client thread/INFO]	at java.util.concurrent.ForkJoinTask.reportException(Unknown Source)
[Client thread/INFO]	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
[Client thread/INFO]	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source)
[Client thread/INFO]	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[Client thread/INFO]	at java.util.stream.ReferencePipeline.collect(Unknown Source)
[Client thread/INFO]	at codechicken.nei.recipe.GuiUsageRecipe.lambda$openRecipeGui$2(GuiUsageRecipe.java:26)
[Client thread/INFO]	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
[Client thread/INFO]	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[Client thread/INFO]	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[Client thread/INFO]	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[Client thread/INFO]	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[Client thread/INFO]Caused by: java.lang.NullPointerException
[Client thread/INFO]	at codechicken.nei.recipe.FuelRecipeHandler.loadUsageRecipes(FuelRecipeHandler.java:68)
[Client thread/INFO]	at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:358)
[Client thread/INFO]	at codechicken.nei.recipe.FurnaceRecipeHandler.loadUsageRecipes(FurnaceRecipeHandler.java:111)
[Client thread/INFO]	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:480)
[Client thread/INFO]	at codechicken.nei.recipe.GuiUsageRecipe.lambda$null$0(GuiUsageRecipe.java:24)
[Client thread/INFO]	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[Client thread/INFO]	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[Client thread/INFO]	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[Client thread/INFO]	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[Client thread/INFO]	at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
[Client thread/INFO]	at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
[Client thread/INFO]	at java.util.stream.AbstractTask.compute(Unknown Source)
[Client thread/INFO]	at java.util.concurrent.CountedCompleter.exec(Unknown Source)
[Client thread/INFO]	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[Client thread/INFO]	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source)
[Client thread/INFO]	... 3 more
```

</details>
Can confirm the NEI version is 2.0.6, which has @mitchej123's fix on null fuel. Wondering if reconnect and MT plays a role in this null...

#
#### What do you suggest instead/what changes do you propose?

Identify what is causing yet another null and fix it.

**Comment by mitchej123** [comment]
Should be addressed by https://github.com/GTNewHorizons/NotEnoughItems/pull/33
