### ISSUE TITLE
(Crash)When I put some Oak Saplings into a witchery oven

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#7363]
#### Which modpack version are you using?

# 2.1.0.0

---- Minecraft Crash Report ----
// My bad.

Time: 1/22/21 3:05 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at alkalus.main.core.util.WitchesOvenUtils.canSmelt(WitchesOvenUtils.java:197)
	at com.emoniph.witchery.blocks.BlockWitchesOven$TileEntityWitchesOven.canSmelt(BlockWitchesOven.java:155)
	at com.emoniph.witchery.blocks.BlockWitchesOven$TileEntityWitchesOven.func_145845_h(BlockWitchesOven.java:414)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

NullPointerException has been thrown in methode canSmelt()?
maybe it can be fixed.

**Comment by Prometheus0000** [comment]
Already fixed in 2.1.0.1 I believe

**Comment by Dream-Master** [comment]
yes this is fixed
