### ISSUE TITLE
Can't land on Ross 128b (Tier 3)

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#7386]
#### Which modpack version are you using?

#2.1.0.0

When i try to land on Ross128b , my character always float in the void,no NEI items.
And the planet never be loaded.
It's the first time i go to Ross128 and other Tier 3 planets,but Ceres Astorid all run well except Ross.

**Comment by mitchej123** [comment]
Same issue

```
  1 Stall report from 2021-01-24 14:06:47 -0800, 71 threads, stalled for at least 30000 ms.
  2 Heap memory usage: 2288 / 6383 MB (max. 6383 MB).
  3 Created by sampler 1.60.1 (MC 1.7.10).
  4 
  5 "Server thread" #167 prio=5
  6 TIMED_WAITING
  7         at java.lang.Thread.sleep(Native Method)
  8         at com.github.bartimaeusnek.bartworks.system.material.BW_MetaGenerated_Blocks.func_149726_b(BW_MetaGenerated_Blocks.java:66)
  9         at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:655)
 10         at net.minecraft.world.World.func_147465_d(World.java:451)
 11         at com.github.bartimaeusnek.bartworks.system.material.BW_MetaGenerated_Ores.setOreBlock(BW_MetaGenerated_Ores.java:76)
 12         at com.github.bartimaeusnek.bartworks.system.oregen.BW_OreLayer.setOreBlock(BW_OreLayer.java:187)
 13         at com.github.bartimaeusnek.bartworks.system.oregen.BW_OreLayer.executeWorldgen(BW_OreLayer.java:149)
 14         at com.github.bartimaeusnek.bartworks.system.oregen.BW_WordGenerator$WorldGenContainer.run(BW_WordGenerator.java:112)
 15         at com.github.bartimaeusnek.bartworks.system.oregen.BW_WordGenerator.generate(BW_WordGenerator.java:48)
 16         - locked com.github.bartimaeusnek.bartworks.system.oregen.BW_WordGenerator@6b4dc194
 17         at com.github.bartimaeusnek.crossmod.galacticraft.planets.ross128b.ChunkProviderRoss128b.func_73153_a(ChunkProviderRoss128b.java:164)
 18         at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
 19         at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
 ```
 
 
```
[14:06:47] [Sampler watchdog thread/WARN] [sampler]: The watchdog detected that execution has been stalled for 30000 ms.
[14:06:47] [Sampler watchdog thread/INFO] [sampler]: Stall report created at /home/jason/.local/share/multimc/instances/MORE TESTING/.minecraft/stall-reports/stall-2021-01-24_14.06.47.txt.
[14:07:17] [Sampler watchdog thread/WARN] [sampler]: The watchdog detected that execution has been stalled for 60000 ms.
[14:07:18] [Sampler watchdog thread/INFO] [sampler]: Stall report created at /home/jason/.local/share/multimc/instances/MORE TESTING/.minecraft/stall-reports/stall-2021-01-24_14.07.17-1.txt.
[14:08:18] [Sampler watchdog thread/WARN] [sampler]: The watchdog detected that execution has been stalled for 120000 ms.
[14:08:18] [Sampler watchdog thread/INFO] [sampler]: Stall report created at /home/jason/.local/share/multimc/instances/MORE TESTING/.minecraft/stall-reports/stall-2021-01-24_14.08.18-2.txt.
```

**Comment by Skiftcha** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7235
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7212

**Comment by bartimaeusnek** [comment]
should be fixed indev.
