### ISSUE TITLE
Unable to launch server on Debian 10

### ISSUE THREAD

**Issue by SmashingQuasar** [GTNewHorizons/GT-New-Horizons-Modpack#7554]
#### Which modpack version are you using?

2.1.0.0

#
#### If in multiplayer; On which server does this happen? 

My own.

#
#### What did you try to do, and what did you expect to happen?

I used the `startserver.sh` script after downloading it from the official folder.

#
#### What happened instead? (Attach screenshots if needed)

I got the following StackTrace:

```
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
```

#
#### What do you suggest instead/what changes do you propose?

I am unsure to understand the problem and thus cannot propose any solution.

**Comment by mitchej123** [comment]
Make sure you are using Java 8.

**Comment by boubou19** [comment]
Also, to get technical support, please use #help in our discord server instead.
