### ISSUE TITLE
Can't use void miner in Twilight Forest

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#7738]
#### Which modpack version are you using?
2104

#### What did you try to do, and what did you expect to happen?
Mine some ores from TF with void miner

#### What happened instead? (Attach screenshots if needed)
No ores produced 
![image](https://user-images.githubusercontent.com/49871378/113350902-f712ac80-92ee-11eb-8478-e85f61ee9e5a.png)
![image](https://user-images.githubusercontent.com/49871378/113350915-fe39ba80-92ee-11eb-952d-fdf36ec3ff3f.png)
I tried on some galactic planet like VB BC, all worked

is this intended or a bug?
If it's a bug, please fix it!

**Comment by johnch18** [comment]
I had a similar issue today on Oberon, I took it down and moved it and it started working again.

**Comment by miaowwwwww** [comment]
emm I tried 3 times in server and 3 times in single-player, still not working，but other planets are fine. just TF

**Comment by miaowwwwww** [comment]
@bartimaeusnek would u mind have a look? thank you!

**Comment by speckbrot** [comment]
I had the same problem in the Caustic Everglades and on ross 128ba

**Comment by Skiftcha** [comment]
same issue for me with TF and Nether
Overworld, Triton, Venus working ok.

**Comment by GTNH-Afx237v7** [comment]
I faced the same problem today with a T1 miner on Ross128b. It consumed energy, Neon, but did not output any ores. Broke and replaced the controller, same thing. Relocated about 15 chunks away, same problem.

**Comment by boubou19** [comment]
i looked in the source code, and looks like the dropmap is not defined for the TF. It's only defined for the vanilla dim, galacticraft and galaxyspace dims by bartworks. The core mod adds support for the Deep Dark. So any other dim is not supposed to work with the void miner. As fas as i know, it only affects the twilight forest and the everglades, but i might have forgotten some other dims.

**Comment by GTNH-Afx237v7** [comment]
It should also work with both BartWorks dimensions (Ross128b and Ross128ba) as they are also defined in the sourcecode. However I can’t get it to work on Ross128b (have not tried Ross128ba).

**Comment by GTNH-Afx237v7** [comment]
So even after deleting the DIM folder of Ross128b, it does not work. The miner is active, consumes energy but does not output anything.

**Comment by GTNH-Afx237v7** [comment]
Looking at GregTech.log I keep getting the following error message:

```
java.lang.ArithmeticException: / by zero
	at gregtech.api.objects.XSTR.nextInt(XSTR.java:244)
	at com.github.bartimaeusnek.crossmod.galacticgreg.GT_TileEntity_VoidMiner_Base.getOreDamage(GT_TileEntity_VoidMiner_Base.java:251)
	at com.github.bartimaeusnek.crossmod.galacticgreg.GT_TileEntity_VoidMiner_Base.handleOutputs(GT_TileEntity_VoidMiner_Base.java:382)
	at com.github.bartimaeusnek.crossmod.galacticgreg.GT_TileEntity_VoidMiner_Base.workingAtBottom(GT_TileEntity_VoidMiner_Base.java:141)
	at gregtech.common.tileentities.machines.multi.GT_MetaTileEntity_DrillerBase.checkRecipe(GT_MetaTileEntity_DrillerBase.java:313)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:281)
	at gregtech.common.tileentities.machines.multi.GT_MetaTileEntity_DrillerBase.onPostTick(GT_MetaTileEntity_DrillerBase.java:139)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:563)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at fastcraft.at.a(F:978)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

This happened on 2.1.0.0 and still happens in 2.1.1.0

**Comment by Skiftcha** [comment]
> I keep getting the following error message:

looks like this is because dropmap is empty so totalWeight == 0

**Comment by GTNH-Afx237v7** [comment]
The question is why is the dropmap empty? As my void miners are on Io (no issues), Titan (no issues) and Ross128b (no ores produced). It should work with all those dimensions...

**Comment by Glease** [comment]
Look further up maybe. Maybe you can see an exception for void miner with a different stack trace

**Comment by GTNH-Afx237v7** [comment]
Just checked again, there is none related to the void miner, just some NPE from GT++ related to the breaker boxes. The above mentioned message from bartworks appears 34 times in a row before the document ends.

**Comment by GTNH-Afx237v7** [comment]
Small update from Discord: the above function is in a try-catch which logs into GT-log

**Comment by GTNH-Afx237v7** [comment]
Aaaaaa y u no work? 
I believe the try-catch bart was referring to begins here:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/77c57a97b7286863f9239de806ac9659013d6852/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L316

There is a commented out logger info here:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/77c57a97b7286863f9239de806ac9659013d6852/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L624

Upon deactivating this logger info and trying to run the Void Miner on a bartworks dimension (Ross128b) the following info is given:

Encountered exception while ticking MetaTileEntity in Step14.

Not sure what step14 is, it might be this one?
https://github.com/GTNewHorizons/GT5-Unofficial/blob/77c57a97b7286863f9239de806ac9659013d6852/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L561

Perhaps this is of any help...
