### ISSUE TITLE
Disconnect from server upon harvesting Thaumic tinkerer's infused seeds

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#7893]
#### Which modpack version are you using?
2.1.0.6b
#
#### If in multiplayer; On which server does this happen? 
zeta
#
#### What did you try to do, and what did you expect to happen?
I was trying to farm infused seeds, but when i break them, they make me disconnect from the server. Also i can use the hoe of growth to make them grow, which shouldn't happen.
#
#### What happened instead? (Attach screenshots if needed)
log given by boubou when i dc'd
```
java.lang.NullPointerException
        at thaumic.tinkerer.common.block.BlockInfusedGrain.getDrops(BlockInfusedGrain.java:133) ~[BlockInfusedGrain.class:?]
        at net.minecraft.block.Block.func_149690_a(Block.java:664) ~[aji.class:?]
        at net.minecraft.block.BlockCrops.func_149690_a(BlockCrops.java:148) ~[akf.class:?]
        at net.minecraft.block.Block.func_149697_b(Block.java:657) ~[aji.class:?]
        at net.minecraft.block.Block.func_149636_a(Block.java:988) ~[aji.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73084_b(Unknown Source) ~[mx.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73074_a(Unknown Source) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:742) ~[nh.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) ~[ji.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) ~[ji.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[22:45:56 INFO]: Maniifestantes lost connection: Internal server error
[22:45:56 DEBUG]: Unloading Player: Maniifestantes
[22:45:56 INFO]: Maniifestantes left the game.
```

**Comment by Alastors** [comment]
which infused seeds were you using?

**Comment by maniifestantes** [comment]
all of them made me dc, but it didn't work on single player( i still didn't got anything from it when matured, even the seed)

**Comment by Alastors** [comment]
Yeah I can confirm this issue persists, I tried it myself and got the same result

**Comment by Alastors** [comment]
breaking the dirt fixes this issue though, so some flavour should be added to the data entry that specifies that "DO NOT BREAK THE CROP ITSELF, BREAK THE DIRT UNDERNEATH! BREAKING THE CROP WILL CAUSE A CLIENT FAILURE IF DONE BY A PERSON AND A SERVER CRASH IF DONE BY A NON-PLAYER ENTITY" or whatever
