### ISSUE TITLE
[FTB-Utilities] FTB Utilities Backups fail to execute after first

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [GTNewHorizons/GT-New-Horizons-Modpack#7923]
#### Which modpack version are you using?
2.1.0.6b
FTB Utils version 1.7.10-1.0.18.2
FTB Lib   version 1.7.10-1.0.18.2
#
#### What did you try to do, and what did you expect to happen?
1. Installed FTB utilities (and its deps) and enabled backups (config follows)
2. Backups would run normally (Everything else works fine -- Claims, chunkloading)
#
#### What happened instead? (Attach screenshots if needed)
1. Waited for a backup to run, works fine
2. Second backup runs, errors on a FileNotFound
```
[00:11:38] [Thread-40/INFO] [FTBU Backups]: Backing up 480 files...
[00:11:38] [Thread-40/INFO] [FTBU Backups]: Compressing 480 files!
[00:11:38] [Thread-40/INFO] [FTBU Backups]: [0 | 0.00%]: Take 1/data/SpectreHandler.dat
[00:11:38] [Client thread/INFO]: [CHAT] [Server: Saved the world]
[00:11:40] [Thread-40/INFO]: Failed to save world! (java.io.FileNotFoundException)
[00:11:40] [Thread-40/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.io.FileNotFoundException: /games/minecraft/multimc_instances/GTNH2.1.0.6b/.minecraft/saves/Take 1/betterquesting/QuestProgress.json.tmp (No such file or directory)
[00:11:40] [Thread-40/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at java.io.FileInputStream.open0(Native Method)
[00:11:40] [Thread-40/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at java.io.FileInputStream.open(FileInputStream.java:195)
[00:11:40] [Thread-40/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at java.io.FileInputStream.<init>(FileInputStream.java:138)
[00:11:40] [Thread-40/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at ftb.utils.world.ThreadBackup.doBackup(ThreadBackup.java:91)
[00:11:40] [Thread-40/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at ftb.utils.world.ThreadBackup.run(ThreadBackup.java:27)
[00:11:40] [Server thread/INFO]: Turned on world auto-saving
[00:11:40] [Client thread/INFO]: [CHAT] Failed to save world! (java.io.FileNotFoundException)
[00:11:40] [Client thread/INFO]: [CHAT] [Server: Turned on world auto-saving]
```

#
#### What do you suggest instead/what changes do you propose?
@mitchej123 Said they'd take a look at the code side. I'd _assume_ FTBu does some tracking of files that exist but doesnt remove them when they're deleted? or something similar -- I have not poked into the code to find out
#
#### What is your GTNH Discord username?
`A_D#7588` (Just A_D on the GTNH Discord)

**Comment by A-UNDERSCORE-D** [comment]
I allegedly have that version from the dev version Im running, but the hashes dont match so Im going to _assume_ that they are different

**Comment by Glease** [comment]
Interesting. Please let me know if that doesn't work either

**Comment by A-UNDERSCORE-D** [comment]
it appears to have worked. Will update if that changes. Hashes follow
```
╙─╴% sha256sum BetterQuesting-3.0.342-GTNH.jar ~/Downloads/BetterQuesting-3.0.342-GTNH.jar
7cff0f04e80b01632a7251921c009ea783e2f6b0cf54ea64312c6828bfdea073  BetterQuesting-3.0.342-GTNH.jar
```
