### ISSUE TITLE
Internal server error with the Primordial armor

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#8127]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Whenever i get poisoned(wheter by warp or by potion, haven't tested with a cave spider) while wearing the primordial armor from witching gadgets, i get an internal server error. This can't be solved by removing all warp since the armor gives you an innate 40 warp.
#
#### What happened instead? (Attach screenshots if needed)
Not disconnect me when i get poisoned. Also glee took a look at my latest fml log, and he said it wasn't really that useful. Also it's 65 mb so i can't upload.

**Comment by MotiasF33** [comment]
@maniifestantes,
Please call this error again(or upload the log with it trouble) and 
upload your fml-client-latest.log to https://pastebin.com/ or to anycloudstorate

**Comment by maniifestantes** [comment]
here you go, got it after a poison warp.
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6720692/fml-client-latest.log)

**Comment by MotiasF33** [comment]
> 
> 
> here you go, got it after a poison warp.
> [fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6720692/fml-client-latest.log)

Thank you! i simply had to make sure it was clean there :)
We need to see the Zeta server logs.

(a until these slippers )  🥿
![image](https://user-images.githubusercontent.com/47714084/123527585-86aada00-d6e9-11eb-9561-a560fb6da0db.png)

*i'm trying reproduce it in a local server but not successful*

**Comment by maniifestantes** [comment]
My armor is enchanted, maybe that has something to do

**Comment by maniifestantes** [comment]
i tested with the same enchantments on single player and i didn't crash, i think this is server side.

**Comment by boubou19** [comment]
Ok so i clone Manii's playerprofile onto mine, and i got the same error. Here is what i got:
<details>
  <summary>Client side</summary>

  ```
  [27/06/2021 16:49:18 PM] java.lang.NullPointerException
[27/06/2021 16:49:18 PM] 	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$5.selectNetworks(FMLOutboundHandler.java:129) ~[FMLOutboundHandler$OutboundTarget$5.class:?]
[27/06/2021 16:49:18 PM] 	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:?]
[27/06/2021 16:49:18 PM] 	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
[27/06/2021 16:49:18 PM] 	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
[27/06/2021 16:49:18 PM] 	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
[27/06/2021 16:49:18 PM] 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
[27/06/2021 16:49:18 PM] 	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
[27/06/2021 16:49:18 PM] 	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
[27/06/2021 16:49:18 PM] 	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
[27/06/2021 16:49:18 PM] 	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
[27/06/2021 16:49:18 PM] 	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
[27/06/2021 16:49:18 PM] 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
[27/06/2021 16:49:18 PM] 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
[27/06/2021 16:49:18 PM] 	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAll(SimpleNetworkWrapper.java:182) [SimpleNetworkWrapper.class:?]
[27/06/2021 16:49:18 PM] 	at DummyCore.Utils.MiscUtils.syncTileEntity(MiscUtils.java:248) [MiscUtils.class:?]
[27/06/2021 16:49:18 PM] 	at tb.common.tile.TileOverchanter.func_145845_h(TileOverchanter.java:58) [TileOverchanter.class:?]
[27/06/2021 16:49:18 PM] 	at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
[27/06/2021 16:49:18 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006) [bao.class:?]
[27/06/2021 16:49:18 PM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
[27/06/2021 16:49:18 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[27/06/2021 16:49:18 PM] 	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[27/06/2021 16:49:18 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
[27/06/2021 16:49:18 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
[27/06/2021 16:49:18 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
[27/06/2021 16:49:18 PM] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
[27/06/2021 16:49:18 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[27/06/2021 16:49:18 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
  ```
</details>

<details>
  <summary>Server side</summary>

  ```
  [16:49:18 WARN]: Failed to handle packet for [redacted]
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:477) ~[mw.class:?]
        at api.player.server.ServerPlayerAPI.onUpdateEntity(Unknown Source) ~[ServerPlayerAPI.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java) ~[mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:488) ~[nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) ~[jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:101) ~[jd.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_191]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_191]
        at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:589) ~[sv.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.localUpdatePotionEffects(EntityPlayerMP.java) ~[mw.class:?]
        at api.player.server.ServerPlayerAPI.updatePotionEffects(Unknown Source) ~[ServerPlayerAPI.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70679_bo(EntityPlayerMP.java) ~[mw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:330) ~[sv.class:?]
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:417) ~[sa.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1903) ~[sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(Unknown Source) ~[yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:399) ~[mw.class:?]
        ... 12 more
[16:49:18 INFO]: boubou_19 lost connection: Internal server error

  ```
</details>

**Comment by MotiasF33** [comment]
#https://github.com/GTNewHorizons/WitchingGadgets/pull/13
may cause overlays of effects, but may help stop crash 💀

**Comment by Glease** [comment]
With coordinated testing bug seems to only happen with thermos, again 🤦‍♂️
