### ISSUE TITLE
Issues with GT enet change

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8171]
#### Which modpack version are you using?
2.1.1.0 with dev version og GT5U
#
#### If in multiplayer; On which server does this happen? 
zeta
#
i noticed few issues with the enet change:

- [ ] IC² enet conversion to GT is not 100% working:
The historical way of converting IC² EU to GT EU via a GT transformer works, but looks like cables aren't able to give IC² EU anymore:

(i disconnected/reconnected all the sides after placing the setup to ensure the cable was updated)
![2021-07-03_14 53 33](https://user-images.githubusercontent.com/12850933/124355039-79bd4780-dc0f-11eb-8812-937e35b0a98c.png)
same setup, i just switched the industrial apiary with an UV batbuf and an ultimate battery (i also updated the wire after setting up) and it works
![2021-07-03_14 55 34](https://user-images.githubusercontent.com/12850933/124355041-7d50ce80-dc0f-11eb-9c98-4b364cabe30b.png)

- [ ] Shutter modules on cables are now useless as the graph ignores the cables, so you cannot make modular GT power grid anymore

- [ ] crash the server on explosion:hv machine connected to a GT cable connected to a spectral solar pannel (ic2 source)

```
java.lang.NullPointerException: Exception in server tick loop
	at gregtech.api.metatileentity.BaseMetaTileEntity.doExplosion(BaseMetaTileEntity.java:1341)
	at gregtech.api.metatileentity.BaseMetaTileEntity.injectEnergyUnits(BaseMetaTileEntity.java:1911)
	at gregtech.api.graphs.consumers.NodeGTBaseMetaTile.injectEnergy(NodeGTBaseMetaTile.java:15)
	at gregtech.api.graphs.PowerNodes.processNodeInject(PowerNodes.java:156)
	at gregtech.api.graphs.PowerNodes.powerNode(PowerNodes.java:59)
	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Cable.transferElectricity(GT_MetaPipeEntity_Cable.java:195)
	at gregtech.api.metatileentity.TileIC2EnergySink.injectEnergy(TileIC2EnergySink.java:93)
	at ic2.core.energy.EnergyNetLocal.processChanges(EnergyNetLocal.java:704)
	at ic2.core.energy.EnergyNetLocal.onTickEnd(EnergyNetLocal.java:389)
	at ic2.core.energy.EnergyNetGlobal.onTickEnd(EnergyNetGlobal.java:69)
	at ic2.core.TickHandler.onWorldTick(TickHandler.java:79)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_39_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1006)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)
```

- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9011

i'll update if i find more issues

<details>
<summary>solved issues</summary>

- [x] ~~cables aren't automatically reconnecting to the others when broken and placed again~~ fixed with https://github.com/GTNewHorizons/GT5-Unofficial/commit/a8e36458531f5a06856c34251c9dc93ae19998de

![2021-07-03_11 55 53](https://user-images.githubusercontent.com/12850933/124350599-c3993400-dbf5-11eb-859d-0c13594185c9.png)
![2021-07-03_11 56 16](https://user-images.githubusercontent.com/12850933/124350601-c431ca80-dbf5-11eb-826f-b3c83a752575.png)

- [x] ~~RF conversion doesn't always work~~ fixed with https://github.com/GTNewHorizons/GT5-Unofficial/commit/5b7dfe22ea8db7a861d5a16b974bf87bcff704fa and https://github.com/GTNewHorizons/GT5-Unofficial/commit/5268975ff2713516230b34a45ea77b2e77d207d9:

![2021-07-03_12 03 26](https://user-images.githubusercontent.com/12850933/124350742-b9c40080-dbf6-11eb-8c44-8b7c898d4881.png)
![2021-07-03_12 03 29](https://user-images.githubusercontent.com/12850933/124350745-bdf01e00-dbf6-11eb-89d2-01decfe1cd70.png)

It seems that if the GT Amp is too high, the conversion doesn't happen, so it forces to adapt the GT EU input to the RF destination, it wasn't the case before.

- [x] ~~solar panel covers aren't working~~ User error

- [x] ~~https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8321~~ fixed with https://github.com/GTNewHorizons/GT5-Unofficial/commit/fe883d00df245c726dca6271978b8aed739d4a28

- [x] ~~looks like GT EU p2p is not transmitting the power anymore~~ fixed with https://github.com/GTNewHorizons/GT5-Unofficial/commit/12315a9b056b69abcdfe1474959a846753208529
left P2P is set in GT EU mode (input side) and right P2P is set in GT EU mode (output side). The UV transformer has power in it, but the battery buffer isn't charging the ultimate battery.
![2021-07-03_15 45 58](https://user-images.githubusercontent.com/12850933/124356384-1387f300-dc16-11eb-89b0-227ca538ba05.png)

- [x] ~~NPE in gregtech.log happened in the same timeframe as a player overvolted a LuV energy hatch.~~ fixed with https://github.com/GTNewHorizons/GT5-Unofficial/commit/c31ba09f8fb68b02879dc2934f3e23d38c3f1ff6
```
java.lang.NullPointerException
	at gregtech.api.graphs.paths.PowerNodePath.applyVoltage(PowerNodePath.java:43)
	at gregtech.api.graphs.PowerNodes.processNextNode(PowerNodes.java:117)
	at gregtech.api.graphs.PowerNodes.powerNode(PowerNodes.java:42)
	at gregtech.api.graphs.PowerNodes.processNextNode(PowerNodes.java:121)
	at gregtech.api.graphs.PowerNodes.powerNode(PowerNodes.java:42)
	at gregtech.api.graphs.PowerNodes.processNextNode(PowerNodes.java:121)
	at gregtech.api.graphs.PowerNodes.powerNode(PowerNodes.java:42)
	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Cable.transferElectricity(GT_MetaPipeEntity_Cable.java:195)
	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Cable.injectEnergyUnits(GT_MetaPipeEntity_Cable.java:165)
	at gregtech.api.metatileentity.BaseMetaPipeEntity.injectEnergyUnits(BaseMetaPipeEntity.java:1297)
	at gregtech.api.interfaces.tileentity.IEnergyConnected$Util.emitEnergyToNetwork(IEnergyConnected.java:73)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:458)
	at net.minecraft.world.World.func_72939_s(World.java:2583)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)```

</details>

**Comment by boubou19** [comment]
- [ ] looks like GT EU p2p is not transmitting the power anymore:
left P2P is set in GT EU mode (input side) and right P2P is set in GT EU mode (output side). The UV transformer has power in it, but the battery buffer isn't charging the ultimate battery.
![2021-07-03_15 45 58](https://user-images.githubusercontent.com/12850933/124356384-1387f300-dc16-11eb-89b0-227ca538ba05.png)

**Comment by boubou19** [comment]
- [ ] NPE in gregtech.log happened in the same timeframe as a player overvolted a LuV energy hatch.
```
java.lang.NullPointerException
	at gregtech.api.graphs.paths.PowerNodePath.applyVoltage(PowerNodePath.java:43)
	at gregtech.api.graphs.PowerNodes.processNextNode(PowerNodes.java:117)
	at gregtech.api.graphs.PowerNodes.powerNode(PowerNodes.java:42)
	at gregtech.api.graphs.PowerNodes.processNextNode(PowerNodes.java:121)
	at gregtech.api.graphs.PowerNodes.powerNode(PowerNodes.java:42)
	at gregtech.api.graphs.PowerNodes.processNextNode(PowerNodes.java:121)
	at gregtech.api.graphs.PowerNodes.powerNode(PowerNodes.java:42)
	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Cable.transferElectricity(GT_MetaPipeEntity_Cable.java:195)
	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Cable.injectEnergyUnits(GT_MetaPipeEntity_Cable.java:165)
	at gregtech.api.metatileentity.BaseMetaPipeEntity.injectEnergyUnits(BaseMetaPipeEntity.java:1297)
	at gregtech.api.interfaces.tileentity.IEnergyConnected$Util.emitEnergyToNetwork(IEnergyConnected.java:73)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:458)
	at net.minecraft.world.World.func_72939_s(World.java:2583)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by boubou19** [comment]
- [ ] Shutter modules on cables are now useless as the graph ignores the cables, so you cannot make modular GT power grid anymore

**Comment by boubou19** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8321

**Comment by boubou19** [comment]
- [ ] crash the server on explosion:hv machine connected to a GT cable connected to a spectral solar pannel (ic2 source)

```
java.lang.NullPointerException: Exception in server tick loop
	at gregtech.api.metatileentity.BaseMetaTileEntity.doExplosion(BaseMetaTileEntity.java:1341)
	at gregtech.api.metatileentity.BaseMetaTileEntity.injectEnergyUnits(BaseMetaTileEntity.java:1911)
	at gregtech.api.graphs.consumers.NodeGTBaseMetaTile.injectEnergy(NodeGTBaseMetaTile.java:15)
	at gregtech.api.graphs.PowerNodes.processNodeInject(PowerNodes.java:156)
	at gregtech.api.graphs.PowerNodes.powerNode(PowerNodes.java:59)
	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Cable.transferElectricity(GT_MetaPipeEntity_Cable.java:195)
	at gregtech.api.metatileentity.TileIC2EnergySink.injectEnergy(TileIC2EnergySink.java:93)
	at ic2.core.energy.EnergyNetLocal.processChanges(EnergyNetLocal.java:704)
	at ic2.core.energy.EnergyNetLocal.onTickEnd(EnergyNetLocal.java:389)
	at ic2.core.energy.EnergyNetGlobal.onTickEnd(EnergyNetGlobal.java:69)
	at ic2.core.TickHandler.onWorldTick(TickHandler.java:79)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_39_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1006)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by boubou19** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9011

**Comment by boubou19** [comment]
this is still a thing btw

**Comment by mitchej123** [comment]
> this is still a thing btw

Would you mind reorganizing the OP and spoiler/moving everything that's been fixed to the bottom, and any open issues to the top?  Or opening new issues for the ones that remain an issue?  It's hard to figure out what's still broken at a quick glance.

**Comment by boubou19** [comment]
will do when i'll be back home
