### ISSUE TITLE
Rock Breaker causing crash via infinite loop

### ISSUE THREAD

**Issue by Judisch** [GTNewHorizons/GT-New-Horizons-Modpack#8216]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen?
A private server

#
#### What did you try to do, and what did you expect to happen?
I tried to feed Redstone to a Rock Breaker with a Hopper

#
#### What happened instead? (Attach screenshots if needed)
Server crashed

#
#### Stack trace:
```
net.minecraft.util.ReportedException: Ticking block entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.StackOverflowError
    at gregtech.api.util.GT_OreDictUnificator.getAssociation(GT_OreDictUnificator.java:323) ~[GT_OreDictUnificator.class:?]
    at gregtech.api.util.GT_OreDictUnificator.get(GT_OreDictUnificator.java:155) ~[GT_OreDictUnificator.class:?]
    at gregtech.api.util.GT_OreDictUnificator.get(GT_OreDictUnificator.java:150) ~[GT_OreDictUnificator.class:?]
    at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_BasicMachine.allowPutStack(GT_MetaTileEntity_BasicMachine.java:839) ~[GT_MetaTileEntity_BasicMachine.class:?]
    at gregtech.common.tileentities.machines.basic.GT_MetaTileEntity_RockBreaker.allowPutStackValidated(GT_MetaTileEntity_RockBreaker.java:67) ~[GT_MetaTileEntity_RockBreaker.class:?]
    at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_BasicMachine.allowPutStack(GT_MetaTileEntity_BasicMachine.java:840) ~[GT_MetaTileEntity_BasicMachine.class:?]
    at gregtech.common.tileentities.machines.basic.GT_MetaTileEntity_RockBreaker.allowPutStackValidated(GT_MetaTileEntity_RockBreaker.java:67) ~[GT_MetaTileEntity_RockBreaker.class:?]
    at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_BasicMachine.allowPutStack(GT_MetaTileEntity_BasicMachine.java:840) ~[GT_MetaTileEntity_BasicMachine.class:?]
    at gregtech.common.tileentities.machines.basic.GT_MetaTileEntity_RockBreaker.allowPutStackValidated(GT_MetaTileEntity_RockBreaker.java:67) ~[GT_MetaTileEntity_RockBreaker.class:?]
    at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_BasicMachine.allowPutStack(GT_MetaTileEntity_BasicMachine.java:840) ~[GT_MetaTileEntity_BasicMachine.class:?]
    at gregtech.common.tileentities.machines.basic.GT_MetaTileEntity_RockBreaker.allowPutStackValidated(GT_MetaTileEntity_RockBreaker.java:67) ~[GT_MetaTileEntity_RockBreaker.class:?]
    at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_BasicMachine.allowPutStack(GT_MetaTileEntity_BasicMachine.java:840) ~[GT_MetaTileEntity_BasicMachine.class:?]
    at gregtech.common.tileentities.machines.basic.GT_MetaTileEntity_RockBreaker.allowPutStackValidated(GT_MetaTileEntity_RockBreaker.java:67) ~[GT_MetaTileEntity_RockBreaker.class:?]
    at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_BasicMachine.allowPutStack(GT_MetaTileEntity_BasicMachine.java:840) ~[GT_MetaTileEntity_BasicMachine.class:?]
    at gregtech.common.tileentities.machines.basic.GT_MetaTileEntity_RockBreaker.allowPutStackValidated(GT_MetaTileEntity_RockBreaker.java:67) ~[GT_MetaTileEntity_RockBreaker.class:?]
    [repeats forever]
```

I don't see `allowPutStackValidated()` in any of the GregTech repos I've seen, so I don't know where to submit a fix to. 
I think it's just a copy/paste error within `GT_MetaTileEntity_RockBreaker`. It should be calling `super.allowPutStackValidated()` instead of `super.allowPutStack()`.

**Comment by Prometheus0000** [comment]
Read the announcements in discord. If that doesn't work, then come back.
