### ISSUE TITLE
forbid players to put heads inside the stargate base blocks

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8224]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
eta
#
if someone puts a head on the block base of a stargate, when he'll try to get it back, the player will crash:
<details>
  <summary>crash</summary>
  
  ```
java.lang.NullPointerException: Updating screen events
	at gcewing.sg.BaseContainer.transferSlotRange(BaseContainer.java:213)
	at gcewing.sg.BaseContainer.func_82846_b(BaseContainer.java:139)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:193)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(Unknown Source)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:518)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:461)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
	at gcewing.sg.BaseGui$Screen.func_73864_a(BaseGui.java:297)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
  ```
  
</details>

**Comment by repo-alt** [comment]
I don't see how it may be easily fixed from the SG side (checking all the neighbours in the onNeighborBlockChange?)
This may be somewhat easily fixed by mixin in the BlockSkull, but it just doesn't feel like being worth the effort

**Comment by GTNH-Colen** [comment]
This isn't limited to just skulls though, I believe any non block placed inside the stargate causes this issue. The same occurred when someone put stamps inside of the Eta stargate a long time ago.

**Comment by GTNH-Afx237v7** [comment]
Guess that’s fixedindev then?
