### ISSUE TITLE
usual crashes on the officials

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8248]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
delta, epsilon, eta
#

This crash happened once on eta and once on delta last week.
<details>
  <summary>Fire spreading (usually in nether) crash</summary>

  ```javascript
  Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
	at net.minecraft.world.World.func_147439_a(World.java:703)
	at net.minecraft.block.BlockFire.tryCatchFire(BlockFire.java:256)
	at net.minecraft.block.BlockFire.func_149674_a(BlockFire.java:157)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:776)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:283)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)
  ```
  
</details>

This one happened 4 times on eta, once on epsilon, and 5 times on delta over the last week
<details>
  <summary>light value computed by grass block (usually in garden dims)</summary>

  ```javascript
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.World.getBlockLightValue_do(World.java:1265)
	at net.minecraft.world.World.getBlockLightValue_do(World.java:1225)
	at net.minecraft.world.World.getBlockLightValue(World.java:1214)
	at net.minecraft.block.BlockGrass.updateTick(BlockGrass.java:52)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:568)
	at net.minecraft.world.WorldServer.tick(WorldServer.java:287)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:963)
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)
  ```
  
</details>

**Comment by GTNH-Colen** [comment]
This is a pretty big bug that has been floating around for a long time now, hopefully someone can take a look at it. It can crash the officials 1-2 times a day easily which gets old really fast.

**Comment by boubou19** [comment]
looks like https://github.com/GTNewHorizons/Hodgepodge/commit/d2295c6f6f7a3db6ba70f5154ade4cff2f49705e and https://github.com/GTNewHorizons/Hodgepodge/commit/8c2e6bf161408a67e69698e43a3a59ae8951573a fixed the issues, because no more crashes from those were observed. I think we can close this.

**Comment by Glease** [comment]
Said commits aren't even merged into master. Let's wait a bit more before closing it.
