### ISSUE TITLE
Server crash after you break web with a sword

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#8317]
#### Which modpack version are you using?
2.1.1.1a dev pack
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Break web with a sword
#
#### What happened instead? (Attach screenshots if needed)
Server crashed:

java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_71011_bu()Lnet/minecraft/item/ItemStack;
	at net.minecraft.block.BlockWeb.func_149636_a(SourceFile:546)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(Unknown Source)
	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(Unknown Source)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:761)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Dream-Master** [comment]
fix https://github.com/GTNewHorizons/BugTorch/commit/04c2995d2bc70561a1f3d4920e9fcd85e8d4063b
