### ISSUE TITLE
UEV 1,048,576A Laser Hatches do not work with MEBF (Int overflow)

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#8346]
If you feed a MEBF > 2^31 EU/t it seems to bug out and refuse to run. I tested a ZPM 16384A Laser hatch (exactly 1A MAX) and it worked fine.

![image](https://user-images.githubusercontent.com/54497873/128087851-0333d52a-b33e-4f7f-a4f4-6d6ccccbe703.png)

I assume other multis have this problem. As a secondary point could we please get commas in the tooltip for these items as it's really hard to read the numbers. For example see:

![image](https://user-images.githubusercontent.com/54497873/128088018-dc97153c-d98d-4e02-8433-ff0328a31b47.png)

Gregtech.log seems to yield this error:

```
java.lang.ArrayIndexOutOfBoundsException: 16
    at com.github.bartimaeusnek.bartworks.common.tileentities.multis.mega.GT_TileEntity_MegaBlastFurnace.checkRecipe(GT_TileEntity_MegaBlastFurnace.java:345)
    at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:296)
    at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:563)
    at net.minecraft.world.World.func_72939_s(World.java:2583)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
    at java.lang.Thread.run(Thread.java:748)
```

And this error for the LSC also:

```
java.lang.NullPointerException
    at common.tileentities.GTMTE_LapotronicSuperCapacitor.onRunningTick(GTMTE_LapotronicSuperCapacitor.java:528)
    at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:260)
    at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:563)
    at net.minecraft.world.World.func_72939_s(World.java:2583)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
    at java.lang.Thread.run(Thread.java:748)```

**Comment by Prometheus0000** [comment]
I believe EU on tooltips is generated by getting the tier vaule, and not just a string, so it would be hard

**Comment by GTNH-Colen** [comment]
> I believe EU on tooltips is generated by getting the tier vaule, and not just a string, so it would be hard

Do you know where this is done in code?

**Comment by Prometheus0000** [comment]
```java
eM_dynamoTunnel7_UXV.set(new GT_MetaTileEntity_Hatch_DynamoTunnel(
                15298, "hatch.dynamotunnel7.tier.13", "UXV 1048576A/t Laser Source Hatch", 13, 1048576).getStackForm(1L));
```

in MachineLoader in techtech. So you can change the text here and in the lang file about amps.

The rest seems to be in GT_MetaTileEntity_Hatch_DynamoTunnel

```java
@Override
    public String[] getDescription() {
        return new String[]{
                CommonValues.TEC_MARK_GENERAL,
                mDescription,//TODO NOT PASS DESCRIPTION
                translateToLocal("gt.blockmachines.hatch.dynamotunnel.desc.1") + ": " + EnumChatFormatting.YELLOW + (Amperes * maxEUOutput()) + EnumChatFormatting.RESET + " EU/t"//Throughput
        };
    }
```

you would need to change the Amperes * maxEUOutput()) part to somehow add the proper formatting. There might be a way to do that, but I don't know.

**Comment by D-Cysteine** [comment]
I added a bunch of tooltip number formatting and fixed the MEBF. Not sure what's up with the LSC though; the stack trace points here:
https://github.com/GTNewHorizons/KekzTech/blob/master/src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java#L528
but I don't see anything obviously related to excessive voltage there.
