### ISSUE TITLE
killing a villager or a witchery guard with ExU spikes makes the server unstable

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8520]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

Planned to kill villagers or witchery guard via enchanted diamond spikes to get a DE soul from them. Expected no issue.

### The Reality

The server goes in an unstable mode: players near the place of the ExU spikes killing the mobs get disconnected, and every player struggle to join the server after the first mob killed. The console also gets spammed with those errors: https://cdn.discordapp.com/attachments/237965769466445825/885991046268452914/message.txt

<details>

<summary>Stacktrace for easier search</summary>

```

[22:34:18] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$4.selectNetworks(FMLOutboundHandler.java:110) ~[FMLOutboundHandler$OutboundTarget$4.class:1.7.10-1614.58]
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:274) ~[FMLOutboundHandler.class:1.7.10-1614.58]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:196) [SimpleNetworkWrapper.class:1.7.10-1614.58]
	at com.emoniph.witchery.network.PacketPipeline.sendTo(PacketPipeline.java:51) [PacketPipeline.class:?]
	at com.emoniph.witchery.common.ExtendedPlayer.sync(ExtendedPlayer.java:878) [ExtendedPlayer.class:?]
	at com.emoniph.witchery.common.ExtendedPlayer.fillBloodReserve(ExtendedPlayer.java:548) [ExtendedPlayer.class:?]
	at com.emoniph.witchery.common.GenericEvents.onLivingDeath(GenericEvents.java:1796) [GenericEvents.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1306_GenericEvents_onLivingDeath_LivingDeathEvent.invoke(.dynamic) [?:1.7.10-1614.58]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:1.7.10-1614.58]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1614.58]
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:314) [ForgeHooks.class:1.7.10-1614.58]
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1014) [sv.class:?]
	at com.emoniph.witchery.entity.EntityVillageGuard.func_70645_a(EntityVillageGuard.java:324) [EntityVillageGuard.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:978) [sv.class:?]
	at com.emoniph.witchery.entity.EntityVillageGuard.func_70097_a(EntityVillageGuard.java:250) [EntityVillageGuard.class:?]
	at com.rwtema.extrautils.block.BlockSpike.doPlayerLastHit(BlockSpike.java:389) [BlockSpike.class:?]
	at com.rwtema.extrautils.block.BlockSpikeDiamond.func_149670_a(BlockSpikeDiamond.java:62) [BlockSpikeDiamond.class:?]
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1070) [sa.class:?]
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:626) [sa.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1831) [sv.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2163) [sv.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388) [sw.class:?]
	at com.emoniph.witchery.entity.EntityVillageGuard.func_70636_d(EntityVillageGuard.java:240) [EntityVillageGuard.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1954) [sv.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213) [sw.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2740) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877) [mt.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2678) [ahb.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2480) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
```

</details>

### Your Proposal

From a quick look at it, it seems that Witchery blood's mecanic is at fault here, so maybe prevent fake players from triggering the mecanic would solve the issue.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bearsdotzone** [comment]
I ran into this issue myself. Assuming it's a can't or won't fix I think it might warrant a warning in the pack, maybe in the spike quest or on the tooltip for the spikes.

**Comment by PLASMAchicken** [comment]
still reproducable in daily 313
