### ISSUE TITLE
previously existing ores from BW crash the game when the tooltip is displayed

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8594]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Your Server

Delta

### Type of Server

Thermos

### Your Actions

Was looking into my ore storage, and i kept crashing when i hovered a BW ore.

### Crash Report

```
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.github.bartimaeusnek.bartworks.system.material.BW_MetaGeneratedBlock_Item.func_77624_a(BW_MetaGeneratedBlock_Item.java:65)
	at net.minecraft.item.ItemStack.func_82840_a(Unknown Source)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:104)
	at wanion.avaritiaddons.block.chest.infinity.GuiInfinityChest.func_73863_a(GuiInfinityChest.java:166)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Looks like ores with meta ids that aren't registered anymore, so the map at
https://github.com/GTNewHorizons/bartworks/blob/938111c7a1c55ac584d58392c95b98efe05561f0/src/main/java/com/github/bartimaeusnek/bartworks/system/material/BW_MetaGeneratedBlock_Item.java#L65 returns null, causing the error.

Dunno if this is done in other places, but looks like some null checks are needed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alexdoru** [comment]
Got the same crash nice
