### ISSUE TITLE
[EMT] Cannot craft nanosuit googles of revealing

### ISSUE THREAD

**Issue by TheElan** [GTNewHorizons/GT-New-Horizons-Modpack#8723]
### Your GTNH Discord Username

Elan

### Your Pack Version

2.1.1.0

### Your Server

private

### Type of Server

Multiplayer LAN

### Your Expectation

Be able to craft the googles using infusion altar.

### The Reality

Nothing happens, lucky I've noticed error in the logs:

```
[02:13:17] [Server thread/WARN] [IC2.Item]: Detected invalid armor damage application:
java.lang.Throwable
	at ic2.core.item.armor.ItemArmorElectric.setDamage(ItemArmorElectric.java:154) [ItemArmorElectric.class:?]
	at net.minecraft.item.ItemStack.func_77964_b(Unknown Source) [add.class:?]
	at thaumcraft.api.crafting.InfusionRecipe.matches(InfusionRecipe.java:59) [InfusionRecipe.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.findMatchingInfusionRecipe(ThaumcraftCraftingManager.java:245) [ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.tiles.TileInfusionMatrix.craftingStart(TileInfusionMatrix.java:284) [TileInfusionMatrix.class:?]
	at thaumcraft.common.tiles.TileInfusionMatrix.onWandRightClick(TileInfusionMatrix.java:714) [TileInfusionMatrix.class:?]
	at thaumcraft.common.items.wands.ItemWandCasting.onItemUseFirst(ItemWandCasting.java:377) [ItemWandCasting.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source) [mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) [nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

Charging\discharging googles\helmet\crystal didn't change anything.

### Your Proposal

Debug & fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Hmm I was able to make these on mmcc. Was your nano piece fully repaired or otherwise nbt strange?
