### ISSUE TITLE
Infusion Claw server crush

### ISSUE THREAD

**Issue by bugi4vugi** [GTNewHorizons/GT-New-Horizons-Modpack#8840]
### Your GTNH Discord Username

bugivugi#8357

### Your Pack Version

2.1.1.4 QF2

### Your Server

Private

### Type of Server

Open To LAN

### Your Actions

On private server trying to automate infusion by AE. So I used Infusion Claw to activate Infusion Altar. In was the first time I used infusion claw.
I set Infusion claw on activation by lever. In 5 seconds after starting animation server crushes (infusion ritual does not start).  I tryed it several times, changing wands ( I used Ichorium and silverwood wands), infusion recipes. But every time -  server crushes the same way. 

I tryed infusion claw on single player mode. It worked and infusion recept started by infusion claw activation but with client console mistake.

### Crash Report

Server ---------------------------
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
    at makeo.gadomancy.common.blocks.tiles.TileInfusionClaw.performClickBlock(TileInfusionClaw.java:267)
    at makeo.gadomancy.common.blocks.tiles.TileInfusionClaw.func_145845_h(TileInfusionClaw.java:102)
    at net.minecraft.world.World.func_72939_s(World.java:2062)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:516)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:669)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:332)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:566)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:443)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:718)
    ---------------------------------------
    Single player ----------------------------
    [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking memory connection
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) ~[bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NullPointerException
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101) ~[FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
    ... 
--------------------------------------------------------

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ethryan** [comment]
Reopened the old issue #3027
