### ISSUE TITLE
NPE in GT++ recipe loading on startup

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8956]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.5pre2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Don't NPE

### The Reality

NPE happens, doesn't crash the game and everything seems to work:

```
[11:24:36] [Client thread/INFO] [TECTECH]: Recipe Init Done
[11:24:36] [Client thread/INFO] [TECTECH]: Blocks nerf done
[11:24:36] [Client thread/INFO] [TECTECH]: Constructable initialized
[11:24:42] [Client thread/INFO] [TGregworks]: Adding TiCTooltips integration...
[11:24:42] [Client thread/INFO] [TGregworks]: Successfully added TiCTooltips integration.
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NullPointerException
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.core.util.minecraft.RecipeUtils$InternalRecipeObject.run(RecipeUtils.java:572)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.core.handler.COMPAT_HANDLER.runQueuedRecipes(COMPAT_HANDLER.java:278)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.core.common.CommonProxy.postInit(CommonProxy.java:187)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.core.proxy.ClientProxy.postInit(ClientProxy.java:108)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.GTplusplus.postInit(GTplusplus.java:202)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[11:24:43] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[11:24:44] [Client thread/INFO] [YAMCL]: Checking/creating config folders
```

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
That could be literally anything.

**Comment by bombcar** [comment]
Debug doesn't show much - is there an even stronger debug for recipe handling?

```
[16:50:30] [Client thread/DEBUG] [GregTech GTNH/miscutils]: GT_RecipeAdder: Invalid input for (1xtile.bittBlock@2)
[16:50:30] [Client thread/DEBUG] [GregTech GTNH/miscutils]: GT_RecipeAdder: Invalid input for (1xtile.bittBlock@3)
[16:50:30] [Client thread/DEBUG] [GregTech GTNH/miscutils]: GT_RecipeAdder: Invalid input for (1xtile.bittBlock@4)
[16:50:30] [Client thread/DEBUG] [GregTech GTNH/miscutils]: GT_RecipeAdder: Invalid input for (1xtile.bittBlock@5)
[16:50:30] [Client thread/DEBUG] [GregTech GTNH/miscutils]: GT_RecipeAdder: Invalid input for (1xtile.bittBlock@6)
[16:50:30] [Client thread/DEBUG] [GregTech GTNH/miscutils]: GT_RecipeAdder: Invalid input for (1xtile.bittBlock@7)
[16:50:30] [Client thread/DEBUG] [GregTech GTNH/miscutils]: GT_RecipeAdder: Invalid input for (1xtile.bittBlock@8)
[16:50:30] [Client thread/DEBUG] [GregTech GTNH/miscutils]: GT_RecipeAdder: Invalid input for (1xtile.bittBlock@9)
[16:50:30] [Client thread/DEBUG] [GregTech GTNH/miscutils]: GT_RecipeAdder: Invalid input for (1xtile.bittBlock@10)
[16:50:30] [Client thread/DEBUG] [GregTech GTNH/miscutils]: GT_RecipeAdder: Invalid input for (1xtile.bittBlock@11)
[16:50:30] [Client thread/DEBUG] [GregTech GTNH/miscutils]: GT_RecipeAdder: Invalid input for (1xtile.bittBlock@12)
[16:50:30] [Client thread/DEBUG] [GregTech GTNH/miscutils]: GT_RecipeAdder: Invalid input for (1xtile.bittBlock@13)
[16:50:30] [Client thread/DEBUG] [GregTech GTNH/miscutils]: GT_RecipeAdder: Invalid input for (1xtile.bittBlock@14)
[16:50:30] [Client thread/DEBUG] [GregTech GTNH/miscutils]: GT_RecipeAdder: Invalid input for (1xtile.bittBlock@15)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NullPointerException
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.core.util.minecraft.RecipeUtils$InternalRecipeObject.run(RecipeUtils.java:577)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.core.handler.COMPAT_HANDLER.runQueuedRecipes(COMPAT_HANDLER.java:282)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.core.common.CommonProxy.postInit(CommonProxy.java:170)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.core.proxy.ClientProxy.postInit(ClientProxy.java:108)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.GTplusplus.postInit(GTplusplus.java:206)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[16:50:30] [Client thread/INFO] [STDERR/miscutils]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
