### ISSUE TITLE
NPE on load in languageList

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8957]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.5pre2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Don't NPE

### The Reality

Got NPE trying to translate string:

```
[11:48:33] [Client thread/INFO] [gendustry]: Resource manager reload, new language: en_US
[11:48:34] [Client thread/ERROR] [FML]: Unable to access any field [languageList, field_74816_c, d] on type net.minecraft.util.StringTranslate
cpw.mods.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: java.lang.NullPointerException
	at cpw.mods.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:121) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.ObfuscationReflectionHelper.getPrivateValue(ObfuscationReflectionHelper.java:60) [ObfuscationReflectionHelper.class:?]
	at remoteio.common.core.handler.LocalizationUpdater$StringTranslateDelegate.inject(LocalizationUpdater.java:136) [LocalizationUpdater$StringTranslateDelegate.class:?]
	at remoteio.common.core.handler.LocalizationUpdater.loadLangFiles(LocalizationUpdater.java:109) [LocalizationUpdater.class:?]
	at remoteio.common.core.handler.LocalizationUpdater.access$500(LocalizationUpdater.java:28) [LocalizationUpdater.class:?]
	at remoteio.common.core.handler.LocalizationUpdater$2.func_110549_a(LocalizationUpdater.java:99) [LocalizationUpdater$2.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143) [brg.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121) [brg.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:609) [bao.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57) ~[?:1.8.0_282]
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:1.8.0_282]
	at java.lang.reflect.Field.get(Field.java:393) ~[?:1.8.0_282]
	at cpw.mods.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:117) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	... 26 more
[11:48:34] [Client thread/INFO] [GregTech GTNH]: GT_Mod: Starting Block Icon Load Phase
[11:48:34] [Client thread/INFO] [GregTech GTNH]: GT_Mod: Finished Block Icon Load Phase
```

Running in default English on Mac with or without Optifine

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
https://gitlab.zveronline.ru/Mirrors/Minecraft/MinecraftForge/-/commit/275ccac6f14bc66b88c76b1040aa7167f995967c may be related
