### ISSUE TITLE
Hydroelectric doesn't work when running server

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8966]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.5pre2

### Your Server

private server

### Type of Server

Thermos

### Your Actions

According to @mitchej123, running server on the 2.1.1.5pre2 pack won't start if HydroElectric is enabled.

Disabling the mod lets it start.

A 2.1.1.4qf2 server with new HE crashes.

### Crash Report

[crash-2021-11-30_09.16.51-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7626816/crash-2021-11-30_09.16.51-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
Ok pulled from source and got the same crash.

@mitchej123 says Hydro energy was crashing applying client side mixins on the server for me.

[crash-2021-11-30_09.58.11-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7627057/crash-2021-11-30_09.58.11-server.txt)

**Comment by mitchej123** [comment]
Yup

```
java.lang.ClassNotFoundException: com.sinthoras.hydroenergy.client.light.HELightManager
```

**Comment by Glease** [comment]
Supposedly fixed by https://github.com/GTNewHorizons/HydroEnergy/commit/4ce3568778ed351fbef56ea47e6dde1df8f0c78b. Reopen if it still doesn't work.

**Comment by combusterf** [comment]
I managed to trigger it again and take Delta down with it:
```
java.lang.NoClassDefFoundError: com/sinthoras/hydroenergy/client/light/HELightManager
    at com.sinthoras.hydroenergy.client.light.HELightSMPHooks.onLightUpdate(HELightSMPHooks.java:18)
    at net.minecraft.world.chunk.Chunk.handler$zlp000$hydroenergy$onSetExtBlocklight(Chunk.java:4281)
    at net.minecraft.world.chunk.Chunk.func_76603_b(Chunk.java:332)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:682)
    at net.minecraft.world.World.func_147465_d(World.java:860)
    at net.fuzzycraft.botanichorizons.util.structurelib.HoloExtractor.wrapExtractor(HoloExtractor.java:58)
    at net.fuzzycraft.botanichorizons.util.structurelib.HoloExtractor.scanTileEntity(HoloExtractor.java:79)
    at net.fuzzycraft.botanichorizons.addons.item.ItemSelectiveWrench.onItemUseTileEntity(ItemSelectiveWrench.java:83)
    at net.fuzzycraft.botanichorizons.addons.item.ItemSelectiveWrench.onItemUseFirst(ItemSelectiveWrench.java:77)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:447)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:861)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
    at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: com.sinthoras.hydroenergy.client.light.HELightManager
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 20 more
Caused by: java.lang.RuntimeException: Attempted to load class com/sinthoras/hydroenergy/client/light/HELightManager for invalid side SERVER
    at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:51)
    at makamys.coretweaks.optimization.transformerproxy.TransformerProxy.invokeNextHandler(TransformerProxy.java:44)
    at makamys.coretweaks.optimization.ForgeFastWildcardTransformers$PatternConditionalTransformerWrapper.wrapTransform(ForgeFastWildcardTransformers.java:53)
    at makamys.coretweaks.optimization.transformerproxy.TransformerProxy.invokeNextHandler(TransformerProxy.java:46)
    at makamys.coretweaks.optimization.transformercache.lite.CachedTransformerWrapper.wrapTransform(CachedTransformerWrapper.java:24)
    at makamys.coretweaks.optimization.transformerproxy.TransformerProxy.invokeNextHandler(TransformerProxy.java:46)
    at makamys.coretweaks.optimization.transformerproxy.TransformerProxy.transform(TransformerProxy.java:27)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 22 more
```

**Comment by PLASMAchicken** [comment]
> I managed to trigger it again and take Delta down with it:


This is due to the Botanic Wrench stuff #22837

**Comment by chochem** [comment]
closed in favor of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/22837 as this one is not relevant.
