### ISSUE TITLE
Minesweeper Lootgame Crash  

### ISSUE THREAD

**Issue by LazyBlanketCat** [GTNewHorizons/GT-New-Horizons-Modpack#9040]
### Your GTNH Discord Username

LazyBlanketCat#8028

### Your Pack Version

GTNewHorizonsClient-1.7.10-2.1.2.0-pre4

### Your Server

SP

### Type of Server

Open To LAN Repeated on normal SP

### Your Actions

was trying to figure out how to play minesweeper minigame and I shift clicked one of the inside (Dark Blue) blocks of the game.

![image](https://user-images.githubusercontent.com/15895655/145653965-620b9a18-8050-496a-8e0f-2af0d287f44f.png)

### Crash Report

https://paste.ee/p/h6lCo (LAN)

https://paste.ee/p/RgP0C (Normal SP)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
Can't get this to happen but not exactly sure how to click on it to get it to ... go

If it happens consistently can you upload the world somewhere?

**Comment by bombcar** [comment]
https://www.dropbox.com/s/kqnybz1ekphzr5c/LazyBlanketCat%20-%20World.zip is the worldfile, still happens on pre5

**Comment by bombcar** [comment]
![image](https://user-images.githubusercontent.com/533931/145654397-4f4b3c85-af45-43e0-b734-42be4864aabb.png)

**Comment by PolkageistHS** [comment]
[21:28:38] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:57715
java.lang.NullPointerException
	at ru.timeconqueror.lootgames.minigame.minesweeper.MSBoard.getField(MSBoard.java:127) ~[MSBoard.class:?]
	at ru.timeconqueror.lootgames.minigame.minesweeper.MSBoard.isHidden(MSBoard.java:53) ~[MSBoard.class:?]
	at ru.timeconqueror.lootgames.minigame.minesweeper.GameMineSweeper$StageWaiting.revealAllNeighbours(GameMineSweeper.java:345) ~[GameMineSweeper$StageWaiting.class:?]
	at ru.timeconqueror.lootgames.minigame.minesweeper.GameMineSweeper$StageWaiting.onClick(GameMineSweeper.java:268) ~[GameMineSweeper$StageWaiting.class:?]
	at ru.timeconqueror.lootgames.api.minigame.BoardLootGame.onClick(BoardLootGame.java:73) ~[BoardLootGame.class:?]
	at ru.timeconqueror.lootgames.api.block.tile.BoardGameMasterTile.onClick(BoardGameMasterTile.java:38) ~[BoardGameMasterTile.class:?]
	at ru.timeconqueror.lootgames.api.block.tile.BoardGameMasterTile.onBlockRightClick(BoardGameMasterTile.java:29) ~[BoardGameMasterTile.class:?]
	at ru.timeconqueror.lootgames.api.block.SmartSubordinateBlock.lambda$onBlockActivated$1(SmartSubordinateBlock.java:36) ~[SmartSubordinateBlock.class:?]
	at ru.timeconqueror.lootgames.api.block.SmartSubordinateBlock.lambda$forMasterTile$3(SmartSubordinateBlock.java:53) ~[SmartSubordinateBlock.class:?]
	at ru.timeconqueror.timecore.api.util.WorldUtils.forTypedTile(WorldUtils.java:49) ~[WorldUtils.class:?]
	at ru.timeconqueror.timecore.api.util.WorldUtils.forTypedTileWithWarn(WorldUtils.java:22) ~[WorldUtils.class:?]
	at ru.timeconqueror.lootgames.api.block.SmartSubordinateBlock.forMasterTile(SmartSubordinateBlock.java:53) ~[SmartSubordinateBlock.class:?]
	at ru.timeconqueror.lootgames.api.block.SmartSubordinateBlock.func_149727_a(SmartSubordinateBlock.java:36) ~[SmartSubordinateBlock.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at fastcraft.u.a(F:289) [fastcraft-1.25.jar:?]
	at fastcraft.H.aq(F:36) [fastcraft-1.25.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

Just got this on 2.1.2.1, happened when I solved the puzzle for the third time.  No client crash was generated and this was the only stacktrace in the server log.
