### ISSUE TITLE
Crash on Version Parsing?

### ISSUE THREAD

**Issue by Erneest** [GTNewHorizons/GT-New-Horizons-Modpack#9082]
### Your GTNH Discord Username

Ernest#1424

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

All I do is start the game and load my save

### Crash Report

https://paste.ee/p/ZJC1w

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
```
java.lang.NumberFormatException: For input string: ".2-11"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.arc.bloodarsenal.common.misc.VersionChecker.onTick(VersionChecker.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1302_VersionChecker_onTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/BloodArsenal/blob/5fb9098dce0aff53f946a642602ba2c5df08ad2b/src/main/java/com/arc/bloodarsenal/common/misc/VersionChecker.java#L37

**Comment by bombcar** [comment]
> https://github.com/GTNewHorizons/BloodArsenal/blob/5fb9098dce0aff53f946a642602ba2c5df08ad2b/src/main/java/com/arc/bloodarsenal/common/misc/VersionChecker.java#L37

Please tell me it isn’t checking version every single tick. Please.

**Comment by bombcar** [comment]
This was caused by a default config created when no config existed. We should default false and/or remove the version check entirely

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/BloodArsenal/blob/5fb9098dce0aff53f946a642602ba2c5df08ad2b/src/main/java/com/arc/bloodarsenal/common/BloodArsenalConfig.java#L121 according to that, it autoregens to true, so looks like an user error (the config is setting the version check to false since nov 2016)

> Please tell me it isn’t checking version every single tick. Please.

it is entering in the method every single tick, but the first time it's executed, it flips a boolean, so the others are just a boolean check that leads to an exit. Not very useful and we might want to remove that.
