### ISSUE TITLE
Visual prospecting causing crash

### ISSUE THREAD

**Issue by FOOTMILK** [GTNewHorizons/GT-New-Horizons-Modpack#9128]
### Your GTNH Discord Username

N4M3_T1TL3_P3R20N#3173

### Your Pack Version

2.1.2.0 

### Your Server

SP

### Type of Server

Single Player

### Your Actions

When loading a world from 2.1.1.0 to 2.1.2.0 visual prospecting crashes the game and brings you back to the home screen. Removing visual prospecting fixes the issue, and putting  visual prospecting back crashes it agin. This crash also causes the game to not be able to be turn of and you have to kill it in MMC.

### Crash Report

A possible solution for the problem is changing visual prospecting so the player has to go back and find the ores insted of it auto updating and causing the game to crash.

[crash_logg.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7716650/crash_logg.txt)

Crash log^

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
<details>

<summary>stacktrace</summary>

```
java.lang.NumberFormatException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_311]
	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source) ~[?:1.8.0_311]
	at java.util.concurrent.ForkJoinTask.reportException(Unknown Source) ~[?:1.8.0_311]
	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[?:1.8.0_311]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[?:1.8.0_311]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_311]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_311]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_311]
	at com.sinthoras.visualprospecting.database.cachebuilder.DimensionAnalysis.processMinecraftWorld(DimensionAnalysis.java:32) ~[visualprospecting-1.7.10-1.0.24b.jar:?]
	at com.sinthoras.visualprospecting.database.cachebuilder.WorldAnalysis.cacheVeins(WorldAnalysis.java:27) ~[visualprospecting-1.7.10-1.0.24b.jar:?]
	at com.sinthoras.visualprospecting.hooks.HooksShared.fmlLifeCycleEvent(HooksShared.java:92) ~[visualprospecting-1.7.10-1.0.24b.jar:?]
	at com.sinthoras.visualprospecting.hooks.HooksClient.fmlLifeCycleEvent(HooksClient.java:49) ~[visualprospecting-1.7.10-1.0.24b.jar:?]
	at com.sinthoras.visualprospecting.VPMod.fmlLifeCycle(VPMod.java:48) ~[visualprospecting-1.7.10-1.0.24b.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789) [Loader.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at Reflector.callBoolean(Reflector.java:391) [Reflector.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:161) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NumberFormatException: For input string: "-1 1"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_311]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_311]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_311]
	at com.sinthoras.visualprospecting.database.cachebuilder.DimensionAnalysis.lambda$processMinecraftWorld$0(DimensionAnalysis.java:36) ~[visualprospecting-1.7.10-1.0.24b.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_311]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_311]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_311]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[?:1.8.0_311]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[?:1.8.0_311]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_311]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_311]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_311]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_311]
```
</details>

**Comment by SinTh0r4s** [comment]
What is the exact name of your visual propecting jar? 1.0.21b? It looks like there are custom files in some dimension. Could you run `find . >> list.txt` in the worlds save folder and post the result? Thanks :-)

**Comment by SinTh0r4s** [comment]
Or do you run windows?

**Comment by bombcar** [comment]
Crash log indicates it's on windows, yeah. I think the default jar is the -dirty one we shipped with 2.1.2.0, but I gave him the 1.0.21b from Jenkins.

**Comment by SinTh0r4s** [comment]
In that case please run `dir /s /b /a >> list.txt` from your world save location.

**Comment by FOOTMILK** [comment]
I do run windows; I do not have the same world anymore, but I ran a different one and it didn't crash I suspect it was a ram issue.

**Comment by ElNounch** [comment]
Looked like something is using space instead of the expected dot in region's foldername ? 
https://github.com/ElNounch/VisualProspecting/commit/11fdcf8f7e97c190a730df1b30de96d4271f0a10
