### ISSUE TITLE
crash when joining my world

### ISSUE THREAD

**Issue by nouille07** [GTNewHorizons/GT-New-Horizons-Modpack#9256]
### Your GTNH Discord Username

Nouille#3780

### Your Pack Version

2.1.2.0 / 2.1.2.1

### Your Server

local server on same computer as the client

### Type of Server

Single Player

### Your Actions

Crash when joining the world in both singleplayer and localy hosted server

Hi, I started this world on a fresh install of 2.1.2.0 on mmc last week and hosted it on a server on my own PC to split the load for my CPU. I removed the following mods from the base install: angry mobs, infernal mobs, special mobs, hardcore darkness, spice of life, holo inventory. I didn't know the server files didn't come with aroma backups so I got lazy and only made manual backup saves every day or so. 

Then one morning I decide to install both aroma backup and ftb utilities for chunk loading. I of course didn't backup my progress from the last day.. After adding them I couldn't join the world again (or rather I could join it and freeze at the 1st frame of my base becoming visible) and then crash back to desktop with my client. The server during this time seemed "fine". no crashes.

I then tried multiple things, namely upgrading to 2.1.2.1 on a fresh client install in singleplayer and using older backups, some combinations of both worked for older saves but my last save still crashes.

I get the exact same crash at the same time and the same error in the crash log

link to world folder download: https://files.catbox.moe/5juwf5.zip

Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 26
	at mantle.items.abstracts.CraftingItem.func_77667_c(CraftingItem.java:70)
	at net.minecraft.item.Item.func_77657_g(Item.java:547)
	at net.minecraft.item.Item.func_77653_i(Item.java:636)
	at net.minecraft.item.ItemStack.func_82833_r(Unknown Source)
	at net.minecraftforge.client.GuiIngameForge.renderToolHightlight(GuiIngameForge.java:583)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:154)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

### Crash Report

[crash-2021-12-23_11.48.44-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7769427/crash-2021-12-23_11.48.44-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
I will take a look at the world file and see if I can find corruption

**Comment by bombcar** [comment]
![image](https://user-images.githubusercontent.com/533931/147248022-a1151df4-81a2-4315-913e-55abcf5bc198.png)

All GT machines are .name, something is horribly wrong

**Comment by tungstensteelwrench** [comment]
It's the same when I try to open the world. I can open the ui of filing cabinets, smeltery on the back, the chest on left etc, but it crashes when I try to open those 3 double chests in the middle, or the crafting station naturally.

[crash-2021-12-23_16.36.14-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7769585/crash-2021-12-23_16.36.14-client.txt)

**Comment by bombcar** [comment]
I was able to open the top one, but not the middle one. Definitely something corrupted in the NBT.

The .name blocks are showing the right "GT" id , but have no data associated with them

The fact that Nouille reports that it has happened *multiple* times and ate his world each time is worrying.

The list of "Removed" mods doesn't jump out at me as a potential trigger:

- angry mobs
- infernal mobs
- special mobs
- hardcore darkness
- spice of life
- holo inventory

and I am seeing this issue on a full 2.1.2.1 pack

```
[08:08:22] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering item
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1092) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10
	at flaxbeard.thaumicexploration.item.ItemBaubleDiscountRing.func_77617_a(ItemBaubleDiscountRing.java:55) ~[ItemBaubleDiscountRing.class:?]
	at net.minecraft.item.Item.func_77650_f(Item.java:440) ~[adb.class:?]
	at net.minecraft.item.ItemStack.func_77954_c(Unknown Source) ~[add.class:?]
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:403) ~[bny.class:?]
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565) ~[bny.class:?]
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:503) ~[GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270) ~[bex.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99) ~[bex.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) ~[blt.class:?]
```

Hmm it can't render something

**Comment by bombcar** [comment]
SO the bad news first.

The world save is corrupt beyond repair, all NBT or whatever information on GT failed to save for some reason.

Good news? Not much really, we don't know what would cause this - can you provide *ANY AND ALL* contents of your logs directory so we can see if we see the error on save when it originally happened.

it is *possible* this is caused somehow by removing the mods. The mob ones shouldn't affect it but HoloLens might.

You may want to disable the features of them but leave them loaded.

Things that could cause this outside of the game: not shutting down the server properly with `stop` (so it only partially saved) or running out of disk space during a world save, or general hard drive corruption (all of these are probably kinda rare except the first)

**Comment by bombcar** [comment]
For spice of life you can change `B:food.modifier.enabled=true` to false in SpiceOfLife.cfg to disable the hunger-stuff (and leave the mod loaded).

**Comment by boubou19** [comment]
after a small talk on discord, we concluded that it was a major corruption caused by an external cause (aromabackup?).
