### ISSUE TITLE
NEI crashes game on some of the new screens (GregTech Material Parts most often)

### ISSUE THREAD

**Issue by PaulVisschers** [GTNewHorizons/GT-New-Horizons-Modpack#9304]
### Your GTNH Discord Username

PaulV#6149

### Your Pack Version

2.1.2.0

### Your Server

private server

### Type of Server

Don't know

### Your Actions

(Not sure what my server type is called but I just downloaded it off the website at http://downloads.gtnewhorizons.com/ServerPacks/, the server is also 2.1.2.0)

Open up NEI for any item that opens up on the new screens added in this update and it will often crash to desktop. GregTech Materials Parts seems to be especially crashy (most metals go there). It doesn't always crash but it does very often and it's the first page for many items so it's hard to avoid. I'm not sure if it crashes immediately on loading or when going to another tab from there or trying to escape out of NEI from it. Weirdly enough the two other players I play with don't crash on these ever, but I do a lot.

### Crash Report

[2021-12-30-1.log.gz](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7792415/2021-12-30-1.log.gz)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
<details>
<summary>stack trace</summary>

```

Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.github.dcysteine.neicustomdiagram.api.draw.GuiManager.getGui(GuiManager.java:304)
	at com.github.dcysteine.neicustomdiagram.api.draw.GuiManager.getViewportPosition(GuiManager.java:264)
	at com.github.dcysteine.neicustomdiagram.api.draw.GuiManager.mouseInBounds(GuiManager.java:174)
	at com.github.dcysteine.neicustomdiagram.api.diagram.DiagramGroup.mouseInBounds(DiagramGroup.java:222)
	at com.github.dcysteine.neicustomdiagram.api.diagram.DiagramGroup.findHoveredInteractable(DiagramGroup.java:207)
	at com.github.dcysteine.neicustomdiagram.api.diagram.DiagramGroup.getStackUnderMouse(DiagramGroup.java:300)
	at com.github.dcysteine.neicustomdiagram.main.NeiIntegration$ObjectHandler.getStackUnderMouse(NeiIntegration.java:56)
	at codechicken.nei.guihook.GuiContainerManager.getStackMouseOver(GuiContainerManager.java:269)
	at mcp.mobius.waila.handlers.nei.HandlerEnchants.lastKeyTyped(HandlerEnchants.java:29)
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:311)
	at codechicken.nei.recipe.GuiRecipe.func_73869_a(GuiRecipe.java:312)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:489)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:474)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.dcysteine.neicustomdiagram.api.draw.GuiManager.getGui(GuiManager.java:304)
	at com.github.dcysteine.neicustomdiagram.api.draw.GuiManager.getViewportPosition(GuiManager.java:264)
	at com.github.dcysteine.neicustomdiagram.api.draw.GuiManager.mouseInBounds(GuiManager.java:174)
	at com.github.dcysteine.neicustomdiagram.api.diagram.DiagramGroup.mouseInBounds(DiagramGroup.java:222)
	at com.github.dcysteine.neicustomdiagram.api.diagram.DiagramGroup.findHoveredInteractable(DiagramGroup.java:207)
	at com.github.dcysteine.neicustomdiagram.api.diagram.DiagramGroup.getStackUnderMouse(DiagramGroup.java:300)
	at com.github.dcysteine.neicustomdiagram.main.NeiIntegration$ObjectHandler.getStackUnderMouse(NeiIntegration.java:56)
	at codechicken.nei.guihook.GuiContainerManager.getStackMouseOver(GuiContainerManager.java:269)
	at mcp.mobius.waila.handlers.nei.HandlerEnchants.lastKeyTyped(HandlerEnchants.java:29)
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:311)
	at codechicken.nei.recipe.GuiRecipe.func_73869_a(GuiRecipe.java:312)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:489)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:474)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)

```
</details>

**Comment by bombcar** [comment]
@D-Cysteine I believe @mitchej123 has tackled and conquered a lot of these; perhaps it's the same kind of thing

**Comment by KiloJoel** [comment]
Reproduced, steps:
-Look up use for gregtech material which will open a new style tab
-Spam backspace while nei loads to exit the recipe immediately
Should crash to desktop

**Comment by D-Cysteine** [comment]
Thanks for all the detailed info, especially the repro instructions!

Looks like this was caused by closing the GUI instantly, before the GUI code has had a chance to run. Should be fixed here:
https://github.com/D-Cysteine/nei-custom-diagram/releases/tag/v1.4.3
