### ISSUE TITLE
GoodGenerator NuclearMetaItemGenerator

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/GT-New-Horizons-Modpack#9425]
### Your Pack Version

2.1.2.1x

### Your Server

Local

### Type of Server

Vanilla Forge

### Your Expectation

```
[19:45:53] [NEI Item Loading/ERROR] [NotEnoughItems]: Ommiting goodgenerator.items.nuclear.NuclearMetaItemGenerator@17f676e4:0 NuclearMetaItemGenerator
java.lang.NullPointerException
    at goodgenerator.items.nuclear.NuclearMetaItemGenerator.func_77617_a(NuclearMetaItemGenerator.java:106) ~[NuclearMetaItemGenerator.class:?]
    at net.minecraft.item.Item.func_77650_f(Item.java:440) ~[adb.class:?]
    at codechicken.nei.ItemList$1.damageSearch(ItemList.java:168) [ItemList$1.class:?]
    at codechicken.nei.ItemList$1.execute(ItemList.java:211) [ItemList$1.class:?]
    at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]
```

### The Reality

NPE

### Your Proposal

No NPE

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
kown issue. it is caused by some wip thing and has been fixed by https://github.com/GTNewHorizons/GoodGenerator/commit/e8928517787acbd12e86f92344df3838e625d925
