### ISSUE TITLE
Multiple errors/exceptions in multimc console

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#9480]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I opened console after minecraft crashed (issue described here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9479) and in console i saw multiple errors/exceptions like:

- java.lang.RuntimeException: Invalid filename format for dependency: CodeChickenLib-${mc_version}-${ccl_version}-universal.jar
- java.lang.NullPointerException
	at org.objectweb.asm.tree.InsnList.insert(Unknown Source)
- The mod craftpresence is expecting signature eca02c6a597321ad22340897683951ba5c76720a for source CraftPresence-Forge-1.7.10-Release-1.8.2.jar, however there is no signature matching that description
java.lang.RuntimeException: ZenSetter must have exactly one parameter - minetweaker.api.vanilla.ILootFunction.setName
- com.gitlab.cdagaming.craftpresence.utils.discord.rpc.exceptions.NoDiscordClientException: No Valid Discord Client was found for this Instance
- The mod lootgames is expecting signature 1cca375192a26693475fb48268f350a462208dce for source lootgames-1.7.10-2.0.3.jar, however there is no signature matching that description
- Invalid registration attempt for an Ore Dictionary item with name dustResiduePlutonium has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
Invalid registration attempt for an Ore Dictionary item with name dustResidueFluoride has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
Invalid registration attempt for an Ore Dictionary item with name dustResidueNoble has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
- [12:06:24] [Client thread/ERROR] [BloodArsenal]: ?????
[12:06:24] [Client thread/ERROR] [BloodArsenal]: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 256
- [12:06:47] [Client thread/FATAL] [LogisticsPipes]: Certificate not correct
[12:06:47] [Client thread/FATAL] [LogisticsPipes]: This in not a LogisticsPipes version from RS485.
- fox.spiteful.avaritia.compat.Compat$ItemNotFoundException: Unable to find :gt.metaitem.01 in mod gregtech! Are you using the correct version of the mod?
	at fox.spiteful.avaritia.compat.Compat.getItem(Compat.java:451)
- [12:08:31] [Client thread/ERROR] [HardcoreEnderExpansion]: [HEE-ORB] Corrupted shaped recipe: [BiblioWoodsForestry]tile.BiblioWoodFstBookcase/0 <= {[Forestry]tile.for.planks/2, <error:null>, [Forestry]tile.for.planks/2, [Forestry]tile.for.planks/2, <error:null>, [Forestry]tile.for.planks/2, [Forestry]tile.for.planks/2, <error:null>, [Forestry]tile.for.planks/2}
[12:08:31] [Client thread/ERROR] [HardcoreEnderExpansion]: [HEE-ORB] Corrupted shaped recipe: [BiblioWoodsForestry]tile.BiblioWoodFstBookcase/1 <= {[Forestry]tile.for.planks/11, <error:null>, [Forestry]tile.for.planks/11, [Forestry]tile.for.planks/11, <error:null>, [Forestry]tile.for.planks/11, [Forestry]tile.for.planks/11, <error:null>, [Forestry]tile.for.planks/11}, etc, more exceptions like these ones
- java.lang.ClassNotFoundException: com.jadarstudios.developercapes.DevCapes
- java.lang.NullPointerException
	at gtPlusPlus.core.util.minecraft.RecipeUtils$InternalRecipeObject.run(RecipeUtils.java:577)
- java.io.IOException: Server returned HTTP response code: 403 for URL: http://widget.mcf.li/mc-mods/minecraft/journeymap-32274.json
- [12:12:17] [Client thread/WARN] [Waila]: [Thermal Expansion] Error while loading Energy Cell hooks.java.lang.ClassNotFoundException: cofh.thermalexpansion.block.cell.TileCell
[12:12:17] [Client thread/WARN] [Waila]: [Thermal Expansion] Error while loading Tank hooks.java.lang.ClassNotFoundException: cofh.thermalexpansion.block.tank.TileTank
[12:12:17] [Client thread/WARN] [Waila]: [Thermal Expansion] Error while loading Tesseract hooks.java.lang.ClassNotFoundException: cofh.thermalexpansion.block.ender.TileTesseract
[12:12:17] [Client thread/WARN] [Waila]: [Thermal Expansion] Error while loading Tesseract hooks.java.lang.ClassNotFoundException: cofh.thermalexpansion.block.cache.TileCache
[12:12:17] [Client thread/WARN] [Waila]: [Thermal Dynamics] Error while loading FluidDuct hooks.java.lang.ClassNotFoundException: cofh.thermaldynamics.ducts.fluid.TileFluidDuct
- [12:12:42] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_2945_expanderPowerTierTwo.png, java.io.FileNotFoundException
- [12:12:43] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_3156_ArmorAnvil.png, java.io.FileNotFoundException
[12:12:43] [Client thread/ERROR]: Unable to parse metadata from thaumicexploration:textures/blocks/soulBrazier.png
java.lang.RuntimeException: broken aspect ratio and not an animation
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147964_a(TextureAtlasSprite.java:303) ~[bqd.class:?]
- 12:12:43] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_2950_expanderInvTierTwo.png, java.io.FileNotFoundException
- [12:12:44] [Client thread/ERROR]: Using missing texture, unable to load gregtech:textures/blocks/basicmachines//OVERLAY_BOTTOM_GLOW.png, java.io.FileNotFoundException
- [12:12:44] [Client thread/ERROR]: Using missing texture, unable to load gregtech:textures/blocks/materialicons/ENRICHED/pipeNonuple.png, java.io.FileNotFoundException

Linking log files below:
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7876847/fml-client-latest.log)
[crash-2022-01-16_13.53.55-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7876848/crash-2022-01-16_13.53.55-client.txt)

### The Reality

No need to describe this step, everything is in Expectations

### Your Proposal

Please fix these errors/exceptions 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by MadRatSRP** [comment]
[12:16:57] [NEI Subset Item Allocation/DEBUG] [FML/]: Attempted to find the oreIDs for an unregistered object (1xitem.null@8). This won't work very well.
[12:16:57] [NEI Subset Item Allocation/DEBUG] [FML/]: Attempted to find the oreIDs for an unregistered object (1xitem.null@8). This won't work very well.
[12:16:57] [NEI Subset Item Allocation/DEBUG] [FML/]: Attempted to find the oreIDs for an unregistered object (1xitem.null@8). This won't work very well.
[12:16:57] [NEI Subset Item Allocation/DEBUG] [FML/]: Attempted to find the oreIDs for an unregistered object (1xitem.null@8). This won't work very well.
[12:16:57] [NEI Subset Item Allocation/DEBUG] [FML/]: Attempted to find the oreIDs for an unregistered object (1xitem.null@8). This won't work very well.
[12:16:57] [NEI Subset Item Allocation/DEBUG] [FML/]: Attempted to find the oreIDs for an unregistered object (1xitem.null@8). This won't work very well.
[12:17:00] [ForkJoinPool-1-worker-0/DEBUG] [FML/]: Attempted to find the oreIDs for an unregistered object (1xitem.null@0). This won't work very well.
[12:17:00] [ForkJoinPool-1-worker-0/DEBUG] [FML/]: Attempted to find the oreIDs for an unregistered object (1xitem.null@0). This won't work very well.
[12:17:00] [ForkJoinPool-1-worker-0/DEBUG] [FML/]: Attempted to find the oreIDs for an unregistered object (1xitem.null@0). This won't work very well.
[12:17:00] [ForkJoinPool-1-worker-0/DEBUG] [FML/]: Attempted to find the oreIDs for an unregistered object (1xitem.null@0). This won't work very well.

also this thing
