### ISSUE TITLE
pollution-related mixin is failing in hodgepudge

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9486]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.2dev2

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

Load without crashing

### The Reality

```
java.lang.NullPointerException
at org.objectweb.asm.tree.InsnList.insert(Unknown Source)
at com.mitchej123.hodgepodge.asm.util.AbstractMethodTransformer.insertAfter(AbstractMethodTransformer.java:35)
at com.mitchej123.hodgepodge.asm.PollutionClassTransformer$5.transform(PollutionClassTransformer.java:71)
at com.mitchej123.hodgepodge.asm.util.AbstractClassTransformer.transform(AbstractClassTransformer.java:71)
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
at java.lang.Class.getDeclaredMethods(Class.java:1975)
at Reflector.getMethods(Reflector.java:685)
at ReflectorMethod.getTargetMethod(ReflectorMethod.java:66)
at ReflectorMethod.<init>(ReflectorMethod.java:46)
at ReflectorMethod.<init>(ReflectorMethod.java:23)
at Reflector.<clinit>(Reflector.java:43)
at ReflectorMethod.getTargetMethod(ReflectorMethod.java:66)
at ReflectorMethod.<init>(ReflectorMethod.java:46)
at ReflectorMethod.<init>(ReflectorMethod.java:23)
at BlockUtils.<clinit>(BlockUtils.java:19)
at ClearWater.updateWaterOpacity(ClearWater.java:32)
at net.minecraft.client.settings.GameSettings.updateWaterOpacity(GameSettings.java:3138)
at net.minecraft.client.settings.GameSettings.loadOfOptions(GameSettings.java:2809)
at net.minecraft.client.settings.GameSettings.func_74300_a(GameSettings.java:2400)
at net.minecraft.client.settings.GameSettings.<init>(GameSettings.java:381)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:378)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
at org.multimc.EntryPoint.listen(EntryPoint.java:143)
at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

### Your Proposal

Apparently a mixin trying to make pooollution for something is failing.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
`Grabs various methods in RenderBlocks when they query for colorMultiplier and overrides the value.`
