### ISSUE TITLE
Missing remapping for ironchest minecarts

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#9490]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.2

### Your Server

SSP

### Type of Server

Single Player

### Your Actions

Update IronchestMinecarts from 1.0.4 to 1.06 from jenkins

### Crash Report

Forge screen informs about missing items "minecart chest silver", confirm with "yes", game won't start

`[12:21:23] [Server thread/ERROR] [FML]: Caught exception from ironchestminecarts
java.lang.NullPointerException: remap target is null
	at cpw.mods.fml.common.event.FMLMissingMappingsEvent$MissingMapping.remap(FMLMissingMappingsEvent.java:138) ~[FMLMissingMappingsEvent$MissingMapping.class:?]
	at ganymedes01.ironchestminecarts.IronChestMinecarts.missingMapping(IronChestMinecarts.java:96) ~[IronChestMinecarts.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.fireMissingMappingEvent(Loader.java:941) [Loader.class:?]
	at cpw.mods.fml.common.registry.GameData.injectWorldIDMap(GameData.java:539) ~[GameData.class:?]
	at cpw.mods.fml.common.FMLContainer.readData(FMLContainer.java:277) ~[FMLContainer.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:403) [FMLCommonHandler.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:124) ~[ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:220) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) ~[mt.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62) ~[bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[12:21:23] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
java.lang.NullPointerException: remap target is null
	at cpw.mods.fml.common.event.FMLMissingMappingsEvent$MissingMapping.remap(FMLMissingMappingsEvent.java:138) ~[FMLMissingMappingsEvent$MissingMapping.class:?]
	at ganymedes01.ironchestminecarts.IronChestMinecarts.missingMapping(IronChestMinecarts.java:96) ~[IronChestMinecarts.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.fireMissingMappingEvent(Loader.java:941) [Loader.class:?]
	at cpw.mods.fml.common.registry.GameData.injectWorldIDMap(GameData.java:539) ~[GameData.class:?]
	at cpw.mods.fml.common.FMLContainer.readData(FMLContainer.java:277) ~[FMLContainer.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:403) [FMLCommonHandler.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:124) ~[ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:220) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) ~[mt.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62) ~[bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]`

Probably related to this commit: https://github.com/GTNewHorizons/IronChestMinecarts/commit/1b880157e3296fd11a3c7774ef1ed4870c263d79 as it points to this line:
https://github.com/GTNewHorizons/IronChestMinecarts/blob/1b880157e3296fd11a3c7774ef1ed4870c263d79/src/main/java/ganymedes01/ironchestminecarts/IronChestMinecarts.java#L96

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
Did you also grab the latest ironchests?

**Comment by GTNH-Afx237v7** [comment]
![homero-simpson](https://user-images.githubusercontent.com/64365566/149768658-ac201184-1ac5-4078-8f2f-eb07850742ae.gif)

**Comment by GTNH-Afx237v7** [comment]
Confirmed, updating both ironchestminecart and ironchest fixed this.
