### ISSUE TITLE
MineTweaker fails to rollback Thaumcraft tweaks

### ISSUE THREAD

**Issue by riking** [GTNewHorizons/GT-New-Horizons-Modpack#9538]
### Your GTNH Discord Username

Riking#6902

### Your Pack Version

2.1.2.2

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

Joining a server, leaving, and joining the server again works without any issues.

### The Reality

Client fails to join due to MineTweaker failing to rollback. "A fatal error has occured, this connection is terminated"

```
[14:55:34] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NullPointerException
[14:55:34] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
...
[14:55:34] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at modtweaker2.mods.thaumcraft.research.MoveResearch.undo(MoveResearch.java:72)
[14:55:34] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:     at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:86)
...
java.lang.NullPointerException
    at modtweaker2.mods.thaumcraft.research.OrphanResearch.undo(OrphanResearch.java:83) ~[OrphanResearch.class:?]
    at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:86) ~[MTTweaker.class:?]
```

### Your Proposal

(searched properly this time, no recent results for OrphanResearch or rollback)

Fix the thaumcraft scripts and/or script APIs

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kde99** [comment]
It also happens in single player when you load a world then quit you cannot load any other single player worlds not even the one you just played. Errors are similar if not same:

```
[09:42:25] [Server thread/ERROR] [FML]: Caught exception from MineTweaker3
java.lang.NullPointerException
	at modtweaker2.mods.thaumcraft.research.OrphanResearch.undo(OrphanResearch.java:83) ~[OrphanResearch.class:?]
	at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:86) ~[MTTweaker.class:?]
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:628) ~[MineTweakerImplementationAPI.class:?]
	at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:594) ~[MineTweakerImplementationAPI.class:?]
	at minetweaker.mc1710.MineTweakerMod.onServerAboutToStart(MineTweakerMod.java:174) ~[MineTweakerMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:859) [Loader.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:273) [FMLCommonHandler.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:91) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

Then same error for like 5 times display in log for AddPage.

**Comment by Dream-Master** [comment]
Will roll back craft tweaker

**Comment by Dream-Master** [comment]
@mitchej123 @Glease any idea how to fix the reload command to use newer version ?

**Comment by Ethryan** [comment]
Fixed in dev. See discord.
