### ISSUE TITLE
Crashed when update from 2.1.2.1 to 2.1.2.2

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#9555]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.1.2.2

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Simply update the Version

### Crash Report

Time: 1/23/22 5:00 PM
Description: Exception while updating neighbours

java.lang.NullPointerException: Exception while updating neighbours
	at gtPlusPlus.core.util.minecraft.EntityUtils.isTileEntityRegistered(EntityUtils.java:220)
	at gtPlusPlus.core.tileentities.general.redstone.TileEntityRedstoneHandler.registerTileEntity(TileEntityRedstoneHandler.java:38)
	at gtPlusPlus.core.tileentities.general.redstone.TileEntityRedstoneHandler.<init>(TileEntityRedstoneHandler.java:34)
	at gtPlusPlus.core.block.general.redstone.BlockGenericRedstoneDetector$TileEntityRedstoneDetector.<init>(BlockGenericRedstoneDetector.java:34)
	at gtPlusPlus.core.block.general.redstone.BlockGenericRedstoneDetector.func_149915_a(BlockGenericRedstoneDetector.java:29)
	at net.minecraft.block.Block.createTileEntity(Block.java:1446)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.World.func_147438_o(World.java:2540)
	at gtPlusPlus.core.block.general.redstone.BlockGenericRedstone.getTileEntity(BlockGenericRedstone.java:335)
	at gtPlusPlus.core.block.general.redstone.BlockGenericRedstone.func_149695_a(BlockGenericRedstone.java:304)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:181)
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:66)
	at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:28)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_89_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at advsolar.common.tiles.TileEntitySolarPanel.onLoaded(TileEntitySolarPanel.java:112)
	at advsolar.common.tiles.TileEntitySolarPanel.intialize(TileEntitySolarPanel.java:153)
	at advsolar.common.tiles.TileEntitySolarPanel.func_145845_h(TileEntitySolarPanel.java:165)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Maxhy21** [comment]
Same for Thermos MP
update exsiting world from 2121 to 2122.
enter the server with pure gtnh 2122 client using multimc
server has no extra mod
client crash report
https://pastebin.com/bQbVnBUy
server log
https://pastebin.com/CKCg7GTR
Largerthan2#3231

**Comment by bombcar** [comment]
Replace TE with this jar http://jenkins.usrv.eu:8080/job/ThaumicExploration/lastSuccessfulBuild/artifact/build/libs/Thaumic-Exploration-%5B1.7.10%5D%201.1.81-GTNH-0.jar

@Dream-Master can we fix this jar in the zips?

**Comment by KamenriderZO** [comment]
> Replace TE with this jar http://jenkins.usrv.eu:8080/job/ThaumicExploration/lastSuccessfulBuild/artifact/build/libs/Thaumic-Exploration-%5B1.7.10%5D%201.1.81-GTNH-0.jar
> 
> @Dream-Master can we fix this jar in the zips?

Doesn't work.
It seems like the problem of GT++ powerstation and advancedsolar?

**Comment by draknyte1** [comment]
```
[23:51:59] [Server thread/ERROR]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent@1cd37be1:
java.lang.NoClassDefFoundError: Could not initialize class flaxbeard.thaumicexploration.misc.brazier.SoulBrazierUtils
	at flaxbeard.thaumicexploration.misc.brazier.SoulBrazierQueue.onConnected(SoulBrazierQueue.java:19) ~[SoulBrazierQueue.class:?]
```

**Comment by KamenriderZO** [comment]
And the Catwalks mod is removed?

**Comment by YannickMG** [comment]
> And the Catwalks mod is removed?

Unused legacy support blocks were removed, the mod is still there.
