### ISSUE TITLE
botania and witchery fighting over potions

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9568]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.2

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

potions load normally

### The Reality

[09:00:52] [Client thread/WARN] [witchery: CLIENT]: witchery: Potion slot 95 already occupided by botania.potion.allure is being overwriting with witchery:potion.wrappedinvine, you may want to change potion ids in the config file!
[09:00:52] [Client thread/WARN] [witchery: CLIENT]: witchery: Potion slot 92 already occupided by botania.potion.featherFeet is being overwriting with witchery:potion.wakingnightmare, you may want to change potion ids in the config file!
[09:00:52] [Client thread/WARN] [witchery: CLIENT]: witchery: Potion slot 91 already occupided by botania.potion.soulCross is being overwriting with witchery:potion.volatility, you may want to change potion ids in the config file!
[09:00:52] [Client thread/WARN] [witchery: CLIENT]: witchery: Potion slot 94 already occupided by botania.potion.bloodthirst is being overwriting with witchery:potion.worship, you may want to change potion ids in the config file!
[09:00:52] [Client thread/WARN] [witchery: CLIENT]: witchery: Potion slot 93 already occupided by botania.potion.emptiness is being overwriting with witchery:potion.wolfsbane, you may want to change potion ids in the config file!

### Your Proposal

move the botania ones if possible to keep the originals the same

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
why this wasnt resolved before we add Botania. Maybe we have to remove it in 2.1.2.3 again and at it at a later stage back

**Comment by bombcar** [comment]
> why this wasnt resolved before we add Botania. Maybe we have to remove it in 2.1.2.3 again and at it at a later stage back

nobody ever watches the log files :(

**Comment by Dream-Master** [comment]
who need logfiles .... :)

**Comment by combusterf** [comment]
Everyone knows its full of A2

**Comment by combusterf** [comment]
So it turns out all potion slots are already occupied - there are some (core)mods out there that deal with the issue such as 
https://github.com/lumien231/Extended-Potions / https://www.curseforge.com/minecraft/mc-mods/extended-potions but that causes ASM conflicts in seemingly unrelated code.

So we can sacrifice some potion IDs of other mods that are deemed useless, or I can remove the brewing recipes for the extra potion effects from the botania patches

**Comment by glowredman** [comment]
No need for these mods, at least Botania and GalaxySpace extend the potion array to 256, another mod extends it to 352.

**Comment by combusterf** [comment]
I'm pretty sure Vazkii initially set it up like that, and then realised that Minecraft is buggy and turns potion >127 into negative array indices

**Comment by Dream-Master** [comment]
> So it turns out all potion slots are already occupied - there are some (core)mods out there that deal with the issue such as https://github.com/lumien231/Extended-Potions / https://www.curseforge.com/minecraft/mc-mods/extended-potions but that causes ASM conflicts in seemingly unrelated code.
> 
> So we can sacrifice some potion IDs of other mods that are deemed useless, or I can remove the brewing recipes for the extra potion effects from the botania patches

its an arr mod :(

**Comment by glowredman** [comment]
> I'm pretty sure Vazkii initially set it up like that, and then realised that Minecraft is buggy and turns potion >127 into negative array indices

He sets it to 256: https://github.com/GTNewHorizons/Botania/blob/master/src/main/java/vazkii/botania/common/brew/ModPotions.java#L57

**Comment by combusterf** [comment]
> He sets it to 256
...and then added a check for potions < 128

> its an arr mod
It's LGPL 
![image](https://user-images.githubusercontent.com/8459776/150857717-1ebd8d4a-3e8e-4ee1-9e9c-7e511de50d1b.png)

**Comment by combusterf** [comment]
> No need for these mods, at least Botania and GalaxySpace extend the potion array to 256, another mod extends it to 352.

So I tried entertaining your opinion and found it being completely bogus:
```
java.lang.ArrayIndexOutOfBoundsException: -128
        at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:105)
        at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:524)
        at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293)
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(Unknown Source)
        at net.minecraft.client.entity.EntityPlayerSP.localOnUpdate(EntityPlayerSP.java)
        at api.player.client.ClientPlayerBase.onUpdate(Unknown Source)
        at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerBaseSP.onUpdate(GCPlayerBaseSP.java:111)
        at api.player.client.ClientPlayerAPI.onUpdate(Unknown Source)
        at api.player.client.ClientPlayerAPI.onUpdate(Unknown Source)
        at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java)
        at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
        at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70071_h_(GCEntityClientPlayerMP.java:347)
        at net.minecraft.world.World.func_72866_a(World.java:2070)
        at net.minecraft.world.World.func_72870_g(World.java:2034)
        at net.minecraft.world.World.func_72939_s(World.java:1887)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by bombcar** [comment]
@mitchej123 https://github.com/lumien231/Extended-Potions is LGPL - how hard would it be to borrow/mimic the ASMs it uses to patch Minecraft itself

**Comment by combusterf** [comment]
The fix is a bit involved and requires PRs across 3 repos:
1. https://github.com/GTNewHorizons/Hodgepodge/pull/56
2. https://github.com/GTNewHorizons/Botania/pull/7
3. https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/9786

Please apply them in exactly that order to avoid complications

Thanks @mitchej123 for the help earlier today
