### ISSUE TITLE
CME when trying to load Opis on Thermos on 2.1.2.0

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9580]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.0

### Your Server

mmcc

### Type of Server

Thermos

### Your Actions

Getting a bit of lag, so went to open Opis which killed the server with

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at thermos.chaud.HashedArrayList$HashedArrayIterator.next(HashedArrayList.java:215)
	at mcp.mobius.opis.data.managers.TileEntityManager.getCumulativeAmountTileEntities(TileEntityManager.java:181)
	at mcp.mobius.opis.events.OpisServerTickHandler.tickEnd(OpisServerTickHandler.java:105)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_604_OpisServerTickHandler_tickEnd_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:252)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:894)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)
```

### Crash Report

[fml-server-3.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7937519/fml-server-3.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
are you sure you have the latest opis? Because i thought we had fixed this CME, and indeed on the officials we can 100% open opis without crashing (trust me i tried hard)

**Comment by bombcar** [comment]
I didn't have the latest (Jenkins just got one?) but I did have

`013fe7e052440bf153ffabb242fb70b3  Opis-1.3.1-MAPLESS_1.7.10.jar` which was the one that came with 2.1.2.0

(don't tell me we shipped an old one?)

**Comment by boubou19** [comment]
>(don't tell me we shipped an old one?)

i won't tell you then 😄
