### ISSUE TITLE
Game Crashes While Opening Backpack and Switching to New Backpack

### ISSUE THREAD

**Issue by ottothielicke** [GTNewHorizons/GT-New-Horizons-Modpack#9629]
### Your Pack Version

2.1.2.0

### Your Server

private server

### Your Actions

When you right click to open a Forestry backpack and switch to a backpack mod backpack before the forestry backpack inventory opens the game crashes. Crashes with an IndexOutOfBoundsException while trying to access inventory.

### Crash Report

[latest.log] (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7964888/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
```
14:20:14] [NEI Item Loading/ERROR]: Ommiting goodgenerator.items.nuclear.NuclearMetaItemGenerator@67bef25e:0 NuclearMetaItemGenerator
java.lang.NullPointerException
	at goodgenerator.items.nuclear.NuclearMetaItemGenerator.func_77617_a(NuclearMetaItemGenerator.java:106) ~[NuclearMetaItemGenerator.class:?]
	at net.minecraft.item.Item.func_77650_f(Item.java:440) ~[adb.class:?]
	at codechicken.nei.ItemList$1.damageSearch(ItemList.java:168) [ItemList$1.class:?]
	at codechicken.nei.ItemList$1.execute(ItemList.java:211) [ItemList$1.class:?]
	at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]
[14:20:34] [Client thread/INFO]: Mapping halted in E:\Users\otto\AppData\Roaming\.technic\modpacks\mcnewhorizons\journeymap\data\mp\That~s~uhhhh_c12fa8ad~b7b9~4ed2~bd7c~cea283bd3bdb\DIM0
```

**Comment by Dream-Master** [comment]
Not sure if the Backpack is here the problem

**Comment by Dream-Master** [comment]
@GlodBlock can you check this issue ? Thanks

**Comment by bombcar** [comment]
Wasn't that the removed item we see on load between 2.1.2.0 -> 2.1.2.2? Maybe one was in the backpack?

**Comment by Dream-Master** [comment]
GlodBlock — Today at 2:41 AM
just in 2.1.2.0, it is caused by some wip thing and have solved in later version
