### ISSUE TITLE
Getting Errored out when you're landing back on Earth from certain Space Station(s) causes the rocket chest to not spawn

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#9922]
### Your GTNH Discord Username

Piky#6375 (181103507711983616)

### Your Pack Version

2.1.2.3

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

I go to Earth from a trip from a station on Uranus

### The Reality

I get a `Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@2ffe20a5:
java.lang.IllegalStateException: Keyboard must be created before you can query key state` error and am kicked from the server. I log back in and the chest that should've spawn no longer exists. I lost a T6 rocket because of this.

### Your Proposal

Is this even fixable considering it's GC?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment]
I was not able to reproduce this (2.1.2.3qf). Does this happen every time? If not, how often? Does it only occure on this space station? Can you upload the log?

**Comment by ScriptedPiky** [comment]
I just got to reproduce again on the server. Apparently this is *the only* error that is stated:
```NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by ScriptedPiky** [comment]
New additional information: This error gets spammed in the server logs while existing within that dimension.
```[00:47:51] [Server thread/TRACE] [SGCraft/]: SGCraft.onChunkUnload: -252,-280
[00:47:51] [Server thread/TRACE] [SGCraft/]: SGCraft.onChunkSave: -252,-280
[00:47:51] [Server thread/TRACE] [SGCraft/]: SGCraft.onChunkUnload: -251,-280
[00:47:51] [Server thread/TRACE] [SGCraft/]: SGCraft.onChunkSave: -251,-280
[00:47:51] [Server thread/TRACE] [SGCraft/]: SGCraft.onChunkUnload: -249,-278
[00:47:51] [Server thread/TRACE] [SGCraft/]: SGCraft.onChunkSave: -249,-278
[00:47:51] [Server thread/TRACE] [SGCraft/]: SGCraft.onChunkUnload: -250,-280
[00:47:51] [Server thread/TRACE] [SGCraft/]: SGCraft.onChunkSave: -250,-280
[00:47:51] [Server thread/TRACE] [SGCraft/]: SGCraft.onChunkUnload: -249,-279
[00:47:51] [Server thread/TRACE] [SGCraft/]: SGCraft.onChunkSave: -249,-279
[00:47:51] [Server thread/TRACE] [SGCraft/]: SGCraft.onChunkLoad: -61,61
[00:47:51] [Server thread/TRACE] [SGCraft/]: SGCraft.onChunkLoad: -83,61
```

For reference of these errors. http://yin.systems/2022/03/2022-03-12_04-12-27_zMWs.png
Addtitionally, it seems that the GC bug of erroring the player out when exiting from a space station is well known by my friend and did occur in 2016. So the bug itself is ancient but I'm not even sure how to go about fixing it. Unfortunately, space stations may not be viable for now and are extremely buggy.

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
